### ISSUE TITLE
[feedback] Pandas.core.datetools deprecated

### ISSUE THREAD

**Issue by merkato** [yumorishita/LiCSBAS#1]
/usr/lib/python3/dist-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

Xubuntu 19.10 / statsmodel 0.8.0

**Comment by yumorishita** [comment]
It is not a issue in LiCSBAS, but in your python environment. Please update your module statsmodel.
