### ISSUE TITLE
python package ?

### ISSUE THREAD

**Issue by sahitono** [yumorishita/LiCSBAS#10]
Hi, why not create python wheel and conda package ? I think it will be easier to use, install and manage. People who use it won't need to bother about installing dependencies and setting up environment variable.

**Comment by yumorishita** [comment]
Thank you for your suggestion. I am sorry for bothering every user to prepare the python environment, but indeed I am not very familiar with python environment. I would like to focus on developing technical things about InSAR at the moment. I would appreciate if someone could share the easy way to create the environment.

**Comment by sahitono** [comment]
It can be done with github action. I can help to set it up, but the project directory need to be restructured. 
This project is great, thank you for creating it.

**Comment by gpsovsicori** [comment]
Hi, fantastic scripts, I save so much time thank to you! Scripts work amazingly! Recently, I get an error with the last month GACOS files, is there any change in the format, I need to take into account?

@t OVSICORI we appreciate you and COMET work, it gives us a complementary angle to asses volcano deformation.

Here the error:
ERROR 4: `/respaldo/InSAR/LiCSAR/157D_07909_131307_rincon/GEOCml1GACOS/sltd/20200529.bil' not recognized as a supported file format.
Traceback (most recent call last):
  File "/respaldo/InSAR/LiCSAR/LiCSBAS-master/bin/LiCSBAS03op_GACOS.py", line 456, in <module>
    sys.exit(main())
  File "/respaldo/InSAR/LiCSAR/LiCSBAS-master/bin/LiCSBAS03op_GACOS.py", line 297, in main
    ztd_geo = gdal.Warp("", bilfile, format='MEM', outputBounds=(lonw_geo, lats_geo, lone_geo, latn_geo), width=width_geo, height=length_geo, resampleAlg=resampleAlg, srcNodata=0).ReadAsArray()
  File "/home/ovsicori/anaconda3/lib/python3.7/site-packages/osgeo/gdal.py", line 579, in Warp
    return wrapper_GDALWarpDestName(destNameOrDestDS, srcDSTab, opts, callback, callback_data)
  File "/home/ovsicori/anaconda3/lib/python3.7/site-packages/osgeo/gdal.py", line 3189, in wrapper_GDALWarpDestName
    return _gdal.wrapper_GDALWarpDestName(*args)
SystemError: <built-in function wrapper_GDALWarpDestName> returned NULL without setting an error

**Comment by yumorishita** [comment]
I have created a new thread for this issue. Please see: https://github.com/yumorishita/LiCSBAS/issues/17

**Comment by yumorishita** [comment]
I have uploaded [LiCSBAS.yml](https://github.com/yumorishita/LiCSBAS/blob/master/LiCSBAS.yml) to create an "licsbas" environment by conda, and also updated the [wiki page](https://github.com/yumorishita/LiCSBAS/wiki/1_Installation#11-python3-and-required-modules). Do you think it is useful? @sahitono

**Comment by sahitono** [comment]
@yumorishita that's useful for creating anaconda environment. I think it will be better to include the package version too, so there wont be a problem when installs different major version. Because conda sometimes install gdal version 2 not gdal 3.  

Btw I have ported the bash script into powershell script so it can be used by windows user too. i can give it to you, if you are interested with it.

**Comment by yumorishita** [comment]
Thank you for your comments. I agree that the package version should be included, but I don't know what version can work or not for each package. I thought the latest version is installed without the explicit version and it would make no problem.

I have never used powershell. I would appreciate if you could upload the script on your repository or somewhere. I will link to it.

**Comment by sahitono** [comment]
What if the package version is the major version of what you currently uses ?

I'll create a fork of it asap, because i made some changes in the joining of url path. Because os.path in windows is backslash which is not a valid url path, so i use posix.path instead os.path.

**Comment by yumorishita** [comment]
I basically use the latest version, but it is not always required. I wonder if the unnecessary version specification increases conflict of multiple packages. LiCSBAS should not require the latest version for a certain package. If no specification of the package version does not cause a significant problem, I would like to keep the current yml file.

**Comment by sahitono** [comment]
I think there won't be significant problem

**Comment by Zeeshan-Ali1992** [comment]
> @yumorishita that's useful for creating anaconda environment. I think it will be better to include the package version too, so there wont be a problem when installs different major version. Because conda sometimes install gdal version 2 not gdal 3.
> 
> Btw I have ported the bash script into powershell script so it can be used by windows user too. i can give it to you, if you are interested with it.

Hello sahitono. Kindly share the "bash script" which you added to Powershell script to run it using Windows OS also.

**Comment by sahitono** [comment]
@Zeeshan-Ali1992 Hi, sadly I don't recommend it to you because I modified the old version of LiCSBAS to be compatible with windows. I recommend you to use WSL to run Linux on windows simultaneously without VM.
