### ISSUE TITLE
Cumulative extract geotiff and png

### ISSUE THREAD

**Issue by alejobeap** [yumorishita/LiCSBAS#101]
Dear

I am trying to extract the date by date from the cumulative map by using the LiCSBAS_plot_ts.py -i TS_GEOCml1GACOSclip/cum_filt.h5 statement. (LICSABS.png)

![LICSBAS](https://user-images.githubusercontent.com/65787135/114052850-05634a00-9854-11eb-956a-e9d1cc765316.png)

I see that it is very different if I use 

LiCSBAS_cum2vel.py -i TS_GEOCml1GACOSclip/cum_filt.h5 --vstd --mask TS_GEOCml1GACOSclip/results/mask --png -r 14:15/69:70 -s 20190808 -e 20190814
LiCSBAS_flt2geotiff.py -i 20190808_20190814.vel.mskd -p TS_GEOCml1GACOSclip/info/EQA.dem_par

![Extract](https://user-images.githubusercontent.com/65787135/114052860-085e3a80-9854-11eb-8de7-db4ed0b34bed.png)

I attach the images of this (the image of 20200814 is very different de LOS deformation value), Also I put with the same reference point and different reference point but is the same results compare the both commands . Can you help me what am I doing wrong? 

Also, Is it possible to see an incremental series of images?

Thanks

**Comment by yumorishita** [comment]
LiCSBAS_cum2vel.py compute the velocity (mm/yr), while what you see in LiCSBAS_plot_ts.py is the difference (mm). You should use LiCSBAS_cum2flt.py to output the difference, e.g.,
```
LiCSBAS_cum2flt.py -d 20190814 -i TS_GEOCml1GACOSclip/cum_filt.h5 -m 20190808 --mask TS_GEOCml1GACOSclip/results/mask --png -r 14:15/69:70
```

**Comment by alejobeap** [comment]
Thank you very much for your clarifications.
And in the case that I want to see an incremental map by date, can I do it?

**Comment by yumorishita** [comment]
You can output the deformation between any epochs (including increment) by indicating the options -d and -m in LiCSBAS_cum2flt.py.

**Comment by alejobeap** [comment]
Ok Thanks for your help.
