### ISSUE TITLE
Have been at this step of "HP filter in time, LP filter in space" for more than 10 hours

### ISSUE THREAD

**Issue by GEOSCIENCELXG** [yumorishita/LiCSBAS#103]
HP filter in time, LP filter in space,
with 8 parallel processing...
    0/127th image...
   20/127th image...
   10/127th image...
   30/127th image...
   40/127th image...
   60/127th image...
   50/127th image...
   80/127th image...
   70/127th image...
   90/127th image...
  100/127th image...
  120/127th image...
  110/127th image...

Create png for increment with 8 parallel processing...

when I clip the data with a small region, it is ok in this step. But with the full-frame processing,  this step is stucked. Could you give me some advice?

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/86
