### ISSUE TITLE
LiCSBAS_out2nc.py 'UnboundLocalError'?

### ISSUE THREAD

**Issue by lam-la** [yumorishita/LiCSBAS#104]
Hi!
I've used LiCSBAS_out2nc.py to export to netcdf4 once to open it in QGIS, it was around Nov or Dec 2020 I forgot.
But at that time it's working perfectly.
But when I use it this time it is gives me error:

```
(licsbas) [lam@gamla-stan Proses]$ LiCSBAS_out2nc.py -i TS_GEOCml1clip/cum_filt.h5 -o cum_filt.nc

LiCSBAS_out2nc.py ver1.0 20200904 M.Lazecky
LiCSBAS_out2nc.py -i TS_GEOCml1clip/cum_filt.h5 -o cum_filt.nc

Traceback (most recent call last):
  File "/home/lam/LiCSBAS/bin/LiCSBAS_out2nc.py", line 257, in <module>
    sys.exit(main())
  File "/home/lam/LiCSBAS/bin/LiCSBAS_out2nc.py", line 229, in main
    if cliparea_geo:
UnboundLocalError: local variable 'cliparea_geo' referenced before assignment
```
I've installed all needed dependecies.
Any idea what might be the cause?

Thanks for the great tools!

**Comment by yumorishita** [comment]
It seems to be a bug. Please try inserting a line:
```    cliparea_geo = []```
after line 161:
```    maskfile = []```

**Comment by lam-la** [comment]
Can confirm it works perfectly now!
![image](https://user-images.githubusercontent.com/82998206/115677295-8b19e600-a37a-11eb-9d82-4f54be835c68.png)
Thanks!
