### ISSUE TITLE
Two problems

### ISSUE THREAD

**Issue by CanZhang-zc** [yumorishita/LiCSBAS#105]
Dear Yu,
Please, I want to ask two questions.
Sorry for any inconvenience caused, your assistance will be highly appreciated.

**1.** 
In step 1-3, How is the number of points which should be solved including nan point-by-point determined? Through some methods, can the number of points that need to be processed be reduced without affecting the quality of the results? Because I found that if the number of points exceeds about 2000000, the step 1-3 will stuck. 

**like this**
LiCSBAS13_sb_inv.py ver1.5.2 20210311 Y. Morishita
LiCSBAS13_sb_inv.py -d GEOCml1GACOSmask --n_para 1 --n_para 1

In geographical coordinates

Not enough memory available compared to mem_size (8000 MB).
Reduce mem_size automatically to 7435 MB.
Read cum data on memory (fast but need memory).

Size of image (w,l)    : 3076, 2695
of all images        : 47
of images to be used : 47
of all ifgs          : 143
of ifgs to be used   : 131
of removed ifgs      : 12
Threshold of used unw  : 47

Reference area (X/Y)   : 1524:1525/1529:1530
Allowed memory size    : 7435 MB
Number of patches      : 2
Inversion algorism     : LS
Gamma value            : 0.0001

Process 1348/2695th line (1/2th patch)...
  Reading 131 ifg's unw data...
  2256395/4146448 points removed due to not enough ifg data...

  Identifing gaps, and counting n_gap and n_ifg_noloop,
  with 1 parallel processing...
/home/zhangcan/anaconda3/envs/licsbas/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py:11: MatplotlibDeprecationWarning: 
The support for Qt4  was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  from matplotlib.backends.qt_compat import QtGui
    Running  1/ 1th patch...

  Solving 170481/1890053th points with full unw at a time...
  Next, solve 1719572 points including nan point-by-point...
  Running 1719000/1719572th point...
  Elapsed time for 1th patch: 00h 23m 01s

Process 2695/2695th line (2/2th patch)...
  Reading 131 ifg's unw data...
  1464962/4143372 points removed due to not enough ifg data...

  Identifing gaps, and counting n_gap and n_ifg_noloop,
  with 1 parallel processing...
    Running  1/ 1th patch...

**2.** 
If I want to use other software for drawing (like Surfer), which files in the results directory should I use for drawing?

**Comment by yumorishita** [comment]
1. The number of processed points per patch would be reduced if you set a smaller number of p13_mem_size (e.g., 2000) in batch_LiCSBAS.sh.

https://github.com/yumorishita/LiCSBAS/blob/5a93dbf5ca3224cbadb9261fa8fb9f425a43d1d7/batch_LiCSBAS.sh#L97

2. You should create a GeoTIFF file for the deformation velocity or time series by LiCSBAS_flt2geotiff.py, LiCSBAS_cum2flt.py, or LiCSBAS_cum2vel.py. The input files for these commands can be found in a [wiki page](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools) or the usage for each command.

**Comment by CanZhang-zc** [comment]
Thanks Yu. I‘ll try it later.
For the **p13_mem_size=""**, the default is 8000, and if I want to keep the result consistent with the default result (8000) as much as possible, should it be slightly reduced on the basis of 8000?

**Comment by yumorishita** [comment]
You would get completely the same result whatever values you use. The parameter just changes the number of patches, i.e., how large data are processed in a patch at a time.

**Comment by CanZhang-zc** [comment]
Thanks Yu, I get it clearly. I'll try it later.
Thank you so much!

**Comment by CanZhang-zc** [comment]
Dear Yu, How to solve this error by editing code?
**Here is the log:**
(licsbas) zhangcan@zhangcan:/media/zhangcan/Seagate4T/113A_05272_131313/TS_GEOCml1maskclip$ LiCSBAS_cum2flt.py -d 20210427
/home/zhangcan/anaconda3/envs/licsbas/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py:11: MatplotlibDeprecationWarning: 
The support for Qt4  was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  from matplotlib.backends.qt_compat import QtGui

LiCSBAS_cum2flt.py ver1.2.1 20210107 Y. Morishita
LiCSBAS_cum2flt.py -d 20210427
Traceback (most recent call last):
  File "/home/zhangcan/LiCSBAS/bin/LiCSBAS_cum2flt.py", line 209, in <module>
    sys.exit(main())
  File "/home/zhangcan/LiCSBAS/bin/LiCSBAS_cum2flt.py", line 149, in main
    refx1, refx2, refy1, refy2 = [int(s) for s in re.split('[:/]', refarea)]
  File "/home/zhangcan/anaconda3/envs/licsbas/lib/python3.6/re.py", line 212, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by yumorishita** [comment]
#65
#40

**Comment by CanZhang-zc** [comment]
Thanks Yu. I get it now.

**Comment by yumorishita** [comment]
The problem seems to have been solved. Let me close this issue.
