### ISSUE TITLE
The Processing stuck in step 1-3

### ISSUE THREAD

**Issue by Gautam5673** [yumorishita/LiCSBAS#106]
Hi Sir,
Here I have tried to run the batch script 
with default n_para and also with fixing the n_para = 1.
But each time program got stuck at step 1-3. I have tried with clipping some portion to reduce the size but again it struck at step 1-3.
I'm attaching log files.
[202105050207batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/6437606/202105050207batch_LiCSBAS_01_16.log)
[202105050357batch_LiCSBAS_11_16.log](https://github.com/yumorishita/LiCSBAS/files/6437608/202105050357batch_LiCSBAS_11_16.log)

**Comment by yumorishita** [comment]
I suggest using larger n_look (e.g. 4 or 10) to reduce the size and avoid the stuck. Sorry but I have no other ideas to fix the stuck problem in your environment because the occurrence of the stuck seems to be environment-dependent. Do you use Mac?

**Comment by Gautam5673** [comment]
Sir
Thank you for the suggestion!
I'll try the above one.
No I'm using Ubantu 20.4 LTS,  with 2.5-2.7 GiHz processor,  12GB ram and
300GB storage. Laptop-Lenovo-ideapad-300-15ISK.

**Comment by yumorishita** [comment]
The problem seems to have been solved. Let me close this issue.
