### ISSUE TITLE
Invalid MIT-MAGIC-COOKIE-1 key h5py(2.10.0) OK

### ISSUE THREAD

**Issue by siavashshami** [yumorishita/LiCSBAS#107]

**Comment by yumorishita** [comment]
https://unix.stackexchange.com/questions/199891/invalid-mit-magic-cookie-1-key-when-trying-to-run-program-remotely
https://askubuntu.com/questions/1238389/invalid-mit-magic-cookie-1-key-message-while-running-a-program-with-the-termin
https://stackoverflow.com/questions/62503731/invalid-mit-magic-cookie-1-key-when-locally-running-mpi-application-or-starting
