### ISSUE TITLE
Displacement value of LOS in software QGIS

### ISSUE THREAD

**Issue by siavashshami** [yumorishita/LiCSBAS#108]
Hello
Why is the displacement value of LOS in software QGIS greater than the output value of LICSBAS?
![los-licsbas](https://user-images.githubusercontent.com/81895426/119214597-57e38780-badd-11eb-915c-064f75f4fd12.png)
![los-qgis](https://user-images.githubusercontent.com/81895426/119214600-5a45e180-badd-11eb-8039-68af9cfeaeb2.png)

**Comment by yumorishita** [comment]
It seems to be the same. The colour range in LiCSBAS is not peak-to-peak. See the exact value, not colour.
