### ISSUE TITLE
Error in "LiCSBAS_profile.py"

### ISSUE THREAD

**Issue by SMJMirzadeh** [yumorishita/LiCSBAS#11]
Dear Morishita,

Thank you so much for your awesome package. I did my processing and tried to see my results by "LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &" command. It works very well.

Then, I would like to try to get a profile between two peak points in my study area using the following command:

LiCSBAS_profile.py -i TS_GEOCml1clip/cum_filt.h5 -p TS_GEOCml1clip/info/EQA.dem_par -g 53.99,32.26/54.20,31.97

But I get the following error:

LiCSBAS_profile.py ver1.0 20190916 Y. Morishita
LiCSBAS_profile.py -i TS_GEOCml1clip/cum_filt.h5 -p TS_GEOCml1clip/info/EQA.dem_par -g 53.99,32.26/54.20,31.97
Traceback (most recent call last):
  File "/application/pi/LiCSBAS/bin/LiCSBAS_profile.py", line 237, in <module>
    sys.exit(main())
  File "/application/pi/LiCSBAS/bin/LiCSBAS_profile.py", line 136, in main
    data = io_lib.read_img(infile, length, width, endian=endian)
  File "/application/pi/LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 146, in read_img
    data = np.fromfile(file, dtype=dtype).reshape((length, width))
ValueError: cannot reshape array of size 55725585 into shape (1002,1002)

Could you please guide me to fix it? I think I have a mistake in using the "LiCSBAS_profile.py" code.

Sincerely,
Sayyed

**Comment by yumorishita** [comment]
The input file for ​LiCSBAS_profile.py must be in float format (not hdf5) as is written in the usage, which can be created by LiCSBAS_cum2vel.py or LiCSBAS_cum2flt.py. Sorry for confusing optional arguments.
