### ISSUE TITLE
LiCSBAS_decomposeLOS.py

### ISSUE THREAD

**Issue by siavashshami** [yumorishita/LiCSBAS#110]
Hello

What do you mean by the following?
vel1.maskd.geo.tiff E1.geo.tiff N1.geo.tiff
vel2.maskd.geo.tiff E2.geo.tiff N2.geo.tiff
Once the results in the descending and once the results of the ascending? 

Best regards,

**Comment by yumorishita** [comment]
Of course both ascending and descending results are necessary for the decomposition. For example,

- vel1.maskd.geo.tiff: velocity in ascending
- E1.geo.tiff: East component of LOS unit vector in ascending
- N1.geo.tiff: North component of LOS unit vector in ascending
- vel2.maskd.geo.tiff: velocity in descending
- E2.geo.tiff: : East component of LOS unit vector in descending
- N2.geo.tiff: : North component of LOS unit vector in descending

**Comment by siavashshami** [comment]
Should only file vel.maskd.geo.tiff be? Or can it be file vel.filt.geo.tiff?

**Comment by yumorishita** [comment]
Any velocity or cumulative deformation GeoTIFF file is OK.

**Comment by as1234554321** [comment]
> Any velocity or cumulative deformation GeoTIFF file is OK.
Hi sir
There are several velocity results files, to determine which file is better to use.
What aspects/things should be considered?

**Comment by as1234554321** [comment]
> File GeoTIFF dengan kecepatan atau deformasi kumulatif apa pun boleh digunakan.

what the meaning of vel, vel. mksd, vel. filt, vel. filt mskd?

**Comment by yumorishita** [comment]
filt: filtered
mskd: masked
