### ISSUE TITLE
Time Series LS Inversion Residuals

### ISSUE THREAD

**Issue by AlirezaS89** [yumorishita/LiCSBAS#111]
Hi,
Is there any way to export residuals of the LS Inversion for every pixel?

**Comment by yumorishita** [comment]
Yes, change to p13_keep_incfile="y" in batch_LiCSBAS.sh,
https://github.com/yumorishita/LiCSBAS/blob/5a93dbf5ca3224cbadb9261fa8fb9f425a43d1d7/batch_LiCSBAS.sh#L101
to use the --keep_incfile option in step13.
https://github.com/yumorishita/LiCSBAS/wiki/2_3_step11_16#step-1-3-small-baseline-inversion

**Comment by AlirezaS89** [comment]
> Yes, change to p13_keep_incfile="y" in batch_LiCSBAS.sh,
> https://github.com/yumorishita/LiCSBAS/blob/5a93dbf5ca3224cbadb9261fa8fb9f425a43d1d7/batch_LiCSBAS.sh#L101
> 
> 
> to use the --keep_incfile option in step13.
> https://github.com/yumorishita/LiCSBAS/wiki/2_3_step11_16#step-1-3-small-baseline-inversion

Thanks!
