### ISSUE TITLE
LICSBAS with other interferograms

### ISSUE THREAD

**Issue by alejobeap** [yumorishita/LiCSBAS#112]
Dear
I understand that I can use LICSBAS with other interferograms like TerrasarX, could you please guide me how to do this. What format should the interferograms be in?

Thank you very much.
Alejandro

**Comment by yumorishita** [comment]
Please see the file structure:
https://github.com/yumorishita/LiCSBAS/wiki/file_structure

**Comment by yumorishita** [comment]
See also https://github.com/yumorishita/LiCSBAS/issues/39#issuecomment-758361987

**Comment by alejobeap** [comment]
Thank you very much
For your information, I have processed the interferograms with ISCE, I don't know if it works.
