### ISSUE TITLE
 LiCSBAS_cum2tstxt.py

### ISSUE THREAD

**Issue by siavashshami** [yumorishita/LiCSBAS#113]
Hi

In this command, how can the time series of all points be obtained?

**Comment by yumorishita** [comment]
Just iterate the command (e.g., using "for" loop), though I do not understand why you need the time series at all points in the text format.

**Comment by siavashshami** [comment]
In LiCSBAS, how can the time series of points be output as text or excel?

**Comment by yumorishita** [comment]
LiCSBAS_cum2tstxt.py can output a text file, but you can use any general tools to read or convert an hdf5 file.

**Comment by yumorishita** [comment]
Let me close this issue because there seem to be no more questions.
