### ISSUE TITLE
LiCSBAS_flt2geotiff.py

### ISSUE THREAD

**Issue by Pirog3266** [yumorishita/LiCSBAS#115]
Hello again,

As you told before, I'm making geotiff file by LiCSBAS_flt2geotiff.py  to run LiCSBAS_decomposeLOS.py
I could make E.geo.tiff and N.geo.tiff but I could not make dispfile1 which can be made from TS_GEOCml1clip/results/vel.mskd.

The log shows as below.
What's problem ?

***************************************************************************************************************
(base) inakura@inagurakanjinnoMac-mini 163D_05736_131313 % LiCSBAS_flt2geotiff.py -i/Users/inakura/LiCSBAS/163D_05736_131313/TS_GEOCml1clip/results/vel.mskd -p/Users/inakura/LiCSBAS/163D_05736_131313/GEOCml1/EQA.dem_par 

LiCSBAS_flt2geotiff.py ver1.5.1 20210209 Y. Morishita
LiCSBAS_flt2geotiff.py -i/Users/inakura/LiCSBAS/163D_05736_131313/TS_GEOCml1clip/results/vel.mskd 
-p/Users/inakura/LiCSBAS/163D_05736_131313/GEOCml1/EQA.dem_par
Use gdal module
Traceback (most recent call last):
  File "/Users/inakura/LiCSBAS/bin/LiCSBAS_flt2geotiff.py", line 213, in <module>
    sys.exit(main())
  File "/Users/inakura/LiCSBAS/bin/LiCSBAS_flt2geotiff.py", line 190, in main
    data = io_lib.read_img(infile, length, width, endian=endian)
  File "/Users/inakura/LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 199, in read_img
    data = np.fromfile(file, dtype=dtype).reshape((length, width))
ValueError: cannot reshape array of size 716130 into shape (2699,3144)

**Comment by yumorishita** [comment]
You should use /Users/inakura/LiCSBAS/163D_05736_131313/GEOCml1clip/EQA.dem_par instead of /Users/inakura/LiCSBAS/163D_05736_131313/GEOCml1/EQA.dem_par.

**Comment by Pirog3266** [comment]
Thanks. I made it.
