### ISSUE TITLE
Area for LiCSBAS_decomposeLOS.py

### ISSUE THREAD

**Issue by Pirog3266** [yumorishita/LiCSBAS#116]
Sorry for repeating question.
Will LiCSBAS_decomposeLOS.py not work if the analysis range is different between descending and ascending (e.g. descending does not have the bottom half)?

The error message is as follows.

**********************************************************************************
(base) inakura@inagurakanjinnoMac-mini decompseLOS % LiCSBAS_decomposeLOS.py -f files2.txt

LiCSBAS_decomposeLOS.py ver1.1.2 20210209 Y. Morishita
LiCSBAS_decomposeLOS.py -f files2.txt
Traceback (most recent call last):
  File "/Users/inakura/LiCSBAS/bin/LiCSBAS_decomposeLOS.py", line 312, in <module>
    sys.exit(main())
  File "/Users/inakura/LiCSBAS/bin/LiCSBAS_decomposeLOS.py", line 120, in main
    LOSe_tifs.append(line[1])
IndexError: list index out of range
(base) inakura@inagurakanjinnoMac-mini decompseLOS %

**Comment by yumorishita** [comment]
LiCSBAS_decomposeLOS.py should work if there is a common area in descending and ascending. Can you show me the file2.txt? The file contains more than 1 lines?

**Comment by Pirog3266** [comment]
Here it is.
[files2.txt](https://github.com/yumorishita/LiCSBAS/files/6781334/files2.txt)
All file are put in same folder.

**Comment by yumorishita** [comment]
The file2.txt should contain only
```
vel1.maskd.geo.tif E1.geo.tif N1.geo.tif
vel2.maskd.geo.tif E2.geo.tif N2.geo.tif
```

**Comment by Pirog3266** [comment]
Thanks ! It works.
