### ISSUE TITLE
A problem in LiCSBAS_cum2vel.py

### ISSUE THREAD

**Issue by CanZhang-zc** [yumorishita/LiCSBAS#117]
Dear Yu,
Please, I meet a problem in **LiCSBAS_cum2vel.py**.
After running the **LiCSBAS_cum2vel.py**, what's the colorbar's unit? mm/yr or m/yr?

When I use GMT to make a figure, the command "grdinfo" in GMT get the information like these:
vel.nc: Title: 
vel.nc: Command: 
vel.nc: Remark: 
vel.nc: Pixel node registration used [Cartesian grid]
vel.nc: Grid file format: cf = GMT netCDF format (32-bit float, deprecated)
vel.nc: x_min: 101.9236667 x_max: 104.959664302 x_inc: 0.00099999921 name:  n_columns: 3036
vel.nc: y_min: 28.9678910318 y_max: 31.6668888996 y_inc: 0.00099999921 name:  n_rows: 2699
**vel.nc: z_min: -253.940658569 z_max: 218.511489868 name: meters**
vel.nc: scale_factor: 1 add_offset: 0
vel.nc: format: classic

So I want to ask this problem. And the vel from the **LiCSBAS_cum2vel.py** looks not the same as **LiCSBAS_plot_ts.py**.
Sorry for any inconvenience caused, your assistance will be highly appreciated.

![20180315_20200527 vel](https://user-images.githubusercontent.com/78521332/125257028-96ecc700-e32f-11eb-93a5-174c792b644e.png)
![微信截图_20210712163603](https://user-images.githubusercontent.com/78521332/125257036-98b68a80-e32f-11eb-9205-414b56942b1e.png)

**Comment by yumorishita** [comment]
The unit is mm/yr.
The image in the second figure is not the velocity but the displacement at 2020/05/27 with reference to 2018/03/15 (unit mm). Please click again 'vel' to show the velocity.

**Comment by CanZhang-zc** [comment]
Thanks a lot. Like this is the velocity, right?
![3](https://user-images.githubusercontent.com/78521332/125260245-ba654100-e332-11eb-84a7-86b784769062.png)

But the velocity value's ranges of colorbar in LiCSBAS_cum2vel.py and LiCSBAS_plot_ts.py are not the same. The velocity colorbar of LiCSBAS_cum2vel.py looks so huge. 
So how can I solve the problem to **make a more beautiful figure in GMT like LiCSBAS_plot_ts.py shows**?

**Comment by yumorishita** [comment]
The reason of the different color scale is in the LiCSBAS_plot_ts.py the color range is 99% of the data by default while 100% in LiCSBAS_cum2vel.py. See also https://github.com/yumorishita/LiCSBAS/issues/108.
You can create png or kmz in any color scales as you want with --cmin and --cmax options.

**Comment by CanZhang-zc** [comment]
Thanks a lot Yu.
I have seen the issue #108 and already understood why. But I can't find the options **"--cmin and --cmax"**.
Where are the options? Which .py please?
Thank you so much for your response!

**Comment by yumorishita** [comment]
Sorry, I forgot to mention that the options are available in LiCSBAS_disp_img.py. They just control the color range but do not modify the data.

**Comment by CanZhang-zc** [comment]
Thanks Yu.
But if I want to create a tif in any scales as I want, should I edit the options --cmin and --cmax in LiCSBAS_color_geotiff.py? Does this way modify the data or just control the color range?

**Comment by yumorishita** [comment]
Yes, use LiCSBAS_color_geotiff.py with the --cmin and --cmax options. The data is not modified.

**Comment by CanZhang-zc** [comment]
Thank a lot, Yu.
I'll try it.

**Comment by CanZhang-zc** [comment]
Dear Yu,
What are the meaning of the **vel(1) and vel(2)** in **LiCSBAS_plot_ts.py**?

**Comment by yumorishita** [comment]
They correspond to cum*.h5 files indicated by -i and --i2 options. By default vel(1) and vel(2) are velocities of filtered and unfiltered time series, respectively.
