### ISSUE TITLE
reshape error in iCSBAS11_check_unw.py

### ISSUE THREAD

**Issue by Linya-Peng** [yumorishita/LiCSBAS#118]
Dear Yumorishita!
Thank you for your wonderful software in SBAS-InSAR.
Today I met an error in LiCSBAS11_check_unw.py
![image](https://user-images.githubusercontent.com/61902717/125458966-58f71b85-3da6-4c56-bef3-8fc6fba9b157.png)
![image](https://user-images.githubusercontent.com/61902717/125459627-503d915c-ae6f-42f0-8338-6386f83fece0.png)
I didn't clip the data. My **unw** is 7333 x 5071=37185643, and I wrote some lines to read the **unw** in **GEOml1** folder directly, and found that the size was just 37185643, I didn't know where the problem was. Can you help me?

**Comment by Linya-Peng** [comment]
> I do not understand your problem. Can you show me the full error log?

Yes, the whole error was as below:
![image](https://user-images.githubusercontent.com/61902717/125461573-10fafa6b-1531-4320-9d3a-47e142ff1149.png)

**Comment by yumorishita** [comment]
I think one (or more) of unw files except 20170722_20170815.unw has different size.

**Comment by Linya-Peng** [comment]
> I think one (or more) of unw files except 20170722_20170815.unw has different size.

Yes, you are right~I checked them one by one and found the different sized unw. By the way, can I solve the problem by clipping the common area of all unw files using  LiCSBAS05op_clip_unw.py with the [-g]?

**Comment by yumorishita** [comment]
No, all the input unw files must have the same size in the step05 as well.

**Comment by Osmanpour** [comment]
Hi. I have the same problem. How can I solve these issues?
I was clipping my area in step 05
<img width="879" alt="image_2024_04_25T11_40_21_395Z-1" src="https://github.com/yumorishita/LiCSBAS/assets/105474833/a9a22528-b157-4c8e-9b16-a3f691db0a8e">
