### ISSUE TITLE
How to get the errors from the unwrapped interferogram

### ISSUE THREAD

**Issue by sizzer13** [yumorishita/LiCSBAS#12]
Hi,
If I want to get the error data or the standard deviation information from one pair of the products like one DInSAR product of date1_date2.geo.unw.tif, how could I do?

Best,
Sizzer

**Comment by yumorishita** [comment]
For example:

```python
import gdal
import numpy as np

geotiff = 'date1_date2.geo.unw.tif'
data = gdal.Open(geotiff).ReadAsArray()
data[data==0] = np.nan
print('STD: {:.2f} rad'.format(np.nanstd(data)))
```

**Comment by sizzer13** [comment]
This can be calculated the mean std. for the whole pair. Because I only got
one std. value (e.g. 3.92 rad.). How could we output the std. file for
every pixel?

**Comment by yumorishita** [comment]
I see. Assuming that the std can be calculated by (1-coh\*\*2)/(2*coh\*\*2) (e.g., Spaans and Hooper, 2016; https://doi.org/10.1002/2015JB012752):

```python
import gdal
import numpy as np

cc_geotiff = 'data1_data2.geo.cc.tif'
cc = gdal.Open(cc_geotiff).ReadAsArray().astype(np.float32)/255
cc[cc<0.01] = 0.01
cc[cc>0.99] = 0.99
std = np.sqrt((1-cc**2)/(2*cc**2))
```

**Comment by sizzer13** [comment]
Thank you for your answer.
I'm curious about why the cc values are grouped into < 0.01 and > 0.99 ?
Besides, why the cc value divides 255, and then use the results to calculate the std? I found cc values are limited into a range of -128 to 127. It means, after dividing 255, the cc value should be in a span of -0.50196 to 0.49803. I'm not sure they should be grouped into two groups by abs(cc) < 0.01 and abs(cc) > 0.99, right?

**Comment by yumorishita** [comment]
0.01 and 0.99 are just for avoiding infinity and zero division in std.

The format of cc is uint8 which ranges 0-255 (see below). Perhaps you have read the cc as int8

https://comet.nerc.ac.uk/comet-lics-portal-product-details/
“geo.cc.tif: This is the coherence image of the interferometric pair. The values varies between 0-255 in which 0 refers to the lowest coherence values and 255 indicates the highest values of coherence.”

**Comment by HN-Jiang** [comment]
Hi, I would like to know. If I prepare the geo.cc.tif for LiCSBAS by myself (Because LiCSAR don't cover my area). I should make the cc between 0-1 or 0-255? I use cc_wave and it give me the result is between 0-1. Do I need to change it to 0-255 for LiCSBAS?
Thank you

**Comment by yumorishita** [comment]
Either is fine because both formats can be handled.
https://github.com/yumorishita/LiCSBAS/blob/master/bin/LiCSBAS02_ml_prep.py#L425
https://github.com/yumorishita/LiCSBAS/blob/master/bin/LiCSBAS11_check_unw.py#L225
