### ISSUE TITLE
Problem in Gacos correction step

### ISSUE THREAD

**Issue by Hvmanshu** [yumorishita/LiCSBAS#120]
Dear sir, I am applying GACOS correction and I have yyyymmdd.ztd.rsc files in the GACOS directory. But in the processing step, most of the dates showing no valid data. Please guide me!
![Screenshot from 2021-07-19 15-57-18](https://user-images.githubusercontent.com/74150900/126105426-7722ef3c-918c-4c75-a774-c0a5da9deca5.png)

LiCSBAS03op_GACOS.py ver1.5.5 20201119 Y. Morishita
LiCSBAS03op_GACOS.py -i /home/himanshu/Downloads/DHR/129A_05935_131313/GEOCml1clip -o /home/himanshu/Downloads/DHR/129A_05935_131313/GEOml1*g -g /home/himanshu/Downloads/DHR/129A_05935_131313/g --fillhole

Convert ztd/sltd.geo.tif files to sltd.geo files...
  8 parallel processing...
  Finished    0/ 105th sltd...
    Use 20170308.ztd[.rsc]
    Use 20170519.ztd[.rsc]
    Use 20170823.ztd[.rsc]
    Use 20171221.ztd[.rsc]
  Finished   20/ 105th sltd...
    Use 20180315.ztd[.rsc]
    Use 20180514.ztd[.rsc]
    Use 20180713.ztd[.rsc]
    Use 20180830.ztd[.rsc]
    No valid data in 20180713.ztd! Skip.
    No valid data in 20170519.ztd! Skip.
    No valid data in 20180830.ztd! Skip.
    No valid data in 20180315.ztd! Skip.
    No valid data in 20170823.ztd! Skip.
    No valid data in 20170308.ztd! Skip.
    No valid data in 20171221.ztd! Skip.
    No valid data in 20180514.ztd! Skip.
    Use 20180102.ztd[.rsc]
    Use 20180911.ztd[.rsc]
    Use 20170718.ztd[.rsc]
    Use 20170928.ztd[.rsc]
    Use 20180327.ztd[.rsc]
    Use 20170320.ztd[.rsc]
    Use 20180526.ztd[.rsc]
    Use 20180725.ztd[.rsc]
    No valid data in 20180102.ztd! Skip.
    No valid data in 20170928.ztd! Skip.
    Use 20180114.ztd[.rsc]
  Finished   10/ 105th sltd...
    Use 20171103.ztd[.rsc]
    No valid data in 20180911.ztd! Skip.
  Finished   30/ 105th sltd...
    Use 20180923.ztd[.rsc]
    No valid data in 20170320.ztd! Skip.
    No valid data in 20180327.ztd! Skip.
    No valid data in 20170718.ztd! Skip.
    Use 20170401.ztd[.rsc]
    Use 20180408.ztd[.rsc]
    Use 20170730.ztd[.rsc]
    No valid data in 20180725.ztd! Skip.
    Use 20180806.ztd[.rsc]
    No valid data in 20180526.ztd! Skip.
    Use 20180607.ztd[.rsc]
    No valid data in 20170401.ztd! Skip.
    No valid data in 20170730.ztd! Skip.
    Use 20170811.ztd[.rsc]
    Use 20170413.ztd[.rsc]
    No valid data in 20171103.ztd! Skip.
    Use 20171209.ztd[.rsc]
    No valid data in 20180408.ztd! Skip.
    No valid data in 20180923.ztd! Skip.
    Use 20180420.ztd[.rsc]
    Use 20181005.ztd[.rsc]
    No valid data in 20180114.ztd! Skip.
    No valid data in 20180806.ztd! Skip.
    Use 20180818.ztd[.rsc]
    Use 20180303.ztd[.rsc]
    No valid data in 20180607.ztd! Skip.
    Use 20180701.ztd[.rsc]
    No valid data in 20170413.ztd! Skip.
    No valid data in 20171209.ztd! Skip.
    No valid data in 20180818.ztd! Skip.
    No valid data in 20180701.ztd! Skip.
    No valid data in 20180303.ztd! Skip.
    No valid data in 20170811.ztd! Skip.
    Use 20181017.ztd[.rsc]
    Use 20181204.ztd[.rsc]
  Finished   40/ 105th sltd...
    Use 20190121.ztd[.rsc]
    Use 20190310.ztd[.rsc]
    Use 20190427.ztd[.rsc]
    No valid data in 20181005.ztd! Skip.
    No valid data in 20180420.ztd! Skip.
    Use 20190614.ztd[.rsc]
    Use 20190801.ztd[.rsc]
  Finished   60/ 105th sltd...
    Use 20190918.ztd[.rsc]
    No valid data in 20181017.ztd! Skip.
    No valid data in 20190614.ztd! Skip.
    No valid data in 20181204.ztd! Skip.
    No valid data in 20190121.ztd! Skip.
    Use 20181029.ztd[.rsc]
    Use 20190626.ztd[.rsc]
    No valid data in 20190310.ztd! Skip.
    Use 20181216.ztd[.rsc]
    Use 20190202.ztd[.rsc]
    Use 20190322.ztd[.rsc]
    No valid data in 20190801.ztd! Skip.
    No valid data in 20190918.ztd! Skip.
    Use 20190813.ztd[.rsc]
    Use 20190930.ztd[.rsc]
    No valid data in 20190427.ztd! Skip.
    Use 20190509.ztd[.rsc]
    No valid data in 20181029.ztd! Skip.
    No valid data in 20190202.ztd! Skip.
    Use 20190214.ztd[.rsc]
    Use 20181110.ztd[.rsc]
    No valid data in 20190322.ztd! Skip.
    Use 20190403.ztd[.rsc]
    No valid data in 20181216.ztd! Skip.
    No valid data in 20190626.ztd! Skip.
    Use 20181228.ztd[.rsc]
    Use 20190708.ztd[.rsc]
    No valid data in 20190813.ztd! Skip.
    Use 20190825.ztd[.rsc]
    No valid data in 20190509.ztd! Skip.
  Finished   50/ 105th sltd...
    Use 20190521.ztd[.rsc]
    No valid data in 20190930.ztd! Skip.
    Use 20191012.ztd[.rsc]
    No valid data in 20190825.ztd! Skip.
    No valid data in 20181228.ztd! Skip.
    Use 20190906.ztd[.rsc]
    Use 20190109.ztd[.rsc]
    No valid data in 20190403.ztd! Skip.
    No valid data in 20190214.ztd! Skip.
    Use 20190415.ztd[.rsc]
    Use 20190226.ztd[.rsc]
    No valid data in 20190708.ztd! Skip.
    Use 20190720.ztd[.rsc]
    No valid data in 20181110.ztd! Skip.
    Use 20181122.ztd[.rsc]
    No valid data in 20190521.ztd! Skip.
    Use 20190602.ztd[.rsc]
    No valid data in 20191012.ztd! Skip.
    Use 20191024.ztd[.rsc]
    No valid data in 20190109.ztd! Skip.
    No valid data in 20190906.ztd! Skip.
    Use 20191105.ztd[.rsc]
    Use 20191223.ztd[.rsc]
    No valid data in 20190415.ztd! Skip.
    Use 20200209.ztd[.rsc]
    No valid data in 20190226.ztd! Skip.
    Use 20200328.ztd[.rsc]
    No valid data in 20190720.ztd! Skip.
    No valid data in 20191024.ztd! Skip.
  Finished   80/ 105th sltd...
    Use 20200515.ztd[.rsc]
    No valid data in 20190602.ztd! Skip.
    Use 20200702.ztd[.rsc]
    No valid data in 20181122.ztd! Skip.
    Use 20200819.ztd[.rsc]
    Use 20201006.ztd[.rsc]
    No valid data in 20191105.ztd! Skip.
    No valid data in 20191223.ztd! Skip.
    Use 20200104.ztd[.rsc]
    Use 20191117.ztd[.rsc]
    No valid data in 20200209.ztd! Skip.
    Use 20200221.ztd[.rsc]
    No valid data in 20200328.ztd! Skip.
    Use 20200409.ztd[.rsc]
    No valid data in 20201006.ztd! Skip.
    No valid data in 20200515.ztd! Skip.
    Use 20201018.ztd[.rsc]
    Use 20200527.ztd[.rsc]
    No valid data in 20200819.ztd! Skip.
    Use 20200831.ztd[.rsc]
    No valid data in 20200702.ztd! Skip.
    Use 20200714.ztd[.rsc]
    No valid data in 20191117.ztd! Skip.
    Use 20191129.ztd[.rsc]
    No valid data in 20200104.ztd! Skip.
  Finished   70/ 105th sltd...
    Use 20200116.ztd[.rsc]
    No valid data in 20200221.ztd! Skip.
    Use 20200304.ztd[.rsc]
    No valid data in 20201018.ztd! Skip.
    Use 20201030.ztd[.rsc]
    No valid data in 20200527.ztd! Skip.
    Use 20200608.ztd[.rsc]
    No valid data in 20200409.ztd! Skip.
    Use 20200421.ztd[.rsc]
    No valid data in 20200831.ztd! Skip.
  Finished   90/ 105th sltd...
    Use 20200912.ztd[.rsc]
    No valid data in 20200714.ztd! Skip.
    Use 20200726.ztd[.rsc]
    No valid data in 20200116.ztd! Skip.
    Use 20200128.ztd[.rsc]
    No valid data in 20191129.ztd! Skip.
    Use 20191211.ztd[.rsc]
    No valid data in 20200304.ztd! Skip.
    Use 20200316.ztd[.rsc]
    No valid data in 20201030.ztd! Skip.
    Use 20201111.ztd[.rsc]
    No valid data in 20200608.ztd! Skip.
    Use 20200620.ztd[.rsc]
    No valid data in 20200912.ztd! Skip.
    Use 20200924.ztd[.rsc]
    No valid data in 20200421.ztd! Skip.
    Use 20200503.ztd[.rsc]
    No valid data in 20200726.ztd! Skip.
    Use 20200807.ztd[.rsc]
    No valid data in 20200128.ztd! Skip.
    Use 20201123.ztd[.rsc]
    No valid data in 20191211.ztd! Skip.
  Finished  100/ 105th sltd...
    Use 20210110.ztd[.rsc]
    No valid data in 20200316.ztd! Skip.
    Use 20210311.ztd[.rsc]
    No valid data in 20201111.ztd! Skip.
    No valid data in 20200620.ztd! Skip.
    No valid data in 20200924.ztd! Skip.
    No valid data in 20200503.ztd! Skip.
    No valid data in 20200807.ztd! Skip.
    No valid data in 20201123.ztd! Skip.
    No valid data in 20210110.ztd! Skip.
    Use 20201205.ztd[.rsc]
    Use 20210122.ztd[.rsc]
    No valid data in 20210311.ztd! Skip.
    No valid data in 20210122.ztd! Skip.
    No valid data in 20201205.ztd! Skip.
    Use 20210203.ztd[.rsc]
    Use 20201217.ztd[.rsc]
    No valid data in 20201217.ztd! Skip.
    No valid data in 20210203.ztd! Skip.
    Use 20201229.ztd[.rsc]
    Use 20210215.ztd[.rsc]
    No valid data in 20201229.ztd! Skip.
    No valid data in 20210215.ztd! Skip.

Correct unw data...
  8 parallel processing...
  Finished    0/ 390th unw...
  ztd file not available for 20170308_20170401
  ztd file not available for 20170718_20170730
  ztd file not available for 20170308_20170413
  ztd file not available for 20171103_20171221
  ztd file not available for 20170718_20170823
  ztd file not available for 20170320_20170401
  ztd file not available for 20171103_20180102
  ztd file not available for 20170730_20170811
  ztd file not available for 20170320_20170413
  ztd file not available for 20171209_20171221
  ztd file not available for 20170730_20170823
  ztd file not available for 20170320_20170519
  ztd file not available for 20170730_20170928
  ztd file not available for 20171209_20180102
  ztd file not available for 20170811_20170823
  ztd file not available for 20170401_20170413
  Finished   30/ 390th unw...
  ztd file not available for 20180114_20180327
  ztd file not available for 20170811_20170928
  ztd file not available for 20170401_20170519
  ztd file not available for 20171209_20180114
  Finished   20/ 390th unw...
  ztd file not available for 20170413_20170519
  Finished   40/ 390th unw...
  ztd file not available for 20171221_20180102
  ztd file not available for 20170823_20170928
  ztd file not available for 20170413_20170718
  ztd file not available for 20180303_20180315
  ztd file not available for 20171221_20180114
  ztd file not available for 20170413_20170823
  ztd file not available for 20170823_20171209
  ztd file not available for 20171221_20180303
  Finished   10/ 390th unw...
  ztd file not available for 20180303_20180327
  ztd file not available for 20180327_20180514
  ztd file not available for 20170928_20171103
  ztd file not available for 20170519_20170718
  ztd file not available for 20180102_20180114
  ztd file not available for 20180303_20180408
  ztd file not available for 20170928_20171209
  ztd file not available for 20170519_20170730
  ztd file not available for 20180102_20180303
  ztd file not available for 20180327_20180526
  ztd file not available for 20180315_20180327
  ztd file not available for 20170928_20171221
  ztd file not available for 20170519_20170823
  ztd file not available for 20180102_20180315
  ztd file not available for 20180315_20180408
  ztd file not available for 20171103_20171209
  ztd file not available for 20180327_20180607
  ztd file not available for 20180114_20180303
  ztd file not available for 20180607_20180923
  ztd file not available for 20180315_20180420
  ztd file not available for 20180114_20180315
  ztd file not available for 20180327_20180911
  ztd file not available for 20180315_20180514
  ztd file not available for 20180806_20180818
  ztd file not available for 20180701_20180713
  ztd file not available for 20180327_20180923
  ztd file not available for 20180315_20180607
  Finished   80/ 390th unw...
  ztd file not available for 20180514_20180526
  ztd file not available for 20180408_20180420
  ztd file not available for 20180806_20180830
  ztd file not available for 20180315_20180911
  ztd file not available for 20180701_20180725
  ztd file not available for 20180408_20180514
  ztd file not available for 20180806_20180911
  ztd file not available for 20180514_20180607
  ztd file not available for 20180701_20180806
  ztd file not available for 20180315_20180923
  ztd file not available for 20180408_20180526
  Finished   50/ 390th unw...
  ztd file not available for 20180806_20180923
  ztd file not available for 20180701_20180818
  ztd file not available for 20180514_20180701
  Finished   60/ 390th unw...
  ztd file not available for 20180327_20180408
  ztd file not available for 20180818_20180830
  ztd file not available for 20180713_20180725
  ztd file not available for 20180408_20180607
  ztd file not available for 20180514_20180713
  ztd file not available for 20180327_20180420
  ztd file not available for 20180911_20181005
  ztd file not available for 20180818_20180911
  ztd file not available for 20180420_20180514
  ztd file not available for 20180526_20180607
  ztd file not available for 20180713_20180806
  ztd file not available for 20181005_20181122
  ztd file not available for 20180911_20181017
  Finished  130/ 390th unw...
  ztd file not available for 20181017_20181029
  Finished   70/ 390th unw...
  ztd file not available for 20180713_20180818
  ztd file not available for 20181122_20181204
  ztd file not available for 20181017_20181110
  ztd file not available for 20180911_20181029
  ztd file not available for 20180713_20180830
  Finished  120/ 390th unw...
  ztd file not available for 20181122_20181216
  ztd file not available for 20180911_20190310
  ztd file not available for 20180725_20180806
  ztd file not available for 20181017_20181122
  ztd file not available for 20180526_20180701
  ztd file not available for 20180911_20190322
  ztd file not available for 20180725_20180818
  ztd file not available for 20181017_20181204
  ztd file not available for 20181228_20190121
  ztd file not available for 20180526_20180713
  ztd file not available for 20181029_20181110
  ztd file not available for 20180420_20180526
  ztd file not available for 20181228_20190202
  ztd file not available for 20180526_20180725
  ztd file not available for 20181029_20181122
  ztd file not available for 20181228_20190214
  ztd file not available for 20180420_20180607
  ztd file not available for 20180607_20180701
  ztd file not available for 20181029_20181204
  ztd file not available for 20190109_20190121
  ztd file not available for 20180818_20180923
  ztd file not available for 20180420_20180701
  ztd file not available for 20180607_20180713
  ztd file not available for 20181029_20181216
  ztd file not available for 20190109_20190202
  ztd file not available for 20181122_20181228
  ztd file not available for 20180607_20180725
  ztd file not available for 20180923_20181017
  ztd file not available for 20180725_20180830
  ztd file not available for 20180818_20181005
  ztd file not available for 20181122_20190109
  ztd file not available for 20180607_20180806
  Finished  110/ 390th unw...
  Finished   90/ 390th unw...
  ztd file not available for 20181110_20181122
  ztd file not available for 20190109_20190214
  ztd file not available for 20181204_20181216
  ztd file not available for 20180607_20180911
  ztd file not available for 20180923_20181029
  ztd file not available for 20181204_20181228
  ztd file not available for 20190109_20190226
  ztd file not available for 20181110_20181204
  Finished  150/ 390th unw...
  ztd file not available for 20180923_20181110
  ztd file not available for 20181110_20181216
  ztd file not available for 20181204_20190109
  ztd file not available for 20181110_20181228
  ztd file not available for 20190121_20190202
  ztd file not available for 20181204_20190121
  ztd file not available for 20180923_20190310
  ztd file not available for 20190121_20190214
  ztd file not available for 20190202_20190310
  ztd file not available for 20181216_20181228
  ztd file not available for 20180923_20190322
  ztd file not available for 20190121_20190226
  ztd file not available for 20190202_20190322
  ztd file not available for 20181216_20190109
  ztd file not available for 20181005_20181017
  Finished  140/ 390th unw...
  ztd file not available for 20190310_20190602
  ztd file not available for 20190121_20190310
  Finished  170/ 390th unw...
  ztd file not available for 20190214_20190226
  ztd file not available for 20181005_20181029
  ztd file not available for 20181216_20190121
  ztd file not available for 20190310_20190614
  ztd file not available for 20190202_20190214
  ztd file not available for 20190310_20190626
  ztd file not available for 20190214_20190310
  ztd file not available for 20181005_20181110
  ztd file not available for 20190310_20190906
  ztd file not available for 20181216_20190202
  Finished  160/ 390th unw...
  ztd file not available for 20190202_20190226
  ztd file not available for 20190310_20190918
  ztd file not available for 20190310_20190930
  ztd file not available for 20190214_20190322
  ztd file not available for 20190322_20190930
  ztd file not available for 20181228_20190109
  ztd file not available for 20190322_20190403
  ztd file not available for 20190322_20190415
  ztd file not available for 20190403_20190415
  ztd file not available for 20190214_20190403
  ztd file not available for 20190322_20190427
  ztd file not available for 20190322_20190509
  ztd file not available for 20190322_20190614
  ztd file not available for 20190226_20190310
  ztd file not available for 20190403_20190427
  Finished  180/ 390th unw...
  ztd file not available for 20190509_20190521
  ztd file not available for 20190322_20190626
  ztd file not available for 20190614_20190708
  ztd file not available for 20190322_20190906
  ztd file not available for 20190226_20190403
  ztd file not available for 20190403_20190509
  ztd file not available for 20190509_20190602
  ztd file not available for 20190614_20190720
  ztd file not available for 20190403_20190521
  ztd file not available for 20190226_20190415
  ztd file not available for 20190708_20190801
  ztd file not available for 20190509_20190614
  Finished  210/ 390th unw...
  ztd file not available for 20190310_20190322
  ztd file not available for 20190415_20190427
  ztd file not available for 20190813_20190930
  ztd file not available for 20190614_20190801
  ztd file not available for 20190708_20190813
  ztd file not available for 20190509_20190626
  ztd file not available for 20190825_20190906
  ztd file not available for 20190310_20190403
  ztd file not available for 20190415_20190509
  ztd file not available for 20190825_20190918
  ztd file not available for 20190614_20190906
  ztd file not available for 20190708_20190825
  ztd file not available for 20190521_20190602
  ztd file not available for 20190825_20190930
  Finished  200/ 390th unw...
  ztd file not available for 20190415_20190521
  ztd file not available for 20190825_20191012
  ztd file not available for 20190310_20190415
  ztd file not available for 20190720_20190801
  ztd file not available for 20190614_20190918
  ztd file not available for 20190906_20190918
  ztd file not available for 20190521_20190614
  Finished  190/ 390th unw...
  Finished  240/ 390th unw...
  ztd file not available for 20190310_20190427
  ztd file not available for 20190906_20190930
  ztd file not available for 20190720_20190825
  ztd file not available for 20190614_20190930
  ztd file not available for 20190415_20190602
  ztd file not available for 20190521_20190626
  ztd file not available for 20190906_20191012
  ztd file not available for 20190906_20191024
  ztd file not available for 20190720_20190906
  ztd file not available for 20190626_20190708
  ztd file not available for 20190521_20190708
  ztd file not available for 20190906_20200328
  ztd file not available for 20190427_20190509
  ztd file not available for 20190918_20190930
  ztd file not available for 20190801_20190813
  ztd file not available for 20190602_20190614
  ztd file not available for 20190626_20190720
  ztd file not available for 20190918_20191012
  ztd file not available for 20190427_20190521
  ztd file not available for 20190918_20191024
  ztd file not available for 20190801_20190825
  ztd file not available for 20190602_20190626
  ztd file not available for 20190626_20190801
  ztd file not available for 20190427_20190602
  ztd file not available for 20190918_20191105
  ztd file not available for 20190801_20190906
  ztd file not available for 20190602_20190708
  ztd file not available for 20190626_20190813
  Finished  260/ 390th unw...
  Finished  230/ 390th unw...
  ztd file not available for 20190427_20190614
  ztd file not available for 20190918_20200304
  ztd file not available for 20191024_20191105
  ztd file not available for 20190626_20190918
  ztd file not available for 20190602_20190720
  ztd file not available for 20190801_20190918
  ztd file not available for 20191024_20191117
  ztd file not available for 20190918_20200328
  ztd file not available for 20191024_20191129
  ztd file not available for 20190626_20190930
  ztd file not available for 20190614_20190626
  ztd file not available for 20190813_20190825
  ztd file not available for 20191024_20191211
  Finished  250/ 390th unw...
  Finished  220/ 390th unw...
  ztd file not available for 20191105_20191117
  ztd file not available for 20190930_20191012
  ztd file not available for 20190813_20190906
  ztd file not available for 20191105_20191129
  ztd file not available for 20190708_20190720
  ztd file not available for 20191105_20191211
  ztd file not available for 20190930_20191024
  ztd file not available for 20191129_20191223
  ztd file not available for 20191105_20191223
  ztd file not available for 20190813_20190918
  ztd file not available for 20191117_20191129
  ztd file not available for 20191117_20191211
  ztd file not available for 20191129_20200104
  ztd file not available for 20190930_20191105
  Finished  270/ 390th unw...
  ztd file not available for 20200104_20200209
  ztd file not available for 20191117_20191223
  ztd file not available for 20191129_20200116
  ztd file not available for 20190930_20191117
  ztd file not available for 20191117_20200104
  ztd file not available for 20191129_20191211
  ztd file not available for 20200104_20200221
  ztd file not available for 20200209_20200328
  ztd file not available for 20191211_20191223
  ztd file not available for 20190930_20200316
  Finished  300/ 390th unw...
  ztd file not available for 20200116_20200128
  ztd file not available for 20200316_20200503
  ztd file not available for 20200221_20200304
  ztd file not available for 20190930_20200328
  ztd file not available for 20191211_20200104
  ztd file not available for 20200421_20200527
  ztd file not available for 20200116_20200209
  ztd file not available for 20200221_20200316
  ztd file not available for 20200316_20200608
  ztd file not available for 20200421_20200608
  ztd file not available for 20191211_20200116
  ztd file not available for 20191012_20191024
  Finished  290/ 390th unw...
  ztd file not available for 20200503_20200515
  ztd file not available for 20200221_20200328
  ztd file not available for 20200503_20200527
  ztd file not available for 20200316_20200620
  ztd file not available for 20200116_20200221
  ztd file not available for 20191211_20200128
  ztd file not available for 20191012_20191105
  ztd file not available for 20200503_20200608
  Finished  330/ 390th unw...
  Finished  280/ 390th unw...
  ztd file not available for 20200116_20200304
  ztd file not available for 20200221_20200409
  ztd file not available for 20200328_20200409
  ztd file not available for 20200503_20200620
  ztd file not available for 20191012_20191117
  ztd file not available for 20191223_20200104
  ztd file not available for 20200515_20200527
  ztd file not available for 20200304_20200316
  ztd file not available for 20200128_20200209
  ztd file not available for 20200328_20200421
  ztd file not available for 20200515_20200608
  ztd file not available for 20191012_20191129
  ztd file not available for 20191223_20200116
  ztd file not available for 20200515_20200620
  ztd file not available for 20200128_20200221
  ztd file not available for 20200304_20200328
  ztd file not available for 20200328_20200503
  ztd file not available for 20200515_20200702
  ztd file not available for 20191223_20200128
  ztd file not available for 20200527_20200608
  ztd file not available for 20200304_20200409
  ztd file not available for 20200128_20200304
  ztd file not available for 20200527_20200702
  ztd file not available for 20200328_20200515
  ztd file not available for 20191223_20200209
  ztd file not available for 20200527_20200714
  ztd file not available for 20200128_20200316
  ztd file not available for 20200304_20200421
  ztd file not available for 20200328_20200620
  ztd file not available for 20200104_20200116
  Finished  320/ 390th unw...
  ztd file not available for 20200608_20200620
  ztd file not available for 20200304_20200608
  ztd file not available for 20200209_20200221
  ztd file not available for 20200409_20200421
  ztd file not available for 20200104_20200128
  ztd file not available for 20200714_20200819
  ztd file not available for 20200608_20200702
  ztd file not available for 20200209_20200304
  ztd file not available for 20200304_20200620
  ztd file not available for 20200726_20200807
  ztd file not available for 20200409_20200503
  Finished  340/ 390th unw...
  Finished  310/ 390th unw...
  ztd file not available for 20200726_20200819
  ztd file not available for 20200209_20200316
  ztd file not available for 20200726_20200912
  ztd file not available for 20200608_20200714
  ztd file not available for 20200316_20200328
  ztd file not available for 20200409_20200515
  ztd file not available for 20200807_20200819
  ztd file not available for 20200608_20200726
  ztd file not available for 20200421_20200503
  ztd file not available for 20200316_20200409
  ztd file not available for 20200807_20200924
  ztd file not available for 20200421_20200515
  ztd file not available for 20200924_20201006
  ztd file not available for 20180725_20180911
  ztd file not available for 20201205_20201217
  ztd file not available for 20200819_20200831
  ztd file not available for 20200924_20201111
  ztd file not available for 20200819_20201006
  ztd file not available for 20201205_20210122
  ztd file not available for 20200924_20210311
  ztd file not available for 20200831_20200912
  ztd file not available for 20201217_20201229
  Finished  360/ 390th unw...
  Finished  380/ 390th unw...
  ztd file not available for 20201006_20201018
  ztd file not available for 20200831_20201018
  ztd file not available for 20201217_20210203
  ztd file not available for 20180830_20180911
  ztd file not available for 20201006_20201123
  ztd file not available for 20200912_20200924
  ztd file not available for 20200620_20200702
  ztd file not available for 20201229_20210110
  Finished  100/ 390th unw...
  ztd file not available for 20201018_20201030
  ztd file not available for 20200912_20201030
  ztd file not available for 20201229_20210215
  Finished  370/ 390th unw...
  ztd file not available for 20200620_20200714
  ztd file not available for 20180830_20180923
  ztd file not available for 20200912_20210311
  ztd file not available for 20210110_20210122
  ztd file not available for 20201018_20201205
  ztd file not available for 20200620_20200726
  ztd file not available for 20180830_20181005
  ztd file not available for 20210110_20210311
  ztd file not available for 20201030_20201111
  ztd file not available for 20200620_20200807
  ztd file not available for 20180830_20181017
  ztd file not available for 20210122_20210203
  ztd file not available for 20180911_20180923
  ztd file not available for 20200702_20200714
  ztd file not available for 20210122_20210311
  ztd file not available for 20210203_20210215
  ztd file not available for 20200702_20200726
  ztd file not available for 20210203_20210311
  ztd file not available for 20200702_20200807
  ztd file not available for 20210215_20210311
  ztd file not available for 20200714_20200726
  Finished  350/ 390th unw...
  ztd file not available for 20200714_20200807
  ztd file not available for 20201030_20201217
  ztd file not available for 20201111_20201123
  ztd file not available for 20201111_20201229
  ztd file not available for 20201123_20201205
  ztd file not available for 20201123_20210110

Traceback (most recent call last):
  File "/home/himanshu/Downloads/DHR/129A_05935_131313/LiCSBAS/bin/LiCSBAS03op_GACOS.py", line 550, in <module>
    sys.exit(main())
  File "/home/himanshu/Downloads/DHR/129A_05935_131313/LiCSBAS/bin/LiCSBAS03op_GACOS.py", line 369, in main
    plot_lib.plot_gacos_info(gacinfofile, pngfile)
  File "/home/himanshu/Downloads/DHR/129A_05935_131313/LiCSBAS/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 147, in plot_gacos_info
    xylim1 = np.max(np.concatenate((std_bf, std_af)))+1
  File "<__array_function__ internals>", line 5, in amax
  File "/home/himanshu/.conda/envs/licsbas/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2754, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/home/himanshu/.conda/envs/licsbas/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by yumorishita** [comment]
Perhaps the area of the GACOS data does not cover the processing area? Please check the rsc file.

**Comment by Hvmanshu** [comment]
Thank you sir for your guidence, now it is working prefectly.
