### ISSUE TITLE
Error when dowloading the .unw file

### ISSUE THREAD

**Issue by zhiqiang513** [yumorishita/LiCSBAS#121]
Dear Yu, thanks for establishing such a powerful tool to process the InSAR time series . 
I have one problem with the preparation step , I am confused that why in some folders ,the unw files are missing  which result in  the failure of downloading unw files in  LiCSBAS  step 1,  and is it necessary in the following  processing steps? should I pay attention to it ?
![image](https://user-images.githubusercontent.com/82689775/127154193-3bb25679-00ee-4b71-ae1d-863a5c059964.png)
![image](https://user-images.githubusercontent.com/82689775/127154365-dfea304e-1dec-42df-adc6-58a89d69ee72.png)
![image](https://user-images.githubusercontent.com/82689775/127154344-3aa50e73-d64a-4953-aa99-8673e6375ce5.png)
As you can see .the folder in the first picture missed the .unw file which  is need for  LiCSBAS step 1

**Comment by yumorishita** [comment]
I guess just a few missing unw data do not significantly affect the result.

To fill the missing data, reprocessing in the LiCSAR system is required. Please contact to COMET if you need the missing unw data.
