### ISSUE TITLE
Export to GeoTIFF

### ISSUE THREAD

**Issue by NKakar** [yumorishita/LiCSBAS#122]
Dear Yumorishita,

I would like to export the final results to tiff files and develop plots using QGIS or etc. I see the deformation is less compare to the time series in LiCSBAS. e.g the deformation of ~14cm over the period of 4 years is around 2.7cm in the exported tiff file. I think, there is some sort of average values during the export e.g 14cm/5yrs = 2.7???

Is it possible to export the final cumulative deformation rates with of the tiff files?

Best, 
Najib

**Comment by yumorishita** [comment]
I guess you exported the velocity (unit in mm/yr). What do you mean by "the final cumulative deformation rates"? Cumulative deformation from the first epoch to the last epoch, or deformation rate (i.e., velocity) estimated from all epochs? The former can be created by LiCSBAS_cum2flt.py, and the latter is probably what you exported.

**Comment by NKakar** [comment]
Thank you very much for the quick response, I was able to solve the problem. I wanted to have the cumulative results for the tiff files not mm/yr. I was able to achieve it easily. I just needed to follow the instruction in the Wiki.
