### ISSUE TITLE
Problem in Install LiCSBAS

### ISSUE THREAD

**Issue by PeiyanXi** [yumorishita/LiCSBAS#126]
Dear sir, I have installed anaconda and set up the path of LiCSBAS, but this problem still occurs
![1631762642(1)](https://user-images.githubusercontent.com/88068467/133544379-e313ad26-a5d4-4e17-a21d-fb4fe02d6cd5.png)

**Comment by yumorishita** [comment]
You must install gdal, e.g., by `conda install gdal`.
https://github.com/yumorishita/LiCSBAS/wiki/1_Installation#example-1-using-anaconda

I cannot identify the reason why the PYTHONPATH is not set from this screenshot. Does LiCSBAS_io_lib.py exist in /data1/std2/LiCSBAS/LiCSBAS/LiCSBAS_lib?
