### ISSUE TITLE
parameter's setting

### ISSUE THREAD

**Issue by faranab** [yumorishita/LiCSBAS#13]
Dear all
I'm a little bit new to python and I'm interested in SAR time series analysis. I have faced this issue, can you give me an idea to fix this problem?
I don't know where can I change the parameters in the batch (which parameters and which lines)file to get the correct result.
![problem](https://user-images.githubusercontent.com/44191721/82722761-bf0a0880-9cde-11ea-8d39-ed90058a4405.png)

**Comment by yumorishita** [comment]
As the log says "All pixels would be masked with n_ifg_noloop thre of 10", you should change the parameter of n_ifg_noloop from 10 (default) to e.g. 50 on L49 in batch_LiCSBAS.sh.

https://github.com/yumorishita/LiCSBAS/blob/04700112acec7c120dfd9c1a1243aa5f1f12e018/batch_LiCSBAS.sh#L49

Also you can change the start_step to 15 on L19 in batch_LiCSBAS.sh to start from step15 at which the error occurred.

https://github.com/yumorishita/LiCSBAS/blob/04700112acec7c120dfd9c1a1243aa5f1f12e018/batch_LiCSBAS.sh#L19

**Comment by ederliga07** [comment]
![Issue](https://user-images.githubusercontent.com/60079150/108444052-e3702280-7227-11eb-8a19-b5acb828753a.jpg)
Hi I have some simillar problem can u help me please? its an emergency. I already change the L49 to 50 but still not working

**Comment by yumorishita** [comment]
Change of the L49 and L50 does not seem to be working. Perhaps you edited a different file? Please check again the file you edited and ran.

**Comment by ederliga07** [comment]
[batch_LiCSBAS.zip](https://github.com/yumorishita/LiCSBAS/files/6007649/batch_LiCSBAS.zip)
I only edit L49 with 50
Please give me a hand

**Comment by yumorishita** [comment]
Try p15_n_ifg_noloop_thre="200"
