### ISSUE TITLE
LICSBAS_get_geotiff.py Error

### ISSUE THREAD

**Issue by javadhatamiafko** [yumorishita/LiCSBAS#130]
![image](https://user-images.githubusercontent.com/79446318/135674585-a6dec533-b208-4a3a-9906-f2d6d3b23df7.png)

**Comment by yumorishita** [comment]
Can you try using python3.8?
What is your OS (Linux, Windows, or Mac) and its version?

**Comment by javadhatamiafko** [comment]
python version is Python 3.8.8 .Also I using windows 10

**Comment by yumorishita** [comment]
But your log shows "Python39". Are you sure that you are using 3.8.11?
I am not a windows user and cannot guarantee the normal operation on windows. I recommend using Linux by WSL, VM ware, or VirtualBox.

**Comment by yumorishita** [comment]
See also https://github.com/yumorishita/LiCSBAS/issues/85#issuecomment-863040843
