### ISSUE TITLE
How to check the coords for the automatic reference point

### ISSUE THREAD

**Issue by cglanchares** [yumorishita/LiCSBAS#133]
Hi! How can I check the exact coords for the automatic reference point that LiCSBAS selects?Thank you!

**Comment by yumorishita** [comment]
The lat lon values of the reference point are written in info/16ref.kml.

**Comment by cglanchares** [comment]
Great Thank you! on more question, If I generate a CSV file with the Coords and interferograms veolocities; I thought first line are the reference point, but inmost of the cases these coords are 0,0, ¿What does this information really is?. 

Thank you!

**Comment by cglanchares** [comment]
Thank you very much!
