### ISSUE TITLE
Question about comparability of InSAR and GPS velocities

### ISSUE THREAD

**Issue by Hvmanshu** [yumorishita/LiCSBAS#134]
Dear sir, Can we compare InSAR decompose i.e. EW and UD velocities directly to the GPS ITRF velocity or we have to do something.

**Comment by yumorishita** [comment]
InSAR and GNSS velocities should have a common reference. Weiss et al. (2020) may be helpful;
https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2020GL087376#grl60856-sec-0003-title
