### ISSUE TITLE
Band Dates of Tiff or H5

### ISSUE THREAD

**Issue by ahmetselimboyali** [yumorishita/LiCSBAS#136]
While creating graphs with Qgis with tiff or H5 file the X axis comes with Band Numbers. But while creating graphs with licsbas_plot_ts.py the x axis shown as dates. Is there anyway to show dates on Qgis from Tiff or H5 file?

**Comment by yumorishita** [comment]
I may not understand your question correctly, but this might help:
https://github.com/yumorishita/LiCSBAS/wiki/3_visualization#prototype-licsbas_out2ncpy

**Comment by ahmetselimboyali** [comment]
Thank you for reply. In addition to this solution I exported the tables as csv, match the numbers to dates and created graphs separately on plotly.
![resim](https://user-images.githubusercontent.com/32059584/144750006-e9e856e0-480d-4814-9420-efe5663dd84e.png)
