### ISSUE TITLE
LiCSBAS11_check_unw.py Nan error

### ISSUE THREAD

**Issue by zachzen** [yumorishita/LiCSBAS#137]
Dear professor,
  I got some unexpected error in step 11 as following img
it shows all of my unw. cc value is Nan . it's a little weird . Because I can clip my data by cc file in Step
My unw&cc file is under float32 of geotiff (I had tried to convert my cc file into byte[0,255] but it did't work) 
![image](https://user-images.githubusercontent.com/33368807/146373449-c01870ca-5df7-4cf2-9bc5-c7b1db9a5672.png)

**Comment by yumorishita** [comment]
Can you upload the full log file?

**Comment by zachzen** [comment]
Besides,I doubted that if the problem is about my IFG network .
For test, I only use the 12/d period for IFG 
![image](https://user-images.githubusercontent.com/33368807/146386739-ed9a2dd3-3bc7-444a-b8a1-12b6415477f9.png)
it seems to be not closure . Does it Influence the step 11.12 ?

**Comment by yumorishita** [comment]
LiCSBAS needs at least one loop. Please try adding an interferogram to make a loop.

**Comment by zachzen** [comment]
It works after adding the new ifg pairs! 
Thank you
