### ISSUE TITLE
LiCSBAS data processing

### ISSUE THREAD

**Issue by wuxiantan-chenxiaoli** [yumorishita/LiCSBAS#138]
Dear yumorishita
, 
I've been studying LiSBAS, is now in the experiment, I found in the experiments, each step will appear in a certain node caton, not even running, especially such as (195/198) will stop running. Thank you
#
![QQ截图20211222193110](https://user-images.githubusercontent.com/64968912/147086488-d70a4de2-424c-460a-97a8-833e60b57eed.png)

**Comment by yumorishita** [comment]
Have you tried several times? Does it always stop at the same point?

**Comment by wuxiantan-chenxiaoli** [comment]
Yes, many times, don't know if my computer configuration problem, every step is always the same, will run into such as (310/314). Thank you, teacher, for your guidance

**Comment by wuxiantan-chenxiaoli** [comment]
![QQ截图20211223113100](https://user-images.githubusercontent.com/64968912/147183963-8a0f4071-7514-4776-b8c1-157237d64871.png)
he experiment again, also is such, (271/271) in fact, it is not in the end, has been pause here

**Comment by yumorishita** [comment]
What is the frame ID?

**Comment by wuxiantan-chenxiaoli** [comment]
128A_05769_131313

**Comment by wuxiantan-chenxiaoli** [comment]
I don't know if he deal with not in time order, when he handles to the most close to the end of the value of time is not running, but actually he is not processed, I changed the ubuntu version, even in the computer is like this. I really don't know what the reason is. I hope the teacher can help me solve it.

**Comment by yumorishita** [comment]
The log "(271/271)" means all files have been downloaded. Please try running again without removing the downloaded files.

**Comment by wuxiantan-chenxiaoli** [comment]
I have this problem every step of the way, but by the time of this 1-2 step, a command that runs this step will always be stuck in this place.

**Comment by wuxiantan-chenxiaoli** [comment]
Dear teacher, I think I have found my own reason. This software requires a large amount of memory. I used to set the memory as 4 G, but now I set it as 16G. Thank you teacher for answering my question.
