### ISSUE TITLE
Error in Step02

### ISSUE THREAD

**Issue by sizzer13** [yumorishita/LiCSBAS#14]
Hi,
I met a problem in the Step02:
ERROR 1: 
/004D_04916_131313/GEOC/20161217_20170209/20161217_20170209.geo.unw.tif:Failed to allocate memory for to read TIFF directory (0 elements of 12 bytes each)
ERROR 1: TIFFReadDirectory:Failed to read directory at offset 28408512
  20161217_20170209.geo.unw.tif cannot open. Skip
  No 20170209_20170428.geo.unw.tif found. Skip
  No 20170311_20170428.geo.unw.tif found. Skip
  No 20170428_20170709.geo.unw.tif found. Skip
  No 20180926_20181020.geo.unw.tif found. Skip
  No 20181020_20181101.geo.unw.tif found. Skip
  No 20181020_20181113.geo.unw.tif found. Skip
  No 20181020_20181125.geo.unw.tif found. Skip
  No 20181020_20181207.geo.unw.tif found. Skip
  No 20190406_20190605.geo.unw.tif found. Skip
   10/ 21th IFG...
  No 20190418_20190617.geo.unw.tif found. Skip
  No 20190430_20190629.geo.unw.tif found. Skip
  No 20191214_20200131.geo.unw.tif found. Skip
  No 20191226_20200131.geo.unw.tif found. Skip
  No 20200107_20200131.geo.unw.tif found. Skip
  No 20200119_20200131.geo.unw.tif found. Skip
  No 20200131_20200212.geo.unw.tif found. Skip
  No 20200131_20200224.geo.unw.tif found. Skip
  No 20200131_20200307.geo.cc.tif found. Skip
  No 20200131_20200319.geo.unw.tif found. Skip
   20/ 21th IFG...
  No 20200212_20200412.geo.unw.tif found. Skip

Copy baselines file
ERROR: bperp for 20150310 not found!
  baselines file found, but not complete. Make dummy

This is the first time for me to meet this kind of error in the step02, in which runs very well and never happens before. I don't know it is because of lack of data, or something else?

**Comment by yumorishita** [comment]
This problem stems from LiCSAR products, not LiCSBAS. The interferograms shown in the log must be reprocessed by LiCSAR. Please report to “LiCSAR frame request” on the COMET-LiCS-portal web (https://comet.nerc.ac.uk/comet-lics-portal/). 

You can check if the LiCSAR products are correctly exist or not:
http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/4/004D_04916_131313/interferograms/
