### ISSUE TITLE
ISSUE WITH STEP 2 OF BATCH PROCESSING

### ISSUE THREAD

**Issue by schandandey** [yumorishita/LiCSBAS#140]
Thank you for the brilliant program. However, I am facing an issue with the batch processing (may be case with the selected frame ID or that I'm running the program in virtual box ubuntu).

While trying batch processing (I left all the parameters to default), the second step, i.e. LiCSBAS02_ml_prep.py, causes a few errors for my selected frame id (041A_06428_131313) and the program is interrupted. Following log may aid in identifying the problem:

Elapsed time: 00h 05m 34s

LiCSBAS01_get_geotiff.py Successfully finished!!

Output directory: /home/vsys/041A_06428_131313/GEOC

LiCSBAS02_ml_prep.py ver1.7.4 20201119 Y. Morishita
LiCSBAS02_ml_prep.py -i GEOC -n 1

Create E.geo
  E.geo created

Create N.geo
  N.geo created

Create U.geo
  U.geo created

Create slc.mli
ERROR 1: TIFFFillStrip:Read error at scanline 752; got 7741 bytes, expected 10379
ERROR 1: TIFFReadEncodedStrip() failed.
ERROR 1: /home/vsys/041A_06428_131313/GEOC/041A_06428_131313.geo.mli.tif, band 1: IReadBlock failed at X offset 0, Y offset 753: TIFFReadEncodedStrip() failed.
Traceback (most recent call last):
  File "/home/vsys/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 453, in <module>
    sys.exit(main())
  File "/home/vsys/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 222, in main
    mli[mli==0] = np.nan
TypeError: 'numpy.float32' object does not support item assignment

________

Thanks

**Comment by yumorishita** [comment]
I could not reproduce the error. Probably the GeoTIFF file is corrupted. Please try removing /home/vsys/041A_06428_131313/GEOC/041A_06428_131313.geo.mli.tif and restarting from step01 again.

**Comment by schandandey** [comment]
Dear Dr. Morishita,

The suggestion worked perfectly. I am much obliged. Thank you.
