### ISSUE TITLE
LiCSBAS16_filt_ts.py keeps indefinitely running without result

### ISSUE THREAD

**Issue by schandandey** [yumorishita/LiCSBAS#141]
The LiCSBAS16_filt_ts.py is taking too much time to process without any result. I'm using an ubuntu system installed in virtual box with 20 gb RAM assigned and 8 CPU cores. I had waited for more than 2 days to see if it finishes execution. However, it remained stuck at at he same point. I have tried it for several data frames and found the issue for all. The following log may be useful in understanding the issue:

LiCSBAS16_filt_ts.py ver1.5.1 20210311 Y. Morishita
LiCSBAS16_filt_ts.py -t TS_GEOCml1

Size of image (w,l)      : 2950, 2713
Number of images         : 41
Width of filter in space : 2 km (19.9x18.0 pixel)
Width of filter in time  : 0.227 yr (82 days)
Deramp flag              : []
hgt-linear flag          : False

HP filter in time, LP filter in space,
with 8 parallel processing...
    0/ 41th image...
   10/ 41th image...
   20/ 41th image...
   30/ 41th image...
   40/ 41th image...

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/62
https://github.com/yumorishita/LiCSBAS/issues/86

**Comment by schandandey** [comment]
Thank you, Dr. Morishita. Assigning n_para to 1 fixed the problem. And, accept my apologies for failing to notice the highlighted issues.
