### ISSUE TITLE
Command "eog" not found

### ISSUE THREAD

**Issue by ZachJon1** [yumorishita/LiCSBAS#142]
Hi,

I am having issues running commands related to "eog". For example, I run into errors when I tried using "sudo apt install eog" Also, using "apt-get update" I ran into problems with permissions.

See the images for context.
Initial error involving using eog command

![WM-Screenshots-20220304002410](https://user-images.githubusercontent.com/59528459/156705126-7d0a951f-afbf-460e-b907-f9e5a2c1c81f.png)

Sudo apt install error:
![sudo apt install eog](https://user-images.githubusercontent.com/59528459/156705208-3c749b08-c11d-4c9f-8e20-b4870ae1eff4.png)

apt update error:
![apt update](https://user-images.githubusercontent.com/59528459/156705248-5b81030e-6aa9-4e15-ba27-1491d9067e3d.png)

Thanks

**Comment by yumorishita** [comment]
You can use any other commands (e.g, gimp) to display images instead of eog. I have no idea about the eog installation problem because it is irrelevant to LiCSBAS.

**Comment by ZachJon1** [comment]
Thanks
