### ISSUE TITLE
JupyterNotebook-Possibility

### ISSUE THREAD

**Issue by NKakar** [yumorishita/LiCSBAS#143]
**Dear Morishita,** 
Is there any possibility to provide the step by step code (LiCSBAS) using Jupyternotebook?
Best, 
Najib

**Comment by yumorishita** [comment]
Sorry, but I have no plan to do so. Instead, the check_only option in the batch_LiCSBAS.sh returns the step-by-step commands without running the programs and can do the same thing as the Jupyternotebook.
https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/batch_LiCSBAS.sh#L26
