### ISSUE TITLE
LiCSBAS command not found after installation

### ISSUE THREAD

**Issue by Surfix** [yumorishita/LiCSBAS#144]
I am having issue using this package. I successfully installed it but when I call any command, I get an error. 
"[/bin/bash](): LiCSBAS01_get_geotiff.py: command not found'

I guess it is related to path setting but I have no idea how to go about it. Kindly suggest what to do. 
Thanks.

**Comment by NKakar** [comment]
Hello, 
Were you able to successfully source the location?
as followings:
source <your_LiCSBAS_path>/LiCSBAS/bashrc_LiCSBAS.sh

**Comment by Surfix** [comment]
Thank you @NKakar 
The LicSBAS_Path on my computer is '[/home/naheemadebisi/PhD/git_workspace/LiCSBAS]'. So I did: source /home/naheemadebisi/PhD/git_workspace/LiCSBAS/bashrc_LiCSBAS.sh

I did that in the terminal while my licsbas env is still activated. I noticed another instruction on the installation page-You may add the line above to your ~/.bashrc or ~/.bash_profile. I don't quiet understand this.

Thanks

**Comment by Surfix** [comment]
![image](https://user-images.githubusercontent.com/51313944/159293548-dbba642a-dbde-47be-92ee-2523ffb8b237.png)
Thank you @NKakar , I added the path as shown above but the error still persist. Is there anything else that I am missing

![image](https://user-images.githubusercontent.com/51313944/159293825-23b2b43b-c49f-4793-9d8f-63acb8bd612a.png)
