### ISSUE TITLE
I got an error running the LiCSBAS12_loop_closure. py.

### ISSUE THREAD

**Issue by DYY429** [yumorishita/LiCSBAS#145]
Dear author,  
Hello!  I got an error running the LiCSBAS12_loop_closure. py.  Licsbas_tools_lib. py failed because n_loop=0.  All the previous runs were successful and the results were obtained. Now I don't know why this error occurred.  
![n_loop](https://user-images.githubusercontent.com/59045809/160040646-d44c6df0-b52e-411f-9480-88c8ca306f76.png)

**Comment by yumorishita** [comment]
Please try increasing the interferograms or using lower thresholds in step1-1.
