### ISSUE TITLE
Gacos and clipping

### ISSUE THREAD

**Issue by vikrumar** [yumorishita/LiCSBAS#146]
Hi,
Any idea why the scene is cut in the weird rectangle while using GACOS?
I checked the gacos images already and it seems fine. The problem happens only when i use gacos correctio
![mask_ts](https://user-images.githubusercontent.com/104144139/164458879-5eaba872-ae15-475a-a3a0-5f1eb003b8b3.png)
n

**Comment by yumorishita** [comment]
Please visually check the TS_GEOCml*/12ifg_ras/*.unw.png. I guess most of the unw data have valid values only in the weird rectangle.

**Comment by vikrumar** [comment]
Yes. Thats true. But its happening only when I am using gacos. Otherwise
the process is ok. Attaching both for reference

**Comment by yumorishita** [comment]
I cannot find any attached files. Please also see GEOCml*GACOS/*/*.gacos.png, which shows how the GACOS correction worked.

**Comment by vikrumar** [comment]
Oops sorry. Attaching them again. Yes the gacos fil
![20211222_20211228 gacos](https://user-images.githubusercontent.com/104144139/164878069-2157958e-2f94-45aa-a04e-fc8f9f2d7e31.png)
![20180106_20180112_without_gacos unw](https://user-images.githubusercontent.com/104144139/164878071-b87e81e1-f90a-42c7-9c28-52bf7a4760b0.png)
![20180307_20180406_with_gacos unw](https://user-images.githubusercontent.com/104144139/164878073-ddcb0db4-9789-4050-8003-071921b8f9a1.png)
es are also cut

**Comment by yumorishita** [comment]
This means the GACOS data do not cover the entire area. I would recommend getting the GACOS data again with the expanded area.
