### ISSUE TITLE
  Does this code have splicing function

### ISSUE THREAD

**Issue by ThreeIcug** [yumorishita/LiCSBAS#147]
Dear author,
LiCSBAS have provided a very convenient and fast method to get the time series of InSAR.  Because the earthquake happened at the junction of the two images. A single image can't show all of the influence region.  Does this code have a splicing function. I read the wiki ,but i can't find it.

**Comment by yumorishita** [comment]
The input GeoTIFF files can be merged by [gdal_marge.py](https://gdal.org/programs/gdal_merge.html).

**Comment by ThreeIcug** [comment]
Yes, I merge the data, the problem that you realized is happened.
![Screenshot from 2022-05-07 22-55-47](https://user-images.githubusercontent.com/47657302/167259776-1d649370-0a95-4f94-b93d-d5faa5f79a92.png)
How can I remove the phase biases.

**Comment by yumorishita** [comment]
Compute the phase difference in the overlapping area and its average (e.g., by gdal_calc.py), then subtract the average from the one data. I am not sure if this works well.
Otherwise, you could produce the interferograms covering the area of interest from the SLC yourself.
