### ISSUE TITLE
Infinite Processing @ LiCSBAS16_filt_ts.py -t TS_GEOCml1GACOS

### ISSUE THREAD

**Issue by rakeshgosain** [yumorishita/LiCSBAS#148]
Hello Prof Yu,

I am newbie to LiCSBAS, so apologizes for any silly query.

I am trying to run a batch_LiCSBAS.sh file for trial (batch file attached). All commands runs okay for me but command "LiCSBAS16_filt_ts.py -t TS_GEOCml1GACOS" is running without producing any output (seems never ending process). I have also attached Log file. [202204301035batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/8596536/202204301035batch_LiCSBAS_01_16.log)

[Log_batchfile.zip](https://github.com/yumorishita/LiCSBAS/files/8596539/Log_batchfile.zip)
My system config is as follows:

OS : Ubuntu 20.04.3 LTS 64bit
GENOME version: 3.36.8
RAM : 16GB 
Processor: AMD® Ryzen 5 5500u with radeon graphics × 12
Disk Space: 512.1 GB (SSD)

Any help will be appreciated.

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/62
https://github.com/yumorishita/LiCSBAS/issues/86
https://github.com/yumorishita/LiCSBAS/issues/141

**Comment by rakeshgosain** [comment]
Thank you Prof. Yu, for prompt response and sharing the relevant issues thread.
Now it is working..
Appreciate your efforts and support.
