### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: 

### ISSUE THREAD

**Issue by Gautam5673** [yumorishita/LiCSBAS#149]
Hello Sir!
I'm getting the following error while converting the IMG into a kmz file using the visualisation tool-"LiCSBAS_disp_img.py."
Kindly have a look.
Attaching the screenshot
![Screenshot from 2022-05-01 11-14-45](https://user-images.githubusercontent.com/66096290/166134053-ed6ea41e-8098-410e-9ce1-0708104f33e8.png)

**Comment by yumorishita** [comment]
`--kmz TS_GEOCml1clip/results` should not be an existing directory, but an kmz file name to be created (e.g., vel.geo.kmz)

**Comment by Gautam5673** [comment]
Thank you, Sir!
Solved
