### ISSUE TITLE
Visualization as a KML/KMZ file 

### ISSUE THREAD

**Issue by SMJMirzadeh** [yumorishita/LiCSBAS#15]
Dear Morishita,

I did the processing by the LiCSBAS and would like to see and interpret the results in google earth but I didn't find any code to convert. Could you please let me know there is any program in your package to convert to the KML/KMZ format?

Sincerely,
Sayyed

**Comment by yumorishita** [comment]
You can convert the float32 file to kmz using LiCSBAS_disp_img.py with the --kmz option. Please see usage:

https://github.com/yumorishita/LiCSBAS/wiki/3_visualization#licsbas_disp_imgpy
