### ISSUE TITLE
Strange difference between velocity.png (after step15) and filtered.velocity (after step 16) 

### ISSUE THREAD

**Issue by miladmz** [yumorishita/LiCSBAS#151]
Hi 
when I used step 16 to apply the Spatio-temporal filter velocity range completely changed and I don't know how it happen!!

![vel filt mskd](https://user-images.githubusercontent.com/43873834/166633210-619a37de-9bfc-4eaf-ad59-010b64a2d91f.png)
![vel mskd](https://user-images.githubusercontent.com/43873834/166633243-378aa2fb-ae0e-4bb2-9e52-f0194ccfad84.png)

**Comment by yumorishita** [comment]
It is because the reference point is different between them. These velocities are actually almost the same because the velocity and displacement are relative to the reference.
