### ISSUE TITLE
No TS_GEOCml1clip/cum_filt.h5

### ISSUE THREAD

**Issue by julianpach** [yumorishita/LiCSBAS#152]
Hello sr. yumorishita.
I am a student and somewhat new to working with LiCSBAS and programming in general,
  lately trying to run the line corresponding to derived time series and velocity : LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &
  It appears to me in all the images that I try to process the following error:

 (LicsBAS) hot@HotPotatoKirby:~/anaconda3/envs/LicsBAS/LiCSBAS/165A_07945_001113$ 
LiCSBAS_plot_ts.py ver1.13.4 20210910 Y. Morishita
LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5

No TS_GEOCml1clip/cum_filt.h5 found!

I have no idea what it is, I have tried to do the other post with similar errors but it has not worked.
If you could give me ideas or suggestions I would appreciate it.
Have a nice day or night.

![image](https://user-images.githubusercontent.com/104925643/167531181-7f6df7b9-bd85-4a82-906a-506ead0328f4.png)

![image](https://user-images.githubusercontent.com/104925643/167531657-dfb7bc04-bb85-4bfa-a091-dc42be752aeb.png)

**Comment by yumorishita** [comment]
Please check if the TS_GEOCml1clip/cum_filt.h5 exists. It should be created if the last step (step1-6) successfully finishes.

**Comment by julianpach** [comment]
Hello sr. yumorishita.
I already checked and in fact it doesnt exist.If I understood correctly, to make this appears, the clips corresponding to the study area must be entered in batch_LiCSBAS.sh in lines do05op_clip and p05_clip_range_geo, right? cause, that's the first thing that I tried to do, could the problem be here?

thank you and have a nice day or night.

**Comment by julianpach** [comment]
Hello sr. yumorishita.
I'm still running your code step by step and I realised that in fact the folder and the cum.h5 archive are being generated how you can see in the image that I add, but for some reason that I don't understand when I'm running the function they aren't recognize 

![imagen](https://user-images.githubusercontent.com/104925643/167707761-a4ad4e3b-bd64-4fac-8da6-f165c820399a.png)


have a good day.
