### ISSUE TITLE
Reference point after step 16

### ISSUE THREAD

**Issue by siavashshami** [yumorishita/LiCSBAS#153]
Hi

I change the reference point with the following command:
LiCSBAS_plot_ts.py -i TS-GEOCml/cum_filt.h5 --ref_geo 50.10/50.10/36.10/36.10

Now, how do I save the results in file vel.filt with the new reference point?

**Comment by yumorishita** [comment]
You can create the velocity file with a specified reference point by [LiCSBAS_cum2vel.py](https://github.com/yumorishita/LiCSBAS/blob/master/bin/LiCSBAS_cum2vel.py), e.g., 
```
LiCSBAS_cum2vel.py -i TS_GEOCml1/cum_filt.h5 --ref_geo 50.10/50.10/36.10/36.10
```

**Comment by siavashshami** [comment]
> You can create the velocity file with a specified reference point by [LiCSBAS_cum2vel.py](https://github.com/yumorishita/LiCSBAS/blob/master/bin/LiCSBAS_cum2vel.py), e.g.,
> 
> ```
> LiCSBAS_cum2vel.py -i TS_GEOCml1/cum_filt.h5 --ref_geo 50.10/50.10/36.10/36.10
> ```

Thank a lot
