### ISSUE TITLE
error reshape in step 03?

### ISSUE THREAD

**Issue by Osmanpour** [yumorishita/LiCSBAS#154]
Hi, 
why i have this error in stap 03?

cannot reshape array of size 27932672 into shape [(7410,7255)](/home/asus/Pictures/Screenshot from 2022-04-28 02-15-03.png)

**Comment by yumorishita** [comment]
I cannot see the png file. Please upload the full log file.

**Comment by Osmanpour** [comment]
![Screenshot from 2022-04-28 02-15-03](https://user-images.githubusercontent.com/105474833/168487897-9faf4a13-f83f-4686-a2c9-cc2d78d3c0c5.png)
this file, and also when it run without get gacos.
and without get GACOS in step 02
![Screenshot from 2022-05-15 10-15-17](https://user-images.githubusercontent.com/105474833/168488064-9d7f8d48-e420-4bc1-8d2e-64cf944990cb.png)

**Comment by yumorishita** [comment]
I guess one or more unw data have different size. Please check the size of unw by `ls -l GEOCml1/*/*.unw`, remove the incomplete file and restart from step1 again to get the complete file.

**Comment by Osmanpour** [comment]
Hi, 
I check the zise by ls -l GEOCml1/*/*.unw, and solved the error RESHAPE AND RESIZE  
.
but I have a question about how this command works because, as shown in the image below, all the unw data are executed by executing the command without explaining whether the image size is faulty or not. Finally, errors were resolved fortunately
![Screenshot from 2022-05-26 13-19-07](https://user-images.githubusercontent.com/105474833/172671447-84212e36-6552-4b2d-b99c-07edf5606dd4.png)
![Screenshot from 2022-05-26 13-19-07](https://user-images.githubusercontent.com/105474833/172671641-a714b3d5-5e1a-4f69-b43b-c84a990a8f94.png)
![Screenshot from 2022-05-25 23-28-22](https://user-images.githubusercontent.com/105474833/172671678-1eca41b4-7eb3-4c5d-952c-76ea162c5396.png)

**Comment by Osmanpour** [comment]
And now I have other problem in step 13, that due to using high resolution or otheres, although I have clipped the study area, it stopped in the third part of step 13 without any error ?! 
![Screenshot from 2022-06-08 22-09-50](https://user-images.githubusercontent.com/105474833/172682138-04b0878b-09a9-45f8-9386-57f6acae15f4.png)
![Screenshot from 2022-06-08 22-10-08](https://user-images.githubusercontent.com/105474833/172682161-bf947be5-352c-402d-905a-0bcc29106c76.png)

**Comment by yumorishita** [comment]
It seems that the process takes a very long time but is ongoing (the previous patch took 63 hours to finish). It would be because your machine spec is not enough to process such a large data set. I suggest reducing the size by using a large nlook (e.g., 10) or clipping a narrower area.

**Comment by Osmanpour** [comment]
Hi,

I appreciate for your response.
with
I am PH.D student and my thesis is about determine fault damage size in
north of Tehran that we have unactive fault  with small displacement. And
Dr. Yasser Maghsoudiis my supervisore that he is with COMET group.

 I need high resolution
 and as it shown in the picture above in this step we need 8000 MB= 64 GB
and my laptop have 360 GB free space.

In the attach file you could see my area (that cliped smaller).

and do this process with multilook 10 for hole of assending frim.

I hope that I could make good progress in doing my research better with
your guidance.

sincerely
.
Ava.

**Comment by yumorishita** [comment]
I cannot find the attached file.
What do you mean by "fault damage size"? I don't understand why you need high resolution because generally we don't need ~100m resolution to discuss faults.

**Comment by Osmanpour** [comment]
![coh_avg](https://user-images.githubusercontent.com/105474833/173137311-fceb914a-5a0d-4eff-a9ee-29ccde64ee2d.png)
![vel](https://user-images.githubusercontent.com/105474833/173137419-cc6fede2-fe60-440c-9d38-ddc70ce3b46e.png)

**Comment by Osmanpour** [comment]
"Fault Damage Zone" its true.
It means displacement around fault that we have limited for building and ....

**Comment by yumorishita** [comment]
@Osmanpour Do you have any more questions? If not, let me close this issue.

**Comment by Osmanpour** [comment]
thanks for this topic yes you could close.
