### ISSUE TITLE
GACOS not working

### ISSUE THREAD

**Issue by DaisyUoE** [yumorishita/LiCSBAS#155]
Hi, I am a Post-doc from the University of Edinburgh. I have tried the GACOS atmospheric correction in the batch file, however, I got an error, please see attached log file.
[202205102327batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/8696238/202205102327batch_LiCSBAS_01_16.log)

**Comment by DaisyUoE** [comment]
Got it, thanks Morishita, I will have a try with the steps that you suggested. -Daisy

**Comment by DaisyUoE** [comment]
Hi Morishita, I have tried your suggested steps, still got error. Please see attached log file
[202205182233batch_LiCSBAS_03_16.log](https://github.com/yumorishita/LiCSBAS/files/8721051/202205182233batch_LiCSBAS_03_16.log)
.

**Comment by yumorishita** [comment]
I have processed the frame and found that the data below are corrupted:
20170808_20170820
20170808_20170901
20170901_20171007
result in inf of std in the GACOS_info.txt, and raise Exception when plotting a figure.
Please remove these 3 corrupted data from GEOCml1 dir and try again.

**Comment by DaisyUoE** [comment]
I have done your suggested step, still error. Please see attached log
[202205222301batch_LiCSBAS_03_16.log](https://github.com/yumorishita/LiCSBAS/files/8750355/202205222301batch_LiCSBAS_03_16.log)
.

**Comment by yumorishita** [comment]
Please remove GEOCml1GACOS as well and try again.

**Comment by DaisyUoE** [comment]
Thanks Morishita. Good and bad news. Finally I have got the batch file running successfully, please see attached log file. Bad news is when I plot the data, is empty result, please see attached screen capture.
[202205231436batch_LiCSBAS_03_16.log](https://github.com/yumorishita/LiCSBAS/files/8758245/202205231436batch_LiCSBAS_03_16.log)
![Capture1](https://user-images.githubusercontent.com/105612384/169910815-18603cb6-4986-4298-b6ab-374512a18b6b.JPG)

**Comment by yumorishita** [comment]
Strange. Can you show me TS_GEOCml1GACOSclip/mask_ts.png?

**Comment by DaisyUoE** [comment]
please see attached!
![mask_ts](https://user-images.githubusercontent.com/105612384/170137832-2d43908d-cf1e-4ed8-b30c-ffaef7275253.png)

**Comment by yumorishita** [comment]
I found that the following data are also corrupted:
```
20170808_20170913
20170820_20170901
20170820_20170913
20170901_20170913
20170913_20171007
```
(You can see the corrupted data images GEOCml1GACOSclip/*/*.png)

Please remove them from GEOCml1GACOSclip (or other GEOC* directories for earlier steps) and rerun from step11. Then clear subsidence signals would appear!

**Comment by DaisyUoE** [comment]
Thank you sooooo much! I got a good result, please see attached screen capture.
The GACOS result is same with the without GACOS result, probably the atmospheric affect is not significant in this valley, anyway, good to have GACOS applied in the processing!
I noticed the colour bar has an issue. In the attached screen capture, the time-series show some areas has subsidence value around -160 mm/yr. However the colour bar shows up to -100 mm/yr. How do I update the colour bar please?
P.S. how did you find out which data are corrupted?
![Capture1](https://user-images.githubusercontent.com/105612384/170821091-45bc20b9-fc67-4468-b39d-63b7662c9f59.JPG)

**Comment by yumorishita** [comment]
It is not an issue. The color range is automatically set to 99% of the data to exclude outliers by default (see [here](https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/bin/LiCSBAS_plot_ts.py#L48)). If you want to set the color range to min/max of the data, add an option `--auto_crange 100`.

I firstly ran with nlook=10 without clipping. Then I checked all the GEOCml10/*/*.png and identified the corrupted data.

**Comment by DaisyUoE** [comment]
Got it, thanks, it works!
