### ISSUE TITLE
error use  LiCSBAS_cum2tstxt.py

### ISSUE THREAD

**Issue by wutianS** [yumorishita/LiCSBAS#156]
**Script：LiCSBAS_cum2tstxt.py .**
When I use 104/30, the code will not report an error, and when I use 104.14309/30.45397, the program will report an error, that is to say, when the latitude and longitude are not an integer, an error will be reported. How to modify the code to make it work properly? Thank you！
**ValueError: invalid literal for int() with base 10: '104.14309'**

**Comment by yumorishita** [comment]
Could you show me the full log? I wonder if you used -p option, but -g option should be used for lat lon.

**Comment by wutianS** [comment]
> 



> 
Thank you for your answer. I used the -p option for the first time. When I followed your suggestion and used the -g option, the program worked properly.

**Comment by wutianS** [comment]
> Could you show me the full log? I wonder if you used -p option, but -g option should be used for lat lon.

Thank you for your answer. I used the -p option for the first time. When I followed your suggestion and used the -g option, the program worked properly.
