### ISSUE TITLE
error in step 03 for GACOS correction

### ISSUE THREAD

**Issue by miladmz** [yumorishita/LiCSBAS#158]
I'm a Ph.D. student at Khaje Nasir university, I got this error in step03, please see attached file.
<img width="1440" alt="Screen Shot 1401-03-07 at 19 03 44" src="https://user-images.githubusercontent.com/43873834/170829930-ace8f164-de12-461b-ac70-889127d594a2.png">

**Comment by yumorishita** [comment]
Do you use batch_LiCSBAS.sh? If not, I recommend using it.

**Comment by miladmz** [comment]
No, I run step by step 
Thank you I will try the batch_LICSBAS.sh that you suggested

**Comment by miladmz** [comment]
I use this batch file but again the same error appears!!

**Comment by yumorishita** [comment]
Please upload the log file.

**Comment by miladmz** [comment]
[202205292255batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/8795552/202205292255batch_LiCSBAS_01_16.log)

**Comment by yumorishita** [comment]
I am not quite sure but making symbolic links in your mounted disk seems not to be allowed. Please change your disk setting to enable symbolic links.

**Comment by lyx5201314** [comment]
> I'm a Ph.D. student at Khaje Nasir university, I got this error in step03, please see attached file. <img alt="Screen Shot 1401-03-07 at 19 03 44" width="1440" src="https://user-images.githubusercontent.com/43873834/170829930-ace8f164-de12-461b-ac70-889127d594a2.png">



> I am not quite sure but making symbolic links in your mounted disk seems not to be allowed. Please change your disk setting to enable symbolic links.

Dear Professor,I have had the same question recently.The solution to this problem is whether the words you have mentioned that change  disk setting to enable symbolic links and how can i change disk setting to enable symbolic links?
