### ISSUE TITLE
batch_LiCSBAS.sh

### ISSUE THREAD

**Issue by Sgzanjani1367** [yumorishita/LiCSBAS#159]
Hi yu

I am studying about faults slip rates by InSAR.
I want to know what parameters are better to use in batch_LiCSBAS.sh and Optional steps (03-05) and also Frequently used options for an area with low vegetation coverage by the sea?

**Comment by yumorishita** [comment]
It highly depends on the AOI and available data. I recommend playing with the parameters to understand how each parameter affects the result and get better results.

**Comment by Sgzanjani1367** [comment]
Thank you very much for your recommendation.

I have a velocity map with the range of -20 to 20 mm/yr, covered by
subsidence, but I would like to follow the lower rates like -4 to 4 mm/yr.
Is it possible to mask the greater rates in the final result?

‫‪Yu Morishita‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۱ ژوئن
۲۰۲۲ ساعت ۱۶:۵۹ نوشت:‬

**Comment by yumorishita** [comment]
What do you mean by "mask"? If you want to just reduce the color range, use options (e.g., --vmin, --vmax, --dmin, and --dmax in LiCSBAS_plot_ts.py). If you want to replace the large deformation data with no data, I suggest using [gdal_calc.py](https://gdal.org/programs/gdal_calc.html) after converting the velocity to GeoTIFF.

**Comment by yumorishita** [comment]
LiCSBAS_profile.py can create a profile.
https://github.com/yumorishita/LiCSBAS/wiki/3_visualization#licsbas_profilepy
