### ISSUE TITLE
Gacos download and apply

### ISSUE THREAD

**Issue by alejobeap** [yumorishita/LiCSBAS#16]
Dear I run the script but in the step when download GACOS data. 
Download GACOS data
No GACOS data available from 20190101 to 20200601

I'm not sure if there is no GACOS data.
How can I check?
Thank you very much.

**Comment by yumorishita** [comment]
If the GACOS data is available, it is stored in:

http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/[track]/[frame]/epochs/[yyyymmdd]/[yyyymmdd].sltd.geo.tif

For example,
http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/87/087A_05317_121617/epochs/20180318/

Unless the [yyyymmdd] directory or [yyyymmdd].sltd.geo.tif exists, it means the GACOS data is not available at the moment (not created yet). You can request prioritising upload of the GACOS data for your frame of interest from "LiCSAR frame request" (in the right column of https://comet.nerc.ac.uk/comet-lics-portal/).

**Comment by alejobeap** [comment]
Thanks for your help

**Comment by 4restwilliams** [comment]
Hi @yumorishita, is it possible to externally request GACOS data from here[http://ceg-research.ncl.ac.uk/v2/gacos/](url) and use it within the LiCSBAS workflow?

**Comment by yumorishita** [comment]
Sure.

1. Order the GACOS data you need. (See also https://github.com/yumorishita/LiCSBAS/issues/3)
2. Download and unzip *.tar.gz
3. Move *.ztd and *.ztd.rsc to your GACOS dir (e.g., <your frame>/GACOS)
4. Set your GACOS dir at https://github.com/yumorishita/LiCSBAS/blob/346d26a704bb6df7963f89faf7a03715e5ed439b/batch_LiCSBAS.sh#L69
5. Set start_step <= 03 at https://github.com/yumorishita/LiCSBAS/blob/346d26a704bb6df7963f89faf7a03715e5ed439b/batch_LiCSBAS.sh#L19
6. Run batch_LiCSBAS.sh

**Comment by MarcoSal** [comment]
Greetings,
I'll add a comment here even if it's closed so as not to waste the replies.
I noticed that a lot of GACOS data is missing and therefore needs to be downloaded manually.
Are there any precautions to take to do this operation manually?
- can the size of the tifs be different?
- do we need to change the extension of ztd.tif files to sltd.geo.tif?
- the site asks me for the reference hour and minute. How do I know them?

Thanks

**Comment by yumorishita** [comment]
Thank you for your nice question. I don't remember clearly, but as far as I see my codes,

> can the size of the tifs be different?

Yes. gdalwarp reads each input file's geolocation from each GeoTIFF.

https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/bin/LiCSBAS03op_GACOS.py#L418

> do we need to change the extension of ztd.tif files to sltd.geo.tif?

No. You must not change ztd.tif to sltd.geo.tif because ztd and sltd are different and ztd need to be converted to sltd.
https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/bin/LiCSBAS03op_GACOS.py#L433

> the site asks me for the reference hour and minute. How do I know them?

You can find it in slc.mli.par.

https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/bin/LiCSBAS03op_GACOS.py#L6

**Comment by MarcoSal** [comment]
Great I'd say.
I try to download the GACOS files and do the processing.
I will report as soon as possible if I have encountered any critical issues.

Thank you

**Comment by MarcoSal** [comment]
Ok, it works perfectly. Simply download the GACOS data and insert it into the relevant folder. The request for data is also processed quickly.
Excellent.
