### ISSUE TITLE
error in installing 

### ISSUE THREAD

**Issue by miladmz** [yumorishita/LiCSBAS#161]
I installed LiCSBAS_requirements.txt but I got this error
I tried to install gdal with 'conda install -c conda-forge gdal' in my environment but yet get this error
![err1](https://user-images.githubusercontent.com/43873834/172678247-78ec87bd-2990-4da0-92c0-a9a408354b7e.JPG)

**Comment by yumorishita** [comment]
I have never seen that error. I am not sure but I suggest using python<=3.8 and installing gdal without "-c conda-forge".
The message also says "PYTHONPATH is not set". Have you done `source bashrc_LiCSBAS.sh`?

**Comment by miladmz** [comment]
yes, I  source bashrc_LiCSBAS.sh but not working 
I think gdal has a conflict with other packages in the new version 
which versions do you install?

**Comment by yumorishita** [comment]
One of my LiCSBAS environment:
```
gdal                      3.4.1            py38h2c27f0e_0  
python                    3.8.13               h12debd9_0  
```

**Comment by yumorishita** [comment]
```
(licsbas) morishita@morishita-VirtualBox:~$ LiCSBAS_check_install.py 

Python version: 3.8.13
  OK

Check required modues and versions
  astropy(5.0.4) OK
  bs4(4.11.1) OK
  h5py(3.6.0) OK
  matplotlib(3.5.1) OK
  numpy(1.21.5) OK
  psutil(5.8.0) OK
  requests(2.27.1) OK
  statsmodels(0.13.2) OK
  gdal(3.4.1) OK

Check LiCSBAS commands
  OK

Check LiCSBAS library
  OK

LiCSBAS install is OK
```
