### ISSUE TITLE
Error accessing data

### ISSUE THREAD

**Issue by Sgzanjani1367** [yumorishita/LiCSBAS#162]
Hi Yu
There seems to be a problem with the connection to access new data, so when I want to download data, the " ConnectionError" appears.

**Comment by yumorishita** [comment]
Please upload the log.

**Comment by alejobeap** [comment]
Hi
I have been trying to download the data in step 1 but it always hangs when downloading the interferograms and cc's, I have tried on several computers and the same thing happens.
Thanks

**Comment by yumorishita** [comment]
Please upload the log.

**Comment by alejobeap** [comment]
The log is empty but today the message is 
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
or now the running stop and wait a lot time in this step

Download geotiff of unw and cc
762 IFGs available from 20160131 to 20220523
Checking existing unw and cc (4 parallel, may take time)...

Thanks.

**Comment by Zuzchan** [comment]
Were you able to solve it?
