### ISSUE TITLE
LOS decomposition to EW and vertical direction 

### ISSUE THREAD

**Issue by DaisyUoE** [yumorishita/LiCSBAS#163]
Hi Morishita,
I am looking for a user friendly code/software to decomposition the LOS result from the LiCSBAS output. Do you have any suggestions?

Many thanks,
Daisy

**Comment by yumorishita** [comment]
Is the [LiCSBAS_decomposeLOS.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_decomposelospy) not user friendly for you?

**Comment by yumorishita** [comment]
Please see this https://github.com/yumorishita/LiCSBAS/issues/39

**Comment by DaisyUoE** [comment]
Thanks, I have created all the files from both ascending and descending frames, now I got 'list index out of range' error. please see attached screen capture.
Another thing is the descending frame has limited coverage, could this be the issue? Please see attached capture2. -Daisy

![Capture](https://user-images.githubusercontent.com/105612384/175323868-8e3b9d81-200d-4e9d-a867-a2d066d09cb4.JPG)
![Capture2](https://user-images.githubusercontent.com/105612384/175323879-fb7b7c69-7297-49a8-92e3-06d50b25ecf4.jpg)

**Comment by yumorishita** [comment]
It seems that the format of files.txt is incorrect. Could you show me the contents or upload it?

**Comment by DaisyUoE** [comment]
Here it is, I was planning to upload all the geotif files that mentioned in the txt file, however, Github website do not support that file type.
[files.txt](https://github.com/yumorishita/LiCSBAS/files/8980666/files.txt)

**Comment by yumorishita** [comment]
The files.txt is empty. You must write your own file paths to the vel and EN geotiff files in the files.txt.

**Comment by DaisyUoE** [comment]
[files.txt](https://github.com/yumorishita/LiCSBAS/files/8981672/files.txt)

**Comment by DaisyUoE** [comment]
I do not know why it is empty on Github, not empty on my computer. Anyway, here is a screen capture of the content in files.txt
![Capture](https://user-images.githubusercontent.com/105612384/175698564-6690d367-7108-4728-a577-e1599778f513.JPG)

**Comment by yumorishita** [comment]
Please remove 1st and 4th lines.

**Comment by DaisyUoE** [comment]
It works perfect, I could not thanks more of your code. Thanks!!!
Here is another question, what is the coordinate system of those geotiff files? Is it WGS 84? Somehow, when I load those geotiff in ArcGIS software, the square clipped area, become shorter in the EW direction.

**Comment by yumorishita** [comment]
Yes, it is WGS84.

**Comment by DaisyUoE** [comment]
I noticed that the clipped area should be 0.35 degree in square as shown in capture2.jpg for my study area. However, the result is 800*700 pixels, as shown in capture3.jpg. That is may explain in my ArcGIS project, the result area not square as I expected, even they are all in WGS84.
![Capture2](https://user-images.githubusercontent.com/105612384/175835896-7326337f-3a5d-469a-9528-72ba72668561.JPG)
![Capture3](https://user-images.githubusercontent.com/105612384/175835901-fb02365a-f722-4255-96b8-bb18420ba80a.JPG)

**Comment by yumorishita** [comment]
Can you upload the log file of step05?

**Comment by DaisyUoE** [comment]
I use batch_LiCSBAS.sh for processing, so attached is the log file of all steps. Thanks! -Daisy
[202205272210batch_LiCSBAS_03_16.log](https://github.com/yumorishita/LiCSBAS/files/8992210/202205272210batch_LiCSBAS_03_16.log)

**Comment by yumorishita** [comment]
The 800x700 pixel is the size of png file including the color bar. The actual size of the result is 351x351.

**Comment by DaisyUoE** [comment]
I am back to my first confusion of why the square clipped area become shorter in the EW direction when load the geotiff in ArcGIS? Any advice please?

**Comment by yumorishita** [comment]
zip file can be uploaded.

**Comment by DaisyUoE** [comment]
[geotiff.zip](https://github.com/yumorishita/LiCSBAS/files/9023564/geotiff.zip)

**Comment by yumorishita** [comment]
It is because 121D_06267_131313 does not cover the entire AOI. 019D_06217_131313 would cover the area.

**Comment by DaisyUoE** [comment]
Thanks, I will try with 019D_06217_131313.
The LOS velocity result from ascending frame, the file name is 20151006_20210706.vel.geo.tiff in my previous uploaded zip folder. Could you open this file in ArcGIS software please? Does it look square for you in the ArcGIS software? It definitely shorter in EW direction when I load the 20151006_20210706.vel.geo.tiff file in the ArcGIS software.

**Comment by yumorishita** [comment]
I have never used ArcGIS. I displayed the 20151006_20210706.vel.geo.tif on QGIS and it has an equal length in EW and UD in WGS84 CRS. I wonder if you displayed it in other projected CRS than WGS84 (e.g., EPSG3875). In that case, it is natural that the EW length is shorter because the unit is in meters not in degrees.

**Comment by DaisyUoE** [comment]
Good to know that the geotiff files are square, as it supposed to be. I will look into the CRS issue again in my ArcGIS project.
Another question back to decompose the LOS to EW/vertical. Does the order matter in the txt.file, put the ascending, or descending velocity files in the first line?

**Comment by yumorishita** [comment]
The order does not matter.

**Comment by DaisyUoE** [comment]
Now I am trying to use 'LiCSBAS_mask_flt.py' tool to mask the velocity file, where is the mask file that I suppose to use here please?

**Comment by yumorishita** [comment]
In a results directory. Please see this page: https://github.com/yumorishita/LiCSBAS/wiki/file_structure

**Comment by DaisyUoE** [comment]
I found the mask file in the results folder under TS_XXX directory, and got the masked geotiff file by using  'LiCSBAS_mask_flt.py' tool. Thank you so much for the great technical help, and LiCSBAS software will be citied in the paper I am working on, and you will be surely acknowledge in my paper. Thanks again! -Daisy

**Comment by DaisyUoE** [comment]
I got the masked results for UD.geo.tif, and expected the extreme values will be gone after masking. Luckily I got rid of some extreme values, however, one area which at the promising location (not on the edge), the UD.geo.tif value is -200 mm/yr, at the same location the LOS value is -160 mm/yr. Is it mathematically possible that the vertical value is bigger than LOS value? Because I simply use the V_LOS×cos⁡38.5° for vertical velocity, it always end up smaller than LOS velocity.

**Comment by yumorishita** [comment]
If you project the LOS displacement to vertical, 1/cosθ must be multiplied, not cosθ, and the vertical projected displacement must be always larger than the LOS. The LOS displacement is the projection of 3D displacement along LOS and is always smaller than the absolute value of 3D displacement.

**Comment by DaisyUoE** [comment]
Got it, thanks! How about reference point? I noticed that the descending result and ascending result are using different reference point. So is it OK for the decompose step with different reference points inputs?

**Comment by yumorishita** [comment]
It would be better to use a common reference point (or area) for both ascending and descending. It can be done by using -r or --ref_geo options of LiCSBAS_cum2vel.py when computing the velocity.

**Comment by DaisyUoE** [comment]
I used the 'LiCSBAS_cum2vel.py' tool to compute the velocity for ascending to have common reference point with descending, all work smoothly. Thanks! The results of are similar, it is reassuring what I have got, and good to state in the paper that during the calculation of decompose, I have used a common reference point for inputs.

**Comment by DaisyUoE** [comment]
Hi Morishita,
My supervisor has suggested that I could invite you as a co-author, and I think its great if you could make more contributions on the SBAS-InSAR processing and analysis in my study area with your expertise. Please let me know if you interested? -Daisy

**Comment by yumorishita** [comment]
Thank you for the invitation, but it would be difficult for me to make more contributions because I am no longer in an academic position. I would appreciate it if you could mention me in the acknowledgments.

**Comment by DaisyUoE** [comment]
Sure, thanks for letting me know. I have a question regard to the error bar/uncertainty of the values. Because in the EW component result, the distribution of the high EW movement location are geologically making sense, however, the magnitude of -50 to 50 mm/yr, it seems a bit fast for me.

**Comment by yumorishita** [comment]
Unfortunately, there is no function to derive the uncertainty of the decomposed deformation in LiCSBAS.

**Comment by DaisyUoE** [comment]
Is there a function to derive the uncertainty of the LOS velocity in LiCSBAS please?

**Comment by yumorishita** [comment]
[LiCSBAS_cum2vel.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_cum2velpy) with the `--vstd` option

**Comment by yumorishita** [comment]
Don't insert `[]`. Try `LiCSBAS_cum2vel.py --vstd`.

**Comment by DaisyUoE** [comment]
Hi Morishita,
I just slowly recover from COVID, sorry take a while to get back to work. Now I got the standard deviation in the range of 0-2.19, please see attached picture. What is the high value in the red colour mean? Does it mean it has high uncertainty in the red coloured area? What do you think about this 0-2.19 of the standard deviation in my study area, is it a good uncertainty number in general? -Daisy
![Screenshot 2022-08-04 233130](https://user-images.githubusercontent.com/105612384/182964353-d375ccad-cb14-429a-bcbe-b69ec4323adb.jpg)

**Comment by yumorishita** [comment]
The high vstd could mean nonlinear deformation. The range 0-2.19 seems to be normal for 5-6 years.

**Comment by DaisyUoE** [comment]
Great, good to know.

**Comment by DaisyUoE** [comment]
Hi Morishita,
I am working on the text in method section, and looking for some parameters used in the processing. The input number of SAR images, I have found in the TS_GEOCml1clip/info folder, the 13parameters.txt file (please see attached screen capture). So the number for the processing input SAR images is 450, am I right? Thanks. -Daisy
![Screenshot 2022-08-09 215752](https://user-images.githubusercontent.com/105612384/183760117-afb436f3-d904-4c77-ac20-75bfb03af750.jpg)

**Comment by yumorishita** [comment]
Yes, right.

**Comment by DaisyUoE** [comment]
Hi Morishita, I am trying to output a time-series text file by using cum2tstxt.py and got an error, please see attached capture below.
![Screenshot 2022-09-02 170949](https://user-images.githubusercontent.com/105612384/188195562-9ed0ff27-76df-4930-864a-40103fc1de26.jpg)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/7

**Comment by DaisyUoE** [comment]
Thanks, that was the issue, just back from holiday, a bit blur.
Another issue regard to masking, I am trying the process the descending frame covers Kathmandu. However, the mask deleted the top of the result, even in the unmasked result, the coverages is the entire valley. Please advise how to resolve this issue, please se
![Screenshot 2022-09-03 180115](https://user-images.githubusercontent.com/105612384/188280975-d2219bfa-f396-4538-a865-8946314fcc68.jpg)
e attached screen capture.

**Comment by yumorishita** [comment]
Show mask_ts.png, not mask_ts_mskd.png.

**Comment by yumorishita** [comment]
`n_loop_err` is the cause of the mask. You should check `12loop/bad_loop_cand_png/*.png` and `12no_loop_ifg_ras/*.png`, manually identify the unw data with unwrapping errors, remove them from `GEOCml*`, and rerun from step11.

**Comment by DaisyUoE** [comment]
I have done the suggested step, and removed 20161020-20161107, 20161101-20161107, 20161107-20161201, 20161020-20161113, 20161113-20161201 from both /GEOCml1 clip and /GEOCml1 folder. However, the result ends up only has bit data in the middle, please see attached mask_ts.png
![Screenshot 2022-09-06 170927](https://user-images.githubusercontent.com/105612384/188685072-8fe28d4b-45de-4a2c-88da-738c635d65ae.jpg)

**Comment by yumorishita** [comment]
You are showing the unclipped result in TS_GEOCml1. Run LiCSBAS again using the clipped data GEOCml1clip.

**Comment by DaisyUoE** [comment]
Thanks, I got a good result by rerunning it from step 03, instead of step 11. Now trying to apply GACOS.

**Comment by DaisyUoE** [comment]
I got the results both with and without GACOS. Somehow the time-series from the result that with GACOS, lost the annual sinusoidal pattern. I am wondering if it is may caused by the over correction from GACOS. If that is the case, I may use the result that without GACOS. Please see attached capture, that the time-series at the same location, one has sinusoidal pattern, one lost sinusoidal pattern after applying GACOS. Also there is a gap happened at year 2019-2020 at the GACOS result, which did not happen at the without GACOS result. Is it common to use the Sentinel result without GACOS? Please advise, thanks! -Daisy

![Screenshot 2022-09-08 225555](https://user-images.githubusercontent.com/105612384/189233309-33b164c6-f40f-4873-b3bd-b20d150d6b70.jpg)

**Comment by DaisyUoE** [comment]
Could I define the reference point when run batch_LiCSBAS.sh? I am trying to use the same reference point for both ascending and descending processing, then compare their time-series at the same location. Thanks! -Daisy

**Comment by yumorishita** [comment]
Please see this: https://github.com/yumorishita/LiCSBAS/issues/102.

**Comment by DaisyUoE** [comment]
Could you please advise on which command to define E.geo (N.geo)'s reference point. Because I am trying to define the descending results reference point match with ascending, then run LiCSBAS_decomposeLOS.py, thanks! -Daisy

**Comment by yumorishita** [comment]
E.geo is a LOS unit vector component and should have no reference point.

**Comment by zhouhuayun** [comment]
Hi, When I use LiCSBAS_decomposeLOS.py to obtain the deformation information of the vertical ground, I keep getting the following error (Figure 1). What is the reason?
![image](https://user-images.githubusercontent.com/42872898/192321491-0aae306b-e396-458d-8dce-2f9c5d3d213f.png)

Figure 2 shows the txt document content required by-f of LiCSBAS_decomposeLOS.py.
![image](https://user-images.githubusercontent.com/42872898/192323439-9e515930-d49f-4c1b-bc82-cb69d87df514.png)

**Comment by DaisyUoE** [comment]
Hi Morishita,
Is it possible to regenerate the network figure? I found automatic generated network_*.png at TS_*/network folder. However, I would like to remove the notation of time at each SAR image dot. I have tried LiCSBAS_plot_network.py, did not find the input files 'ifg_list' and 'bperp_list'.
Thanks,
Daisy

**Comment by yumorishita** [comment]
'ifg_list' can be easily created, e.g., by
```
ls -d GEOCml1/20*_20* > ifg_list
```

'bperp_list' is GEOCml1/baselines.

**Comment by DaisyUoE** [comment]
Thanks Morishita, another question. Is there any way to find out the equation for the fitted sinusoidal curve of the time-series points (please see attached figure)?
![Picture1](https://user-images.githubusercontent.com/105612384/195718210-39c4f8d6-5f14-4cc4-8e80-e61d21fe6e24.jpg)

**Comment by yumorishita** [comment]
The equation is coded [here](https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/bin/LiCSBAS_plot_ts.py#L144).
If you want to get the coefficients of the model, please modify the LiCSBAS_plot_ts.py to print the coefficients.

**Comment by DaisyUoE** [comment]
I ran LiCSBAS_plot_ts.py, got a time-series text file output, in the file, it has linear model coefficients. However, no sinusoidal model coefficients. Please see attached picture.
![Picture2](https://user-images.githubusercontent.com/105612384/195879170-fa29ffe8-f6b6-454c-b5d8-9db5b850281d.jpg)

**Comment by yumorishita** [comment]
I think you used LiCSBAS_cum2tstxt.py. Yes, it does not compute the coefficients of the sinusoidal model. You need to modify the source code of LiCSBAS_plot_ts.py.

**Comment by DaisyUoE** [comment]
> baselines.

I managed to run the 'LiCSBAS_plot_network.py' successfully, however, the time notation of each SAR image automatically plotted. Is there any parameter I could use to remove the month/year notation at each plotted dots please? please see attached screen capture below.
![Screenshot 2022-10-18 104707](https://user-images.githubusercontent.com/105612384/196397814-a8c45710-509e-4231-b661-fd544e814447.jpg)

**Comment by yumorishita** [comment]
Comment out the followoing two lines.
https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/LiCSBAS_lib/LiCSBAS_plot_lib.py#L264
https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/LiCSBAS_lib/LiCSBAS_plot_lib.py#L265

**Comment by DaisyUoE** [comment]
Thank you so much, I got it working based on your advice. -Daisy

**Comment by DaisyUoE** [comment]
Hi Morishita,
I noticed there is a big gap in my descending network figure (please see attached). Is it ok to have a one year gap in network for SBAS-InSAR processing? The result seems still good, just worried about the reviewer are going to be picky about it. 
I am trying to figure out why there is a gap. First, I check COMET-LiCS website, the network has no gap there (please see attached). Then I run 'batch_LiCSBAS.sh' to process the data, the network has a gap in the result. I also checked my processing back in May, somehow, with the same workflow, no gap in the LiCSBAS result network. I am so confused. 
Daisy

![1](https://user-images.githubusercontent.com/105612384/197071809-83dcbf0b-5cc6-4701-a637-04a8b269eae0.jpg)
![2](https://user-images.githubusercontent.com/105612384/197071816-1daf577b-a39f-46be-a70c-92d7a659b0af.jpg)

**Comment by yumorishita** [comment]
It is quite strange. You should use all the available interferograms for the paper. Can you upload the log file?

**Comment by DaisyUoE** [comment]
Attached is the log file, thanks. -Daisy

[202210202130batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/9840274/202210202130batch_LiCSBAS_01_16.log)

**Comment by yumorishita** [comment]
The reason of the missing dates is that you have the GAOCS data for the dates are missing. Please see the log in step03. You need to prepare them yourself or turn off the GACOS correction in step03.

**Comment by DaisyUoE** [comment]
Thanks for explaining the cause of the issue. If GAOCS data is missing from the server, how could I prepare them myself? In this case, do not apply GACOS correction in descending processing, a better choice? Or with GACOS correction, however with a GAP in network, a better choice? -Daisy

**Comment by yumorishita** [comment]
You can submit the GACOS request [here](http://www.gacos.net/). See [this](https://github.com/yumorishita/LiCSBAS/wiki/2_2_step01_5#step-0-3-gacos-correction-optional) as well. GACOS correction to all interferograms would be required for the peer-reviewed paper.

**Comment by DaisyUoE** [comment]
I requested some GACOS to try to make it work. First, for the 'location' parameter, I put the latitude and longitude value that covers entire descending footprint. Second, for the 'time of day' parameter, I kept default 0:00 (any advice? please see Fig.4)
Then the server back to me really fast, and I downloaded the data, rename it with the same name style as in GACOS folder, and add those files in the GACOS folder (Fig.2 and 3).
After that, I rerun the workflow from step03, however, the result did not pick up the GACOS file that I added in (covers beginning of 2019), the gap still there (Fig 1 and log file).
Please advise!
![1](https://user-images.githubusercontent.com/105612384/197633597-2f6b277d-7957-44f7-9c99-8126916e9bf5.jpg)
![2](https://user-images.githubusercontent.com/105612384/197633603-93a8a5f1-4cbc-4502-9465-e2d77bed5484.jpg)
![3](https://user-images.githubusercontent.com/105612384/197633606-b3efd025-8cfe-41ee-8770-ba0f716e9e00.jpg)
![4](https://user-images.githubusercontent.com/105612384/197633608-d74ffefc-5db2-442e-a6d3-d215027088f4.jpg)

[202210242138batch_LiCSBAS_03_16.log](https://github.com/yumorishita/LiCSBAS/files/9855509/202210242138batch_LiCSBAS_03_16.log)

**Comment by yumorishita** [comment]
The 'time of day' should not be 0:00, but be center_time written in metadata.txt or slc.mli.par (e.g., 0:19 for [019D_06217_131313](https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/19/019D_06217_131313/metadata/metadata.txt)).

What is the file name of the downloaded data? If it is *.ztd or *.ztd.tif, you should not rename it to *.sltd.geo.tif because they are different. The *.ztd or *.ztd.tif files can be used in step03 (see [here](https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/bin/LiCSBAS03op_GACOS.py#L20)).

Please see `GEOCml*GACOS/yyyymmdd_yyyymmdd/yyyymmdd_yyyymmdd.gacos.png` to check how the correction worked.

**Comment by DaisyUoE** [comment]
I requested the GACOS data again with time at 0:19, and did not change *.ztd.tif files name, kept as it was.
However, still the GACOS did not apply through the newly added GACOS files. For example, the 20190102_20190207 correction is empty (please see attached figure).
I also attached one sample GACOS file that already exists in the GACOS folder, another one is newly requested, maybe you could have a look at them to help find out what is wrong? Thanks! -Daisy
![11](https://user-images.githubusercontent.com/105612384/197868076-50fc6e1f-1bb8-4814-be9d-18a0837305b0.jpg)

[GACOS file1.zip](https://github.com/yumorishita/LiCSBAS/files/9863609/GACOS.file1.zip)
[GACOS file2.zip](https://github.com/yumorishita/LiCSBAS/files/9863612/GACOS.file2.zip)

**Comment by yumorishita** [comment]
The attached 20190102.ztd.tif seems to be normal. If you retried without removing existing GEOCml*GACOS/sltd/yyyymmdd.sltd.geo, please retry again after removing them because they are not overwritten if exist.

If the problem still exist, please attach GEOCml1GACOS/sltd/20190102.sltd.geo, 20181221.sltd.geo and EQA.dem_par.

**Comment by DaisyUoE** [comment]
After removing existing GEOCml*GACOS/sltd/yyyymmdd.sltd.geo, and it works. The gap caused by GACOS is gone. Please see Figure 3, and log file.
There are two small gaps in the current network, please see figure 2. The cause of the gap are 'bad' pairs got removed, please see figure 1.
Since it is caused by bad pairs, I do not think there are anyway to 'fill' the gap. Is it OK to have couple small gaps in the network for SBAS-InSAR result for the peer-reviewed paper? Thanks! -Daisy
![3](https://user-images.githubusercontent.com/105612384/198831720-2f062f96-a466-446e-be03-c2e9bfa3c8f6.jpg)
![2](https://user-images.githubusercontent.com/105612384/198831724-5e54b949-f955-4824-aec8-0d4e5177f716.jpg)
![1](https://user-images.githubusercontent.com/105612384/198831726-2c72c9ab-2519-48e8-8ae7-99528da9d582.jpg)
[202210291105batch_LiCSBAS_03_16.log](https://github.com/yumorishita/LiCSBAS/files/9893675/202210291105batch_LiCSBAS_03_16.log)

**Comment by irmayolii** [comment]
Dear Prof. Yumorishita
After we get EN/UD.geotif from processing LiCSBAS_decomposeLOS.py, can I generate specified point timeseries from EN/UD.geotif timeseries?

**Comment by yumorishita** [comment]
No, currently LiCSBAS has no function to do that.

**Comment by irmayolii** [comment]
so how do we know how big the shift is of EN/UD.tif in numerically, can we get file in txt about cumulative displacement or anything to exctract value from that?

**Comment by araditiya** [comment]
> Please see this #39
It looks no clear the flow command for me, in order to get E/W, U/D. Could you help me to guide this issue.
I success to execute the first command cum2vel and it generates 20151122_20221227.vel file. 
Then, I face an error in further step as follows,

saka@xps8930:~/work$ LiCSBAS_flt2geotiff.py -i 20151122_20221227.vel -p EQA.dem_par

LiCSBAS_flt2geotiff.py ver1.5.1 20210209 Y. Morishita
LiCSBAS_flt2geotiff.py -i 20151122_20221227.vel -p EQA.dem_par
Use gdal module
Traceback (most recent call last):
  File "/home/saka/LiCSBAS/bin/LiCSBAS_flt2geotiff.py", line 213, in <module>
    sys.exit(main())
  File "/home/saka/LiCSBAS/bin/LiCSBAS_flt2geotiff.py", line 190, in main
    data = io_lib.read_img(infile, length, width, endian=endian)
  File "/home/saka/LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 199, in read_img
    data = np.fromfile(file, dtype=dtype).reshape((length, width))
ValueError: cannot reshape array of size 63001 into shape (2515,2676)

saka@xps8930:~/work$

**Comment by yumorishita** [comment]
> so how do we know how big the shift is of EN/UD.tif in numerically, can we get file in txt about cumulative displacement or anything to exctract value from that?

You can extract value from geotiff, e.g., by [gdal2xyz.py](https://gdal.org/programs/gdal2xyz.html).

**Comment by yumorishita** [comment]
@araditiya The size of the vel file seems to be inconsistent with what it should be. I cannot identify the cause from this limited information.

**Comment by araditiya** [comment]
> @araditiya The size of the vel file seems to be inconsistent with what it should be. I cannot identify the cause from this limited information.

What should I check or provide to you in my case ?
I success to generate vel file using this command previously LiCSBAS_flt2geotiff.py -i 20151122_20221227.vel -p EQA.dem_par. Then followed by LiCSBAS_flt2geotiff.py -i 20151122_20221227.vel -p EQA.dem_par -o 20151122_20221227.vel.geo.tiff but there is an error.

**Comment by araditiya** [comment]
> @araditiya The size of the vel file seems to be inconsistent with what it should be. I cannot identify the cause from this limited information.

Thank you. It has solved due to file E,N come from different folder.

**Comment by ditafaith** [comment]
Hi, does it possible to decompose only from short period, says for each asc  and desc 2 images (e.g. before and after EQ) ?
Is there any minimum stack of images ?

**Comment by yumorishita** [comment]
I think it is possible.

**Comment by ditafaith** [comment]
> I think it is possible.

It sounds good opportunity. Then, is it possible the licsbas read the output from snap software ?

**Comment by yumorishita** [comment]
Yes, if you convert the output to the proper format (see [here](https://github.com/yumorishita/LiCSBAS/wiki/file_structure)).

**Comment by NabilAttar** [comment]
excuse me sir. I have done ascending and descending processing in #334 . but I think the results of descending are quite bad. i have use LiCSBAS_decompose but i think the result of UD is bad caused descending frame. Is it possible to get a UD velocity value just by using ascending? I only need UD and not EW. thank you sir

**Comment by as1234554321** [comment]
Hi sir, I have decomposition problems like this picture
Can you help me?"

![image](https://github.com/user-attachments/assets/7d85e2cf-ac90-4947-992e-fbd24067b29d)
Thank You

**Comment by ditafaith** [comment]
@as1234554321 it looks difficult without additional information such as log file/ files.txt. 
You may check the input files, I guess.

**Comment by as1234554321** [comment]
> @as1234554321Tampaknya sulit tanpa informasi tambahan seperti file log/files.txt. Anda dapat memeriksa input file, saya kira.
I have created a geotiff for each orbit in a different folder but still in the licsbas directory, then created a txt file.

**Comment by ditafaith** [comment]
@as1234554321 All geotiffs should be gathered into same directory where files.txt located in, then you might run the command.

**Comment by as1234554321** [comment]
hello @ditafaith 
sorry for out of topic
Are you Indonesian? If yes, I would like to contact you personally to discuss. thankyou
