### ISSUE TITLE
Querry about LiCSBAS toolbox

### ISSUE THREAD

**Issue by Hvmanshu** [yumorishita/LiCSBAS#165]
Does LiCSBAS have the ability to overcome posismic deformation? Or Does the LiCSBAS based velocity field consider this?

**Comment by yumorishita** [comment]
I may not understand your question correctly, but LiCSBAS can detect any type of deformation regardless of the source if the signal is included in InSAR data because LiCSBAS just derives the deformation time series from the differential deformation in multiple interferograms.

**Comment by Hvmanshu** [comment]
Thank you for the information.
