### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by gshirazinejad** [yumorishita/LiCSBAS#166]
Hi Yu,
I'm processing a LiCSAR frame with number of multilooks 10 but it stuck in step 1-3 (small baseline inversion). I was thinking that maybe my system does not have enough memory or ram.  Thus, what are recommended specs to process a frame with multilook = 1 (My frame has a spatial resolution of 0.0005 degrees)?

Thanks,
Golsa

**Comment by yumorishita** [comment]
You should set the parameter below if the memory size is small.
https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/batch_LiCSBAS.sh#L97

**Comment by gshirazinejad** [comment]
Thank you. So if my system has 7 GB ram, i should set p13_mem_size as 7000?

and i have another question…how much ram and storage do i need to process a LiCSAR frame with a spatial resolution of 0.0005 degrees?

**Comment by yumorishita** [comment]
7000 would be fine. If the memory problem occurs, try a smaller value. I think 7GB or smaller (e.g., 1GB) RAM is enough if you correctly indicate the p13_mem_size. The required storage size depends on the number of interferograms.

**Comment by gshirazinejad** [comment]
I changed the mem_size as you suggested based on my system but it was replaced by lower value.
I attached screen shots.
![1](https://user-images.githubusercontent.com/108024393/178270681-8d190836-603b-46e5-94ed-b62fae4624ce.png)
![2](https://user-images.githubusercontent.com/108024393/178270821-2854fb26-3a3c-473e-90e8-c5c9c1ad9589.png)

**Comment by yumorishita** [comment]
It is a natural behavior. Because the required memory size estimation is not strict, the limit is set to half of the machine memory size. Do you still have the memory issue?

**Comment by gshirazinejad** [comment]
I can’t have higher memory size than half of the machine memory size, whether I set the mem_size parameter or not?

yes I still have the memory issue. At first I processed the descending frame with multilook=10, but after 6 days it was still running (at step 1-3). I stopped the process And was forced to process with multilook=20.

**Comment by gshirazinejad** [comment]
It was running but took so much time because I have nearly 2000 interferograms... After 6 days it was still running. So what could be the problem?

**Comment by yumorishita** [comment]
プロセスが停止していない限り、できることはただ待つことだと思います。もしくは、もっと性能の高いマシンを使うべきでしょう。

**Comment by gshirazinejad** [comment]
Thank you very much...I think I have to use a machine with higher performance.

"mem_size" parameter is still a challenge for me. Before running step 1-3, I checked top command (it is shown in the first picture). Then I run step 1-3 and based on the top command results I expected memory of 2000 mb, but it was still 3000 mb. 
Maybe top command does not give us usable memory. Do you knw any command that I can get access to the usable memory?
![11](https://user-images.githubusercontent.com/108024393/178740739-6304869c-7c88-494c-9588-6619872e5ccb.png)
![22](https://user-images.githubusercontent.com/108024393/178740767-32aa3f46-3f5e-4432-8a68-945e789d1ff2.png)

**Comment by yumorishita** [comment]
LiCSBAS get the memory size using psutil.virtual_memory().available. 
https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/bin/LiCSBAS13_sb_inv.py#L406
The `free` command can be also used for memory checking. However, I don't think memory matters in your case.

**Comment by yumorishita** [comment]
Perhaps this may help:
https://comet-licsar.github.io/licsbas/index.html

They says 

> check new parameters --nullify in step 12, and --fast in step 13 as (very) useful key changes.

though I don't know how change was made at all.

**Comment by gshirazinejad** [comment]
Thanks for your guidance.
