### ISSUE TITLE
Step 1-5

### ISSUE THREAD

**Issue by siavashshami** [yumorishita/LiCSBAS#167]
Dear Morishita,

Step 1-5: Mask Time Series:
Default thresholds for C-band:
 -c 0.05 -u 1.5 -v 100 -T 1 -g 10 -s 5  -i 50 -l 5 -r 2

 -v  Threshold of vstd (std of the velocity (mm/yr))

Why -v is 100 mm/yr? (100 or 10)

Many thanks,
Siavash Shami

**Comment by yumorishita** [comment]
Because I thought the vstd is not an appropriate index for masking.

**Comment by siavashshami** [comment]
So, why did you use 10 mm/year in the original article (LiCSBAS: An Open-Source InSAR Time Series
Analysis Package Integrated with the LiCSAR Automated Sentinel-1 InSAR Processor)?

**Comment by yumorishita** [comment]
At that time I thought the 10mm/yr was good. As far as I remember, 10mm/yr or 100mm/yr made any difference in the results in the cases of the paper. However, in some other cases, I realized that 10mm/yr could have a bad effect.
