### ISSUE TITLE
plot profile

### ISSUE THREAD

**Issue by Osmanpour** [yumorishita/LiCSBAS#168]
Hi Yu,

I have EW and UD geotiff, Now i want to plot  some profiles using these two outputs,

I know that I should use the code below.
LiCSBAS_profile.py -i infile -p dempar [-r x1,y1/x2,y2] [-g lon1,lat1/lon2,lat2] [-o outfile] [--bigendian] [--nodisplay]

{LiCSBAS_profile.py -i EW.geo.tif -p ~/Desktop/comet_licsbas/licsbas/035D_05397_131013/TS_GEOCml10clipGACOS/info/EQA.dem_par -g 51.29,35.75/51.31,35.81}

However, I don't have associated DEM files for these,  when I use the  code above  witch ASSENDING/ASSENDING DEM files
but it gives some  error

can you please advice me on wich the DEM I should use to plot profiles or any other solution 

thanks.
Ava

**Comment by yumorishita** [comment]
The input file of LiCSBAS_profile.py is not GeoTIFF but a float image. LiCSBAS_profile.py does not support the decomposed GeoTIFF file. I suggest using other general GIS tools, e.g., [QGIS profile tool](https://www.youtube.com/watch?v=UD0Oumv5y1w).

**Comment by Osmanpour** [comment]
thanks Yu.
