### ISSUE TITLE
Error with a GACOS file

### ISSUE THREAD

**Issue by yumorishita** [yumorishita/LiCSBAS#17]
From [gpsovsicori](https://github.com/gpsovsicori):

Hi, fantastic scripts, I save so much time thank to you! Scripts work amazingly! Recently, I get an error with the last month GACOS files, is there any change in the format, I need to take into account?

@t OVSICORI we appreciate you and COMET work, it gives us a complementary angle to asses volcano deformation.

Here the error:
ERROR 4: `/respaldo/InSAR/LiCSAR/157D_07909_131307_rincon/GEOCml1GACOS/sltd/20200529.bil' not recognized as a supported file format.
Traceback (most recent call last):
File "/respaldo/InSAR/LiCSAR/LiCSBAS-master/bin/LiCSBAS03op_GACOS.py", line 456, in
sys.exit(main())
File "/respaldo/InSAR/LiCSAR/LiCSBAS-master/bin/LiCSBAS03op_GACOS.py", line 297, in main
ztd_geo = gdal.Warp("", bilfile, format='MEM', outputBounds=(lonw_geo, lats_geo, lone_geo, latn_geo), width=width_geo, height=length_geo, resampleAlg=resampleAlg, srcNodata=0).ReadAsArray()
File "/home/ovsicori/anaconda3/lib/python3.7/site-packages/osgeo/gdal.py", line 579, in Warp
return wrapper_GDALWarpDestName(destNameOrDestDS, srcDSTab, opts, callback, callback_data)
File "/home/ovsicori/anaconda3/lib/python3.7/site-packages/osgeo/gdal.py", line 3189, in wrapper_GDALWarpDestName
return _gdal.wrapper_GDALWarpDestName(*args)
SystemError: returned NULL without setting an error

**Comment by yumorishita** [comment]
I have update the script to avoid the error. Could you please update your module (e.g. by git pull), try using it, and report whether it works?

**Comment by gpsovsicori** [comment]
I download the bin folder and replace it but the same error apear. Let me know if you want to check the sltd file

LiCSBAS03op_GACOS.py ver1.3 20200609 Y. Morishita
LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOCml1GACOS --fillhole

Convert ztd/sltd.geo.tif files to sltd.geo files...
  Finished    0/  28th sltd...
  Finished   10/  28th sltd...
  Finished   20/  28th sltd...
ERROR 4: `/respaldo/InSAR/LiCSAR/157D_07909_131307_rincon/GEOCml1GACOS/sltd/20200505.bil' not recognized as a supported file format.
ERROR 4: `/respaldo/InSAR/LiCSAR/157D_07909_131307_rincon/GEOCml1GACOS/sltd/20200505.bil' not recognized as a supported file format.
/respaldo/InSAR/LiCSAR/157D_07909_131307_rincon/GACOS/20200505.ztd cannot open, but trying minor update. You can ignore this error unless this script stops.
Traceback (most recent call last):
  File "/respaldo/InSAR/LiCSAR/LiCSBAS-master/bin/LiCSBAS03op_GACOS.py", line 470, in <module>
    sys.exit(main())
  File "/respaldo/InSAR/LiCSAR/LiCSBAS-master/bin/LiCSBAS03op_GACOS.py", line 311, in main
    resampleAlg=resampleAlg, srcNodata=0).ReadAsArray()
  File "/home/ovsicori/anaconda3/lib/python3.7/site-packages/osgeo/gdal.py", line 579, in Warp
    return wrapper_GDALWarpDestName(destNameOrDestDS, srcDSTab, opts, callback, callback_data)
  File "/home/ovsicori/anaconda3/lib/python3.7/site-packages/osgeo/gdal.py", line 3189, in wrapper_GDALWarpDestName
    return _gdal.wrapper_GDALWarpDestName(*args)
SystemError: <built-in function wrapper_GDALWarpDestName> returned NULL without setting an error

**Comment by yumorishita** [comment]
Can you check if all the ztd files have the same file size?

**Comment by sahitono** [comment]
Hi @yumorishita , what kind of format is BIL ? It seems gdal doesn't support it, and i dont find it in https://gdal.org/drivers/raster/index.html. That's why the error said not recognized file format.

**Comment by yumorishita** [comment]
The format is [ESRI .hdr Labelled](https://gdal.org/drivers/raster/ehdr.html). GDAL can handle it because more than 20 files before erroneous 20200505 have successfully been processed in the reported error case.

**Comment by sahitono** [comment]
Sorry, i'm not familiar with that format. Maybe there are error in header file. May i get the file ? so i can test it

**Comment by yumorishita** [comment]
The header file should be correct because it is common for all epochs and the other epochs have been read. I guess the error is in the bil file (linked to ztd file) itself.

**Comment by gpsovsicori** [comment]
Hello, it is exactly that the *ztd is empty 0kb....

**Comment by yumorishita** [comment]
OK, please request the GACOS data again and try using the correct ztd file.

**Comment by namini40** [comment]
Hi, first of all thanks a million to build such amazing script, I just got this error in loop closure part with unw data after using GACOS files. I run the same without using GACOS and no error appears.
thanks
```
LiCSBAS12_loop_closure.py ver1.2 20200228 Y. Morishita
LiCSBAS12_loop_closure.py -d GEOCml10 -t TS_gacos

loop_thre : 1.5 rad

1st Loop closure check and make png for all possible 696 loops...
    0/696th loop...
  100/696th loop...
  200/696th loop...
  300/696th loop...
  400/696th loop...
/home/na3r/anaconda3/lib/python3.7/site-packages/numpy/lib/nanfunctions.py:1115: RuntimeWarning: All-NaN slice encountered
  overwrite_input=overwrite_input)
Traceback (most recent call last):
  File "/home/na3r/Downloads/LiCSBAS-master/bin/LiCSBAS12_loop_closure.py", line 704, in <module>
    sys.exit(main())
  File "/home/na3r/Downloads/LiCSBAS-master/bin/LiCSBAS12_loop_closure.py", line 256, in main
    loop_2pin = int(np.round(np.nanmedian(loop_ph)/(2*np.pi)))*2*np.pi
ValueError: cannot convert float NaN to integer

```

**Comment by yumorishita** [comment]
Have you solved the issue? @gpsovsicori

**Comment by gpsovsicori** [comment]
Yes, I do, there were an issue with GACOS service it is know working! Thanks a lot @yumorishita

**Comment by yumorishita** [comment]
Great!
