### ISSUE TITLE
Some problems of step1-6

### ISSUE THREAD

**Issue by QiuBL** [yumorishita/LiCSBAS#170]
Dear Yu Morishita:

    I am using LiCSBAS to extract large-scale surface deformation, which is a very good tool. Thank you very much for sharing. 
    Now I encountered some problems in Step 1-6, Spatiotemporal Filtering. My data size is 4229 * 4627, and there are 291 interferograms. First, I use 1 of the multilook for data processing, but it stops at step 1-6. There is no error message output here. It seems to be running, but there is no result for a long time. When I use the the multilook of 4, it runs quickly and outputs the result. My cum.h5 file is about 3.1G, and the memory of my computer is 32g. I'm sure it's not a memory problem. I guess filtering does not require too much resources, but it is needed to remove some noise, especially atmospheric signals. For the accuracy, I must use multilook of 1.Is there any way to solve this problem?

    Best wishes!

Wenzhi Fan 
![1](https://user-images.githubusercontent.com/110988063/183918349-d2a06897-635e-464e-9533-677fc62bfd94.png)

**Comment by yumorishita** [comment]
Please try several times, or n_para=1 (see https://github.com/yumorishita/LiCSBAS/issues/62, https://github.com/yumorishita/LiCSBAS/issues/64)

**Comment by QiuBL** [comment]
Hi Yu Morishita:
      Thank you for your reply, but there is a new problem. After I change the number of threads of the CPU to 1, when I run Step 1-6, it is at 60 or 80 steps or........ Anyway, it stops running and does not report any errors. This is very strange. I've tried it many times and it's the same result.

**Comment by QiuBL** [comment]
Here, I uploaded its display


![1](https://user-images.githubusercontent.com/110988063/184302393-da8754d2-e0b3-4a7e-a111-787647c50032.png)

**Comment by yumorishita** [comment]
What is the memory size of your machine?

**Comment by QiuBL** [comment]
I use Ubantu with 32GB memory

**Comment by yumorishita** [comment]
Do you have enough disk space? Can you check the memory usage during the processing by top or htop?

**Comment by QiuBL** [comment]
I have enough hard disk, it still has 55GB left. Thank you for your reminder. Just now, I carefully checked the memory utilization rate during the running process of the program. Most of the time, it is 50% - 80%, and rarely more than 90%.
![1](https://user-images.githubusercontent.com/110988063/184378409-2ec7f507-c905-487e-9904-3031f7b03825.png)

**Comment by yumorishita** [comment]
I am not sure but it might be because of a memory problem. I recommend clipping the area and reducing the size in step5.

**Comment by QiuBL** [comment]
Thank you, I will try to upgrade my memory. In fact, I have kept the data to a minimum, because I need to get a result with a resolution of 30m, so it looks very large. In fact, it has only 6 bursts.

**Comment by QiuBL** [comment]
Hi Yu Morishita:
    You are right ！I just borrowed a 16GB memory and changed my memory to 48GB. It worked. Thank you for your advice.
