### ISSUE TITLE
NameError: name 'imdates2' is not defined in step 03

### ISSUE THREAD

**Issue by qihan1990** [yumorishita/LiCSBAS#172]
Hello, this error occurred in step 03. Can you help me solve it? Thank you.
[202208301620batch_LICSBAS_01_03.log](https://github.com/yumorishita/LiCSBAS/files/9451222/202208301620batch_LICSBAS_01_03.log)

**Comment by yumorishita** [comment]
I have never seen such an error. It seems that multiprocessing does not work well. Are you working on Windows or Mac?

**Comment by qihan1990** [comment]
I&nbsp;am&nbsp;working on Windows，modified from reference question 35 "Does LiCSBAS run on Mac OS?" before, but still doesn't work.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yu ***@***.***&gt;; 
发送时间: 2022年8月30日(星期二) 晚上9:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yumorishita/LiCSBAS] NameError: name &#39;imdates2&#39; is not defined in step 03 (Issue #172)





 
I have never seen such an error. It seems that multiprocessing does not work well. Are you working on Windows or Mac?

**Comment by qihan1990** [comment]
I am working on Windows，modified from reference question 35 "Does LiCSBAS run on Mac OS?" before, but still doesn't work.

**Comment by yumorishita** [comment]
The multiprocessing uses the start method of "[fork](https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/bin/LiCSBAS03op_GACOS.py#L186)" in LiCSBAS, but it could not work in Windows or Mac (see [this](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods)).
What python version do you use? Perhaps python3.8 might work.

**Comment by qihan1990** [comment]
Yes, so I replaced fork with spawn, but it still doesn't work. I used Python 3.6 and 3.10, and there were errors in both versions.

**Comment by yumorishita** [comment]
You cannot replace "fork" with "spwan" because "spwan" does not work in LiCSBAS. Please try using Linux on Mac,

**Comment by qihan1990** [comment]
OK, I try to run it on python3.8. If there is still an error, I will run licsbas on Linux OS using virtual box or VM ware.

**Comment by qihan1990** [comment]
OK, I see. Thank you very much.
