### ISSUE TITLE
Bug in LiCSBAS_plot_network.py -- plot_network() function call

### ISSUE THREAD

**Issue by bwwjohnson** [yumorishita/LiCSBAS#173]
Hi there,

I've getting an error when running **_LiCSBAS_plot_network.py_** in a folder with a ifg list and a baseline file. The error says "TypeError: 'bool' object is not iterable" and is referring to line 226 of  **_LiCSBAS_plot_lib.py_**

I think there's a small bug in **_LiCSBAS_plot_network.py_**. When the _plot_network()_ function is called from **_LiCSBAS_plot_lib.py_**, the _plot_bad_flag_ variable is interpreted by the function as the _ifg_cands_ variable. This means the _ifg_cands_ variable is saved as a bool which then breaks line 226 in **_LiCSBAS_plot_lib.py_**

To fix this I suggest modifying line 115 in _**LiCSBAS_plot_network.py**_ from:
plot_lib.plot_network(ifgdates, bperp, bad_ifgdates, pngfile, plot_bad_flag)
to something like:
plot_lib.plot_network(ifgdates, bperp, bad_ifgdates, pngfile, [], plot_bad_flag)

This fixed the error for me.

**Comment by yumorishita** [comment]
What do you mean by `ifg_cands`? I could not find it in `LiCSBAS_plot_lib.py` or `LiCSBAS_plot_network.py`.

**Comment by bwwjohnson** [comment]
Ah...whoops. Turns out I forgot I'm using a someone elses' fork of LiCSBAS where they've added a feature to display good, bad and bad candidate IFGs, so I should be sticking this issue on their page instead. Sorry for wasting your time!
