### ISSUE TITLE
Dear all,
Kindly there is a video or any steps for install LiCSBAS on ubuntu 20.04 ?

### ISSUE THREAD

**Issue by Obaida777** [yumorishita/LiCSBAS#174]

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/6#issuecomment-711165508

**Comment by Zuzchan** [comment]
This may be late but 

https://youtu.be/7K8M80fLRZU

But, I wouldn't be able to install LiCSBAS  without  this man!
