### ISSUE TITLE
Can LiCSBAS process data of multiple Frame at the same time?

### ISSUE THREAD

**Issue by zhouhuayun** [yumorishita/LiCSBAS#175]
My research area is covered by multiple Sentinel-1 Frames. I want to use LiCSBAS to process these multiple frames, but I can't find the relevant modules or codes. Can LiCSBAS handle multiple frames of Sentinel-1?

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/24
