### ISSUE TITLE
update licsbas

### ISSUE THREAD

**Issue by Osmanpour** [yumorishita/LiCSBAS#176]
Hi, YU,
how could I get update code?

one month a go i found it in bellow adress but I can't find it now!

github.com/comet-licsar/licsbas

**Comment by yumorishita** [comment]
I can normally see the page of the URL.

**Comment by Osmanpour** [comment]
https://github.com/comet-licsar/licsbas

**Comment by yumorishita** [comment]
What do you mean?

**Comment by Osmanpour** [comment]
I wanted to download the updated version that was previously available to
me in the link below, but now I can't find it.
https://github.com/comet-licsar/licsbas

**Comment by yumorishita** [comment]
I can find it. I don't know why you can't.

![スクリーンショット 2022-09-27 231947](https://user-images.githubusercontent.com/37470321/192552222-e884117c-2005-4020-97bf-ebcb7bf9aa09.png)

**Comment by Osmanpour** [comment]
thanks

**Comment by Osmanpour** [comment]
My study area is an urban area (Tehran, Iran) with little tectonic activity
in the past years, although there are faults with activity potential.
  The method in my studying is the combination of insar, GNSS DATA and
engineering geological information.
 Can you help me do my research better? Or put me in touch with members of
the comet team.

**Comment by Osmanpour** [comment]
that's my email adress:
ava.osmanpour@gmail.com

**Comment by yumorishita** [comment]
Sorry, but I cannot help you in my current position.
COMET would be a good collaborator for you because some researchers have studied the deformation in Iran. See the following links:
https://twitter.com/jrelliott82/status/1529075043631759360
https://comet-subsidencedb.org/

**Comment by Osmanpour** [comment]
thanks for your kindness respounbality

did you think that could I git image with better resolution than those are available on LiCSBAS for my research region? 
one time  did increased resolution 3 month ago.

**Comment by yumorishita** [comment]
Sorry but I don't understand your question. If you did it then you could.

**Comment by araditiya** [comment]
Hi Yu Morishita,
I can make sure the installation was pretty good, all messages are ok.
However, when I try to run a file batch_LiCSBAS_sample_CF.sh, it stopped at step 12 as the log file attached.
Is there something missing ?

[202211041641batch_LiCSBAS_sample_CF_01_16.log]

**Comment by araditiya** [comment]
[202211041641batch_LiCSBAS_sample_CF_01_16.log](https://github.com/yumorishita/LiCSBAS/files/9936532/202211041641batch_LiCSBAS_sample_CF_01_16.log)

**Comment by yumorishita** [comment]
Maybe there is something wrong with the latest matplotlib. Please try downgrading the matplotlib version.

**Comment by araditiya** [comment]
Thank you, it works.
Previously I used 3.6.1, then downgraded to 3.4.2.
