### ISSUE TITLE
GACOS CORRECTION

### ISSUE THREAD

**Issue by kquresh2** [yumorishita/LiCSBAS#178]
Hi,
    I have been running script for multiple areas and it worked fine. For one area, it has the issue of file sizes, so I was able to get help from previously answered questions. Right now, I am facing this issue that after GACOS correction (step-0-3), slc.mli.par file is not generated due to which the next step of unwrapping (step-0-4) also dont work. I checked and found that file size is not an issue. I even tried to re-download dataset but the issue is not resolved. I have attached error screenshot that appears after the GACOS correction completes. Also, I have attached screenshot of nan values for some Ifg in GACOS text files. Can you please help with this issue? Thanks

![process 2](https://user-images.githubusercontent.com/63307218/196775077-2c51b888-5f8d-4f2f-a469-aadc333ed2d6.JPG)

![process 3](https://user-images.githubusercontent.com/63307218/196775730-6b2cb42e-eb80-4391-8a06-d855570c23c2.JPG)

**Comment by kquresh2** [comment]
@yumorishita Looking for your help related to the above query. Thanks

**Comment by kquresh2** [comment]
@yumorishita Thanks for the quick reply. I was thinking the same to remove bad interferograms using GACOS info file. I did removed all bad ifg's from GEOC folder and even deleted GEOCml1 folder and started again from step 0-2. After doing so, I did not get any error or NaN values after GACOS correction (step 0-3). Now, the process is going smooth. Cheers!

**Comment by kquresh2** [comment]
@yumorishita I have all my results but they are raster images. I want to convert final displacement to feature layer so that I can do hotspot analysis with vector data. Is there any script or workout for that? Thanks

**Comment by yumorishita** [comment]
What do you mean by "feature layer"? Maybe [LiCSBAS_flt2geotiff.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_flt2geotiffpy) and [gdal tools](https://gdal.org/programs/index.html) (e.g., [gdal2xyz.py](https://gdal.org/programs/gdal2xyz.html)) can help.

**Comment by kquresh2** [comment]
@yumorishita by feature layer, I mean conversion from raster to point feature layer. Once I have the point data with displacement, I can run hotspot analysis tool to see the displacement pattern. I used to do SBAS in sarscape which give me feature layer with velocity point rather than raster layer. LiCSBAS_flt2geotiff.py output is single raster image which can be open in ArcGIS Pro but it is not what I am looking for.

**Comment by yumorishita** [comment]
You should be able to convert the raster data into vector data (i.e., feature layer with velocity point) in ArcGIS, though I am not familiar with ArcGIS.
https://desktop.arcgis.com/en/arcmap/latest/extensions/3d-analyst/converting-raster-surfaces-to-features.htm
https://desktop.arcgis.com/en/arcmap/latest/extensions/3d-analyst/converting-surface-data-to-vector-data.htm
https://desktop.arcgis.com/en/arcmap/latest/tools/conversion-toolbox/raster-to-point.htm

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/147
https://github.com/yumorishita/LiCSBAS/issues/24

**Comment by kquresh2** [comment]
@yumorishita cum_filt.h5 file do not have coordinate system assigned to it. Do you know how we can assign it a coordinates to it? I am not interested in one final Geotiff image which we can do by using LiCSBAS_flt2geotiff.py tool. I want to work with cum_filt.h5 file. Please let me know if you know how to do that. Thanks
