### ISSUE TITLE
Velocity Error

### ISSUE THREAD

**Issue by putriwardhanii** [yumorishita/LiCSBAS#179]
Hi,

i tried to replicate the result shown on the web [](https://comet.nerc.ac.uk/comet-volcano-portal/volcano-index/Indonesia/Indonesia/Rinjani/S1_analysis) https://comet.nerc.ac.uk/comet-volcano-portal/volcano-index/Indonesia/Indonesia/Rinjani/S1_analysis
![image](https://user-images.githubusercontent.com/116241781/196851458-9488480c-8900-44fc-8d94-c92470f8bd1f.png)

But after masking, it failed to get velocity in the peak area.
![image](https://user-images.githubusercontent.com/116241781/196851657-65062364-c9b3-4893-9d7e-3fe58650fa05.png)

What are the parameters that used to get the results that are processed on the web?

Thank you

**Comment by yumorishita** [comment]
I cannot answer your question because the result on the web was not produced by me. I suggest contacting the person in charge of the website: https://comet.nerc.ac.uk/comet-volcano-portal/contact.
