### ISSUE TITLE
How to keep those pairs with have long spatial baseline in the network

### ISSUE THREAD

**Issue by sizzer13** [yumorishita/LiCSBAS#18]
Hi,
I met a problem that in most cases, the SB of the S-1A image is small. However, if I wanna use those have longer SB, how could I add them in the Step 11?

**Comment by yumorishita** [comment]
You mean the interferograms with long spatial baselines are removed in the step11? The removed interferograms are selected based on the coherence and coverage of unwrapped pixels. You can change (lower) the thresholds to keep the interferograms in batch_LiCSBAS.sh:
https://github.com/yumorishita/LiCSBAS/blob/d8c56e7ad07d463c318e4535d7aad306e607f5db/batch_LiCSBAS.sh#L40
https://github.com/yumorishita/LiCSBAS/blob/d8c56e7ad07d463c318e4535d7aad306e607f5db/batch_LiCSBAS.sh#L41
