### ISSUE TITLE
Temporal baseline value between pairs for SBAS analysis

### ISSUE THREAD

**Issue by suatcoskun** [yumorishita/LiCSBAS#180]
Does LICSBAS  have standart value for temporal baseline  between pairs for SBAS analysis? For example  I am currently allowing for a max of 48 days between pairs.

Thank you..

**Comment by yumorishita** [comment]
No, but generally interferograms with long temporal baselines and decorrelated phases should not be used because they would include many unwrapping errors and degrade the result.

**Comment by suatcoskun** [comment]
Thank you for explanations.
