### ISSUE TITLE
On step 13, Not enough memory available compared to mem_size (8000 MB). 

### ISSUE THREAD

**Issue by zth1015** [yumorishita/LiCSBAS#181]
Hello!
On step 13, it begins with "In coordinates.
Not enough memory available compared to mem_size (8000 MB).
Reduce mem_size automatically to 1872 MB.
Read cum data on memory (fast but need memaory)."  
This does not affect the first "Identifing gaps, and counting n_gap and n_ifg_noloop "operation.  
However, on the second gaps of "Identifing, and counting n_gap and n_ifg_noloop", the application dies. Don't move at all.
What happened?
Look forward to your reply.

**Comment by yumorishita** [comment]
I don't know why but sometimes the processing gets stuck there in step13, especially when huge data is processed or the machine spec is low. I would suggest the following options to reduce data size:
- Crop the area in step05
- Shorten the time period by removing yyyymmdd_yyyymmdd dirs in GEOCml* and restart from step11
- Use larger nlook and start from step02

**Comment by zth1015** [comment]
@yumorishita Thank you very much.
