### ISSUE TITLE
Swath Profile

### ISSUE THREAD

**Issue by Sgzanjani1367** [yumorishita/LiCSBAS#182]
Hi Yu
How can I plot a swath profile ?
Do you have any tools to do that?

I would appreciate it if you have any suggestions.
Saeed

**Comment by Sgzanjani1367** [comment]
The profile is not a line, it is for example a rectangle. and the min and max and also mean values are calculated.

**Comment by yumorishita** [comment]
I may not understand your point but there is no tool to output the min/max or average in LiCSBAS. I think you can easily do it on e.g., QGIS.
