### ISSUE TITLE
about results

### ISSUE THREAD

**Issue by Alenhasha** [yumorishita/LiCSBAS#184]
Hi Yu
What is a difference between "vintercept" and "vel"?
I would appreciate it if you explain about it.

**Comment by yumorishita** [comment]
In d=vt+c, v is "vel" (velocity) and c is "vintercept" (intercept of the linear trend). They are estimated by the least-square method.

https://github.com/yumorishita/LiCSBAS/issues/22#issuecomment-652401574

**Comment by araditiya** [comment]
Hi Morishita,
I have completed to process a sample data.
Unfortunately, it can't use left click to plot the desire point meanwhile the right click is work.
I am using matplotlib 3.4.2 version. Is there any similar problem how to solve it ?
![sample](https://user-images.githubusercontent.com/60040845/200220622-ba9537dc-82e9-4ac2-bf94-ae8443c8999a.png)

**Comment by yumorishita** [comment]
I have never encountered such a problem. Please note left-"double"-click, not single-click. If you could show me a video (not the figure) of your situation, I would be able to suggest a solution.

**Comment by araditiya** [comment]
Yes, I did left double click to choose the desired point.
In the video, I plot a specific point (double left click) and change the reference using right drag. 
Unfortunately, only right-drag function is working. There is no issue with the mouse. I tried it on another machine, and it works. Looks strange on my computer.
https://user-images.githubusercontent.com/60040845/200475403-b40c3329-60a3-45fd-a1ea-a346e82a8112.mp4

**Comment by yumorishita** [comment]
Are you using matplotlib 3.4.2 as you mentioned? I see 3.5.1 in your video. Numpy version might be also the cause. I suggest downgrading them, though I am not sure if this can solve the problem,

**Comment by araditiya** [comment]
Firstly I used 3.5.1 then upgraded to 3.4.2 and got LiCSBAS properly.
However, both of them did not solve this issue.

**Comment by araditiya** [comment]
Current machine as follows,
  astropy(5.1.1) OK
  bs4(4.11.1) OK
  h5py(3.7.0) OK
  matplotlib(3.4.2) OK
  numpy(1.23.4) OK
  psutil(5.9.3) OK
  requests(2.22.0) OK
  statsmodels(0.13.2) OK
  gdal(3.3.2) OK
  
Another machine which is the old one,
  astropy(4.2.1) OK
  bs4(4.9.3) OK
  h5py(3.3.0) OK
  matplotlib(3.4.2) OK
  numpy(1.21.0) OK
  psutil(5.8.0) OK
  requests(2.22.0) OK
  statsmodels(0.12.2) OK
  gdal(3.0.4) OK

**Comment by yumorishita** [comment]
Please create the same environment as the old one and try again.

**Comment by araditiya** [comment]
I did, but it makes LiCSBAS not run well. The problem is statsmodels 0.12.2 make an error as follows. After I change back to 0.13.2, then LiCSBAS back to normal.

Check LiCSBAS library
/home/saka/.local/lib/python3.8/site-packages/statsmodels/tsa/base/tsa_model.py:7: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import (to_datetime, Int64Index, DatetimeIndex, Period,
/home/saka/.local/lib/python3.8/site-packages/statsmodels/tsa/base/tsa_model.py:7: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import (to_datetime, Int64Index, DatetimeIndex, Period,
  ERROR: PYTHONPATH is not set to LiCSBAS library

ERROR: LiCSBAS install is NOT OK

**Comment by yumorishita** [comment]
The error is not caused by statsmodels (just warning) but PYTHONPATH. Please make sure you have done `source bashrc_LiCSBAS.sh`.

**Comment by araditiya** [comment]
I was thinking as you said, but when I changed the version of statsmodels back to the latest one then no issue with PYTHONPATH. I make sure have done source bashrc_LiCSBAS.sh when I use statsmodels 0.12.2.

**Comment by Alenhasha** [comment]
Hi 
Are the results from "vel" also usable and reasonable? 
Or should only  "vel.mskd" be used for interpretation?

**Comment by yumorishita** [comment]
Generally, masked velocities should be used because the masked pixels have significant noise. You can tweak the masking thresholds in step15 and improve the masked result.

**Comment by Alenhasha** [comment]
So how can I choose not to mask based on some of these parameters? for example "vstd"

**Comment by yumorishita** [comment]
See mask_ts.png or LiCSBAS_plot_ts.py. Take trial-and-error.

**Comment by Alenhasha** [comment]
Thank you very much.

**Comment by araditiya** [comment]
The paper  doi.org/10.1186/s40645-020-00402-7 is inspiring. I assumed you use GMT to plot the figures.
Could you share us, how to plot LoS file (*.h5 ?) to GIS formats e.g. shp, kml, etc ?
How we can get shp file of the footprint of all images from the Comet portal as you showed in the paper ?

**Comment by yumorishita** [comment]
I used QGIS. You can create GeoTIFF from *h5 using [LiCSBAS_flt2geotiff.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_flt2geotiffpy), [LiCSBAS_cum2flt.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_cum2fltpy), and [LiCSBAS_cum2vel.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_cum2velpy).
The kml files of the footprint are ascending.kml and descending.kml in https://gws-access.jasmin.ac.uk/public/nceo_geohazards/shared/frames/

**Comment by yumorishita** [comment]
I recommend using [batch_LiCSBAS.sh](https://github.com/yumorishita/LiCSBAS/wiki/2_4_batch_proc#24-batch-processing).

**Comment by caijigiser** [comment]
> I recommend using [batch_LiCSBAS.sh](https://github.com/yumorishita/LiCSBAS/wiki/2_4_batch_proc#24-batch-processing).
hi Morishita，i have get through the process by the shell, it really works, you did a good job!
 And I also read about your paper "LiCSBAS: An Open-Source InSAR Time Series Analysis Package Integrated with the LiCSAR Automated Sentinel-1 InSAR Processor" , it inspired me, but I have 3 questions, i'd appreciate it if you can give me some advice~
1. What drawing software do you use？ Its visualization works well !
2. In your paper you said  If the actual displacements significantly deviate from a linear function , the solution between the gaps would become highly unreliable. In that case, functions other than linear might be better. And in my research the displacements is evidently a  non-linear type, it changes with the seasons(like the underground water level in Ojiya City)，how can I change the linear function to a seasonal non-linear function with LiCSBAS?
3. Derivative question of question 2：
![time series](https://user-images.githubusercontent.com/50088827/203488557-244c66bc-e30b-4c77-a68c-3a3fa68a71fa.png)
![gap](https://user-images.githubusercontent.com/50088827/203488606-f016efa4-c24c-4ff2-b993-a7a3372581ce.png)
There are 5 gaps in the three-year time series monitoring, I doubt it has anything to do with the non-linear displacement，the  gaps span the summer and autumn seasons and make the displacement line like a linear, what do you think about it?
ps: 537 ifgs ,464 was removed :<

Again, thank you very much~

**Comment by yumorishita** [comment]
1. I used matplotlib.
2. LiCSBAS does not support any other function than linear. What we can do is try to fill the gap (by adding ifgs or tweaking parameters) or post-process of the derived time series with linear assumption using other models (e.g., seasonal) yourself.
3. It is difficult to say something from this very limited data. I would suggest trying to improve the result, e.g., by cropping the area in step05, masking in step04, or tweaking parameters.

**Comment by araditiya** [comment]
Hi Phil Yang.

May I know what is your operating system do you use for running LiCSBAS ?
and what is the version of NumPy and matplotlib did you use ?

**Comment by kquresh2** [comment]
@yumorishita cum_filt.h5 file do not have coordinate system assigned to it. Do you know how we can assign it a coordinates to it? I am not interested in one final Geotiff image which we can do by using LiCSBAS_flt2geotiff.py tool. I want to work with cum_filt.h5 file. Please let me know if you know how to do that. Thanks
