### ISSUE TITLE
plot_ts error still exists

### ISSUE THREAD

**Issue by MDiercks** [yumorishita/LiCSBAS#187]
Dear Yu Morishita,

I still get the 'TypeError: cannot use a string pattern on a bytes-like object' message when using LiCSBAS_plot_ts.py.
I am aware that this issue has been raised multiple times already (#40 #65 #93 #119 #124 ), so apologies for the duplicate. I am using the most recent version of LiCSBAS and also tried the temporary fix suggested in #40 and #65 . 

The output of `print(h5py.File('cum_filt.h5','r')['refarea'][()])` is `b'1361:1362/1388:1389'` .

Any advice is much appreciated.
Best wishes,
Manuel

**Comment by yumorishita** [comment]
Does not the temporary solution work for you? It is the only solution I can provide.

**Comment by MDiercks** [comment]
I tried the temporary solution a second time. Somehow it causes the same error if I execute it from the installation directory, but it works when I copy the fixed LiCSBAS_plot_ts.py file to the processing directory. Not sure what's going on here...
Anyway, it works (using the temporary fix), so thanks a lot for your support!
