### ISSUE TITLE
How to remove the topographic errors

### ISSUE THREAD

**Issue by sizzer13** [yumorishita/LiCSBAS#19]
Hi
I find there remains a lot of topo. error in the velocity result. How to remove it from the velocity result?
![vel](https://user-images.githubusercontent.com/63180009/84196464-19cc8f80-aa55-11ea-97bd-9822b1535637.png)

**Comment by yumorishita** [comment]
What do you mean by topo. error? DEM error or topography-correlated tropospheric noise? Why do you think they are the error, not true deformation signals? These errors should be quite small and I wonder if they could be true deformation signals.

**Comment by sizzer13** [comment]
The reasons  why I don't consider that is a DEM error but not a deformation
signal is that, they are quite similar with the topographic relief in the
regions. For example, the basin, the river valley and etc. are quite
consistent with the velocity results. Therefore, I'm a little curious about
how to display or just remove the topo or DEM errors  in the LiCSBAS?

**Comment by yumorishita** [comment]
I haven't implemented the function to estimate/remove the DEM error (though I have a plan to implement it).

Just for a quick check, I would suggest checking the SB network plot (network/network13.png) and time series at a point with the suspected DEM error. The impact of DEM error is proportional to the perpendicular baseline. If the time series is correlated with the baseline, the point has the DEM error. If not, the topography-correlated time series and velocity are not attributed to the DEM error.

Could you show me the SB network plot and the time series?

**Comment by sizzer13** [comment]
This is one of the time series and the other one is 13.png
[image: network13.png]
[image: Time-series.png]

**Comment by sizzer13** [comment]
Maybe I made a mistake. It is not a DEM or topographic error, but an
effect resulting from the topographic relief. So, how could we consider
this part of contribution to our final results when there appears a strong
correction with the topography?

**Comment by yumorishita** [comment]
I cannot see the network13.png and Time-series.png.

If the error could be caused by topography-correlated tropospheric noises, you can remove it using --hgt_linear option at [step16](https://github.com/yumorishita/LiCSBAS/wiki/2_3_step11_16#step-1-6-filter--deramp-time-series).

**Comment by sizzer13** [comment]
The point is I have used --hgt_linear and it seems also appear the same situation there.

**Comment by yumorishita** [comment]
It might be caused by a velocity bias (see https://www.techrxiv.org/articles/Study_of_Systematic_Bias_in_Measuring_Surface_Deformation_with_SAR_Interferometry/11672532/1). Currently there is no approach for correcting this bias. Or the signal could be true deformation. I have no idea about the other error sources.
