### ISSUE TITLE
Loop problem

### ISSUE THREAD

**Issue by HN-Jiang** [yumorishita/LiCSBAS#191]
Dear Yumorishita,
I run into a problem maybe with 1-2.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FileNotFoundError: [Errno 2] No such file or directory: '/misc/zs4/hnjiang/TSX_Wuhan/Process/100/TS_GEOCml10/12loop/good_loop_png/20130508_20130826_20130508_loop.png' -> '/misc/zs4/hnjiang/TSX_Wuhan/Process/100/TS_GEOCml10/12loop/bad_loop_png/20130508_20130826_20130508_loop.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/misc/zs1/students/hnjiang/LiCSBAS/bin/LiCSBAS12_loop_closure.py", line 880, in <module>
    sys.exit(main())
  File "/misc/zs1/students/hnjiang/LiCSBAS/bin/LiCSBAS12_loop_closure.py", line 539, in main
    shutil.move(looppngfile, badlooppngfile)
  File "/misc/zs1/students/hnjiang/conda/envs/licsbas/lib/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/misc/zs1/students/hnjiang/conda/envs/licsbas/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/misc/zs1/students/hnjiang/conda/envs/licsbas/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/misc/zs4/hnjiang/TSX_Wuhan/Process/100/TS_GEOCml10/12loop/good_loop_png/20130508_20130826_20130508_loop.png'
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

However, when I check the folder, the '20130508_20130826_20130508_loop.png' is inside bad_loop_png. So it can not be inside good loop folder. 

So what should I do?

Thank you!

[202212121340batch_LiCSBAS_02_16.log](https://github.com/yumorishita/LiCSBAS/files/10209126/202212121340batch_LiCSBAS_02_16.log)

![network11](https://user-images.githubusercontent.com/53942586/207076813-4f51fcca-6527-454a-94cf-60b9d3d663bc.png)

**Comment by HN-Jiang** [comment]
I tried again, this time it's in bad_loop_cand_png folder.

**Comment by yumorishita** [comment]
Can you try again? Does the same error happen for the same file?

**Comment by HN-Jiang** [comment]
Yes, I tried 3-4 times. And I also tried to delate one of the relate igfs (like above, 20130508_20130826_20130508_loop_png-->so i delate 20130826_20130508 in GEOC).  But when I try again, it show me the same error, but another loop_png. (the name should also be A_B_A_loop_png)

**Comment by yumorishita** [comment]
It seems that your dataset has reverse "secondary_primary" (e.g., 20130826_20130508) interferograms. The name of the interferogram must be cronological "primary_secondary".

**Comment by HN-Jiang** [comment]
Thanks for this helpful suggestion. I rechecked the code, it's a stupid mistake from my GAMMA code.
Everything is fine now. Let's close this issue.

Best!
