### ISSUE TITLE
No map- blank screen

### ISSUE THREAD

**Issue by Zuzchan** [yumorishita/LiCSBAS#192]
Hey, I managed after a long time and efforts to install and run LiCSBAS 
but, I got this after run LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &

![image](https://user-images.githubusercontent.com/120248666/207156686-bfb056b3-67f3-4a19-85a4-b418dfc9eabb.png)

I really need help or any advice can be appreciated.
thank you!

**Comment by yumorishita** [comment]
Can you show me mask_ts.png? I guess all of the pixels except the reference point were masked.

**Comment by Zuzchan** [comment]
> Can you show me mask_ts.png? I guess all of the pixels except the reference point were masked.

I am sorry but I have zero knowledge so I am not sure where I can find the mask_ts.png.

**Comment by Zuzchan** [comment]
I apologize I still lack so much information so I am not sure where  to find this file,  but I looked it up in my pc and found this.

![mask_ts](https://user-images.githubusercontent.com/120248666/207444302-6c813ad0-bb5b-481c-9823-f9f2825fa29d.png)

**Comment by yumorishita** [comment]
It seems that you have mistakenly clipped the one-line area. Please check the clip area setting.

**Comment by Zuzchan** [comment]
Can you please tell me where can I check the clipped area?
I am still trying to understand how to use LiCSBAS. 
Thank you!

**Comment by yumorishita** [comment]
You must have indicated the clip area in step05. Did you use batch_LiCSBAS.sh? If so, please upload it.

**Comment by Zuzchan** [comment]
sorry, it took me so long to reply, but I was hoping to get better results, my pc kept breaking down, so I sent it the repair center and I had to start everything over again, now I have not reached this point yet,  
after doing everything in the tutorial the download files took way too much and for three times it was frozen, yet I had to close the terminal and reopen another one and rerun the batch script again which is * ./batch_LiCSBAS.sh* 
it continued downloading, but that what I get after running LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &
it is a problem with the downloading file, right?

![image](https://user-images.githubusercontent.com/120248666/208419708-8f615649-4789-4731-962f-249752d0af6e.png)
 
Later, I inserted a space in the code LiCSBAS_plot_ts.py -i TS_GEOCml1clip /cum_filt.h5 &
I got this 


![image](https://user-images.githubusercontent.com/120248666/208420208-b54dd5b9-9f4d-47a7-9073-11c38f52523a.png)

Honestly, I don't know what to do ;(

**Comment by yumorishita** [comment]
You can use LiCSBAS_plot_ts.py after batch_LiCSBAS.sh is successfully finished.

**Comment by Zuzchan** [comment]
So, you mean there is no need to redownload the files? 

I got this, I don't know if I run it at the right time, 


![image](https://user-images.githubusercontent.com/120248666/208524211-3e80f07b-53ca-46b8-9ab2-efc0f4572f79.png)


please say if I got anything wrong.
-------
Those are the files; can you tell if anything is missing?

![image](https://user-images.githubusercontent.com/120248666/208524540-f642a512-5277-4c1e-b321-abf912f9f96b.png)

**Comment by yumorishita** [comment]
No, you need to finish all steps including step01 (downloading) without errors. Please upload the log files in the `log` directory.

**Comment by Zuzchan** [comment]
I do not know why the download keeps lagging 
[202212160803batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/10273247/202212160803batch_LiCSBAS_01_16.log)
[202212170247batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/10273248/202212170247batch_LiCSBAS_01_16.log)
[202212170759batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/10273249/202212170759batch_LiCSBAS_01_16.log)
[202212182251batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/10273250/202212182251batch_LiCSBAS_01_16.log)

I tried to download another frame but got the same lagging, I didn't face this problem before, so I hope it is the internet or even ubuntu issues.

**Comment by yumorishita** [comment]
Downloading was successfully finished according to the log. The error occurred in step12 and is caused by the version of matplotlib (see https://github.com/yumorishita/LiCSBAS/issues/176#issuecomment-1303124941). Please downgrade matplotlib. I also recommend using python3.8.

**Comment by Zuzchan** [comment]
Thank you!!
I did as you said and I was able to download the whole file successfully yet, got another issue. 
I don't know why it refuses to work with me I am just that close to running it.

![image](https://user-images.githubusercontent.com/120248666/209480305-1c8c090d-1103-4812-b0b4-9787cd982591.png)

**Comment by Zuzchan** [comment]
I had to make a work environment for python 3.8 since Ubuntu kept running Python 3.10 even then uninstallation and reinstalling were not enough to solve it, this is how I was able to run step 12, 
then had to manually install python's modules. 
then it was impossible to run the LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &
it shows " osoge" is not found, could not install it with pip or conda.
so I run it again at the base without the environment of python 3.8

**Comment by Zuzchan** [comment]
Thank you so much, it worked.
now, I need to change the frame, I managed to download the files but got this error.

![image](https://user-images.githubusercontent.com/120248666/209637405-bd67ae91-cb6d-4d1e-b738-e809de4c3e65.png)

I know, I have to determine p05_clip_range_geo but I don't know how to determine it or from where I should get it.

**Comment by yumorishita** [comment]
Most of the messages are just warnings, not errors. Do you still have trouble displaying the result?

**Comment by Zuzchan** [comment]
No, it worked perfectly, thank you for your efforts, I actually have one more thing, I want to use results to be more specific about the DEM
![image](https://user-images.githubusercontent.com/120248666/210227455-dfa7e186-c63c-4108-948a-60a7a1f64a87.png)

I know I should use on of those tools
 https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#4-other-tools

but my knowledge of coding is just too poor 


LiCSBAS_flt2geotiff.py -i infile -p dempar [-o outfile] [--zero2nan] [--nan2zero] [--a_nodata num] [--bigendian]

 -i  Path to input file (float, little endian)
 -p  Path to dem parameter file (EQA.dem_par)
 -o  Output geotiff file (Default: infile[.geo].tif)
 --a_nodata   Assign a specified nodata value in output (Default: nan)
              "None" assigns no value as nodata
 --zero2nan   Replace 0 with nan (Default: NOT replace 0 with nan)
 --nan2zero   Replace nan with 0 (Default: NOT replace nan with 0)
 --bigendian  If input file is in big endian


I just don't understand how I should edit the code to run it. 
I just want an example to be able to understand the basics.

**Comment by yumorishita** [comment]
For example,
`LiCSBAS_flt2geotiff.py -i results/hgt -p info/EQA.dem_par` will create `results/hgt.geo.tif`

**Comment by Zuzchan** [comment]
This is what I get when I run it

![image](https://user-images.githubusercontent.com/120248666/210229305-4edbc014-61aa-4551-9738-6ab8b1837a09.png)

**Comment by Zuzchan** [comment]
By reviewing what you sent and issue #115 
LiCSBAS_flt2geotiff.py -i/mnt/d/licsbas/072A_05688_131313/TS_GEOCml1clip/results/hgt -p/mnt/d/licsbas/072A_05688_131313/GEOCml1clip/EQA.dem_par
this code worked 
but I need to download over different periods and more than one

LiCSBAS_flt2geotiff.py  -d 20210909 [-i/mnt/d/licsbas/072A_05688_131313/TS_GEOCml1clip/results/hgt] [-m 20220513] 
     [- p/mnt/d/licsbas/072A_05688_131313/GEOCml1clip/EQA.dem_par]
i tried this code but I hot this


ERROR:  option -d not recognized

For help, use -h or --help.

**Comment by yumorishita** [comment]
LiCSBAS_flt2geotiff.py does not have the `-d` option as is written in the usage. `hgt` is not time-dependent data.

**Comment by Zuzchan** [comment]
Then what should I do if I want to download the DEMA over different periods of time ;(

**Comment by Zuzchan** [comment]
like instead of getting just the first one 

![image](https://user-images.githubusercontent.com/120248666/210510862-1bb1551d-1df3-4084-8a45-c6a4e26d57db.png)


I want to be able to download the interference between the first image or period and for example the last one 


![image](https://user-images.githubusercontent.com/120248666/210511176-4c5ece8a-c8b2-486d-ba9d-3fbc886ac67e.png)

please say there is a way ;(

**Comment by yumorishita** [comment]
Do you mean cumulative displacement? Then, for example,
`LiCSBAS_cum2flt.py -d 20220513 -m 20210909` (run in TS_GEOCml* dir) creates `20210909_20220513.cum` file which contains displacement between 20210909 and 20220513, and
`LiCSBAS_flt2geotiff.py -i 20210909_20220513.cum -p info/EQA.dem_par` creates GeoTIFF `20210909_20220513.cum.geo.tif`.

**Comment by Zuzchan** [comment]
Is it the same as the DEM between those periods?

**Comment by Zuzchan** [comment]
I- I don't know how to write the code 
I tried this 
 LiCSBAS_cum2flt.py -d 20220513 [-i/TS_GEOCml1clip/cum_filt.h5 &] -m 202
10909
and this 
LiCSBAS_cum2flt.py -d 20220513 -m 20210909 [-i/TS_GEOCml1clip/cum_filt.
h5 &]
also this
 LiCSBAS_cum2flt.py -d 20220513 [-i/mnt/d/licsbas/072A_05688_131313/TS_GEOCml1clip/cum_filt.h5&] -m 20210909  [-p/mnt/d/licsbas/072A_05688_131313/TS_GEOCml1clip/cum_filt.h5]

but, they all show ed this error 


LiCSBAS_cum2flt.py ver1.2.2 20210910 Y. Morishita
LiCSBAS_cum2flt.py -d 20220513 [-i/TS_GEOCml1clip/cum_filt.h5

ERROR:  No cum_filt.h5 exists! Use -i option.

For help, use -h or --help.


[1]+  Exit 2                  LiCSBAS_cum2flt.py -d 20220513 [-i/TS_GEOCml1clip/cum_filt.h5



May you correct me please?

**Comment by Zuzchan** [comment]
I went back to the main page, and this worked

(licsbas) zuz@galaxyj6:/mnt/d/072A_05688_131313$ LiCSBAS_cum2flt.py -d 20220513 -m 20210909 -i TS_GEOCml1clip/cum_filt.h5 &

**Comment by Zuzchan** [comment]
I- I don't how to run this code 
LiCSBAS_flt2geotiff.py -i 20210909_20220513.cum -p info/EQA.dem_par

wrote this showed an error

ERROR:  No info/EQA.dem_par exists!

For help, use -h or --help.


So I tried to insert the path and got this


(licsbas) zuz@galaxyj6:/mnt/d/072A_05688_131313$ LiCSBAS_flt2geotiff.py -i TS_GEOCml1clip/20210909_20220513.cum -p/mnt/d
/licsbas/072A_05688_131313/GEOCml1clip/EQA.dem_par

LiCSBAS_flt2geotiff.py ver1.5.1 20210209 Y. Morishita
LiCSBAS_flt2geotiff.py -i TS_GEOCml1clip/20210909_20220513.cum -p/mnt/d/licsbas/072A_05688_131313/GEOCml1clip/EQA.dem_par

ERROR:  No TS_GEOCml1clip/20210909_20220513.cum exists!

For help, use -h or --help.

**Comment by yumorishita** [comment]
No. The DEM used in LiCSAR is SRTM.
https://comet.nerc.ac.uk/comet-lics-portal-product-details/#:~:text=1%20arc%2Dsecond%20SRTM%20DEM%20data

**Comment by Zuzchan** [comment]
So, by using LiCSBAS I won't be able to get DEM over different periods ?

**Comment by yumorishita** [comment]
No. LiCSBAS can detect mm-cm scale small displacement. The accuracy of DEM is meter order and the small displacement does not change DEM.

**Comment by Zuzchan** [comment]
okay, thank you so much, 
allow me to close it for now, but I'll reopen it, if I need anything :)

**Comment by Zuzchan** [comment]
Hey,
[202301150859batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/10419584/202301150859batch_LiCSBAS_01_16.log)


Can you please tell me how to solve this, everything was working just fine then this happened, at first, I changed the environment it was fixed, then when the downloading was paused, and I tried to resume it this happened.

**Comment by yumorishita** [comment]
I cannot reproduce the error. Can you try again?

**Comment by Zuzchan** [comment]
I tried many times nothing happened apparently it was my internet connection, it worked when I used 4G. 
Have a nice day/night!

**Comment by Zuzchan** [comment]
Uhm, I hope I am not being annoyed close this and open it a lot, butt
[202301171912batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/10441564/202301171912batch_LiCSBAS_01_16.log)

the download reaches this point and never goes further, is it because my period is too long? 2017-2021, 
I actually need to get the whole area yet; I kept making the clipping area smaller hoping it may work.
any suggests?

**Comment by yumorishita** [comment]
See this: https://github.com/yumorishita/LiCSBAS/issues/181#issuecomment-1288915501

**Comment by Zuzchan** [comment]
Just to be sure I got it right.

Crop the area in step05
**I will clip my area here and run** it.

Shorten the time period by removing yyyymmdd_yyyymmdd dirs in GEOCml* and restart from step11
**then, I will go to my file and delete all  the folders in  GEOCml and run step11, it is not clear if I have to rest of steps or do the next step of the nlook?**

Use larger nlook and start from step02
**After that I will increase the nlook 
LiCSBAS02_ml_prep.py -i GEOC -n 2
like this and run it from step2
Did I get them right???**

**Comment by yumorishita** [comment]
I cannot understand your questions. I suggest choosing one of the options and trying it, then if it does not work well, try another option. I also recommend using batch_LiCSBAS.sh.

**Comment by Zuzchan** [comment]
[202301230538batch_LiCSBAS_03_16.log](https://github.com/yumorishita/LiCSBAS/files/10476309/202301230538batch_LiCSBAS_03_16.log)
[202301230320batch_LiCSBAS_03_16.log](https://github.com/yumorishita/LiCSBAS/files/10476310/202301230320batch_LiCSBAS_03_16.log)


;(((((((((((((((((((((((((((

**Comment by Zuzchan** [comment]
I have a question; I got the same error as issue #154 
which is -ERROR: No browse image /mnt/d/006D_05509_131313/GEOCml1clip/20180611_20180617/20180611_20180617.unw.png available! -

You said " I guess one or more unw data have different size. Please check the size of unw by ls -l GEOCml1/*/*.unw, remove the incomplete file and restart from step1 again to get the complete file."

My question is: why should I start from step 01?
Since the problem is in GEOCml1 which is created in step 02???

**Comment by yumorishita** [comment]
Because the files downloaded in step01 might be corrupted.

**Comment by Zuzchan** [comment]
Then, is there a way to cancel the download when it takes so long or when it freezes instead of closing the Terminal?
So I can be sure the data won't be corrupted.

**Comment by yumorishita** [comment]
ctrl+C

**Comment by Zuzchan** [comment]
![vel filt](https://user-images.githubusercontent.com/120248666/215309400-fe0ced38-0f6f-489a-a48e-b5143e663cf6.png)

I wonder why it became like this, is there a reason? And,
Can you tell me how can I fix this, I know it's a filter, but I have no idea how to get the map without those fuss in the upper right corner.

**Comment by yumorishita** [comment]
Where is it? It may be true deformation.

**Comment by Zuzchan** [comment]
I want it to stayed like this

![vel](https://user-images.githubusercontent.com/120248666/215323909-be289270-0c15-4f33-8dbf-87d6e721465e.png)
 

instead of this 
![vel filt](https://user-images.githubusercontent.com/120248666/215323992-03150698-5381-45f2-97e0-941def0334ad.png)

**Comment by yumorishita** [comment]
I see please upload mask_ts.png.

**Comment by yumorishita** [comment]
To reduce the masked area, try increasing the threshold of n_loop_err (e.g., to 10 or more) in step15 and reprocess from step15.

Please note that loosening thresholds mean increasing noises. If possible, I recommend manually checking the 12_loop/bad_loop_cand_png, removing ifgs with unwrapping errors, and reprocessing from step11 to reduce noise.

**Comment by Zuzchan** [comment]
I tried to increase n_loop_err  to 15, I wonder what is it for like if i increase it more will this completely fix it.
![image](https://user-images.githubusercontent.com/120248666/215434993-f1b77b73-a064-4c7b-8073-5a3266a0d29c.png)


And, uhmmm 

![image](https://user-images.githubusercontent.com/120248666/215435769-cdf1f62c-03fa-470a-92ea-dd5f46d62e5d.png)



should I remove them from GEOCml7clip folder?

**Comment by yumorishita** [comment]
The ifgs in 12bad_ifg_cand_ras are just candidates of bad ifgs. You should manually check 12_loop/bad_loop_cand_png. identify the ifgs with unwrapping errors from the candidates, and remove them.

**Comment by Zuzchan** [comment]
I have no idea how to check them 
:< can you please be more specific.

**Comment by yumorishita** [comment]
Can you upload the 12bad_ifg_cand_ras directory after zipping?

**Comment by yumorishita** [comment]
It is strange. We cannot identify the unwrapping errors without 12_loop/bad_loop_cand_png.

**Comment by Zuzchan** [comment]
> 

It's unsupported

**Comment by Zuzchan** [comment]
![image](https://user-images.githubusercontent.com/120248666/215468396-ba130e5b-76e7-4367-b88a-1d66cd30158d.png)

could it be assigned under a different name.

**Comment by Zuzchan** [comment]
https://drive.google.com/file/d/1PZF9x6cnTYVPKoZOen8NmcRDe27t9daq/view?usp=drivesdk

I uploaded them to this link.

**Comment by yumorishita** [comment]
Please open the 12loop directory.

**Comment by yumorishita** [comment]
No, the ifgs in the bad_loop_png are already removed. Please upload the bad_loop_cand_png.

**Comment by Zuzchan** [comment]
It's kinda big, so here's the link

https://drive.google.com/file/d/1qOEQ6K39vphO9xhmXDTMiwMisil9hnGT/view?usp=sharing

**Comment by yumorishita** [comment]
For example, `20180130_20180205_20180217_loop.png` show a dark red area in the north-east in the loop phase (bottom right figure), which means one (or more) ifg has an unwrapping error in the area. In this case, I guess the '20180205_20180217' pair (and maybe `20180130_20180217` as well) has an unwrapping error and should be removed.
Manual inspection needs a lot of work. You might be able to ignore the unwrapping errors if you don't need very high accuracy.
![20180130_20180205_20180217_loop](https://user-images.githubusercontent.com/37470321/215763461-f326a9c0-90bf-4dea-935a-61cc26bc8949.png)

**Comment by Zuzchan** [comment]
My supervisor said we don't need it, so I guess  I'll skip this part,thank you for your efforts ✨.

**Comment by Sakina-A** [comment]
Hi Morishita
I run LiCSBAS without error using Ubuntu in Windows 10, but whenever I try to display the results using 
**eog TS_GEOCml1clip/11bad_ifg_ras/*.png &** 
or any other display command I get "cannot open display" error or nothing will show (see attached pic). 


![display error](https://user-images.githubusercontent.com/125351152/219351327-d8bc050e-1a07-4d99-9736-bc328c7d9d3d.png)

**Comment by yumorishita** [comment]
It is irrelevant to LiCSBAS. For example,
https://www.softprayog.in/troubleshooting/gtk-warning-cannot-open-display#:~:text=Make%20sure%20that%20Cygwin%2FXServer,the%20relevant%20packages%20from%20Cygwin.&text=Better%20still%2C%20put%20the%20code,DISPLAY%2C%20in%20the%20source%20code.

**Comment by Sakina-A** [comment]
Thank you so much I fixed the problem. However, I got blank display just like @Zuzchan (see attached pic) but when I open the mask_ts image it looks good (see attached pic). I used the following script:

**(licsbas) sakina@DESKTOP-JT9FAM4:~/LiCSBAS/062D_07629_131313$ LiCSBAS05op_clip_unw.py -i GEOCmldir -o GEOCml1clip -g 99.8028/100.97/13.42/14.6772 --n_para 4

LiCSBAS05op_clip_unw.py ver1.2.5 20210105 Y. Morishita
LiCSBAS05op_clip_unw.py -i GEOCmldir -o GEOCml1clip -g 99.8028/100.97/13.42/14.6772 --n_para 4

Area to be clipped:
  0:2746/0:2744 -> 919:2087/383:1642
  98.8836111/101.6286089/12.3175577/15.0605555 ->
  99.8026104/100.9696095/13.4195568/14.6775558
  Width/Length: 2746/2744 -> 1168/1259

Clip E.geo
Clip N.geo
Clip U.geo
Copy baselines
Clip hgt
Recreate hgt.png
Copy no_unw_list.txt
Clip slc.mli
Recreate slc.mli.png

Clip unw and cc
  4 parallel processing...
    0/1417th unw...
  100/1417th unw...
  200/1417th unw...
  300/1417th unw...
  400/1417th unw...
  500/1417th unw...
  600/1417th unw...
  700/1417th unw...
  900/1417th unw...
  1000/1417th unw...
  800/1417th unw...
  1100/1417th unw...
  1200/1417th unw...
  1300/1417th unw...
  1400/1417th unw...

Elapsed time: 00h 13m 44s

LiCSBAS05op_clip_unw.py Successfully finished!!

Output directory: GEOCml1clip**

I should mention that other displays works fine (e.g. network, loop, bad_infg).

![mask_ts](https://user-images.githubusercontent.com/125351152/219564759-9956e339-bde4-4a7a-b696-c086ba842329.png)
![Empty display](https://user-images.githubusercontent.com/125351152/219564901-4a9f2df7-d61e-485e-9112-627aeff360cb.png)

**Comment by yumorishita** [comment]
Please try turning off the mask.

**Comment by Sakina-A** [comment]
Thanks it worked! 
I would like to ask what`s the difference between vel(1) and vel(2) because they both give the same image? Also. I have noticed that my area is cropped at the bottom in vel.masked (see attached pic) although the previously attached vel image is fine. I have tried to change the threshold of noise indices in step 1-5 but there was no change. Could it be related to the GACOS data in step 0-3? If so my frame has 100% GACOS (see attached pic).
 
![cropped area](https://user-images.githubusercontent.com/125351152/220265149-c0a3b6f7-4016-4498-8aa8-7469f0b38b28.png)


![GACOS](https://user-images.githubusercontent.com/125351152/220266506-e54c47a5-befd-4a9e-bc54-e8091e566cba.png)

**Comment by yumorishita** [comment]
Regarding vel(1) and vel(2), see https://github.com/yumorishita/LiCSBAS/issues/117#issuecomment-878956383.
The masked bottom area is because of n_gap. Try increasing `p15_n_gap_thre`, e.g., 10.

**Comment by Sakina-A** [comment]
I tried increasing -g to 10 and 15 and also changing -l and -i but the masked bottom remained the same. I also checked GACOS tiffs individually and they were all good but I found some tiffs in the GEOC file (both cc and unw) that were cut (see attached pics). Could this be the reason? and if so will the solution be deleting them before step 0-4?

![unw](https://user-images.githubusercontent.com/125351152/221477899-50e27d64-eef9-47a0-8ef5-15d3f18c5659.png)

![cc](https://user-images.githubusercontent.com/125351152/221477934-7ff082ef-e4f1-4eb3-ad49-d28ea47a534e.png)

**Comment by yumorishita** [comment]
Can you upload `results/n_gap.png`?
Maybe the unw files published on the LiCSAR portal are corrupted.

**Comment by Sakina-A** [comment]
Sure. 
![n_gap](https://user-images.githubusercontent.com/125351152/221571436-0a9ea215-dac6-4e96-94ac-25068bc275cb.png)

**Comment by yumorishita** [comment]
Please try p15_n_gap_thre=15 or more.

**Comment by Sakina-A** [comment]
It worked! Thanks a lot.

![mask_ts_g=20](https://user-images.githubusercontent.com/125351152/221760007-a9a2f076-1e9c-4ed3-90e9-e5396e58fdc2.png)

**Comment by Zuzchan** [comment]
I have a question,
There are about 950 files in GEOC, I think this represents the number of interferograms, right?
How can I know how many images LiCSBAS used to make the interferograms?

**Comment by yumorishita** [comment]
Please see TS_GEOCml*/info/13parameters.txt.

**Comment by Zuzchan** [comment]
This may not be a good question, but I'll ask anyway.
n_im_all:       184
n_im:           183
n_ifg_all:      945
n_ifg:          926

If I want to refer to the number of interferograms, I should say 926, since it's the number of ifg that was actually produced?

**Comment by yumorishita** [comment]
926 is the number of ifg that were actually used for deriving the time series (i.e., 19 ifgs were removed).

**Comment by Zuzchan** [comment]
Thank you!
