### ISSUE TITLE
Error in inversion

### ISSUE THREAD

**Issue by mdehgani** [yumorishita/LiCSBAS#194]
Hi,

while running the LiCSBAS13_sb_inv.py, I have got the following error:

LiCSBAS13_sb_inv.py ver1.5.2 20210311 Y. Morishita
LiCSBAS13_sb_inv.py -d GEOCml1clip

In geographical coordinates
Read cum data on memory (fast but need memory).

Size of image (w,l)    : 661, 361
# of all images        : 14
# of images to be used : 14
# of all ifgs          : 51
# of ifgs to be used   : 51
# of removed ifgs      : 0
Threshold of used unw  : 14

Reference area (X/Y)   : 203:204/336:337
Allowed memory size    : 8000 MB
Number of patches      : 1
Inversion algorism     : LS
Gamma value            : 0.0001

Process 361/361th line (1/1th patch)...
  Reading 51 ifg's unw data...
  1255/238621 points removed due to not enough ifg data...

  Identifing gaps, and counting n_gap and n_ifg_noloop,
  with 8 parallel processing...
    Running  1/ 8th patch...
    Running  2/ 8th patch...
    Running  3/ 8th patch...
    Running  4/ 8th patch...
    Running  5/ 8th patch...
    Running  6/ 8th patch...
    Running  7/ 8th patch...
    Running  8/ 8th patch...

  Small Baseline inversion by LS...

  Solving  60531/237366th points with full unw at a time...
  Next, solve 176835 points including nan point-by-point...
  8 parallel processing
  Running      0/176835th point...
  Running  39000/176835th point...
  Running  28000/176835th point...
  Running   6000/176835th point...
  Running  17000/176835th point...
  Running  34000/176835th point...
  Running   1000/176835th point...
  Running  12000/176835th point...
  Running  23000/176835th point...
  Running  40000/176835th point...
  Running  29000/176835th point...
  Running   7000/176835th point...
  Running  18000/176835th point...
  Running  35000/176835th point...
  Running  13000/176835th point...
  Running   2000/176835th point...
  Running  24000/176835th point...
  Running  41000/176835th point...
  Running  30000/176835th point...
  Running   8000/176835th point...
  Running  36000/176835th point...
  Running  19000/176835th point...
  Running  14000/176835th point...
  Running   3000/176835th point...
  Running  42000/176835th point...
  Running  31000/176835th point...
  Running  25000/176835th point...
  Running   9000/176835th point...
  Running  37000/176835th point...
  Running   4000/176835th point...
  Running  15000/176835th point...
  Running  20000/176835th point...
  Running  43000/176835th point...
  Running  32000/176835th point...
  Running  10000/176835th point...
  Running  26000/176835th point...
  Running  38000/176835th point...
  Running   5000/176835th point...
  Running  16000/176835th point...
  Running  44000/176835th point...
  Running  33000/176835th point...
  Running  21000/176835th point...
  Running  11000/176835th point...
  Running  27000/176835th point...
  Running  50000/176835th point...
  Running  61000/176835th point...
  Running  72000/176835th point...
  Running  45000/176835th point...
  Running  22000/176835th point...
  Running  56000/176835th point...
  Running  67000/176835th point...
  Running  83000/176835th point...
  Running  51000/176835th point...
  Running  62000/176835th point...
  Running  78000/176835th point...
  Running  46000/176835th point...
  Running  73000/176835th point...
  Running  57000/176835th point...
  Running  68000/176835th point...
  Running  84000/176835th point...
  Running  52000/176835th point...
  Running  63000/176835th point...
  Running  79000/176835th point...
  Running  74000/176835th point...
  Running  47000/176835th point...
  Running  58000/176835th point...
  Running  53000/176835th point...
  Running  69000/176835th point...
  Running  64000/176835th point...
  Running  85000/176835th point...
  Running  80000/176835th point...
  Running  75000/176835th point...
  Running  59000/176835th point...
  Running  48000/176835th point...
  Running  54000/176835th point...
  Running  70000/176835th point...
  Running  65000/176835th point...
  Running  81000/176835th point...
  Running  76000/176835th point...
  Running  86000/176835th point...
  Running  60000/176835th point...
  Running  49000/176835th point...
  Running  55000/176835th point...
  Running  71000/176835th point...
  Running  66000/176835th point...
  Running  77000/176835th point...
  Running  82000/176835th point...
  Running  94000/176835th point...
  Running  87000/176835th point...
  Running  89000/176835th point...
  Running 100000/176835th point...
  Running 111000/176835th point...
  Running  95000/176835th point...
  Running 106000/176835th point...
  Running 122000/176835th point...
  Running  90000/176835th point...
  Running 117000/176835th point...
  Running  88000/176835th point...
  Running 101000/176835th point...
  Running 112000/176835th point...
  Running 107000/176835th point...
  Running  96000/176835th point...
  Running 123000/176835th point...
  Running  91000/176835th point...
  Running 118000/176835th point...
  Running 102000/176835th point...
  Running 113000/176835th point...
  Running 128000/176835th point...
  Running 124000/176835th point...
  Running 108000/176835th point...
  Running  92000/176835th point...
  Running 119000/176835th point...
  Running  97000/176835th point...
  Running 103000/176835th point...
  Running 114000/176835th point...
  Running 129000/176835th point...
  Running  93000/176835th point...
  Running 125000/176835th point...
  Running 104000/176835th point...
  Running 109000/176835th point...
  Running 120000/176835th point...
  Running  98000/176835th point...
  Running 115000/176835th point...
  Running 130000/176835th point...
  Running 126000/176835th point...
  Running 105000/176835th point...
  Running  99000/176835th point...
  Running 110000/176835th point...
  Running 121000/176835th point...
  Running 116000/176835th point...
  Running 133000/176835th point...
  Running 131000/176835th point...
  Running 127000/176835th point...
  Running 144000/176835th point...
  Running 139000/176835th point...
  Running 155000/176835th point...
  Running 134000/176835th point...
  Running 166000/176835th point...
  Running 150000/176835th point...
  Running 132000/176835th point...
  Running 161000/176835th point...
  Running 145000/176835th point...
  Running 140000/176835th point...
  Running 156000/176835th point...
  Running 135000/176835th point...
  Running 167000/176835th point...
  Running 151000/176835th point...
  Running 162000/176835th point...
  Running 146000/176835th point...
  Running 141000/176835th point...
  Running 136000/176835th point...
  Running 172000/176835th point...
  Running 157000/176835th point...
  Running 152000/176835th point...
  Running 168000/176835th point...
  Running 147000/176835th point...
  Running 163000/176835th point...
  Running 142000/176835th point...
  Running 137000/176835th point...
  Running 158000/176835th point...
  Running 173000/176835th point...
  Running 153000/176835th point...
  Running 169000/176835th point...
  Running 148000/176835th point...
  Running 164000/176835th point...
  Running 143000/176835th point...
  Running 138000/176835th point...
  Running 159000/176835th point...
  Running 154000/176835th point...
  Running 174000/176835th point...
  Running 149000/176835th point...
  Running 170000/176835th point...
  Running 165000/176835th point...
  Running 160000/176835th point...
  Running 175000/176835th point...
  Running 171000/176835th point...
  Running 176000/176835th point...
  Elapsed time for 1th patch: 00h 00m 21s

Find stable reference point...
Selected ref: 223:224/261:262

Writing to HDF5 file...
Traceback (most recent call last):
  File "/home/maryam/LICSBAS_PACKAGE/LiCSBAS/bin/LiCSBAS13_sb_inv.py", line 996, in <module>
    sys.exit(main())
  File "/home/maryam/LICSBAS_PACKAGE/LiCSBAS/bin/LiCSBAS13_sb_inv.py", line 838, in main
    data = io_lib.read_img(file, length, width)
  File "/home/maryam/LICSBAS_PACKAGE/LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 199, in read_img
    data = np.fromfile(file, dtype=dtype).reshape((length, width))
ValueError: cannot reshape array of size 12005560 into shape (361,661)

is there any idea to what the problem is due?

Many thank,
Maryam

**Comment by yumorishita** [comment]
It seems that `GEOCml1clip/E.geo` does not have the correct size. Remove `GEOCml1clip/[ENU].geo` and rerun step13, or retry from step05 to create the correct ones.

**Comment by mdehgani** [comment]
Thanks. It worked!

**Comment by HN-Jiang** [comment]
Hi, I run into the same problem.
Since licsbas can only clip to rectangular, but I need a polygon. So I use QGIS. And I only clip the *.geo.unw.tif and *.geo.cc.tif.

Can you please tell me what else need to be clip? 

Thank you


[202212191120batch_LiCSBAS_12_16.log](https://github.com/yumorishita/LiCSBAS/files/10259168/202212191120batch_LiCSBAS_12_16.log)

**Comment by HN-Jiang** [comment]
The unw I clipped is like this;
<img width="539" alt="clip" src="https://user-images.githubusercontent.com/53942586/208425628-ddae3ad8-847f-4c70-86f9-b44942822726.png">

**Comment by yumorishita** [comment]
All the GeoTIFF files must be clipped with the same area.
