### ISSUE TITLE
ValueError: A colormap named "SCM.romaO" is already registered

### ISSUE THREAD

**Issue by yakubhariana70** [yumorishita/LiCSBAS#195]
Hello, sir,
For the past few days, I have been repeating my lecturer's videos regarding the operation of licbas with resources from yumorishita repository. I tried several times and ran into some problems so I restarted. My last problem appears with an error message when running batch_LiCSBAS.sh to the best of my knowledge in step 12 as follows

ValueError: A colormap named "SCM. romaO" is already registered

Is there anything I can do about this?
![messageImage_1671752916576](https://user-images.githubusercontent.com/72399616/209273627-b5876b8e-5826-4f5d-afa9-1482fe097691.jpg)

**Comment by steveen9** [comment]
I have this Same problem @yumorishita

**Comment by steveen9** [comment]
I deleted it and re-install it but still the same problem

**Comment by yumorishita** [comment]
See this https://github.com/yumorishita/LiCSBAS/issues/176#issuecomment-1303308876

**Comment by steveen9** [comment]
> See this https://github.com/yumorishita/LiCSBAS/issues/176#issuecomment-1303308876

I installed matplotlib 3.4 But the problem is still there

**Comment by yumorishita** [comment]
Then please try matplotlib3.3. I also recommend python3.8.

**Comment by yakubhariana70** [comment]
my problem is solved thank you for the clue Mr @yumorishita . I using matplotlib version 3.4.2, with the steps I have been done below :
1. uninstall matplotlib
`pip uninstall matplotlib`
2. install the specific version 3.4.2
`conda install -c conda-forge matplotlib==3.4.2`

the problem SCM.romaO error was solved for me, but when you run it again you will face some new errors like h5py need to downgrade or need to install other packages/modules. I think this is normal, like playing some puzzle let's help each other haha
Now, I can run the batch_licsbas.sh smoothly

**Comment by steveen9** [comment]
Hi dear

**Comment by steveen9** [comment]
Hi dear Yumorishita 

I deleted the anaconda and licsbas and re-installed it 
Then I changed matplotlib version to 3.4.2 but still the problem
![image](https://user-images.githubusercontent.com/118799806/209470282-7a449770-34fd-4ff3-a139-493bda0e7e8e.jpeg)

**Comment by steveen9** [comment]
> my problem is solved thank you for the clue Mr @yumorishita . I using matplotlib version 3.4.2, with the steps I have been done below :
> 
> 1. uninstall matplotlib
> 
> `pip uninstall matplotlib`
> 
> 2. install the specific version 3.4.2
> 
> `conda install -c conda-forge matplotlib==3.4.2`
> 
> 
> 
> the problem SCM.romaO error was solved for me, but when you run it again you will face some new errors like h5py need to downgrade or need to install other packages/modules. I think this is normal, like playing some puzzle let's help each other haha
> 
> Now, I can run the batch_licsbas.sh smoothly

Hi dear 
Please Can you show me the version of these tools in your laptop

![image](https://user-images.githubusercontent.com/118799806/209472426-8d0c0830-96b2-458f-a452-e8eeaea8fc31.jpeg)

**Comment by steveen9** [comment]
@yumorishita
