### ISSUE TITLE
Result have uplift from LiCSBAS

### ISSUE THREAD

**Issue by HN-Jiang** [yumorishita/LiCSBAS#196]
Dear yumorishita,
Hi.
I process the urban area with LiCSBAS. The detected deformation area is correct. But in the result, it have some large area of uplift which is wrong. 
So do you think I did anything worng? Or how can I fix it?

Many thanks!

<img width="449" alt="nomaskvelocity" src="https://user-images.githubusercontent.com/53942586/209328943-ca913b98-d6d4-422e-8420-966025acfdd4.png">
<img width="451" alt="velocity" src="https://user-images.githubusercontent.com/53942586/209328950-97c3610e-c3f6-4995-98a6-c821593685ce.png">
<img width="453" alt="cumulative" src="https://user-images.githubusercontent.com/53942586/209328951-8583d946-436d-4e74-b13c-3797b3063276.png">
<img width="453" alt="no mask cumulative" src="https://user-images.githubusercontent.com/53942586/209328952-39f15c46-f3c6-4e07-92f8-eb06c4cfb353.png">

**Comment by yumorishita** [comment]
Where is the "wrong uplift area"? How do you know the area is not uplifting?
One of the possible causes is unwrapping errors. You should check all the loop phase images and unwrapped images.
Another possible cause is the reference selection issue. If the selected reference point actually has subsidence, the surrounding stable area would show artificial uplift. You should manually select the stable area as the reference if you know the stable area apriori.

**Comment by HN-Jiang** [comment]
Thank you for your suggestion. I think I have found the problem. The uplift is from the bad unwrapping interferogram. I will reprocess it.
By the way, if I want to output all points time series cumulative deformation value, is that possible in licsbas? (With lon and lat)

**Comment by HN-Jiang** [comment]
Since I checked the closed answer, I know that it can be get by using for cyclic. And I already did. But it's too slow. Is there a way to read float32 generate from LiCSBAS_cum2flt.py?

**Comment by HN-Jiang** [comment]
![图片](https://user-images.githubusercontent.com/53942586/209659551-8e9a4e02-dc6e-4789-a96d-5bcff8273c47.png)
For now I can only use for cyclic and it's super slow. (Because I'm trying some further processing by coding, so I need the all points time series) .Please give me some suggestion.
