### ISSUE TITLE
Colormap ValueError

### ISSUE THREAD

**Issue by dinsar2008** [yumorishita/LiCSBAS#198]
Hi Morishita,

I am trying to obtain velocity by LiCSBAS. When I get to the step12  `**LiCSBAS12_loop_closure.py -d GEOCml1GACOSmaskclip**` , the software exits and an error is reported as " **ValueError: A colormap named "SCM.roma0" is already registered**", and part figures of the loop closure checking results are generated in the folder TS_GEOCml1maskclip/12loop/good_loop_png. The error report as follows.

 ![屏幕截图 2022-12-31 162037](https://user-images.githubusercontent.com/62060340/210128846-28d2b9d0-bb0f-490a-a006-9593ca9b3c37.png)

I check the code track, it seems like that the colormap is not created correctly or cited by the multiprocessing/pool.py.  I wonder what's going on， and how to fix it?
Any suggestion would be appreciated.

**Comment by dinsar2008** [comment]
Maybe it's caused by the enviroment problem. I reinstalled the anaconda3 and LiCSBAS, then this step works through.

**Comment by Zuzchan** [comment]
can you please upload the log file?

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/176#issuecomment-1303308876
https://github.com/yumorishita/LiCSBAS/issues/195#issuecomment-1363954623

**Comment by Zuzchan** [comment]
I had the same issue and as you can see your Ubuntu is running Python version3.9, delete the app and reinstalling everything would be just a waste of time, 
Here is how I solved it 
I installed python3.8 and make an environment work for it and rerun the same stapes and it worked like a miracle 


sudo apt update
sudo apt upgrade
sudo apt install python3-venv python3-pip python3-tk
sudo apt install python3.8 python3.8-dev python3.8-venv
python3.8 -m venv work3.8
source work3.8/bin/activate

**to activate it

**Comment by dinsar2008** [comment]
Thank you very much, yumorishita and Zuzchan. It works well following your suggestion.
