### ISSUE TITLE
About the GACOS

### ISSUE THREAD

**Issue by xbdqs** [yumorishita/LiCSBAS#199]
Hello,
Happy new year!
Does the gacos data download from the GACOS website need extra process, because I notice the name of the is not the same, *.sltd.geo.tif, *.ztd.tif.  What is the meaning of sltd.  In addation, when I load them with the QGIS, the value of them are different. You can see as the screenshot.

![QGIS](https://user-images.githubusercontent.com/67006502/210222251-1398bdf5-192e-4a7a-ab64-1273fd499ba5.png)

p.s.  I confirm the time of gacos as fellow.
https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/77/077D_05487_141313/metadata/metadata.txt
![TIME](https://user-images.githubusercontent.com/67006502/210222621-0ee1de23-f2b0-41a8-8533-f6027c17be06.png)

**Comment by yumorishita** [comment]
sltd and ztd are "slant total delay" in radian and "zenith total delay" in meter.

**Comment by xbdqs** [comment]
Is it derived from the *ztd.tif product? Or htey are the same.

**Comment by yumorishita** [comment]
sltd is derived from ztd 
https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/bin/LiCSBAS03op_GACOS.py#L433

**Comment by xbdqs** [comment]
> sltd is derived from ztd
> 
> https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/bin/LiCSBAS03op_GACOS.py#L433

Thank you for your reply.

Another issue is about the memory limit in Step1-2 and 1-3, sometimes it doesn't work in 1-2, sometimes in 1-3. I browse the analogous issue and your suggestion. Clip in 0-5, enlarging the n look in 0-2, or reduce the processing data. If I just delete some unw pairs in GEOC file, starting from 0-2, without changing the start and end date, can this issue be resolved? I have a try, but it seems not well.

**Comment by xbdqs** [comment]
The last, 
1. if I want to obtain the decomposition information of  E and U by the ascending and descending, do I need to clip the A and D results with the intersecting area of them?  
3. If the area of interest is crossing some Frame, e.g., linear engineering, to get the deformation of E-W and vertical wholly,  unless the  mosaic of each  intersecting area, can we use the entire merged A and D results, and then computing by the [LiCSBAS_decomposeLOS.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_decomposelospy).

**Comment by yumorishita** [comment]
The unw data must be removed from GEOCml as well as GEOC or the existing file will be used.
1. No, the common area is automatically clipped and used for decomposition.
2. Yes, I think so.

**Comment by xbdqs** [comment]
Hi Morishita,
Great thanks for your reply.

About the U-D/E-W decomposing,  are the heading and incidence angles used the average, or is each pixel different? I tried to read the original code, but with the poor ability of this aspect, I did not find some calculation formulas for its description. Can you recommend me some? 
Thanks a lot.

**Comment by yumorishita** [comment]
The angles at each pixel are used for decomposition.

**Comment by xbdqs** [comment]
> The angles at each pixel are used for decomposition.

Thank you.
