### ISSUE TITLE
Missing LiCSAR products

### ISSUE THREAD

**Issue by merkato** [yumorishita/LiCSBAS#2]
When trying automatic toolchain there's downloading error:

Create E.geo
  No *.geo.E.tif found in GEOC
  Error while downloading from http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/51/051D_03973_131313/metadata/051D_03973_131313.geo.E.tif

Create N.geo
  No *.geo.N.tif found in GEOC
  Error while downloading from http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/51/051D_03973_131313/metadata/051D_03973_131313.geo.N.tif

Create U.geo
  No *.geo.U.tif found in GEOC
  Error while downloading from http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/51/051D_03973_131313/metadata/051D_03973_131313.geo.U.tif

Looking at the webpage in that dataframe or similar there's no those files.
**What should be in these geotiffs?** 
Maybe I can prepare it myself?

**Comment by yumorishita** [comment]
This issue is related to LiCSAR products, not LiCSBAS. I have asked the person in charge to create the missing tif files. They will be ready soon.

**Comment by yumorishita** [comment]
The missing tif files are ready. Please try again.
