### ISSUE TITLE
About the LiCSBAS_out2nc.py

### ISSUE THREAD

**Issue by xbdqs** [yumorishita/LiCSBAS#200]
Hi, 
When I want to use LiCSBAS_out2nc.py to translate the results as a NetCDF4 format, I notice that this script is not included in the LiCSBAS package. So I add this script to the .../bin path of LiCSBAS, but it does not work. Can you tell me how to use this script successfully?

**Comment by yumorishita** [comment]
Put the script in `TS_GEOCml*` and run `python3 ./LiCSBAS_out2nc.py` in `TS_GEOCml*`.

**Comment by xbdqs** [comment]
I have a try, but there is an error.
![error](https://user-images.githubusercontent.com/67006502/211201918-b8ecd28f-ec59-4f15-91f9-558e67171567.png)

**Comment by xbdqs** [comment]
It seems to be the problem of the gdal.

**Comment by yumorishita** [comment]
gdal in conda may have a conflict with gdal in the system. I suggest uninstalling gdal in the system.

**Comment by xbdqs** [comment]
Hi Morishita,
I have changed the gdal, but some issues still exist.

LiCSBAS_out2nc.py ver1.0 20200904 M.Lazecky
LiCSBAS_out2nc.py 

Traceback (most recent call last):
  File "/media/dqssar/3b144a66-46ac-49a8-98f7-3523c6874f8f/new/real/070A_05479_131313/TS_GEOCml1GACOS/./LiCSBAS_out2nc.py", line 262, in <module>
    sys.exit(main())
  File "/media/dqssar/3b144a66-46ac-49a8-98f7-3523c6874f8f/new/real/070A_05479_131313/TS_GEOCml1GACOS/./LiCSBAS_out2nc.py", line 234, in main
    if cliparea_geo:
UnboundLocalError: local variable 'cliparea_geo' referenced before assignment

![error](https://user-images.githubusercontent.com/67006502/211560830-d7126ef8-18d4-4cd6-b73e-68aaa305d88f.png)

**Comment by yumorishita** [comment]
It seems to be a bug. Please comment out lines 234-235.

**Comment by xbdqs** [comment]
Great, it works. Thank you very much.

**Comment by Sakina-A** [comment]
Hi Morishita

I have been having issues with the reference point when converting the time series to NetCDF. I checked that my reference point exists using LiCSBAS_plot_ts.py (see attached pic) and also tried different reference points, but I still get the warning '**no points in the reference area - will export without referencing**'.

![EXIST](https://github.com/yumorishita/LiCSBAS/assets/125351152/797d7509-2586-44c1-9dc8-dc7c4ad11a5d)

![refrence point](https://github.com/yumorishita/LiCSBAS/assets/125351152/fdc522eb-d9b7-44af-bc40-d9966ccc2120)

**Comment by Sakina-A** [comment]
I understand, thank you.

**Comment by NodyPeng** [comment]
Hello, I met the same problem, too.
May I ask you how to fix the problem about the cliparea_geo? 
Thank you very much.
