### ISSUE TITLE
LiCSBAS_loop_closure.py

### ISSUE THREAD

**Issue by irmayolii** [yumorishita/LiCSBAS#201]
Dear Prof. Yumorishita

why when I run the batch without clipping, 2nd loop closure always error like this (picture). But when I run it by clipping to small area the process is successful. Anyway I set the time parameter start from 20180929 to 20220504.

![image](https://user-images.githubusercontent.com/80675405/213623179-8b4011ff-1f51-4962-81b2-aa04fb52ba67.png)

**Comment by yumorishita** [comment]
This error is because all pixels have one or more unwrapping errors. (https://github.com/yumorishita/LiCSBAS/issues/63)
Please clip the area or remove ifgs with unwrapping errors.

**Comment by irmayolii** [comment]
Thankyou!
