### ISSUE TITLE
Colormap conflict between LiCSBAS and matplotlib

### ISSUE THREAD

**Issue by sabmet** [yumorishita/LiCSBAS#202]
Dear Yu,
we encountered the problem of a broken color map name handling, when executing the script _LiCSBAS12_loop_closure.py_ and continuously had the error: 

ValueError: A colormap named "SCM.romaO" is already registered. 

The problem appeared in a classroom environment with 20 PCs with Ubuntu Linux 20.04 LTR, where we choose to install LiCSBAS into an existing conda enviroment, set up with miniconda, using python3.9. In this environment we used your provided _requirements.txt_ file to install the dependencies needed to run LiCSBAS. Students using their own notebooks with different operating systems had the same error.
Our "quick fix" to the error was to uninstall _matplotlib 3.6.3_ and installed the older version _matplotlib-3.5.3_ via _pip_. A further fix of a student was to change the two lines in the _LiCSBAS_loop_lib.py_ where the _SCM.romaO_ color map appears, and replace it by a standard color map.  To continue our class, we decided to downgrade matplotlib via pip. Could you consider to update your library? This could be helpful for many other users of LiCSBAS. 
Thanks! (Harald Schernthanner, Uni Potsdam, Najib Kakar and Sabrina Metzger, GFZ Potsdam)

**Comment by yumorishita** [comment]
The issue and the solution are already reported.
https://github.com/yumorishita/LiCSBAS/issues/176#issuecomment-1303308876
https://github.com/yumorishita/LiCSBAS/issues/195#issuecomment-1363954623
https://github.com/yumorishita/LiCSBAS/issues/198

Unfortunately, I cannot update this repository for a reason. I am planning to create another repository and continue to develop LiCSBAS there. Please wait for a while.

**Comment by sabmet** [comment]
Thanks Yu, and sorry for annoying you with already reported bugs. But I am glad we got to the same solution as you for the fix. I also hope you soon can fix the problem with the repository updates and wish you all the best!
Sabrina

**Comment by yumorishita** [comment]
FYI, I created a new repository LiCSBAS2, develop a new function, and fix bugs there.
https://github.com/yumorishita/LiCSBAS2
