### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by HN-Jiang** [yumorishita/LiCSBAS#206]
Can I please ask is this problem from licsbas?
OSERROR:[Error 12]Cannot allocate memory

[202302031132batch_LiCSBAS_16_16.log](https://github.com/yumorishita/LiCSBAS/files/10578803/202302031132batch_LiCSBAS_16_16.log)

**Comment by yumorishita** [comment]
I cannot find the "OSERROR:[Error 12]Cannot allocate memory" in the attached log.
I see "command not found". Please set the PATH by [source ](https://github.com/yumorishita/LiCSBAS/wiki/1_Installation#12-licsbas-module).

**Comment by YuPengfei1999** [comment]
Hi
I want to run batch_LiCSBAS.sh, but I have the same error at the step 16.And then, the program seemed to stop running.
What should I do?

LiCSBAS15_mask_ts.py Successfully finished!!

Output png: TS_GEOCml1GACOSmask/mask_ts.png


LiCSBAS16_filt_ts.py ver1.5.1 20210311 Y. Morishita
LiCSBAS16_filt_ts.py -t TS_GEOCml1GACOSmask -r 1
No bperp field found in cum.h5. Skip.

Size of image (w,l)      : 3428, 2677
Number of images         : 128
Width of filter in space : 2 km (23.1x18.0 pixel)
Width of filter in time  : 0.117 yr (42 days)
Deramp flag              : 1
hgt-linear flag          : False

Deramp ifgs with the degree of 1,
with 16 parallel processing...
    0/128th image...
   10/128th image...
   20/128th image...
   30/128th image...
   40/128th image...
   50/128th image...
   60/128th image...
   70/128th image...
   80/128th image...
   90/128th image...
  100/128th image...
  110/128th image...
  120/128th image...

Create png for increment with 16 parallel processing...

HP filter in time, LP filter in space,
with 16 parallel processing...
    0/128th image...
   10/128th image...
   20/128th image...
   30/128th image...
   40/128th image...
   50/128th image...
   60/128th image...
   70/128th image...
   80/128th image...
   90/128th image...
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/pool.py", line 513, in _handle_workers
    cls._maintain_pool(ctx, Process, processes, pool, inqueue,
  File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/pool.py", line 337, in _maintain_pool
    Pool._repopulate_pool_static(ctx, Process, processes, pool,
  File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  100/128th image...
  110/128th image...
  120/128th image...

**Comment by YuPengfei1999** [comment]
> Hi I want to run batch_LiCSBAS.sh, but I have the same error at the step 16.And then, the program seemed to stop running. What should I do?
> 
> LiCSBAS15_mask_ts.py Successfully finished!!
> 
> Output png: TS_GEOCml1GACOSmask/mask_ts.png
> 
> LiCSBAS16_filt_ts.py ver1.5.1 20210311 Y. Morishita LiCSBAS16_filt_ts.py -t TS_GEOCml1GACOSmask -r 1 No bperp field found in cum.h5. Skip.
> 
> Size of image (w,l) : 3428, 2677 Number of images : 128 Width of filter in space : 2 km (23.1x18.0 pixel) Width of filter in time : 0.117 yr (42 days) Deramp flag : 1 hgt-linear flag : False
> 
> Deramp ifgs with the degree of 1, with 16 parallel processing... 0/128th image... 10/128th image... 20/128th image... 30/128th image... 40/128th image... 50/128th image... 60/128th image... 70/128th image... 80/128th image... 90/128th image... 100/128th image... 110/128th image... 120/128th image...
> 
> Create png for increment with 16 parallel processing...
> 
> HP filter in time, LP filter in space, with 16 parallel processing... 0/128th image... 10/128th image... 20/128th image... 30/128th image... 40/128th image... 50/128th image... 60/128th image... 70/128th image... 80/128th image... 90/128th image... Exception in thread Thread-7: Traceback (most recent call last): File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/threading.py", line 932, in _bootstrap_inner self.run() File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/pool.py", line 513, in _handle_workers cls._maintain_pool(ctx, Process, processes, pool, inqueue, File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/pool.py", line 337, in _maintain_pool Pool._repopulate_pool_static(ctx, Process, processes, pool, File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static w.start() File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/process.py", line 121, in start self._popen = self._Popen(self) File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/context.py", line 277, in _Popen return Popen(process_obj) File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/popen_fork.py", line 19, in **init** self._launch(process_obj) File "/home/yu/software/miniconda3/envs/licsbas/lib/python3.8/multiprocessing/popen_fork.py", line 70, in _launch self.pid = os.fork() OSError: [Errno 12] Cannot allocate memory 100/128th image... 110/128th image... 120/128th image...

This is problem is not from licsbas. I ran LiCSBAS16_filt_ts.py and give n_para a smaller number, and then, the programe worked.

**Comment by YuPengfei1999** [comment]
There is no detailed information about deramp at steps 1-6. Is the ramp removed from each interferogram using a network approach following Biggs ( 2007 ) ？

**Comment by yumorishita** [comment]
No, the network approach is not used. The deramp is done for each date.

**Comment by YuPengfei1999** [comment]
> No, the network approach is not used. The deramp is done for each date.

Are there any references?

**Comment by yumorishita** [comment]
Do you mean reference paper, reference point/area, or reference date?
