### ISSUE TITLE
Problem in downloading and working on some frames

### ISSUE THREAD

**Issue by mdehgani** [yumorishita/LiCSBAS#207]
Hi,
In working on some frames, the interferograms and other products cannot be downloaded while at the same time there is no problem with other frames. I've got the following message:
OSError for 137D_05960_131313.geo.E.tif in 1th try
ConnectionEncodingError for 137D_05960_131313.geo.E.tif in 2th try
ChunkedEncodingError from ....

Could you please help me how to fix the problem?

Thanks

**Comment by yumorishita** [comment]
Please show the full log.

**Comment by mdehgani** [comment]
> 

LiCSBAS01_get_geotiff.py ver1.6.3 20201207 Y. Morishita
LiCSBAS01_get_geotiff.py -f 064D_06083_131313 -s 20220101 -e 20221109

Frame ID is 064D_06083_131313

Download 064D_06083_131313.geo.E.tif
    ChunkedEncodingError for 064D_06083_131313.geo.E.tif in 1th try
    ChunkedEncodingError for 064D_06083_131313.geo.E.tif in 2th try
    OSError for 064D_06083_131313.geo.E.tif in 3th try
    Error while downloading from http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/64/064D_06083_131313/metadata/064D_06083_131313.geo.E.tif
Download 064D_06083_131313.geo.N.tif
    OSError for 064D_06083_131313.geo.N.tif in 1th try
    064D_06083_131313.geo.N.tif, 23.59MB, 137s, 176.29KB/s
Download 064D_06083_131313.geo.U.tif
    OSError for 064D_06083_131313.geo.U.tif in 1th try
    ChunkedEncodingError for 064D_06083_131313.geo.U.tif in 2th try
    ChunkedEncodingError for 064D_06083_131313.geo.U.tif in 3th try
    Error while downloading from http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/64/064D_06083_131313/metadata/064D_06083_131313.geo.U.tif
Download 064D_06083_131313.geo.hgt.tif
    064D_06083_131313.geo.hgt.tif, 22.37MB, 163s, 140.56KB/s

Download baselines
    baselines, 4.96KB, 1s, 4.96KB/s
Download network.png
    network.png, 568.22KB, 100s, 5.68KB/s
Download metadata.txt
    metadata.txt, 197.0B, 2s, 98.0B/s

Searching latest epoch for mli...
    0/ 22
20221109 found as latest.
Donwnloading 20221109.geo.mli.tif as 064D_06083_131313.geo.mli.tif...
    064D_06083_131313.geo.mli.tif, 18.1MB, 212s, 87.42KB/s



Download geotiff of unw and cc
Traceback (most recent call last):
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/urllib3/response.py", line 443, in _error_catcher
    yield
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/urllib3/response.py", line 818, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/urllib3/response.py", line 771, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/home/dehghani/anaconda3/lib/python3.9/http/client.py", line 626, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/dehghani/anaconda3/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/dehghani/anaconda3/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/home/dehghani/anaconda3/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/urllib3/response.py", line 623, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/urllib3/response.py", line 844, in read_chunked
    self._original_response.close()
  File "/home/dehghani/anaconda3/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/urllib3/response.py", line 460, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dehghani/LiCSBAS/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 499, in <module>
    sys.exit(main())
  File "/home/dehghani/LiCSBAS/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 321, in main
    response = requests.get(url_ifgdir)
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/home/dehghani/anaconda3/lib/python3.9/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

**Comment by yumorishita** [comment]
I could not reproduce the error. Maybe there was an issue on the server side. Please try again.

**Comment by Zuzchan** [comment]
Try changing the internet network, this is what worked for me when I faced a similar error.

**Comment by mdehgani** [comment]
Thanks. But it does not work. I tried with three different internet networks.

**Comment by yumorishita** [comment]
Can you change the line below to
`    LiCSARweb = 'https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/'`
and try again?

https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/bin/LiCSBAS01_get_geotiff.py#L161

**Comment by mdehgani** [comment]
Hi, I will try and let you know about the results. Many thank.

**Comment by mdehgani** [comment]
Unfortunately, the problem still exists. But the point is that in running different times, different statuses occur. I mean, for example, in one run the E component can be easily downloaded but in the next time it cannot be downloaded but other files are downloaded.
It seems that the network connection and disconnection is sequentially happening. However, my internet network is very stable and there is no problem with other websites. This problem also exists when trying to go directly through the https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/. In one time there is no problem for entering the page but in another time I can not connect to the site.
I checked with the IT administrator and found that there is no change in the internet network and its access to websites since 1 month ago. Therefore, maybe the problem is not from our side.

**Comment by yumorishita** [comment]
Then please contact COMET. I cannot help you from the LiCSBAS side.

**Comment by Sakina-A** [comment]
Hi Morishita,
My study area is within two frames, so I was wondering is it possible for LiCSBAS to process two frames (or more) at the same time?

**Comment by yumorishita** [comment]
Of course yes, if your machine has enough computational resources.

**Comment by Sakina-A** [comment]
Great! 
One more thing when I use the command **LiCSBAS01_get_geotiff.py** can I list the two frames together because they have the same start and end date like:
**LiCSBAS01_get_geotiff.py -f FRAME-1 -f FRAME-2 -s start_date -e end_date** 
and will the results merge the two frames into one time series and velocity or consider each frame as a separate result?

**Comment by Sakina-A** [comment]
Got it. Thank you so much.

**Comment by wharfbanger** [comment]
Dear Yu, I am getting the ChunkedEncodingError error when running batch_LiCSBAS.sh :   


**Here is the error during Step 1:**
Donwnloading 20200427_20200602 (15/203)...
    ChunkedEncodingError for 20200918_20210621.geo.cc.tif in 1th try

**Directory is 044D_13529_282617**

**Here is my batch_LiCSBAS.sh:**

#################
### Settings ####
#################
start_step="01"	# 01-05, 11-16
end_step="16"	# 01-05, 11-16

nlook="1"	# multilook factor, used in step02
GEOCmldir="GEOCml${nlook}"	# If start from 11 or later after doing 03-05, use e.g., GEOCml${nlook}GACOSmaskclip
n_para="1" # Number of paralell processing in step 02-05,12,13,16. default: number of usable CPU
gpu="n"	# y/n
check_only="n" # y/n. If y, not run scripts and just show commands to be done

logdir="log"
log="$logdir/$(date +%Y%m%d%H%M)$(basename $0 .sh)_${start_step}_${end_step}.log"

### Optional steps (03-05) ###
order_op03_05="03 04 05"	# can change order e.g., 05 03 04
do03op_GACOS="n"	# y/n
do04op_mask="n"	# y/n
do05op_clip="y"	# y/n
p04_mask_coh_thre=""	# e.g. 0.2
p04_mask_range=""	# e.g. 10:100/20:200 (ix start from 0)
p04_mask_range_file=""	# Name of file containing range list
p05_clip_range=""	# e.g. 10:100/20:200 (ix start from 0)
p05_clip_range_geo="167.830/169.130/-46.66/-45.61"	# e.g. 130.11/131.12/34.34/34.6 (in deg)

### Frequently used options. If blank, use default. ###
p01_start_date="20180701"	# default: 20141001
p01_end_date="20220701"	# default: today

**Comment by yumorishita** [comment]
Please upload the full log. I suggest rerunning it.

**Comment by wharfbanger** [comment]
> Please upload the full log. I suggest rerunning it.

Thanks looks like its all good now after rerunning!
