### ISSUE TITLE
Use LiCSBAS process ALOS PALSAR data

### ISSUE THREAD

**Issue by DaisyUoE** [yumorishita/LiCSBAS#209]
Hi Morishita,
My Kathmandu paper is planning to submit soon, and you are in the first sentence of acknowledgement. Now I am interested in looking at the mountain front area in Nepal. However, the vegetation is generating lots of noise in Sentinel-1 results. I am thinking about trying to use ALOS data instead. If I have  *.geo.unw.tif and *.geo.cc.tif for ALOS interfergrams, could I use LiCSBAS software to process the SBAS results?
Thanks,
Daisy

**Comment by yumorishita** [comment]
Yes.
Do you want to use ALOS data, not ALOS-2? I wonder if there are enough ALOS data in Nepal. The baseline condition is also a point to be considered.

**Comment by DaisyUoE** [comment]
I will use both, ALOS-1 and ALOS-2, I used ALOS data before by using a commercial software, and combined both ALOS-1 and ALOS-2 as input data, it seems have no difference, beside the time coverage. The perpendicular baseline was around +-1000 m for the SBAS network. I have been told for L-band, that perpendicular baseline was acceptable, and the SBAS result was high coherence and reliable.

**Comment by DaisyUoE** [comment]
Hi Morishita,
I managed to use SNAP+SNAPHU to generate *.geo.cc.tif and *.geo.unw.tif. However, I noticed in \GEOC folder, there are also *.geo.E.tif, *.geo.N.tif, *.geo.U.tif, *.geo.hgt.tif, *.geo.mli.tif, baselines, metadata.txt, and network.png (please see attached picture). I suspect those files are output from Gamma software, am I right?
Could I run LiCSBAS software without those additional files, only *.geo.cc.tif and *.geo.unw.tif? Otherwise, I think I need to use GAMMA software to generate DInSAR images.

Thanks,
Daisy
![1](https://user-images.githubusercontent.com/105612384/218789073-295f864c-ca58-445e-b24a-7e8d892a9831.jpg)

**Comment by yumorishita** [comment]
I don't remember but these files are not necessary for LiCSBAS processing.
Even though they are required, they should be able to be created by SNAP. *tif is GeoTIFF and not a GAMMA-specific format.

**Comment by DaisyUoE** [comment]
Got it, thanks. Do you know if there is anywhere I could freely download ALOS L1.1 data. I found 4 images from the ASF website so far, hoping to have more ALSO data.

**Comment by yumorishita** [comment]
[ALOS L1.1 data will become freely available from JAXA](https://www.eorc.jaxa.jp/ALOS/en/dataset/alos_open_and_free_e.htm), but the exact date is not announced yet.
[ALOS interferograms are available in some areas from AIST](https://github.com/yumorishita/LiCSBASpatch_AIST_ALOS), but they do not cover Nepal.
I have no other idea to get ALOS data freely.

**Comment by DaisyUoE** [comment]
I am so excited to see AIST and the LiCSBASpatch_AIST_ALOS, they are really user friendly. Thanks for sharing the link. Do you think AIST may be interested in collaborating with tomorrow cities project (https://www.tomorrowscities.org/city/kathmandu). And adding ALOS interferograms to the Nepal region? -Daisy

**Comment by yumorishita** [comment]
I will discuss it with AIST people (actually I am also a part of the AIST team).

**Comment by DaisyUoE** [comment]
It is great to know you are in the AIST team, hope we could collaborate. If you and the AIST team are interested, please feel free to contact Prof. Hugh Sinclair (hugh.sinclair@ed.ac.uk), he is my supervisor. 
Prof. Tim Wright is also part of the tomorrow cities project, he suggested LiCSBAS software to me at the beginning. -Daisy

**Comment by yumorishita** [comment]
If the area is completely submerged in some periods, I think the time series including the submerged periods are unreliable. Maybe a strong filter of the LiCSAR products has generated artificial signals on water bodies. I suggest checking the unw data in the submerged periods one by one.

We discussed the ALOS data processing in the Nepal region and AIST will process them from April, though we are not sure when we can publish the products. Do you have any high-priority regions and deadlines?

**Comment by yumorishita** [comment]
Sorry but AIST will be able to start processing in May because of the computing resource limitation. We will prioritize the AOI you showed.

I cannot answer 1 and 2 without closely investigating the data and AOI. As I mentioned before, it is difficult for me to spend enough time on other's research in my current situation. I am sorry but I cannot be a collaborator.

**Comment by yumorishita** [comment]
@DaisyUoE I would like to tell you something about the ALOS InSAR products in Nepal via DM or email. Could you please DM my public account below or tell me your contact information?
- Twitter: https://twitter.com/Yu__Morishita
- LinkedIn: https://www.linkedin.com/in/yu-morishita-0955ba139/

**Comment by DaisyUoE** [comment]
Hi Morishita, nice to hear about the ALOS InSAR products in Nepal. My email is jq.huang@ed.ac.uk
I do not use Twitter, and only check LinkedIn occasionally, maybe email is my best contact information. I look forward to hearing from you. -Daisy

**Comment by Sakina-A** [comment]
Hi Morishita
I was wondering can LANDSAT data be used for LiCSBAS? and what other satellite data besides Sentinel and ALOS PALSAR can LiCSBAS use?

**Comment by yumorishita** [comment]
LANDSAT data cannot be used because it is not SAR. Any SAR data from any satellites can be used as long as the unwrapped data is ready in a predefined format.
