### ISSUE TITLE
How to keep more data?

### ISSUE THREAD

**Issue by faranab** [yumorishita/LiCSBAS#21]
Hi
I have processed a dataset with n_ifg_noloop thre=10 all the pixels have been masked, then I have changed the n_ifg_noloop there  to 50 but the algorithm just kept 36% of data.
Is there any possibility to keep more data? even I changed the threshold to 70 but the result didn't change?
Best regards

**Comment by yumorishita** [comment]
Can you show me the log in Step 1-5?

**Comment by yumorishita** [comment]
It seems that your issue has been solved because there is no response.
