### ISSUE TITLE
TypeError: 'RectangleSelector' object is not callable

### ISSUE THREAD

**Issue by tzhu0526** [yumorishita/LiCSBAS#210]
Hi Yumorishita,

I am sorry to disturb you because of my processing issue. I got an issue in running LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &. 
It showed 'TypeError: 'RectangleSelector' object is not callable', so I got the figures but I could not see the Time Series change figure. The figure always show 0 without change. Do you know how can I solve the problem?

Thank you!

Tianyuan
![Picture1](https://user-images.githubusercontent.com/125206649/218324565-1cec9400-ad68-4927-b5e0-9bb41d4d0563.png)

**Comment by tzhu0526** [comment]
BTW, I have tried to click the points in the picture but it kept 0.

**Comment by yumorishita** [comment]
What is the version of matplotlib? Downgrading matplotlib might solve the issue.

**Comment by tzhu0526** [comment]
Sorry Yumorshita, what I use was the jasmin science computer. I am not sure what the version is and I guess it is hard to downgrading...
