### ISSUE TITLE
Unit Vectors

### ISSUE THREAD

**Issue by Sgzanjani1367** [yumorishita/LiCSBAS#211]
Hi 
I want to use unit vectors(E, U, N) for decomposition but I have an error and I think the Numpy could not read these tiff files. While the 159A_05987_131313.E file is available in the data folder.

Code:
 E_asc = np.fromfile(E_file_asc, dtype='float32').reshape((length_asc, width_asc))

Error:
No such file or directory: 'data\\159A_05987_131313.E'

I would appreciate it if you help me.

**Comment by yumorishita** [comment]
The error message says `No such file or directory: 'data\159A_05987_131313.E'`, which means the path to the file is not correctly set.
