### ISSUE TITLE
install LICSBAS poblem

### ISSUE THREAD

**Issue by Congzhangg** [yumorishita/LiCSBAS#212]
![image](https://user-images.githubusercontent.com/112800803/220128662-09dc69eb-854b-4c98-a8b2-0e555994364a.png)

**Comment by Congzhangg** [comment]
@yumorishita I used the ubuntu20.4 environment with python 3.8.10 as the default. Follow the tutorial to install the latest version of Anaconda using example1 (with Python 3.9). After the required module package is installed, the licSBAS are not installed successfully when I check whether the licSBAS are successfully installed. What's the problem, please?

**Comment by yumorishita** [comment]
The anaconda does not seem to be activated because the active python version is 3.8.10.

**Comment by Zuzchan** [comment]
https://youtu.be/7K8M80fLRZU
Check those videos on this channel, and see the comment sections too, if you still face a problem inform me.
maybe I can help.

**Comment by Congzhangg** [comment]
> https://youtu.be/7K8M80fLRZU Check those videos on this channel, and see the comment sections too, if you still face a problem inform me. maybe I can help.

thank you ! I've already solved it

**Comment by Zuzchan** [comment]
Glad to know.
