### ISSUE TITLE
time 

### ISSUE THREAD

**Issue by Congzhangg** [yumorishita/LiCSBAS#218]
Thanks for the author's guidance, I have obtained satisfactory rate graphs, may I ask how to obtain the cumulative deformation graphs of each ifg?

**Comment by yumorishita** [comment]
You can use [LiCSBAS_cum2flt.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_cum2fltpy) to extract the cumulative deformation.
