### ISSUE TITLE
How to display LOS displacement data to EW and UD components

### ISSUE THREAD

**Issue by khakim** [yumorishita/LiCSBAS#22]
Thanks for updating the LiCSBAS code, especially LiCSBAS_decomposeLOS.py.
 
I used the latest version of the LiCSBAS, but I could not find the EW and UD components of displacements.

How do we display these components?

Best regards,

**Comment by yumorishita** [comment]
You mean EW and NS components of the LOS unit vector (input of LiCSBAS_decomposeLOS.py)? Their float files are in the GEOCml* directory (see [File Structure](https://github.com/yumorishita/LiCSBAS/wiki/file_structure#input-for-step-1-1-or-steps-0-3-to-0-5-output-of-step-0-2)), and GeoTIFF can be created by [LiCSBAS_flt2geotiff.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_flt2geotiffpy).

Or you mean how to display the output [EW|UD].geo.tif from LiCSBAS_decomposeLOS.py? They are GeoTIFF files and can be displayed by GSI software (e.g. QGIS). If you cannot find [EW|UD].geo.tif files, it would mean the LiCSBAS_decomposeLOS.py has failed. Please check the log.

**Comment by khakim** [comment]
I tried to use the following command lines:
1. python3 /usr/local/LiCSBAS/bin/LiCSBAS_flt2geotiff.py -i E.geo -p EQA.dem_par [-o E_geo.tif] [--zero2nan] [--nan2zero] [--a_nodata num]

2. python3 /usr/local/LiCSBAS/bin/LiCSBAS_flt2geotiff.py -i E.geo -p EQA.dem_par [-o E_geo.tif]

the outputs were generated in tif files, but the files can't be opened.

**Comment by yumorishita** [comment]
You shouldn't type "[" and "]". Can you show me the log? What is the file size of E_geo.tif? How (what software or command) did you try to open the file?

**Comment by khakim** [comment]
Sorry, my pc was infected virus and all data were broken. So I have just reinstall the pc and the LiCSBAS program is also successfully installed.

I rerun the program with my data which succeeded to get the time series results. Unfortunately, I get a problem when Small Baseline inversion by LS is running. The process looks like stagned, no progress in processing but there are no error messages.

The process is running like below:

LiCSBAS13_sb_inv.py ver1.2 20200225 Y. Morishita
LiCSBAS13_sb_inv.py -d GEOCml4 --mem_size 16000 --n_core 4
In geographical coordinates

Size of image (w,l)    : 715, 697
# of all images        : 26
# of images to be used : 24
# of all ifgs          : 87
# of ifgs to be used   : 58
# of removed ifgs      : 29
Threshold of used unw  : 24

Reference area (X/Y)   : 292:293/284:285
Allowed memory size    : 16000.0 MB
Number of patches      : 1
Inversion algorism     : LS
Gamma value            : 0.0001

Process 697/697th line (1/1th patch)...
  Reading 58 ifg's unw data...
  341651/498355 points removed due to not enough ifg data...

  Identifing gaps and counting n_gap...
  Counting n_ifg_noloop...

  Small Baseline inversion by LS...

  Solving  57432/156704th points with full unw at a time...
  Next, solve 99272 points including nan point-by-point...
  4 parallel processing
  Running      0/ 99272th point...

**Comment by yumorishita** [comment]
Can you try again without "--n_core 4"?

**Comment by khakim** [comment]
Thanks a lot. It works.

However, I am still wondering why using n_core 4 (or 8) on Ubuntu LTS 18.04 it works but not on Ubuntu 20.04.

**Comment by yumorishita** [comment]
It could be a bug, but I am not sure. I will check it later.

**Comment by khakim** [comment]
Excuse me,  I have another question. 
What does vintercept (intercept of velocity mean) in the results?

**Comment by yumorishita** [comment]
vintercept means c in the linear model vt+c.

**Comment by khakim** [comment]
Ok. thank you very much.

**Comment by yumorishita** [comment]
Have you solved the problem about LiCSBAS_decomposeLOS.py? @khakim

**Comment by khakim** [comment]
I have not solve the problem yet.

this log when I create the tiff file.
python3 /usr/local/LiCSBAS/bin/LiCSBAS_flt2geotiff.py -i E.geo -p EQA.dem_par [-o E_geo.tif] [--zero2nan] [--nan2zero] [--a_nodata num]

LiCSBAS_flt2geotiff.py ver1.4 20200214 Y. Morishita
LiCSBAS_flt2geotiff.py -i E.geo -p EQA.dem_par [-o E_geo.tif] [--zero2nan] [--nan2zero] [--a_nodata num]
Use gdal module

Elapsed time: 00h 00m 00s

LiCSBAS_flt2geotiff.py Successfully finished!!

Output: E.geo.geo.tif

It looks like success but the tiff file is wrong (blank) when it is open. I used ubuntu.

**Comment by yumorishita** [comment]
What software or command did you use to open E.geo.geo.tif? Ubuntu is the name of OS, not software. Normal image viewer? If so, you would see black image because the created GeoTIFF does not contain a image but data. It is normal. You should use GIS software (e.g. QGIS) to open the GeoTIFF as I said. Also please tell me the file size of E.geo.geo.tif.

**Comment by yumorishita** [comment]
Have you solved the problem? @khakim

**Comment by yumorishita** [comment]
It seems that the problem has been solved.

**Comment by khakim** [comment]
Dear Yumorishita,

Sorry, for being late report the problem. But, the results seem to be wrong.
![N_geo_geotif](https://user-images.githubusercontent.com/26349617/89137235-8f3e7300-d561-11ea-8b4d-e8ec0c18f3d9.png)

**Comment by khakim** [comment]
I plot them using QGIS.

**Comment by yumorishita** [comment]
It is absolutely correct. It is just a LOS component of the unit vector, not deformation. You can use it in LiCSBAS_decomposeLOS.py.

**Comment by khakim** [comment]
How do we use LiCSBAS_decomposedLOS.py to create deformation components?
I check the batch_LiCSBAS.sh and the is no the LiCSBAS_decomposedLOS.py in this batch file.

**Comment by yumorishita** [comment]
Please see the usage and related references:
https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_decomposelospy
https://doi.org/10.1029/2003GL018827

You need two LOS displacement data (i.e., ascending and descending).
