### ISSUE TITLE
error when ifgs are discarded from further processing

### ISSUE THREAD

**Issue by irmayolii** [yumorishita/LiCSBAS#220]
Dear Prof. Yumorishita
 I have some error when running file batch

first
when process correct unw data error like this
![image](https://user-images.githubusercontent.com/80675405/223027890-c88d8521-1fda-4ee2-858f-ded0bb64d862.png)

but the process succesfully finished like this
![image](https://user-images.githubusercontent.com/80675405/223027989-431decd9-2e9d-4451-87e9-bd20b4bd2c6f.png)

second
after that the processing has warning like this
![image](https://user-images.githubusercontent.com/80675405/223028172-2504fe7d-b0ee-4838-9820-9757d5ac6646.png)

third 
when reading unw and cc data error like this
![image](https://user-images.githubusercontent.com/80675405/223028380-60c771b3-2b63-47b8-8067-8cf51c66b8ee.png)

last the processing stop and error like this
![image](https://user-images.githubusercontent.com/80675405/223028470-5bbcaee2-5f13-4deb-9e72-6f3061d2a517.png)

how to fix that?

**Comment by yumorishita** [comment]
The top three warnings are not a significant problem and can be ignored.
Please downgrade the matplotlib to solve the bottom error (see https://github.com/yumorishita/LiCSBAS/issues/219).

**Comment by irmayolii** [comment]
it was solved very well by downgrade the matplotlib to 3.1 ver, thankyou
