### ISSUE TITLE
LiCSBAS01_get_geotiff.py: command not found

### ISSUE THREAD

**Issue by HamedAmirkhani1378** [yumorishita/LiCSBAS#221]
Hello everyone!
After running bath file, I get this error:
"LiCSBAS01_get_geotiff.py: command not found"

Can you guide me to fix it? please.

![Screenshot from 2023-03-06 12-35-50](https://user-images.githubusercontent.com/127091917/223065265-af5d8063-ae79-4751-8843-88492a9d784f.png)

**Comment by Zuzchan** [comment]
Hey, did you follow these steps?

2. Running LiCSBAS & Quick Start
Quick Start
Make a working directory with the [frame ID of interest](https://github.com/yumorishita/LiCSBAS/wiki/2_1_Identify_frame) and move, e.g.,

mkdir 124D_04854_171313
cd 124D_04854_171313
Copy the batch script:

**copy_batch_LiCSBAS.sh**
then edit the copied batch_LiCSBAS.sh , e.g., for Campi Flegrei from September 2016 to May 2018:

---Line33---
do05op_clip="y"       # y/n
---Line38---
p05_clip_range_geo="14.03/14.22/40.78/40.90"  # e.g. 130.11/131.12/34.34/34.6 (in deg)
---Line60-61---
p01_start_date="20160909"     # default: 20141001
p01_end_date="20180508"       # default: today
------
Run the batch script:

./batch_LiCSBAS.sh

**Comment by HamedAmirkhani1378** [comment]
Dear @Zuzchan 
Thank you.
I found the problem. I made a mistake in setting PATH. I fixed it using the link below.
https://github.com/yumorishita/LiCSBAS/wiki/1_Installation#12-licsbas-module

**Comment by HamedAmirkhani1378** [comment]
Dear @yumorishita 
I found it now! 
I had not paid attention to this!
But I fixed it.
Thank a lot.
