### ISSUE TITLE
No TS_GEOCml1clip/cum_filt.h5 found!

### ISSUE THREAD

**Issue by khaled1409** [yumorishita/LiCSBAS#222]
we have a trouble with visualiation the results in LiCSBAS 
what you recomended to our fram 124D_04854_171313
and the ubuntu 18.04
![Capture d’écran de 2023-03-06 13-02-20](https://user-images.githubusercontent.com/38710300/223105964-eeb20219-6b09-4e03-9ba4-6d44ea8f9d9c.png)

**Comment by yumorishita** [comment]
Please try downgrading the matplotlib.
https://github.com/yumorishita/LiCSBAS/issues/219

**Comment by khaled1409** [comment]
in which matplotlib version you recommend Dr Yumorishira, we have 3.7.0 version 

![Capture d’écran de 2023-03-06 14-21-10](https://user-images.githubusercontent.com/38710300/223122987-f93fb346-ec88-4ce5-99e9-1efefe243af9.png)

**Comment by khaled1409** [comment]
we downdgrade nearly all the package but the problem not resoulve, please sir we need your help


![Capture d’écran de 2023-03-06 22-21-13](https://user-images.githubusercontent.com/38710300/223234599-a3369510-46af-4ba5-8401-16c7707a259c.png)

**Comment by yumorishita** [comment]
Please try 3.4.2 or less.

**Comment by khaled1409** [comment]
hi MR Yumorishita

i am writing to get me some help in another fram 161A_05343_090806 with coordinate 6.11/6.40/36.40/36.63, and we have the same issue 
best regard

**Comment by yumorishita** [comment]
Please upload the full log.

**Comment by amrit-thapa-2044** [comment]
I also ended with the same error. Here is my log file and the list of packages with the version.
[LiCSBAS_requirements.txt](https://github.com/yumorishita/LiCSBAS/files/11150729/LiCSBAS_requirements.txt)
[202304040214copy_batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/11150732/202304040214copy_batch_LiCSBAS_01_16.log)
<img width="621" alt="licsbas_ok" src="https://user-images.githubusercontent.com/59821600/229855903-ede4abc5-8b88-4ec6-8051-2b22aea904c0.PNG">
<img width="615" alt="licsbas_error" src="https://user-images.githubusercontent.com/59821600/229857392-21d629e5-43af-48f6-ac47-69303c7566f5.PNG">

I am using Python 3.10.10 in Ubuntu 22.04.1 LTS (Windows Subsystem for Linux (WSL) ).

**Comment by yumorishita** [comment]
`14.03/14.22/40.78/40.90` is not correct. This frame covers `79.4658333/82.5248309/28.0969465/30.8119444` (lon1/lon2/lat1/lat2) according to the log and the argument for `-g` should be like `80/81/29/30`.

**Comment by amrit-thapa-2044** [comment]
I could solve my problem. Thank you. I was wondering if I can define my own reference point within the batch_LiCSBAS file but I was unable to locate it.

**Comment by yumorishita** [comment]
Please see https://github.com/yumorishita/LiCSBAS/issues/102 and https://github.com/yumorishita/LiCSBAS/issues/60.
