### ISSUE TITLE
grid_b is not recognized

### ISSUE THREAD

**Issue by Yaoshangheng** [yumorishita/LiCSBAS#224]
Hi,
I have successful installed LiCSBAS and LiCSBAS_check_install.py run out to be OK.
I am running with “./batch_LiCSBAS.sh”,
I changed parameter to my AOI and date.
do05op_clip="y"     
---Line38---
p05_clip_range_geo="102.42/103.33/24.14/26.93"  # e.g. 130.11/131.12/34.34/34.6 (in deg)
---Line60-61---
p01_start_date="20190101"    
p01_end_date="20190630"       
then， I runed command “./batch_LiCSBAS.sh”,Everything is fine until balueError:
![捕获1](https://user-images.githubusercontent.com/20898434/223895862-0d22bfab-1804-4191-b64c-15de885c4ee4.JPG)
I don't know what is going wrong？

Best wish！

**Comment by Yaoshangheng** [comment]
here is my batch_LiCSBAS.sh file.
![QQ截图20230309100207](https://user-images.githubusercontent.com/20898434/223896843-3e7b2307-a3f4-4b06-9ecb-0948d1fd4ff4.jpg)
![QQ截图20230309100313](https://user-images.githubusercontent.com/20898434/223896851-001c16a0-26b8-430e-bd68-38fd52a0d759.jpg)
![QQ截图20230309100330](https://user-images.githubusercontent.com/20898434/223896865-abfcbeec-3c87-4981-8ceb-106baf876dd6.jpg)

**Comment by NabilAttar** [comment]
> I have solved the problem by downgrade matplotlib version to 3.1 and it run successfully. #219

excuse me sir, can you help me how to downgrade the  matplotlib? my  matplotlib version is 3.8.0.
