### ISSUE TITLE
Incidence angel from time series

### ISSUE THREAD

**Issue by irmayolii** [yumorishita/LiCSBAS#225]
Hi Prof Yumorishita
I wanna ask how do we know incidence angel and azimuth (heading) for every extracted time series by specific point. I just try to make EW and UD displacement by time series that running use LiCSBAS_cum2tstxt.py manually. I need incidence angel and azimuth for each specific point that exctracted from ascending and descending interferograms. Can I get it from LiCSBAS? I don't use LiCSBAS_decomposeLOS.py because the input is from geotif whereas I use txt from LiCSBAS_cum2tstxt.py

**Comment by irmayolii** [comment]
Thankyou for the information

**Comment by irmayolii** [comment]
I have another question sir,
why when I try to processing time series with default start date and end date, the results for time series just 2019-2020. But when I try with start date 20170101 & end date 20220405 the results for time series is 2018-2021. I just confused because when I checked interferograms in COMET-LiCS portal it is ready from 2016 to 20220504. Anyway I use ascending frame in Palu.
![image](https://user-images.githubusercontent.com/80675405/224470764-91a5bf9d-b57d-4f70-9334-8512fe804272.png)
![image](https://user-images.githubusercontent.com/80675405/224471113-dd67c8c3-24ed-4175-9a2a-7c6cd5d49383.png)

**Comment by yumorishita** [comment]
Please upload the full log.

**Comment by irmayolii** [comment]
Here is the log file start date 20170101, end date 20220504 and also result for time series
[202303111547batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/10949241/202303111547batch_LiCSBAS_01_16.log)

[ts_210_67.txt](https://github.com/yumorishita/LiCSBAS/files/10949242/ts_210_67.txt)

And this is  log file with start date and end date is default, also the result for time series
[202303111838batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/10949251/202303111838batch_LiCSBAS_01_16.log)

[ts_210_67.txt](https://github.com/yumorishita/LiCSBAS/files/10949252/ts_210_67.txt)

**Comment by yumorishita** [comment]
It is because many dates were removed in step12. Please see network/network12.png.

**Comment by irmayolii** [comment]
why is so much data deleted? can it be solved in another way so that all data can be used?

start date 20170101, end date 20220504
![network12](https://user-images.githubusercontent.com/80675405/224553390-f2ab1334-922d-4154-b4e2-42aa9427b0ad.png)

start date and end date is default
![network12](https://user-images.githubusercontent.com/80675405/224553376-8302e20d-6f2d-484d-8e5d-7b6f7feed82b.png)

**Comment by yumorishita** [comment]
Please read the section 2.4.2 in the LiCSBAS paper
https://www.mdpi.com/2072-4292/12/3/424#sec2dot4dot2-remotesensing-12-00424
and see `12loop/bad_loop_png/*.png`

**Comment by irmayolii** [comment]
Dear Prof. Yumorishita
I have another question, I have generated LiCSBAS_cum2tstxt.py and got time series of displacement at a specified point here, there is a information about # linear model: 1.745*t+1.412 and I bit confused what does it means?, is that the time series displacement is a result of linear model? and there is not real displacement (observation)?
![image](https://user-images.githubusercontent.com/80675405/236146550-b3a55035-e8f2-49d8-981d-65f4d05c356d.png)

**Comment by yumorishita** [comment]
The linear model is the regression line estimated from the displacement time series. The displacement time series is the following lines.

**Comment by irmayolii** [comment]
did the displacement from LiCSBAS_cum2tstxt.py is cumulative displacement?

**Comment by yumorishita** [comment]
Yes.

**Comment by irmayolii** [comment]
Thank you very much Prof

**Comment by irmayolii** [comment]
Dear Prof. Yumorishita
I wanna ask again. Why when I running cumulative displacement timeseries (descending) use LiCSBAS_cum2tstxt.py with specific coordinate (-0.85989, 119.8249) the result is like the picture below. Why the coordinate is changed become ( # lat, lon: -0.86033, 119.82489), it is not same like the input before. I tried to another coordinate and always like that, it is not same like the input we want.

![image](https://github.com/yumorishita/LiCSBAS/assets/80675405/4c6d0cf3-676b-4d91-8a90-e8a2277c4724)

**Comment by yumorishita** [comment]
The time series data is in the grid format. In LiCSBAS_cum2tstxt.py, the nearest grid point to the input lat/lon is selected and the show lat/lon is the selected grid point's.

**Comment by irmayolii** [comment]
Is there a solution to handle calculations of ENU values from a specific point for both ascending and descending directions? This is because when extracting ENU displacements, it requires data from two different directions (ascending and descending) that need to be integrated at the same point.

**Comment by yumorishita** [comment]
[gdalwarp](https://gdal.org/programs/gdalwarp.html) can resample the data to the common grid as is done in [LiCSBAS_decomposeLOS.py](https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/bin/LiCSBAS_decomposeLOS.py#L210).
Or I would simply use the nearest grid point to the point of interest.

**Comment by irmayolii** [comment]
Okay thankyou very much for helping me Prof.

**Comment by blueyeti1994** [comment]
> Hi Prof Yumorishita I wanna ask how do we know incidence angel and azimuth (heading) for every extracted time series by specific point. I just try to make EW and UD displacement by time series that running use LiCSBAS_cum2tstxt.py manually. I need incidence angel and azimuth for each specific point that exctracted from ascending and descending interferograms. Can I get it from LiCSBAS? I don't use LiCSBAS_decomposeLOS.py because the input is from geotif whereas I use txt from LiCSBAS_cum2tstxt.py

were you able to compute the incident angle and the azimuth using unit vector files (i.e., E.geo, N.geo, U.geo)?

**Comment by yumorishita** [comment]
I have not tried but it should be possible.
