### ISSUE TITLE
Error in LiCSBAS01_get_geotiff.py

### ISSUE THREAD

**Issue by laxmangeo** [yumorishita/LiCSBAS#226]
![Screenshot 2023-03-09 151830](https://user-images.githubusercontent.com/127308214/223985190-468aaaa3-d89f-4a1a-a524-f6437f5796fa.jpg)

**Comment by yumorishita** [comment]
Maybe you wrongly edited the batch_LiCSBAS.sh.

**Comment by laxmangeo** [comment]
Hello Yumorishita, i edited only 
1.do05op_clip
2.p05_clip_range_geo
3. p01_start_date
4. p01_end_date
these are edited batch_LiCSBAS.sh file and status
![1](https://user-images.githubusercontent.com/127308214/224229413-06ed517f-5a89-4a2d-a3be-eb78af5024f9.jpg)
![1-2](https://user-images.githubusercontent.com/127308214/224229418-c606f432-37f5-4a81-af39-8b2c42803340.jpg)
![2-3](https://user-images.githubusercontent.com/127308214/224229536-1b41d2e2-6c1a-4613-b253-de16da421a9e.jpg)
![4](https://user-images.githubusercontent.com/127308214/224229541-0176957d-367b-4237-9c26-0fc8c888853d.jpg)

**Comment by laxmangeo** [comment]
Thank you sir
