### ISSUE TITLE
Adding more Interferograms

### ISSUE THREAD

**Issue by kquresh2** [yumorishita/LiCSBAS#227]
Hi @yumorishita,
                          My study area has processed IFG in LICS-portal but the Epochs processed are only 64% due to which I have an issue combining this frame with others (other frames have 98% processed epochs). Can we request anyone in COMET to add more IFG or is there any quick way I can do it by myself? Looking forward for your recommendations. 
Kind regards,

Kamil

**Comment by yumorishita** [comment]
I recommend requesting the LiCSAR processing in your frame of interest from the form on the LiCS portal web (https://comet.nerc.ac.uk/comet-lics-portal/, right column).

https://github.com/yumorishita/LiCSBAS/issues/51

**Comment by kquresh2** [comment]
@yumorishita I did submitted a request but I did not get any reply for my last request. I did submitted a new request yesterday. How can we keep track of our request using that form and how long will it takes to complete the request? I will appreciate your feedback.

**Comment by yumorishita** [comment]
I am not in the position to answer because I am not in COMET.
