### ISSUE TITLE
Drawing problem

### ISSUE THREAD

**Issue by Congzhangg** [yumorishita/LiCSBAS#229]
When using LiCSBAS_disp_image.py command to draw a picture, how to set the color code: as shown in the following figure, values greater than 20 and less than -5 
![1678536809903](https://user-images.githubusercontent.com/112800803/224484027-6b16f1d4-ec55-4e53-bb06-40611b36bbf3.jpg)

**Comment by Congzhangg** [comment]
@yumorishita  Looking forward to hearing from you

**Comment by yumorishita** [comment]
I am not sure what you mean by "the color code", but maybe `--cmin` and `--cmax` options can help.
https://github.com/yumorishita/LiCSBAS/wiki/3_visualization#licsbas_disp_imgpy

**Comment by Congzhangg** [comment]
Sorry I didn't make it clear what I wanted. I used the cmin and cmax parameters when I used LiCSBAS_disp_image.py command to output the image.    What I want to ask is how to set different colors for different values of images, just like the symbol system in arcgis。
![image](https://user-images.githubusercontent.com/112800803/225309229-f995b027-a576-479b-bbf2-93e26af8604f.png)

**Comment by yumorishita** [comment]
LiCSBAS_disp_image.py does not have such a function.

**Comment by Congzhangg** [comment]
OK，thank you
