### ISSUE TITLE
ERROR: No hgt file exist in results dir!

### ISSUE THREAD

**Issue by sizzer13** [yumorishita/LiCSBAS#23]
Hi,
I met a problem showing no hgt file.  Do you know why?

ERROR: No hgt file exist in results dir!

**Comment by yumorishita** [comment]
What command generated this message?

The hgt file is created in Step 1-1. Please see the log.

**Comment by yumorishita** [comment]
Have you solved this issue? @sizzer13

**Comment by sizzer13** [comment]
Sorry for the late reply.
No, not yet. I still don't know what is going on there. Actually, I do have
a hgt file already in the file.

And I met the similar problem when processing the Frame ID
012A_04449_131313 and also 063D_04429_121413.
What does Bus error mean here?

Process 1102/2203th line (1/2th patch)...

  Reading 87 ifg's unw data...

  2787831/3308204 points removed due to not enough ifg data...


  Identifing gaps and counting n_gap...

  Counting n_ifg_noloop...


  Small Baseline inversion by LS...


  Solving 467146/520373th points with full unw at a time...

Bus error: 10

**Comment by yumorishita** [comment]
I have never seen the "Bus error: 10". Can you upload your log files and batch_LiCSBAS.sh? I will try to replicate the error.

**Comment by yumorishita** [comment]
I did not get the "Bus error" using your batch_LiCSBAS.sh that you sent to me by email. Please see the log files below. I guess this error stems from your environment, not LiCSBAS.

[202007150954batch_LiCSBAS_063D_01_13.log](https://github.com/yumorishita/LiCSBAS/files/4922583/202007150954batch_LiCSBAS_063D_01_13.log)
[202007150954batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/4922584/202007150954batch_LiCSBAS_01_16.log)

**Comment by sizzer13** [comment]
Hi

Yes, you're right. The problem is my environment. I have make it through.
Thank you.
