### ISSUE TITLE
The output range in LiCSBAS is inconsistent with that in other software

### ISSUE THREAD

**Issue by Congzhangg** [yumorishita/LiCSBAS#230]
Hello, may I ask why the range of rate map output by me in LiCSBAS is inconsistent with that by ArcGIS? In the following figure, the left is the output result of LiCSBAS, and the right is the output result and attribute information of other software.

What are the coordinate systems and units used in LiCSBAS?
![image](https://user-images.githubusercontent.com/112800803/225514461-6bf95514-f2a1-4d47-b050-2eeeb0c65457.png)

**Comment by yumorishita** [comment]
Perhaps it is because the default of `--auto_crange` in `LiCSBAS_disp_img.py` is 99%. Please try `--auto_crange 100`.
https://github.com/yumorishita/LiCSBAS/issues/155#issuecomment-1140250945

**Comment by Congzhangg** [comment]
YES,I have solved the problem!
Also, what does the --auto_crange parameter do? Whether to filter out some extreme values that might be wrong?

**Comment by yumorishita** [comment]
Yes, to exclude the extreme outliers.
https://github.com/yumorishita/LiCSBAS/blob/master/bin/LiCSBAS_disp_img.py#L277-L278

**Comment by Congzhangg** [comment]
@yumorishita Thank you, and I would like to ask another question. My research time is 20170823-20210826. Which date is the main image of interference pair? Can I customize the super master image date?

**Comment by yumorishita** [comment]
LiCSBAS's approach is multi-master and there is no super master date.
