### ISSUE TITLE
Is it possible to set step times in inversion

### ISSUE THREAD

**Issue by mohseniaref** [yumorishita/LiCSBAS#233]
Hi

I was wondering if there is a way to set time for steps for instance eruption or earthquake dates in LICSBAS?

Thanks in advance for your response.

Best regards,
Mohammad

**Comment by yumorishita** [comment]
Do you mean a step function in time series? LiCSBAS does not have such a function. You can take into account any temporal model in postprocessing of the derived time series yourself.
