### ISSUE TITLE
Error in step 16

### ISSUE THREAD

**Issue by vikrumar** [yumorishita/LiCSBAS#234]
Hello,
I am getting an error in the last step, but it creates the files
the masked velocity is blank. 
Attaching the screenshots
Frame id is 063D_05860_131313

![mask_ts](https://user-images.githubusercontent.com/104144139/228201701-509ef9bd-4e16-4365-9f80-ff217e70dcb1.png)
![WhatsApp Image 2023-03-28 at 12 05 01](https://user-images.githubusercontent.com/104144139/228202620-d7aa0db7-e099-4f61-8de8-49b412ef38ec.jpeg)

**Comment by vikrumar** [comment]
[202303241319batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/11089173/202303241319batch_LiCSBAS_01_16.log)

**Comment by yumorishita** [comment]
I found that some unw data are corrupted (e.g., 20180510_20180627). Manually check `GEOCml1clip/*/*.png`, identify the corrupted data, remove them from `GEOCml1clip`, and rerun from step11.

**Comment by vikrumar** [comment]
Hello, now I get this error now, attaching the log file. Is it a problem with my system?
[202304041624batch_LiCSBAS_11_16.log](https://github.com/yumorishita/LiCSBAS/files/11150334/202304041624batch_LiCSBAS_11_16.log)

**Comment by yumorishita** [comment]
I am not sure but this might help
https://stackoverflow.com/questions/37657939/oserror-269892000-requested-and-269188084-written

**Comment by laxmangeo** [comment]
Hello vikrumar, how to re run from step 11

**Comment by yumorishita** [comment]
Change to `start_step="11"	# 01-05, 11-16` in `batch_LiCSBAS.sh`.
https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/batch_LiCSBAS.sh#L19

**Comment by vikrumar** [comment]
Hola,
Checking and deleting the corrupted files from files from GEOC, and running the process again from step 2 worked!
