### ISSUE TITLE
error in step 01 download 

### ISSUE THREAD

**Issue by Osmanpour** [yumorishita/LiCSBAS#235]
[202303112143batch_LiCSBAS_01_01(1).log](https://github.com/yumorishita/LiCSBAS/files/11105036/202303112143batch_LiCSBAS_01_01.1.log)

- Hi 
As you can see in the log file in step 01, despite the message "success complete", a lot of folders are empty or only the unwrap has been downloaded!
I can not find the reason?

**Comment by yumorishita** [comment]
Maybe the internet connection was unstable. Please try again in a stable internet environment.
