### ISSUE TITLE
strange lines in velocity map

### ISSUE THREAD

**Issue by Meysam-Amiri** [yumorishita/LiCSBAS#237]
I am getting these lines in the resulting velocity map. I haven't changed the settings in batch_LiCSBAS.sh file. Any Idea why they are generated? Thanks for your help.
![image](https://user-images.githubusercontent.com/104680747/229027395-e3078b4c-8946-4e66-9262-9f18b18ea866.png)

**Comment by yumorishita** [comment]
I guess some of the unw data have incomplete coverage.

**Comment by Meysam-Amiri** [comment]
@yumorishita, Thanks for your response. Any idea how can I check it?

**Comment by yumorishita** [comment]
You can visually check `GEOCml*/*/*png` one by one.
