### ISSUE TITLE
Could two datasets from different frame ID are merged?

### ISSUE THREAD

**Issue by khakim** [yumorishita/LiCSBAS#24]
I have questions, if our area of interest is in two frame IDs, how do we merged them ?

**Comment by yumorishita** [comment]
Unfortunately, LiCSBAS has no function to merge two frames during the processing.

One of the possible approaches is to merge GeoTIFF files of the results (i.e., velocities or cumulative displacement time series) by [gdal_merge.py](https://gdal.org/programs/gdal_merge.html).

If you are interested in a large-scale tectonic signal, a method to merge multiple frames by tying to GNSS has been done in [Weiss et al. (2020, accepted)](https://eartharxiv.org/8xa7j/download)
