### ISSUE TITLE
LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &

### ISSUE THREAD

**Issue by Zuzchan** [yumorishita/LiCSBAS#240]
hey, 
I'm asking for my friend since I have no idea how to help her.
After running the plot LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &, they got nothing, the code and the downloads are all fine, but no time series window appear and no deformation map :( 
![image](https://user-images.githubusercontent.com/120248666/229629819-d325becb-286b-4f30-9fb7-532de2f936bd.png)

She runs it on windows, I do too.
But, I don't know what I installed and didn't mention to her.

**Comment by yumorishita** [comment]
I have no idea about Windows. https://github.com/yumorishita/LiCSBAS/issues/85 might be helpful.

**Comment by Zuzchan** [comment]
No, unfortunately this isn't what I'm looking for 
Could you maybe tell what program or what module is required to open the pop screen where the deformation map and the time series are appear?

**Comment by ditafaith** [comment]
> No, unfortunately this isn't what I'm looking for Could you maybe tell what program or what module is required to open the pop screen where the deformation map and the time series are appear?

LiCSBAS is using matplotlib module to view the results. Can you check all the modules are correctly installed ? run a command LiCSBAS_check_install.py
Fyi, I am using matplotlib version 3.4.2

**Comment by yumorishita** [comment]
The messages are warning and there seems to be no problem on the LiCSBAS side. Maybe it is because of the X window system setting. Can you display other commands like `eog` or `gimp`?

**Comment by Zuzchan** [comment]
I'll check them
We actually used remote desktop ssh on chrome 
It does display the results but it's kinda hard to open, and the second time we tried it got an error.

**Comment by Zuzchan** [comment]
@ditafaith 
LiCSBAS is installed correctly 
But i think windows needs more programs to run it.
😅Before I installed many things of linux on my pc 
So it worked, but I can't recall what commands that helped.

**Comment by Zuzchan** [comment]
Anyway it worked by using chrome remote desktop

**Comment by MIEMESSI** [comment]
I have the same problem. Have you solved it

**Comment by MuhammadAsi** [comment]
Dear @yumorishita ,

RuntimeError: x must be a sequence
your comment on this error please. 
![image](https://github.com/user-attachments/assets/8325be92-a476-43dc-b699-3932da525d77)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS2/issues/78
