### ISSUE TITLE
Data downloading  related problem

### ISSUE THREAD

**Issue by shivamshuklaz** [yumorishita/LiCSBAS#245]
**LiCSBAS01_get_geotiff.py -f 129A_05935_131313 -s 20210101 -e 20211231**
 i have facing problem to downloading data from given command. i also attached a snapshot data downloading related problem.
![LiCSBAS  data downloading](https://user-images.githubusercontent.com/75002574/233618544-47b0898a-8fd0-4aee-b52b-dc4f42b87acd.jpg)
.

**Comment by yumorishita** [comment]
I do not know why but the network speed is quite slow now (~20KB/s). Please try again later.
