### ISSUE TITLE
Error matplotlib

### ISSUE THREAD

**Issue by mdavid3** [yumorishita/LiCSBAS#246]
For the following error, it is necessary to downgrade the matplotlib version, but can you help me on how to do it?

![ss](https://user-images.githubusercontent.com/101168839/234821849-479c05ad-7f19-468f-a2f1-95f426f70b1d.jpg)

**Comment by yumorishita** [comment]
It depends on how you created the virtual environemnt.

**Comment by mdavid3** [comment]
> It depends on how you created the virtual environment. Please try [LiCSBAS2](https://github.com/yumorishita/LiCSBAS2). See #244.

Thank you. i solved.
