### ISSUE TITLE
Step 11 and step 13 issues

### ISSUE THREAD

**Issue by swap-sin** [yumorishita/LiCSBAS#247]
Hey, I am using 18 ascending framesids for different locations all over around the globe and some of them(4 ids) have a common error either in step 11 or step 13. In step 11 the issue is:

**Size         : 591 x -269
Traceback (most recent call last):
  File "/home/singh/software/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
  File "/home/singh/software/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 191, in main
    n_unw = np.zeros((length, width), dtype=np.float32)
ValueError: negative dimensions are not allowed**

for which i tried to downloaded and clipped the data again but the issue still remains and in step 13 the processing is stuck and doesn't continue further at the last few lins looks like :

  **Identifing gaps, and counting n_gap and n_ifg_noloop,
  with 32 parallel processing...
    Running  1/32th patch...
    .
    .
    .
    Running 32/32th patch...
    Running 29/32th patch...
    Running 24/32th patch...
    Running 31/32th patch...**

Does someon has idea how to overcome these. Any help will be aprriciated. Thank you!!!

**Comment by yumorishita** [comment]
Please upload the full log files.

**Comment by swap-sin** [comment]
Can you be a bit more specific about the information you willing to look into log files. Are you willing to know the frame_id and the clipp area that i am interested in or the text files in the 'info' folder. 

In any case for the first problem frame_id is 028A_05385_191813 and the screenshot of the programme for step 13 where it is not ending.

![Screenshot (42)](https://user-images.githubusercontent.com/74794616/236487484-ff360fe4-fd5e-4251-8132-a0df4bf7f2bf.png)


For problem with step 11 with frame_id- 058A_04914_121007 :  
![Screenshot (43)](https://user-images.githubusercontent.com/74794616/236488404-b2b2985c-1cc6-4d53-8070-21571b8fca18.png)

**Comment by yumorishita** [comment]
I recommend using `batch_LiCSBAS.sh` which automatically creates a full log file.

**Comment by Rituj27** [comment]
Hi yumorishita even I am facing same issue in step 11, what should I do?

**Comment by yumorishita** [comment]
Please upload the full log file.

**Comment by swap-sin** [comment]
**CAn you please be abit more specific** I have checked the directories. I see that for the sample batch that you have have proviedd also provides a log file. It has no problem but when I am running for other frame_ids . Plus there are no log files formed. I can simply share you the errors. (which I already did using the above sreenshots)

**Comment by yumorishita** [comment]
Did you really run `batch_LiCSBAS.sh`? It must create a log file like `log/202302152220batch_LiCSBAS_01_16.log`. I cannot investigate the error without the log file.

**Comment by yumorishita** [comment]
There seem to be no more questions. Let me close this issue.
