### ISSUE TITLE
Inconsistent InSAR velocity value for the overlapping region of two frames

### ISSUE THREAD

**Issue by SiyuanZhao1** [yumorishita/LiCSBAS#249]
Hi, Morishita

I processed two frames which have an overlapping area using LiCSBAS, but I notice that the InSAR velocity value are different in these two results (I have made the color scale of these two plots the same). Do you have any idea why this happened? I attached the InSAR velocity result of the two frames, the area in the black circle is the overlapping area.

Thanks very much.

<img width="520" alt="frame_1" src="https://github.com/yumorishita/LiCSBAS/assets/51397425/358ea5e7-d218-45b8-be08-a09d5e1db421">

<img width="520" alt="frame_2" src="https://github.com/yumorishita/LiCSBAS/assets/51397425/51da6727-399f-40ae-8e37-dec8517cf04e">

**Comment by yumorishita** [comment]
It could be because of
- the difference in incidence angle
- different references
- noise (atmospheric, ionospheric, or orbital)

**Comment by SiyuanZhao1** [comment]
Thanks for the reply.

About the second possible reason you mentioned, references, I am not quite understand.

When I plot the velocity map, I use the default reference, which should be a zero value place.  So both two frames use the zero value area as the reference, even though they are not the same place. If it is correct, how the reference gonna affect the InSAR velocity result? Thanks.

**Comment by SiyuanZhao1** [comment]
> It could be because of
> 
>     * the difference in incidence angle
> 
>     * different references
> 
>     * noise (atmospheric, ionospheric, or orbital)

Thanks for the reply.

About the second possible reason you mentioned, references, I am not quite understand.

When I plot the velocity map, I use the default reference, which should be a zero value place. So both two frames use the zero value area as the reference, even though they are not the same place. If it is correct, how the reference gonna affect the InSAR velocity result? Thanks.

**Comment by SiyuanZhao1** [comment]
> It is not true that the point with zero displacements is selected as the reference. The displacement at the arbitrarily selected reference is forced to be zero. Any point can be selected as a reference. You should manually specify the common reference point for the two frames in the overlapping area.

I see, thanks very much for the explanation and suggestion.
