### ISSUE TITLE
LiCSBAS_plot_ts.py -i TS_GEOC_CACOS/cum_filt.h5 

### ISSUE THREAD

**Issue by sdlccug** [yumorishita/LiCSBAS#250]
'Traceback (most recent call last):
  File "/mnt/rfchen/licSBSA/LiCSBAS-master/bin/LiCSBAS_plot_ts.py", line 890, in <module>
    printcoords(lastevent)
  File "/mnt/rfchen/licSBSA/LiCSBAS-master/bin/LiCSBAS_plot_ts.py", line 773, in printcoords
    ii = np.int(np.round(event.ydata))
         ^^^^^^
  File "/mnt/rfchen/tools/miniconda3/envs/licsbas/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'? '
It prompted me to lower the version of numpy, but after I did, I found that the lower version of numpy was not compatible with many other packages in the library
'RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem '
How should I solve this problem?

**Comment by yumorishita** [comment]
That bug was already fixed in LiCSBAS2: https://github.com/yumorishita/LiCSBAS2/commit/1560f38ea0bc12215d5bd38a879b5973834aa670#diff-377f64b0637de03d288a5eb69290a739c2cbfb382da7a96d1d860841959567f1L773-R776

Please use [LiCSBAS2](https://github.com/yumorishita/LiCSBAS2) or apply the same modification to your source code in LiCSBAS.

**Comment by irmayolii** [comment]
Hi Prof Yumorishita
I use putty and xming for show the plot, but error below:

LiCSBAS_plot_ts.py -i TS_GEOCml1GACOSmaskclip/cum_filt.h5

Reading TS_GEOCml1GACOSmaskclip/cum_filt.h5
Reading TS_GEOCml1GACOSmaskclip/cum.h5 as 2nd
Reading TS_GEOCml1GACOSmaskclip/results/mask as mask
Reading GEOCml1GACOSmaskclip/U.geo
Reading mask
Reading coh_avg
Reading n_unw
Reading vstd
Reading maxTlen
Reading n_gap
Reading stc
Reading n_ifg_noloop
Reading n_loop_err
Reading resid_rms
Reading slc.mli
Reading hgt
/home/sphere/tesis_irma/irmayoli/LiCSBAS/bin/LiCSBAS_plot_ts.py:504: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  refvalue_vel = np.nanmean((vel*mask)[refy1:refy2+1, refx1:refx2+1])
/home/sphere/tesis_irma/irmayoli/LiCSBAS/bin/LiCSBAS_plot_ts.py:505: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  vmin_auto = np.nanpercentile(vel*mask, 100-auto_crange)
/home/sphere/tesis_irma/irmayoli/LiCSBAS/bin/LiCSBAS_plot_ts.py:506: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  vmax_auto = np.nanpercentile(vel*mask, auto_crange)
qt.qpa.xcb: X server does not support XInput 2
failed to get the current screen resources
/home/sphere/tesis_irma/irmayoli/LiCSBAS/bin/LiCSBAS_plot_ts.py:530: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  data = vel*mask-np.nanmean((vel*mask)[refy1:refy2+1, refx1:refx2+1])
Traceback (most recent call last):
  File "/home/sphere/tesis_irma/irmayoli/LiCSBAS/bin/LiCSBAS_plot_ts.py", line 586, in <module>
    RS = RectangleSelector(axv, line_select_callback, drawtype='box', useblit=True, button=[3], spancoords='pixels', interactive=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RectangleSelector.__init__() got an unexpected keyword argument 'drawtype'

**Comment by yumorishita** [comment]
What is the version of matplotlib? Please try donwgrading it to e.g. 3.3.

**Comment by Sakina-A** [comment]
Hi Morishita 

Am processing a new frame and all the steps have successfully finished. However, when I tried the command **LiCSBAS_plot_ts.py -i TS_GEOCml1_02/cum_filt.h5 &** I got an error saying: "Unable to open object (object 'vel' doesn't exist)"

![vel](https://github.com/yumorishita/LiCSBAS/assets/125351152/0d09bc2a-85fb-49e6-8072-01eb30eacb49)

**Comment by yumorishita** [comment]
I guess you have not successfully finished step16.

**Comment by shubhayanroychowdhury** [comment]
Hi @yumorishita 
After downgrading the matplotlib, I got the same error.
![image](https://github.com/yumorishita/LiCSBAS/assets/129718401/994d3b6f-5c35-4ba3-bc5f-a0e3afb5a7fe)
![image](https://github.com/yumorishita/LiCSBAS/assets/129718401/d987d5e9-f903-48b8-bf55-70197880b2a4)

I am using this software for 8 months. I did not get any error like this. Suddenly today I got this error. 
Please help me how to solve this problem and thank you for your time and consideration.

**Comment by yumorishita** [comment]
Maybe you did not downgrade the matplotlib in your "licsbas" venv.

**Comment by shubhayanroychowdhury** [comment]
Hi @yumorishita 
After downgrading the matplotlib in licsbas evn, I got this error.
![image](https://github.com/yumorishita/LiCSBAS/assets/129718401/eb5fbc3f-8999-4920-99a7-eaa6f31e6a6c)

**Comment by yumorishita** [comment]
Please see https://github.com/yumorishita/LiCSBAS/issues/250#issuecomment-1562850324

**Comment by adillahana** [comment]
Hi Prof Yumorishita,
Earlier I had a problem when plotting. Than I downgraded matplotlib to 3.3, but now i got an error as below:

LiCSBAS_plot_ts.py ver1.14.0 20230219 Y. Morishita

LiCSBAS_plot_ts.py -i TS_GEOCml1GACOSmaskclip/cum_filt.h5
Traceback (most recent call last):
  File "/home/hana2024/home/hana/penelitian/LiCSBAS2/bin/LiCSBAS_plot_ts.py", line 248, in <module>
    cmap = tools_lib.get_cmap(cmap_name)
  File "/home/hana2024/home/hana/penelitian/LiCSBAS2/LiCSBAS_lib/LiCSBAS_tools_lib.py", line 453, in get_cmap
    mpl.colormaps.register(_cmap, name=cmap_name)
AttributeError: module 'matplotlib' has no attribute 'colormaps'

Nothing appears. How do I resolve this? Thank you Prof.

**Comment by yumorishita** [comment]
You should not downgrade matplotlib if you use LiCSBAS2.

**Comment by adillahana** [comment]
> You should not downgrade matplotlib if you use LiCSBAS2.

I have upgraded matplotlib again. but I found problems like the following and nothing appears: 

LiCSBAS_plot_ts.py ver1.14.0 20230219 Y. Morishita
LiCSBAS_plot_ts.py -i TS_GEOCml1GACOSmaskclip/cum_filt.h5

Reading TS_GEOCml1GACOSmaskclip/cum_filt.h5
Reading TS_GEOCml1GACOSmaskclip/cum.h5 as 2nd
Reading mask
Reading mask
Reading coh_avg
Reading n_unw
Reading vstd
Reading maxTlen
Reading n_gap
Reading stc
Reading n_ifg_noloop
Reading n_loop_err
Reading resid_rms
Reading slc.mli
Reading hgt

Thank you Prof

**Comment by sonyakkk** [comment]
Hi Mr. yumorishita

I want to do plotting, but when I try the command "LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &"
I got a message that my data was not found. Do you have any suggestions? 
![WhatsApp Image 2024-03-12 at 23 14 20_9c166f9d](https://github.com/yumorishita/LiCSBAS/assets/152505924/6c4a1680-0b17-4895-9f15-6dc788c2dee1)

**Comment by yumorishita** [comment]
It literally means that TS_GEOCml1clip/cum_filt.h5 does not exist. You must finish LiCSBAS processing first.

**Comment by MIEMESSI** [comment]
Dear Professor, what does this vel(1) and vel(2) mean
![2NNQ9E84G} WKL1OEQ$ QOH](https://github.com/yumorishita/LiCSBAS/assets/161692921/015bafb5-aa3f-4106-b83a-c7262fb87c5b)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/117#issuecomment-878956383

**Comment by Sakina-A** [comment]
Hello, 
I have been trying to plot my results using **LiCSBAS_plot_ts.py -i TS_GEOCml1_02_till2024/cum_filt.h5 &** but I encountered the following error (attached pic). Is it because of my python version (3.10.13) or the LiCSBAS_plot_ts.py? I would be thankful if you could suggest a solution to this problem. 

![drawing](https://github.com/yumorishita/LiCSBAS/assets/125351152/a40061af-c9c8-4e04-b5c8-fc81d30d9afa)

**Comment by yumorishita** [comment]
Please try https://github.com/yumorishita/LiCSBAS/issues/40#issuecomment-732514778

**Comment by MIEMESSI** [comment]
Hello professor, I have encountered the following problem. It says that I do not have the slc.mli file. May I ask which step went wrong
![image](https://github.com/user-attachments/assets/03543cf0-fbea-4710-9d1e-43fa22f89c41)

**Comment by MIEMESSI** [comment]
But i can't plot it

**Comment by yumorishita** [comment]
It is because of your environmental setting, not slc.mli.

**Comment by shubhayanroychowdhury** [comment]
> But i can't plot it
Change your environment using this command 
**conda activate licsbas**

**Comment by MIEMESSI** [comment]
> > 如果使用 LiCSBAS2，则不应降级 matplotlib。
> 
> 我再次升级了 matplotlib。但是我发现了如下问题，但没有任何显示：
> 
> LiCSBAS_plot_ts.py ver1.14.0 20230219 Y. Morishita LiCSBAS_plot_ts.py -i TS_GEOCml1GACOSmaskclip/cum_filt.h5
> 
> 阅读 TS_GEOCml1GACOSmaskclip/cum_filt.h5 阅读 TS_GEOCml1GACOSmaskclip/cum.h5 作为第二阅读面罩 阅读面罩 阅读 coh_avg 阅读 n_unw 阅读 vstd 阅读 maxTlen 阅读 n_gap 阅读 stc 阅读 n_ifg_noloop 阅读 n_loop_err 阅读 resid_rms 阅读 slc.mli 阅读 hgt
> 
> 谢谢教授

Have you solved it? I have the same problem as you

**Comment by as1234554321** [comment]
Hi Prof @yumorishita 
I have been trying to plot my results using LiCSBAS_plot_ts.py -i TS_GEOCml1GACOSmaskclip/cum_filt.h5 but the result the following error 
![image](https://github.com/user-attachments/assets/152cf904-1678-4cbb-b4fd-48519f20e696)

Do you have any suggestions?
thankyou

**Comment by yumorishita** [comment]
I have never seen such an error. Please upload the full log of the processing.

**Comment by as1234554321** [comment]
[202409041526batch_LiCSBAS_01_16.log](https://github.com/user-attachments/files/16870824/202409041526batch_LiCSBAS_01_16.log)

**Comment by yumorishita** [comment]
It seems to be the same as https://github.com/DeepLabCut/DeepLabCut/pull/2599. Please donwgrade matplotlib to <3.7.0 for the time being.

**Comment by as1234554321** [comment]
> It seems to be the same as [DeepLabCut/DeepLabCut#2599](https://github.com/DeepLabCut/DeepLabCut/pull/2599). Please donwgrade matplotlib to <3.7.0 for the time being.

Thank you sir for your help and suggestions

**Comment by as1234554321** [comment]
> You should not downgrade matplotlib if you use LiCSBAS2.

but on this comment, if use licsbas2 should not downgrade matplotlib. 
How do I downgrade matplotlib, do I have to uninstall the previous version ?

**Comment by yumorishita** [comment]
matplotlib 3.6.0 would be acceptable. How did you install it? conda? pip?

**Comment by yumorishita** [comment]
Let me close this ticket because there seem to be no more questions.
