### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by HN-Jiang** [yumorishita/LiCSBAS#251]
Hi，I have a question about network, is that possible for licsbas to have a gap between the interferogram? As show in the pic. Because of the time baseline some time is too long, so I would like to know if it is possible I drop some area and put the rest interferograms into licsbas? I think that linking interferograms between them will also be decoherence and lead to unwrapping error.

![图片](https://github.com/yumorishita/LiCSBAS/assets/53942586/4cac0ba9-2d5a-4ef2-9c8e-0dc8d334e8d9)
![图片](https://github.com/yumorishita/LiCSBAS/assets/53942586/a6302b60-f319-4138-a004-398e0c6a87c1)

**Comment by yumorishita** [comment]
Yes, LiCSBAS can process the interferometric network with gaps. Please read my paper: https://www.mdpi.com/2072-4292/12/3/424#sec2dot4dot3-remotesensing-12-00424.

**Comment by HN-Jiang** [comment]
Understand, thank you!
