### ISSUE TITLE
LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOCml1GACOS 

### ISSUE THREAD

**Issue by sdlccug** [yumorishita/LiCSBAS#252]
LiCSBAS03op_GACOS.py ver1.5.5 20201119 Y. Morishita
LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOCml1GACOS

Convert ztd/sltd.geo.tif files to sltd.geo files...
   26/ 26 sltd already exist. Skip

Correct unw data...
   77/ 77 corrected unw already exist. Skip

Traceback (most recent call last):
  File "/mnt/rfchen/LiCSBAS2-master/LiCSBAS2-master/bin/LiCSBAS03op_GACOS.py", line 549, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/rfchen/LiCSBAS2-master/LiCSBAS2-master/bin/LiCSBAS03op_GACOS.py", line 368, in main
    plot_lib.plot_gacos_info(gacinfofile, pngfile)
  File "/mnt/rfchen/LiCSBAS2-master/LiCSBAS2-master/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 152, in plot_gacos_info
    xylim1 = np.max(np.concatenate((std_bf, std_af)))+1
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in amax
  File "/mnt/rfchen/tools/miniconda3/envs/licsbas/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 2820, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/rfchen/tools/miniconda3/envs/licsbas/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by yumorishita** [comment]
I guess the GACOS data does not cover the processing area.
https://github.com/yumorishita/LiCSBAS/issues/120

**Comment by sdlccug** [comment]
> I guess the GACOS data does not cover the processing area. #120

But why does it work when the number of interference pairs is different?

**Comment by yumorishita** [comment]
What do you mean by "when the number of interference pairs is different"?

**Comment by sdlccug** [comment]
> What do you mean by "when the number of interference pairs is different"?

I mean for the same region, I was previously using all the interference pairs for the period from November 30, 2017 to April 30, 2019, and it was running. But when I use all the interference pairs for the period from January 5, 2018 to December 31, 2018, it doesn't run

**Comment by maulanaheno** [comment]
> > What do you mean by "when the number of interference pairs is different"?
> 
> I mean for the same region, I was previously using all the interference pairs for the period from November 30, 2017 to April 30, 2019, and it was running. But when I use all the interference pairs for the period from January 5, 2018 to December 31, 2018, it doesn't run

did you found the fix for this error??
