### ISSUE TITLE
UTM

### ISSUE THREAD

**Issue by HN-Jiang** [yumorishita/LiCSBAS#256]
Hi，I tried to use asf SBAS products, but it has error in LiCSBAS, And I found all the products is all under UTM coordinate system not wgs84. Do you think this is the cause of the error? Do I need to change to WGS84 first then move in to LiCSBAS?

 
![图片](https://github.com/yumorishita/LiCSBAS/assets/53942586/2fe148e7-2736-497e-8029-6886bb99f7c0)

**Comment by yumorishita** [comment]
I am not sure because I have never used the data in UTM but it might be the cause of the error. Please try converting to WGS84 if possible.

**Comment by yumorishita** [comment]
4byte float.

**Comment by yumorishita** [comment]
32bit = 4byte. What is the problem?

**Comment by HN-Jiang** [comment]
ValueError: can not reshape array of size 9992514 into shape (5591,7151)

I think the first size is under 1byte, but the (longth width)  read is 32 bit.

I go though to your code：
    if coh_thre:
        ### Calc coh_avg
        print("\nCalculate coh_avg and define mask (<={})".format(coh_thre), flush=True)
        coh_avg = np.zeros((length, width), dtype=np.float32)
        n_coh = np.zeros((length, width), dtype=np.int16)
        for ifgix, ifgd in enumerate(ifgdates): 
            ccfile = os.path.join(in_dir, ifgd, ifgd+'.cc')
            if os.path.getsize(ccfile) == length*width:
                coh = io_lib.read_img(ccfile, length, width, np.uint8)
                coh = coh.astype(np.float32)/255
            else:
                coh = io_lib.read_img(ccfile, length, width)
                coh[np.isnan(coh)] = 0 # Fill nan with 0
I think os.path.getsize(ccfile) forced to read it as 1byte(which is a float 32 tiff), but the length and width is still under 4byte size. which makes the reshape error.

**Comment by yumorishita** [comment]
No, if the cc data is in 4byte, `if os.path.getsize(ccfile) == length*width:` is False and it is read as 4byte by `coh = io_lib.read_img(ccfile, length, width)`.
If 9992514 is in 1byte and (5591,7151) is in 4byte, 5591*7151*4 should be 9992514, but it is not. 5591\*7151=39981241 and 9992514\*4=39970056, very close but slightly different. The file size seems to be somewhat wrong.

**Comment by HN-Jiang** [comment]
Yes, you are right, I tried to change cc map to 1byte, but also don't work. So now the question is how did it get this 9992514 from?
I open the cc map with qgis, it show me like this:
after change to 1byte:
![图片](https://github.com/yumorishita/LiCSBAS/assets/53942586/abdaf966-4ce3-4952-8ff3-6f9082511840)
before(ASF product):
![图片](https://github.com/yumorishita/LiCSBAS/assets/53942586/b8de7f70-8179-4364-b8e7-291c5e4149d3)
I don't understand how does LiCSBAS get this 9992514 from.

**Comment by HN-Jiang** [comment]
BTW, Are you interested in this stuff? If so, I can give you the link to download my data from ASF, and the code I wrote to convert it to LiCSBAS format. You can test it.
I noticed that MintPy can load SBAS products directly from ASF. If we can find the problem, I can contribute my code so that more people can use ASF to process the data and move to LiCSBAS for timing analysis : )

**Comment by HN-Jiang** [comment]
Do you mean this?


![图片](https://github.com/yumorishita/LiCSBAS/assets/53942586/62d4f65e-f170-4447-82c7-af05cc0fb76e)

**Comment by yumorishita** [comment]
No. yyyymmdd_yyyymmdd.cc, not *geo.cc.tif.

**Comment by HN-Jiang** [comment]
![图片](https://github.com/yumorishita/LiCSBAS/assets/53942586/58767183-9bde-4560-b0aa-5e41ce122a55)
Should be this one

**Comment by yumorishita** [comment]
9992514x4=39970056. There should be a file with 39970056byte. All *.cc files should (and must) have the same size if they were correctly created.

**Comment by yumorishita** [comment]
Probably `GEOCml*/EQA.dem_par` contains wrong paramters (especially post_lat and post_lon).
