### ISSUE TITLE
Time series network

### ISSUE THREAD

**Issue by Zuzchan** [yumorishita/LiCSBAS#257]
hey, how have you been?
I have a question about the network that I attached its pic below:
Do you know why the number of IFGs is less in this area in the red circle?

![image](https://github.com/yumorishita/LiCSBAS/assets/120248666/1dca951d-e2f2-4e37-adcc-0b9725f6dd39)

**Comment by yumorishita** [comment]
Is it network11.png, network12.png or network13.png?

**Comment by Zuzchan** [comment]
it is network13.png, but I think it does nothing with which network is it, cuz in all three networks.png show the same results. 
Ig it is something related to the LICSAR products?

**Comment by yumorishita** [comment]
Yes, LiCSAR products have fewer interferograms in that period. I cannot do anything from LiCSBAS side.

**Comment by Zuzchan** [comment]
Do you know why there are a few interferograms here?

**Comment by Zuzchan** [comment]
OK, btw 
what does LiCSBAS stand for?

**Comment by yumorishita** [comment]
LiCSBAS is not an abbreviation. LiCSBAS is LiCSBAS.

**Comment by Zuzchan** [comment]
Got it, does the same go for LiCSAR?

**Comment by yumorishita** [comment]
LiCSAR | Looking Into Continents from Space with Synthetic Aperture Radar

https://www.mdpi.com/2072-4292/12/15/2430#:~:text=Continents%20from%20Space-,LiCSAR,Looking%20Into%20Continents%20from%20Space%20with%20Synthetic%20Aperture%20Radar,-LOS

**Comment by yumorishita** [comment]
The Google form of "LiCSAR frame request" on [COMET-LiCS-portal](https://comet.nerc.ac.uk/comet-lics-portal/) would be another way.
![image](https://github.com/yumorishita/LiCSBAS/assets/37470321/c6faedbd-adf4-40b1-9309-7bf3124fae1b)

**Comment by Zuzchan** [comment]
I'm really grateful💙.
