### ISSUE TITLE
Visualization KMZ

### ISSUE THREAD

**Issue by ditafaith** [yumorishita/LiCSBAS#258]
Hello, I success to generate KMZ file, but there is no legend or color ramp. 
Is there no color ramp produced ? otherwise there is something mistake with my command.
LiCSBAS_disp_img.py -i vel_file -p dem --kmz file.kmz -c coolwarm

**Comment by yumorishita** [comment]
Can you attach the kmz?

**Comment by ditafaith** [comment]
Hi,
This is link of KMZ file
https://s.id/1N2qj

**Comment by yumorishita** [comment]
The color map can be displayed by clicking the `ontake` layer.
![image](https://github.com/yumorishita/LiCSBAS/assets/37470321/d3d3d5b4-cf51-46d9-b350-9aad2f40d1b5)

**Comment by ditafaith** [comment]
Thank you, at least I need to inform the unit.
This case can be closed.

**Comment by ditafaith** [comment]
Hello, 
I make sure followed the command properly. However, there is an error mentioned as follows,
ERROR : bperp for 20190120 not found. (There is clear input for 20190120).
My purpose is to create a network diagram bigger than /network.
Here are the files https://s.id/1Ninf

**Comment by yumorishita** [comment]
It is probably because there is no 20190120 in the second column in test_bperp_list.txt.

**Comment by ditafaith** [comment]
This file is originally from 11ifg, not modified. Then, which file I should use to produce the network ?

**Comment by yumorishita** [comment]
How did you create test_bperp_list.txt? The format looks different from the LiCSAR product (e.g., [here](https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/145/145A_05949_131313/metadata/baselines)). The first column should be the single prime and constant.

**Comment by ditafaith** [comment]
As I mentioned, it was copied from 11ifg. That's what I might mistake.

**Comment by ditafaith** [comment]
It sounds strange. If I delete all pairs after 20190120 (almost half pairs). Then, it can generate a network. Not sure. what is the problem and how to produce in the proper way, with the bigger font size and year only for x-axes.
![network2](https://github.com/yumorishita/LiCSBAS/assets/126780178/f1f64d0a-e5e1-4381-93e0-f9b5bf5d1c6d)

**Comment by yumorishita** [comment]
LiCSBAS does not create the baseline file but copies it from the LiCSAR portal.
You can change the font size or any other settings by editing [this function](https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/LiCSBAS_lib/LiCSBAS_plot_lib.py#L212) as you want.

**Comment by ditafaith** [comment]
> LiCSBAS does not create the baseline file but copies it from the LiCSAR portal.
> You can change the font size or any other settings by editing [this function](https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/LiCSBAS_lib/LiCSBAS_plot_lib.py#L212) as you want.

Thank you. I will try to plot the network tjat generated after step 1-3. These pairs are used to produce time series, as shown in h5 file, I though.

**Comment by ditafaith** [comment]
Hi, I use dENU2LOS to convert our GNSS result to LOS.
The displ_file contains as follows,

stcode lat lon dE dN dU
GPS1 -6.887 109.669 0.04767 -0.11035 0.49059

Is it correct (sure, without the header) ?
I'd be glad if there is any example.

**Comment by ditafaith** [comment]
Since there is not possible to extract vertical from EW and UD.geo.tiff, then I extract the time series value using cum2tstxt.
By assuming horizontal movement is negligible, vlos = los/cosθ. 
How to know the incident angle value at the desired point ?

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/242#issuecomment-1551288412

**Comment by ditafaith** [comment]
> https://github.com/yumorishita/LiCSBAS/issues/242#issuecomment-155128841

I was opened GEOCml1/U.geo but can't.
This is binary file.
