### ISSUE TITLE
https://github.com/yumorishita/LiCSBAS/issues/249#issue-1721473094

### ISSUE THREAD

**Issue by Baijingjng** [yumorishita/LiCSBAS#259]
Hi, Morishita

I have a similar problem to (https://github.com/yumorishita/LiCSBAS/issues/249#issue-1721473094). I would like to ask how to set the reference point manually ，where to modify the code？

**Comment by yumorishita** [comment]
Please see https://github.com/yumorishita/LiCSBAS/issues/102
