### ISSUE TITLE
A question about the value of coefficient from radian to meter

### ISSUE THREAD

**Issue by Fanchengyan** [yumorishita/LiCSBAS#26]
As far as I am konw, the equation between the deformation δr along LOS with interferogram phese δφ is expressed as 

>δr  = - (λ · δφ) / (4π)

So, the  coefficient from radian to meter should be the **- λ / (4π)** from radian to meter and **- 1000λ / (4π)** from radian to millimeter. But   in LiCSBAS `coef_r2m` is expressed as : 

```python
coef_r2m = -wavelength/4/np.pi*1000  # rad -> mm, positive is -LOS
```
I'm not sure if it was a mistake or if there were other reasons

**Comment by yumorishita** [comment]
`-wavelength/4/np.pi*1000` is the same as - 1000λ / (4π). What is your question?

**Comment by Fanchengyan** [comment]
I’m so sorry, I mistakenly treating

![深度截图_选择区域_20200714160009](https://user-images.githubusercontent.com/24694181/87400234-1e9fd880-c5eb-11ea-8ab2-633037a2d6d6.png)

as 
![image](https://user-images.githubusercontent.com/24694181/87398454-7852d380-c5e8-11ea-9bec-8b4261f5436e.png)

Thanks for you reply.
