### ISSUE TITLE
Error in LiCSBAS_cum2vel.py output

### ISSUE THREAD

**Issue by Sakina-A** [yumorishita/LiCSBAS#261]
Hello

Am trying to make a velocity GeoTIFF for specific years using LiCSBAS_cum2vel.py , but whenever I run the line I get the same output. To check this I ran LiCSBAS_cum2vel.py for different years and converted it to GeoTIFFs and compared it but the TIFF files were the same.

![velocity](https://github.com/yumorishita/LiCSBAS/assets/125351152/4b083fd9-21d8-4daf-a6cc-2a3a4a3c3a7d)

**Comment by yumorishita** [comment]
Don't put `[` and `]`.

**Comment by Sakina-A** [comment]
Thank You, it worked perfectly :)
