### ISSUE TITLE
LiCSBAS02: ERROR bperp not found

### ISSUE THREAD

**Issue by sincaliz** [yumorishita/LiCSBAS#262]
I run the LiCSBAS02 -i GEOC/ -n 1 and I received the following error

Copy baselines file
ERROR: bperp for 20230616 not found!
  baselines file found, but not complete. Make dummy

Elapsed time: 00h 05m 06s

LiCSBAS02_ml_prep.py Successfully finished!!

Output directory: GEOCml1

What is the cause of this error and how it could be fixed? Does this error cause any problem with following processing steps ?

I will appreciate your help

**Comment by yumorishita** [comment]
It is because 20230616 is not included in the `baselines` file. This error does not affect any following steps (except for the network plot) and you can ignore it.

**Comment by sincaliz** [comment]
Thank you for your reply
