### ISSUE TITLE
LiCSBAS05 warning

### ISSUE THREAD

**Issue by sincaliz** [yumorishita/LiCSBAS#263]
I run the LiCSBAS05  to clip the area of analysis. I received the following output. The part in bold indicates a problem with the clipping command that could affect subsequent processing or not? Is there any problem with the matplotlib package?

LiCSBAS05op_clip_unw.py -i GEOCml1def/ -o GEOCml1defclip -g 137.3/137.75/35.75/36

Area to be clipped:
  0:3278/0:2739 -> 1114:1565/1635:1886
  136.1855556/139.4625556/34.8970000/37.6350000 ->
  137.2995556/137.7495556/35.7500000/36.0000000
  Width/Length: 3278/2739 -> 451/251

Clip E.geo
Clip N.geo
Clip U.geo
Copy baselines
Clip hgt
Recreate hgt.png
Clip slc.mli
Recreate slc.mli.png
**/home/sindy/.local/lib/python3.8/site-packages/matplotlib/image.py:443: UserWarning: Warning: converting a masked element to nan.
  dv = np.float64(self.norm.vmax) - np.float64(self.norm.vmin)
/home/sindy/.local/lib/python3.8/site-packages/matplotlib/image.py:444: UserWarning: Warning: converting a masked element to nan.
  vmid = np.float64(self.norm.vmin) + dv / 2**

Clip unw and cc
  88 parallel processing...
    0/1220th unw...
  100/1220th unw...
  200/1220th unw...
  300/1220th unw...
  400/1220th unw...
  500/1220th unw...
  600/1220th unw...
  700/1220th unw...
  800/1220th unw...
  900/1220th unw...
  1000/1220th unw...
  1100/1220th unw...
  1200/1220th unw...

Elapsed time: 00h 00m 12s

LiCSBAS05op_clip_unw.py Successfully finished!!

Output directory: GEOCml1defclip

I will appreciate your help

**Comment by yumorishita** [comment]
You can ignore the warning.
