### ISSUE TITLE
 the accuracy assessment 

### ISSUE THREAD

**Issue by Zuzchan** [yumorishita/LiCSBAS#265]
Hey Yu, 
How are you doing?
I have a question, I submitted my paper to a conference, and in my paper, I mainly depended on LiCSBAS, I didn't do any fieldwork, due to the region I chose as my study area was unreachable, and two reviewers asked me to verify my results, tbh I have no idea how.

This is one of the comments 
 The results of the paper were not verified via field data, hence they
cannot be trusted.
This is a major requirement for the paper to be accepted.

Do you have an idea of how to verify them without the field data?

Thank you so much.

**Comment by yumorishita** [comment]
I suggest
- Checking and describing the details of the noise indices and discussing the possible noise and errors.
- Referring to other papers in which the uncertainty of LiCSBAS results is validated and discussed (e.g., https://doi.org/10.3390/RS12030424, https://doi.org/10.1186/s40645-020-00402-7)

**Comment by Zuzchan** [comment]
Yeah, I will add a paragraph about this, I think it's the best solution at the given time, 
And maybe applying the GACO correction too, I checked my frame and it has GACO data, but, I don't know which code I have to edit in the batch so it will be downloaded, 
I thought it would be enough to do this:
do03op_GACOS="y"	# y/n
but the output was:
LiCSBAS03op_GACOS.py ver1.5.5 20201119 Y. Morishita
LiCSBAS03op_GACOS.py -i GEOCml7 -o GEOCml7GACOS --fillhole

ERROR:  No GACOS dir exists!

**Comment by Zuzchan** [comment]
I also added an empty folder with the name GACOS, but it resulted in an error too.

**Comment by yumorishita** [comment]
The GACOS dir must include the GACOS data which can be downloaded in step01 or manually from http://www.gacos.net/

**Comment by Zuzchan** [comment]
Wow, you are a lifesaver!
I have to say this:
I am thankful for all your kindness and guidance, I couldn't have done it without you.
You have been here for me more than my professor has ever done. 
I appreciate your time!

**Comment by yumorishita** [comment]
Yes, you can use the figure, but please cite this paper https://www.mdpi.com/2072-4292/12/3/424.

**Comment by Zuzchan** [comment]
Done~
