### ISSUE TITLE
Putting the same reference point for ascending and descending image

### ISSUE THREAD

**Issue by ClementGold** [yumorishita/LiCSBAS#266]
Dear @yumorishita, 

In order to proper analysis a subsidence point, i know one potential GPS i can use in kuala lumpur in both orbit track. And the last step will use the decomposition to get the vertical and horizontal movements. 

But i didn't found where I can include a txt file with the coordinate system to use even in the batch rc i run for my zone. 

I will be very grateful if you have the recommendation to put it. 

I wish you a great day !
Clément

**Comment by yumorishita** [comment]
Do you mean you want to compute the vertical and horizontal components with the reference at the GPS location?
If so, you should set the reference when you compute the LOS velocities using LiCSBAS_cum2vel.py with --ref_geo option, and then you get the vertical and horizontal components using the derived LOS velocities in which the reference is already set.

**Comment by ClementGold** [comment]
So my goal was to take the ascending track putting my reference point, and next extract the data for the GPS location / site I want to know the value and doing the same with the descending track. 

So the basic step was input the reference point in a file, i think the file in question is 16ref.txt but i don't know where i implemant this one. Doing ascending and descending and then take the U.geo and E.geo for both track to doing LiCSBAS_decomposeLOS.py and get the vertical velocity. 

But as you said it seems I don't take any reference point only in LiCSBAS_cum2vel.py but that mean i can only have one point with one reference point which is set to 0 ? 

It's kind of tricky because in mintpy the reference point make all the inversion and next you can decompose when you have descending and ascending track. 

Maybe I missunderstood something.

**Comment by yumorishita** [comment]
> which reference point is took ?

The reference you specified by --ref_geo option, if I understand your question correctly.

> it will be take the good value ?

What do you mean by "good value"?

**Comment by ClementGold** [comment]
> The reference you specified by --ref_geo option, if I understand your question correctly.

But this option is only available when you want to using LiCSBAS_cum2vel.py with --ref_geo 

According to LiCSBAS16_filt_ts.py you put a     #%% Find stable ref point 

This ref point is important because you analysis subsidence compare to this one. The "good value" mean for me stable, (not affected by subsidence, not affected or less by turbulence induced by atmospheric turbulence). 

Because i want only the vertical I need both track ascending and descending but I also need the same ref point in ascending that descending. I just wanted to know where is the option to set the stable ref point manually as I can doing for ascend and descend the same reference point needed to decompose correctly the LOS into vertical and EW by the  LiCSBAS_decomposeLOS.py #260 code 

I don't know if it's more clear.

**Comment by yumorishita** [comment]
Please read https://github.com/yumorishita/LiCSBAS/issues/102
