### ISSUE TITLE
Regarding results

### ISSUE THREAD

**Issue by laxmangeo** [yumorishita/LiCSBAS#267]
Dear Yumorishita, 
                           i working on area of joshimath , India. This area under two Licsar ascending frame id's: 056A_05855131313 and 129A_05935_131313, i used copy_batch_LiCSBAS.sh for batch processing, but my results are not well,113 ifgs discarded in the loop closure method step12. I changed  loop threshold also but the results are not good. How I can get the best results? Please help me. Here i attached my log file and results.
[202307211652batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/12123210/202307211652batch_LiCSBAS_01_16.log)
![mask_ts_masked](https://github.com/yumorishita/LiCSBAS/assets/127308214/586c19cd-a9f2-4065-ba97-7cf655b81940)

**Comment by yumorishita** [comment]
Sorry, I cannot help you because of a conflict of interest.

**Comment by laxmangeo** [comment]
Yeah i understood, at least any suggestions
