### ISSUE TITLE
Run on Anaconda windows

### ISSUE THREAD

**Issue by MarcoSal** [yumorishita/LiCSBAS#268]
i am trying to get python scripts working on anaconda in winodows. when I check the install with 'LiCSBAS_check_install.py', it gives me this error.

Check required modues and versions
  astropy(5.1) OK
  bs4(4.12.2) OK
  h5py(3.7.0) OK
  matplotlib(3.7.1) OK
  numpy(1.24.3) OK
  psutil(5.9.0) OK
  requests(2.29.0) OK
  statsmodels(0.13.5) OK
  gdal(3.6.2) OK

Check LiCSBAS commands
  ERROR: PATH is not set to LiCSBAS commands

Check LiCSBAS library
  ERROR: PYTHONPATH is not set to LiCSBAS library

ERROR: LiCSBAS install is NOT OK

Any idea?

**Comment by yumorishita** [comment]
Maybe this might be helpful: https://github.com/yumorishita/LiCSBAS/issues/85

**Comment by MarcoSal** [comment]
Thank you for the link.
following the instructions, i set both $PATH and $PYTHONPATH
but the check still fails...
is there a way to manually edit bashrc or bash_profile?

**Comment by Zuzchan** [comment]
https://youtu.be/7K8M80fLRZU

Watch Firman Hadi's videos, they were my guide to installing LICSBAS on Windows, and you can see the comments section too, there is useful information there.

**Comment by MarcoSal** [comment]
> https://youtu.be/7K8M80fLRZU
> 
> Watch Firman Hadi's videos, they were my guide to installing LICSBAS on Windows, and you can see the comments section too, there is useful information there.

the video contemplates the use of Umbutu. I would like to make it work under windows using the relative version of Anaconda.

**Comment by yumorishita** [comment]
Have you done https://github.com/yumorishita/LiCSBAS/issues/85#issuecomment-790638841 or https://github.com/Wu-Patrick/LiCSBAS?

**Comment by MarcoSal** [comment]
I'm slowly adjusting. the information I find on the net is conflicting and leads to some confusion.
now i was able to fix PYTHONPATH.
I am left with the error on PATH. set it to 'LiCSBAS\bin' is that correct?
this is the installation check.

Python version: 3.11.3
  OK

Check required modues and versions
  astropy(5.1) OK
  bs4(4.12.2) OK
  h5py(3.7.0) OK
  matplotlib(3.7.1) OK
  numpy(1.24.3) OK
  psutil(5.9.0) OK
  requests(2.29.0) OK
  statsmodels(0.14.0) OK
  gdal(3.6.2) OK

Check LiCSBAS commands
  ERROR: PATH is not set to LiCSBAS commands

Check LiCSBAS library
  OK

ERROR: LiCSBAS install is NOT OK

**Comment by yumorishita** [comment]
How did you fix PYTHONPATH?

**Comment by MarcoSal** [comment]
> How did you fix PYTHONPATH?

My Computer > Properties > Advanced System Settings > Environment Variables
add PYTHONPATH and set to mypersonalpath\LiCSBAS\LiCSBAS_lib

I also tried to set PATH, but it didn't help

however, I decided to focus on visual studio 2019. the first tests gave positive results.

**Comment by yumorishita** [comment]
I recommend using VMware or VirtualBox to use Linux on Windows.
https://github.com/yumorishita/LiCSBAS/issues/38#issuecomment-730830677
https://github.com/yumorishita/LiCSBAS/issues/6#issuecomment-713187052

**Comment by MarcoSal** [comment]
Yes, I will also try Linux in Windows in the near future.
At the moment, I managed to get all the steps working under Visual Studio 2019 by modifying some code parts. Let's say it doesn't support parallel processing. I always set "--n_para 1".
The elaboration of the "Campi Flegrei" was successful and relatively fast.
For me it is important to use VS2019 because I can easily dialogue with other c# scripts created by me.
Now I have to study all the steps well.
