### ISSUE TITLE
Error when run LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOCml1GACOS

### ISSUE THREAD

**Issue by fengnian-chang** [yumorishita/LiCSBAS#269]
Hi,
great work, but I meet a problem when I trying to apply on area 063D_04886_161920.

An error occurred when I performed step 03：
ValueError: cannot reshape array of size 58458715 into shape (7604,7757)

The program executes with an error and terminates, most of the unwrapped data has been corrected. So I wonder if the program is stuck because there is a problem with some scene data. How can I locate the cause of the error or which scene is faulty?
This is not related to the symbolic links in the other answers, because I have already solved this problem.
The full log was attached.

Best regards,
Fengnian Chang
[202307230713batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/12140834/202307230713batch_LiCSBAS_01_16.log)

**Comment by fengnian-chang** [comment]
I found that some of the unwrapped graph files were slightly smaller, resulting in program execution errors. So I manually deleted the images, but another error occurred.
The screenshot was attached.
![CLM5S5YDP23{7@}Q9 SNTX7](https://github.com/yumorishita/LiCSBAS/assets/62586311/b069a5b2-ef0e-4f19-a77c-862fb49f03dc)
![ZFB2)%I5 LE6)B0RB}0T75](https://github.com/yumorishita/LiCSBAS/assets/62586311/8355aa56-c719-430c-b778-c14f52aa49c5)
![0BT~6%AX{WTI~BIT`M1VJ@3](https://github.com/yumorishita/LiCSBAS/assets/62586311/b788fc41-36f6-448c-be6a-07fb46468e73)

**Comment by yumorishita** [comment]
Try again after removing GEOCml1GACOS.

**Comment by fengnian-chang** [comment]
After removing the bad unwrapped images in GEOCml1 and the whole GEOml1GACOS directory, It works！It looks like some frames contain a lot of bad unwrapped data and cause this error.
Thanks again for your quick reply!

**Comment by fengnian-chang** [comment]
I meet a problem in area 063D_04886_161920. Although step 03 was successful, an error occurred (cannot reshape array of size 2337741 into shape***) in step05 or step13. It seems that the file size of [ENU].tif and hgt.tif is inconsistent with the unw.tif. @yumorishita 
![K_RGMMDL98{FZ70PUDKISNT](https://github.com/yumorishita/LiCSBAS/assets/62586311/7b61cf2d-e214-4b95-b76c-995a7928e3ef)
![%(R3B2Q9}ORERBTY)26%C}L](https://github.com/yumorishita/LiCSBAS/assets/62586311/1d7622c1-c987-4c1c-b9a0-3e5bc4d47ae5)

**Comment by yumorishita** [comment]
Please attach the full log. If you don't use batch_LiCSBAS.sh, please use it to make the log file.

**Comment by fengnian-chang** [comment]
Using batch_LiCSBAS.sh will get stuck in step 3, so I need to manually remove the problematic data. However, there is still an error at step 5. And when I skip step 5, step 13 goes wrong.
[202307230713batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/12160777/202307230713batch_LiCSBAS_01_16.log)

**Comment by yumorishita** [comment]
The log file you attached show the error in step03.

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/25#issuecomment-1649827473

**Comment by fengnian-chang** [comment]
> [#25 (comment)](https://github.com/yumorishita/LiCSBAS/issues/25#issuecomment-1649827473)
Thank you for your prompt reply! I have removed these unwrapped data with inconsistent sizes in the last processing. However, the problem has not been solved. So I guess it may have something to do with [ENU].tif and hgt.tif
![1](https://github.com/yumorishita/LiCSBAS/assets/62586311/0ba47dbb-7520-47f1-b6dd-da0d5c09394f)
![2](https://github.com/yumorishita/LiCSBAS/assets/62586311/08909471-55c2-47d4-81ba-19c339763d96)
?

**Comment by Zuzchan** [comment]
I faced something similar a few days ago, as I remember I solved it by running the bash step by step.
start_step="3"	# 01-05, 11-16
end_step="4"
and so on until the process ends, instead of running the 16 steps in one go.

**Comment by fengnian-chang** [comment]
It doesn't work.
[202307262023batch_LiCSBAS_13_13.log](https://github.com/yumorishita/LiCSBAS/files/12179356/202307262023batch_LiCSBAS_13_13.log)


> I faced something similar a few days ago, as I remember I solved it by running the bash step by step. start_step="3" # 01-05, 11-16 end_step="4" and so on until the process ends, instead of running the 16 steps in one go.



> [#25 (comment)](https://github.com/yumorishita/LiCSBAS/issues/25#issuecomment-1649827473)

**Comment by Zuzchan** [comment]
have you checked your clipping area if it was within the frame?

**Comment by yumorishita** [comment]
Please retry from step01.

**Comment by fengnian-chang** [comment]
> Please retry from step01 after removing all the files.

The processing was successful after removing the bad epochs, really appreciate your help!
