### ISSUE TITLE
A permission denied error when running batch_LiCSBAS.sh

### ISSUE THREAD

**Issue by Linya-Peng** [yumorishita/LiCSBAS#27]
Thanks for updating the project! I got a  "/usr/bin/env: ‘python3’: Permission denied" error when run the batch_LiCSBAS using git Bash. Could you please help me? 
I've edited the bath_LiCSBAS.sh following the tutorial, and copied it to my working directory. 
ps: I'm a Windows user and I prepared the environment using Anaconda3. Here is my code:

`Linya@LAPTOP-35FJC4VM MINGW64 /e/Landslides_work/licsbas_test/LiCSBAS/124D_04854_171313 (master)
$ ./batch_LiCSBAS_sample_CF.sh

Start step: 01
End step:   16
Log file:   log/202007211701batch_LiCSBAS_sample_CF_01_16.log

/usr/bin/env: ‘python3’: Permission denied
(licsbas)
`

**Comment by yumorishita** [comment]
Can you run the following command and tell me the output? 
`which python | xargs ls -l`

**Comment by Linya-Peng** [comment]
![image](https://user-images.githubusercontent.com/61902717/88050973-6e9e1280-cb8a-11ea-842e-06937435c897.png)
I got a screenshot after I run the command. Here is the output:
Linya@LAPTOP-35FJC4VM MINGW64 /e/Landslides_work/licsbas_test/LiCSBAS/124D_04854_171313 (master)
$ which python | xargs ls -l
-rwxr-xr-x 3 Linya 197121 95232  5月  6 18:47 /d/Software/Anaconda3/envs/licsbas/python
(licsbas)

ps: licsbas is the environment I prepared by Anaconda

**Comment by yumorishita** [comment]
Sorry, I made a mistake. Please run the following:
`which python3 | xargs ls -l`

**Comment by Linya-Peng** [comment]
That's all right. Here is the output:
![image](https://user-images.githubusercontent.com/61902717/88051696-96da4100-cb8b-11ea-8afb-2e0e4f904f24.png)
Thanks~

**Comment by yumorishita** [comment]
OK. How about just:
`python3 -V`

**Comment by Linya-Peng** [comment]
> python3 -V

![image](https://user-images.githubusercontent.com/61902717/88052091-4fa08000-cb8c-11ea-8704-6b80ff92d15a.png)
Well, I run the command and got this error

**Comment by Linya-Peng** [comment]
> > python3 -V
> 
> ![image](https://user-images.githubusercontent.com/61902717/88052091-4fa08000-cb8c-11ea-8704-6b80ff92d15a.png)
> Well, I run the command and got this error

![image](https://user-images.githubusercontent.com/61902717/88052266-97270c00-cb8c-11ea-9899-c4eb9897fd71.png)
In my licsbas environment, the version of python is 3.7.7

**Comment by Linya-Peng** [comment]
Hi , sorry to disturb~
I do what you said. It seems that the python script can be run, but the module 'LiCSBAS_tools_lib' can't be found.
![image](https://user-images.githubusercontent.com/61902717/88055148-10286280-cb91-11ea-942d-4a1490db5763.png)

**Comment by yumorishita** [comment]
Have you replaced the first line of all the scripts in LiCSBAS_lib as well?
Otherwise, please try:
`echo $PYTHONPATH`

**Comment by Linya-Peng** [comment]
> Have you replaced the first line of all the scripts in LiCSBAS_lib as well?
> Otherwise, please try:
> `echo $PYTHONPATH`

Yes, I've replaced all the scripts in LiCSBAS_lib but still got the same error:

![image](https://user-images.githubusercontent.com/61902717/88057867-4667e100-cb95-11ea-8118-9315232e1184.png)

**Comment by yumorishita** [comment]
Strange. Please try:
```
cd $LICSBAS_PATH/LiCSBAS_lib
python LiCSBAS_tools_lib.py
```

**Comment by Linya-Peng** [comment]
> Strange. Please try:
> 
> ```
> cd $LICSBAS_PATH/LiCSBAS_lib
> python LiCSBAS_tools_lib.py
> ```

I run the commands, and got this:
![image](https://user-images.githubusercontent.com/61902717/88061152-b4160c00-cb99-11ea-9570-5982762c3d95.png)
Thanks a lot for your patience

**Comment by yumorishita** [comment]
OK. Please try:
```
cd $LICSBAS_PATH/LiCSBAS_lib
python -m LiCSBAS_tools_lib
```

**Comment by Linya-Peng** [comment]
I tried and got this:
![image](https://user-images.githubusercontent.com/61902717/88062370-5387ce80-cb9b-11ea-8988-3ac78c16d9c0.png)

**Comment by yumorishita** [comment]
Then bath_LiCSBAS.sh should work. I have no idea...

**Comment by yumorishita** [comment]
How about:
`LiCSBAS01_get_geotiff.py -h`

**Comment by Linya-Peng** [comment]
Sadly, batch_LiCSBAS.sh still could not work, and "LiCSBAS01_get_geotiff.py -h" got the same error:
![image](https://user-images.githubusercontent.com/61902717/88063397-91d1bd80-cb9c-11ea-9e72-a8fdb3bb08bc.png)

**Comment by yumorishita** [comment]
Sorry, I have no idea. If you know someone who is familiar with the Python environment in Windows, please ask them. This problem is due to your Python environment, not LiCSBAS itself.

**Comment by Linya-Peng** [comment]
OK, thank you anyway. Maybe I have to learn something about Linux hahaha. Thanks for your patience again and sorry to disturb.

**Comment by zachzen** [comment]
Try to open your ubuntu in root

**Comment by Zuzchan** [comment]
I need tips on how to run LiCSBAS on windows10 so if you got to know anything to help me out i'd be thankful.

**Comment by yumorishita** [comment]
Please see this https://github.com/yumorishita/LiCSBAS/issues/85.
