### ISSUE TITLE
any way to extract PNGs from timeseries Plot for making GIF?

### ISSUE THREAD

**Issue by soroushyasini** [yumorishita/LiCSBAS#274]
Hi mr. Morishita. I have a long-term case study which I want to make a GIF or animation from the beginning date until the latest date. my question is, can it be possible to save every displacement frame as PNG or other formats automatically so I could make a animated time series video ?
![Uploading Screenshot from 2023-07-31 16-30-57.png…]()

**Comment by yumorishita** [comment]
You can do it using LiCSBAS_cum2flt.py and LiCSBAS_disp_img.py with --png option.

**Comment by soroushyasini** [comment]
thanks for your help ! I used LiCSBAS_cum2flt.py and run the following code below:
```
#bash
dates=(20150121 20150214 20150310 20150403 20150427 20150521 20150614 )
# dates are more, i just remove most of them for this comment to be more readable.
for date in ${dates[@]}; do
LiCSBAS_cum2flt.py -d $date -i ts/cum_filt.h5 -o png_test/disp$date -r 0:0/0:0 --png disp$date
done
```
the problem is, in this command there is no option for adjusting the min and max of the color range. due to this matter, the PNGs can not be used for making animation.
have you any suggestion to solve this issue?
![disp20150121](https://github.com/yumorishita/LiCSBAS/assets/119971742/13eeea63-b715-4539-b6b2-412810f1a1fd)
![disp20150427](https://github.com/yumorishita/LiCSBAS/assets/119971742/da714b66-7c2b-4480-8114-14526fba894e)
![disp20150614](https://github.com/yumorishita/LiCSBAS/assets/119971742/685f2efd-e356-4828-ad94-b0e77798e5b9)
![disp20150825](https://github.com/yumorishita/LiCSBAS/assets/119971742/19068c16-32f5-48ca-8246-4c9d1c6e0d5f)

**Comment by yumorishita** [comment]
Please use [LiCSBAS_disp_img.py](https://github.com/yumorishita/LiCSBAS/blob/master/bin/LiCSBAS_disp_img.py) to set min/max.

**Comment by soroushyasini** [comment]
Hi again. thanks a lot ! after generating all of Cumulative Displacements, I run a new Loop for making PNGs from results of  Cumulative Displacements.
