### ISSUE TITLE
failed to read .h5 in ArcGIS Pro

### ISSUE THREAD

**Issue by vipin2010** [yumorishita/LiCSBAS#278]
Hello Sir, 
When I loaded the cum.h5 file in ArcGIS Pro, it prompted no coordinate system. When I read cum.h5 in Matlab, I did not find any latitude and longitude information except the corner information. 
I want to show satellite imagery or dem in the background of the results, how shall I proceed?
Please suggest!

Thanks in advance.

**Comment by yumorishita** [comment]
cum.h5 is not compatible with GIS. You can create GeoTIFF from cum.h5 by [LiCSBAS_cum2flt.py](https://github.com/yumorishita/LiCSBAS/blob/master/bin/LiCSBAS_cum2flt.py), [LiCSBAS_cum2vel.py](https://github.com/yumorishita/LiCSBAS/blob/master/bin/LiCSBAS_cum2vel.py), and [LiCSBAS_flt2geotiff.py](https://github.com/yumorishita/LiCSBAS/blob/master/bin/LiCSBAS_flt2geotiff.py) for the visualization on GIS.

**Comment by vipin2010** [comment]
Thank You Sir!

I had to ask one more thing regarding PS/DS density.
I processed Sentinel-1A data for the deformation analysis of a landslide using LiCSBAS. The obtained PS/DS density is very less in comparison to the result obtained by SARScape software.
How can we increase the PS/DS density of the results?

**Comment by yumorishita** [comment]
You can play with the parameters to increase the points, but I think it is natural that LiCSBAS results have fewer points than PS results because the input of LiCSBAS is multilooked and low-resolution.
