### ISSUE TITLE
HP LP filter error 

### ISSUE THREAD

**Issue by zachzen** [yumorishita/LiCSBAS#28]
Dear doctor Morishita ,
   I am tring to  use LicSBAS to analyze some area , but unfortunately there are few interfeogram images there .
Due to that ,I tried to use other sofeware to generate images and import it without step-1  ,and everything ran sucessfully and export 'vel-result' except setp-16
It shows ''Exception: The kernel can't be normalized, because its sum is close to zero. The sum of the given kernel is < 0.01"
I wonder know if LicSBAS is compatible with images from other software , or any solution I can adopt
Thanl you !!!

**Comment by yumorishita** [comment]
Can you show me the log file for all the steps? I wonder if the problem occurred in the earlier steps.

**Comment by zachzen** [comment]
[202007221034batch_LiCSBAS_2_16.log](https://github.com/yumorishita/LiCSBAS/files/4958344/202007221034batch_LiCSBAS_2_16.log)
Here is the log file,thank you

**Comment by yumorishita** [comment]
-s 0.1 is too small. Please try 0.2 or more. Otherwise set 0 if you want not to apply the spatial filter.

**Comment by yumorishita** [comment]
-s means p16_filtwidth_km in batch_LiCSBAS.sh.

**Comment by zachzen** [comment]
it still reports same error after tring various parameter , and setting it 0 will get different error .
However that is fine ,without step-16 the result also shows good result .

**Comment by yumorishita** [comment]
Can you upload the log files?

**Comment by zachzen** [comment]
[202007231132batch_LiCSBAS_2_16.log](https://github.com/yumorishita/LiCSBAS/files/4963749/202007231132batch_LiCSBAS_2_16.log)
Here you are ,but now I have some other question.
I tried to use  LiCSBAS_disp_img.py -i coh_avg -p EQA.dem_par --kmz **.kmz to output kmz file
but result will be like this
![111](https://user-images.githubusercontent.com/33368807/88250232-7f10d300-ccd9-11ea-9f55-a1d9ff6c5e04.png)

**Comment by yumorishita** [comment]
Your EQA.dem_par might be wrong. Please upload it.

**Comment by zachzen** [comment]
[EQA.zip](https://github.com/yumorishita/LiCSBAS/files/4964589/EQA.zip)
The DEM from Licsar has some problem(each pixel is zero),so I uesd my own 20m float-type DEM

**Comment by yumorishita** [comment]
Four lines below are wrong:

```
corner_lat:     0.5  decimal degrees
corner_lon:    0.5  decimal degrees
post_lat: 1.0 decimal degrees
post_lon: 1.0 decimal degrees
```

If you use a correct EQA.dem_par, the error in step1-6 will not occur. Please see the sample of EQA.dem_par:
https://github.com/yumorishita/LiCSBAS/wiki/file_structure#example-of-eqadem_par

Note that post_lat must be negative. corner_lat and corner_lon are north and west edge, respectively.

**Comment by zachzen** [comment]
I had solved the promblem. The error occured because I didnt export my inf.img into orthophoto instead geocode. 
Now I assure all the file in that and EQA.dem_par gets right data!!!!
Thank you
