### ISSUE TITLE
Faild LiCSBAS01_get_geotiff.py -f 042A_06133_131313 -s 20150112 -e 20220204

### ISSUE THREAD

**Issue by sajid-zaman** [yumorishita/LiCSBAS#280]
How can i solve this problem
(licsbas) sajid@DESKTOP-IB0AUID:~/MACD/042A_06133_131313$ LiCSBAS01_get_geotiff.py -f 042A_06133_131313 -s 20150112 -e 20220204

LiCSBAS01_get_geotiff.py ver1.6.3 20201207 Y. Morishita
LiCSBAS01_get_geotiff.py -f 042A_06133_131313 -s 20150112 -e 20220204

Frame ID is 042A_06133_131313

Traceback (most recent call last):
  File "/home/sajid/MACD/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 499, in <module>
    sys.exit(main())
  File "/home/sajid/MACD/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 158, in main
    if not os.path.exists(outdir): os.mkdir(outdir)
PermissionError: [Errno 13] Permission denied: '/home/sajid/MACD/042A_06133_131313/GEOC'

**Comment by yumorishita** [comment]
I don't know because the permission error is not caused by LiCSBAS but by your environmental setting. Please check the permission.

**Comment by sajid-zaman** [comment]
> I don't know because the permission error is not caused by LiCSBAS but by your environmental setting. Please check the permission.

Sometime it give permission, i don't know what happened with it. Now it is  working. If i have again problem then i will again contact you.

**Comment by ditafaith** [comment]
Hi,
I'm using licsbas (v1) August has no problem. 
However, today I had a problem when executing steps 0-1. Also, in another frame.

-----------------
Searching latest epoch for mli...

No mli available on http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/171/171A_09587_041313/epochs

Download GACOS data
  There are 0 epochs from 201401001 to 20231001
  Searching available epochs (4 parallel)...
No GACOS data available from 201401001 to 20231001

Download geotiff of unw and cc
Traceback (most recent call last):
  File "/home/saka/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 499, in <module>
    sys.exit(main())
  File "/home/saka/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 339, in main
    print('{} IFGs available from {} to {}'.format(n_ifg, imdates[0], imdates[-1]), flush=True)
IndexError: list index out of range
