### ISSUE TITLE
Error after processing no TS_geoml1clip folder found

### ISSUE THREAD

**Issue by nssuthar16** [yumorishita/LiCSBAS#282]
![Screenshot 2023-08-10 164857](https://github.com/yumorishita/LiCSBAS/assets/100527657/3fbaebfa-abf2-4e3d-ba43-da1f55fa1e2f)
![Screenshot 2023-08-10 164805](https://github.com/yumorishita/LiCSBAS/assets/100527657/a537751c-f770-47b3-8f6f-f7e24dd72119)

**Comment by yumorishita** [comment]
It is probably because you have not successfully finished step16.
