### ISSUE TITLE
step 12 error IndexError: index 0 is out of bounds for axis 0 with size 0  

### ISSUE THREAD

**Issue by vikrumar** [yumorishita/LiCSBAS#284]
Hello,
I am having this error in step 12 of licsbas processing of frame id 048A_08563_131313, attaching the log file. 
I already check for corrupt images manually and removed a few of them. Now all the unwrapped images looks fine. 
[202308111657batch_LiCSBAS_02_16.log](https://github.com/yumorishita/LiCSBAS/files/12322789/202308111657batch_LiCSBAS_02_16.log)

**Comment by yumorishita** [comment]
It seems that all the pixels have unwrapping errors. Please try changing the clip area.

**Comment by yumorishita** [comment]
Please visually check GEOC*/*/*unw.png and try to set the clip area to avoid unwrapping errors (or discontinuity of land).

**Comment by ditafaith** [comment]
I've encountered the same problem when I want to process entire image.
