### ISSUE TITLE
LiCSBAS_cum2tstxt.py

### ISSUE THREAD

**Issue by irmayolii2** [yumorishita/LiCSBAS#286]
Dear Prof. Yumorishita,

I have executed the LiCSBAS_cum2tstxt.py script and obtained the results. I would like to inquire about the unit of measurement for the displacements; is it in millimeters (mm) or centimeters (cm)?

![image](https://github.com/yumorishita/LiCSBAS/assets/90402620/1f71b18b-8a4b-4b67-8e0d-07468347d49e)

Thank you

**Comment by yumorishita** [comment]
It is in mm.
