### ISSUE TITLE
Potential phase biases associated with short temporal baseline ifgs

### ISSUE THREAD

**Issue by fengnian-chang** [yumorishita/LiCSBAS#288]
To reduce potential phase biases associated with short temporal baseline interferograms, I may need to add more interferograms with long temporal baselines. I would like to know how can I make more interferograms and make them consistent with the existing LiCSAR products. Or, are there any effective ways to suppress phase biases?

Thank you in advance for your assistance.

**Comment by yumorishita** [comment]
LiCSBAS uses existing unwrapped interferograms and producing interferograms is out of scope. If you need more interferograms with long temporal baselines, please produce them yourself or ask COMET.

**Comment by fengnian-chang** [comment]
Thank you for your reply! I also want to know how to disable some noise indexes in step 15 (LiCSBAS_mask_ts.py), for example,  not using the n_unw parameter to mask.

**Comment by yumorishita** [comment]
`p15_n_unw_r_thre="0"` will have the same effect as disabled.
