### ISSUE TITLE
Integrating ERA-5 data into LICSBAS

### ISSUE THREAD

**Issue by shapengcheng** [yumorishita/LiCSBAS#289]
Dear Prof. Yumorishita,

Currently LICSBAS only integrates GACOS data, and how to use ERA-5 data for atmospheric correction, or how to use external atmospheric correction software (e.g. PyAPS, TRAIN) to import into LiCSBAS?

Thank you

**Comment by yumorishita** [comment]
I have never tried it but other data than GACOS can be used if you prepare the same format as GACOS (e.g., GACOS/yyyymmdd.sltd.geo.tif).
