### ISSUE TITLE
A 'range format error', when running a 'quick start shell script'

### ISSUE THREAD

**Issue by Linya-Peng** [yumorishita/LiCSBAS#29]
Hi, sorry to disturb. I got a range format error while running the shell script. I edit the batch_LiCSBAS.sh following the wiki:

`---Line32---
do05op_clip="y"       # y/n
---Line36---
p05_clip_range_geo="14.03/14.22/40.78/40.90"  # e.g. 130.11/131.12/34.34/34.6 (in deg)
---Line58-59---
p01_start_date="20160909"     # default: 20141001
p01_end_date="20180508"       # default: today
------`

![image](https://user-images.githubusercontent.com/61902717/88642006-7f9ed480-d0f2-11ea-8c50-a3c6253f1975.png)

Should I change the line36 into "14.03:14.22/40.78:40.90" ?

**Comment by yumorishita** [comment]
It is very strange. I think the Line 36 should be "p05_clip_range=", not "p05_clip_range_geo=" 

https://github.com/yumorishita/LiCSBAS/blob/53125fd3d87898762b3f100fc3abcb8910e0cc9a/batch_LiCSBAS.sh#L36

In your case, parameter settings as follows should work:

```
p05_clip_range=""	# e.g. 10:100/20:200 (ix start from 0)
p05_clip_range_geo="14.03/14.22/40.78/40.90"	# e.g. 130.11/131.12/34.34/34.6 (in deg)
```

**Comment by Linya-Peng** [comment]
Thanks a lot! It seems that it occurs an extra space line in my script.
