### ISSUE TITLE
step 15-vel maskd

### ISSUE THREAD

**Issue by Osmanpour** [yumorishita/LiCSBAS#293]
Hi, 
After running Step 1-5: Mask Time Series,  n_ifg_noloop : 56.0       (100.0%) and I have this result:Masked pixels  : 45063/45066 (100.0%) Kept pixels    : 3/45066 (0.0%) . as you no in below.
I try to solved it but cannot! could you guide me?
and once my result don't show any result just i have vel! could i now that what this happen?

[15parameters.txt](https://github.com/yumorishita/LiCSBAS/files/12478515/15parameters.txt)
[16parameters.txt](https://github.com/yumorishita/LiCSBAS/files/12478518/16parameters.txt)
[12network_gap_info.txt](https://github.com/yumorishita/LiCSBAS/files/12478523/12network_gap_info.txt)
![mask_ts_masked](https://github.com/yumorishita/LiCSBAS/assets/105474833/78ec2581-aa4b-4f90-bb48-5023a2022d53)

**Comment by Osmanpour** [comment]
this is related first question 
![mask_ts](https://github.com/yumorishita/LiCSBAS/assets/105474833/5d64e41c-53fe-4110-9d3b-c83495258539)

**Comment by yumorishita** [comment]
Please try increase p15_n_ifg_noloop_thre (e.g., to 100).

**Comment by Osmanpour** [comment]
my issue was solved, thanks your guide.
