### ISSUE TITLE
A basic question

### ISSUE THREAD

**Issue by Freed-thinks** [yumorishita/LiCSBAS#294]
Dear Mr. Morishita,

I hope you don't mind me asking some basic questions. Regarding the velocity data obtained from LiCSBAS, is it correct to interpret it as follows: "Positive velocity values indicate that the satellite is moving away from the line of sight (mm/year), while negative velocity values indicate that the satellite is moving towards the line of sight (mm/year)"?

Regarding the results of the 2.5D analysis using LiCSBAS_decomposeLOS.py, may I confirm the following interpretations: Positive values in UD.geo.tif indicate uplift, while negative values indicate subsidence. Additionally, positive values in EW.geo.tif indicate eastward movement, while negative values indicate westward movement. Is this understanding correct?

I apologize for asking basic questions, and I appreciate your assistance.

Sincerely,

[Freed-thinks]

**Comment by yumorishita** [comment]
Positive values indicate **towards** the satellite in LOS, uplift in UD, and eastward in EW.

**Comment by Freed-thinks** [comment]
Dear Mr. Morishita,
Thank you very much for your assistance despite your busy schedule.

Sincerely,
[Freed-thinks]
