### ISSUE TITLE
error in step 11 licsbas

### ISSUE THREAD

**Issue by mudjusilfara** [yumorishita/LiCSBAS#295]
Hi, When I am on the step of LiCSBAS11_check_unw.py, receiving the following error:
Start step: 11
End step:   12
Log file:   log/202309182209batch_LiCSBAS_11_12.log

LiCSBAS11_check_unw.py ver1.3.3 20210402 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCml1

coh_thre     : 0.05
unw_cov_thre : 0.3

Size         : 2640 x 2349

Reading unw and cc data...
    0/535th unw to identify valid area...
  100/535th unw to identify valid area...
  200/535th unw to identify valid area...
  300/535th unw to identify valid area...
  400/535th unw to identify valid area...
  500/535th unw to identify valid area...
    0/535th cc and unw...
  100/535th cc and unw...
  200/535th cc and unw...
  300/535th cc and unw...
  400/535th cc and unw...
  500/535th cc and unw...

ERROR: No browse image /mnt/c/users/silvaraa/documents/liCSBAS/LiCSBAS-master/047D_09652_111009/GEOCml1/20170805_20170922/20170805_20170922.unw.png available!

**Comment by yumorishita** [comment]
It seems that `/mnt/c/users/silvaraa/documents/liCSBAS/LiCSBAS-master/047D_09652_111009/GEOCml1/20170805_20170922/20170805_20170922.unw.png` was not created in step02. I suggest removing GEOCml1 and retrying from step02.

**Comment by mudjusilfara** [comment]
Prof, I found the problem in the following text:

LiCSBAS13_sb_inv.py ver1.5.2 20210311 Y. Morishita
LiCSBAS13_sb_inv.py -d GEOCml1 --n_para 1

In geographical coordinates

Not enough memory available compared to mem_size (8000 MB).
Reduce mem_size automatically to 1345 MB.
Read cum data in HDF5 (save memory but slow).

Size of image (w,l)    : 2712, 2776
# of all images        : 142
# of images to be used : 25
# of all ifgs          : 825
# of ifgs to be used   : 18
# of removed ifgs      : 807
Threshold of used unw  : 25

Reference area (X/Y)   : 633:634/682:683
Allowed memory size    : 1345 MB
Number of patches      : 2
Inversion algorism     : LS
Gamma value            : 0.0001

Process 1388/2776th line (1/2th patch)...
  Reading 18 ifg's unw data...
  3764256/3764256 points removed due to not enough ifg data...
  Elapsed time for 1th patch: 00h 00m 09s

Process 2776/2776th line (2/2th patch)...
  Reading 18 ifg's unw data...
  3764256/3764256 points removed due to not enough ifg data...
  Elapsed time for 2th patch: 00h 00m 10s

Find stable reference point...
/home/silvara/anaconda3/lib/python3.9/site-packages/numpy/lib/nanfunctions.py:1119: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,
/mnt/c/users/silvaraa/documents/licsbas/LiCSBAS-master/bin/LiCSBAS13_sb_inv.py:777: RuntimeWarning: All-NaN slice encountered
  min_n_gap = np.nanmin(n_gap)
/mnt/c/users/silvaraa/documents/licsbas/LiCSBAS-master/bin/LiCSBAS13_sb_inv.py:783: RuntimeWarning: All-NaN slice encountered
  min_rms = np.nanmin(rms_cum_wrt_med)
Traceback (most recent call last):
  File "/mnt/c/users/silvaraa/documents/licsbas/LiCSBAS-master/bin/LiCSBAS13_sb_inv.py", line 996, in <module>
    sys.exit(main())
  File "/mnt/c/users/silvaraa/documents/licsbas/LiCSBAS-master/bin/LiCSBAS13_sb_inv.py", line 785, in main
    refy1s, refx1s = refy1s[0], refx1s[0] ## Only first index
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by yumorishita** [comment]
Too many interferograms were removed. I guess the unwrapped data have quite low quality. I suggest checking all the unwrapped data manually.

**Comment by mudjusilfara** [comment]
yes prof, I have checked and the quality is low. how to solve this problem?

**Comment by yumorishita** [comment]
It highly depends on the data. I cannot suggest anything without the read data.

**Comment by MIEMESSI** [comment]
Dear professor, I've been stuck here. What is it?
![image](https://github.com/yumorishita/LiCSBAS/assets/161692921/6726f6a3-cbc7-44a3-ab3a-6baaa01583d6)

**Comment by yumorishita** [comment]
Similar to https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1500877478.
Please try setting 1 here https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/batch_LiCSBAS.sh#L99
