### ISSUE TITLE
Installing LiCSBAS

### ISSUE THREAD

**Issue by RoySreeta** [yumorishita/LiCSBAS#299]
Hello Dr. Yumorishita,
I have tried installing the LiCSBAS on Ubuntu using Anaconda and also not as root but the installation keeps showing one error " PYTHONPATH not set to LiCSBAS". Can you help me clarify this?

**Comment by yumorishita** [comment]
You need to execute `source <your_LiCSBAS_path>/LiCSBAS/bashrc_LiCSBAS.sh` to set the PYTHONPATH.
https://github.com/yumorishita/LiCSBAS/wiki/1_Installation#12-licsbas-module

**Comment by yumorishita** [comment]
What is the return of `echo $PYTHONPATH`?

**Comment by RoySreeta** [comment]
Hello Dr. Yumorishita
This is the return as you asked:
sreetama@sreetama:~/Desktop$ echo $PYTHONPATH
/home/sreetama/licsbas/LiCSBAS/LiCSBAS_lib:

**Comment by yumorishita** [comment]
It is strange. The PYTHONPATH should be `/home/sreetama/roy/LiCSBAS/LiCSBAS_lib` if you run `source /home/sreetama/roy/LiCSBAS/bashrc_LiCSBAS.sh`.
What is the return of `ls /home/sreetama/licsbas/LiCSBAS/LiCSBAS_lib` and `ls /home/sreetama/roy/LiCSBAS/LiCSBAS_lib`?

**Comment by RoySreeta** [comment]
Hello Dr. Yumorishita,
I had two folders previously, so I deleted one and kept only roy.
Now the PYTHONPATH is as follows as you have mentioned:
sreetama@sreetama:~/roy$ source /home/sreetama/roy/LiCSBAS/bashrc_LiCSBAS.sh
sreetama@sreetama:~/roy$ echo $PYTHONPATH
/home/sreetama/roy/LiCSBAS/LiCSBAS_lib:
Then its hows the following:
sreetama@sreetama:~/roy$ ls /home/sreetama/roy/LiCSBAS/LiCSBAS_lib:
ls: cannot access '/home/sreetama/roy/LiCSBAS/LiCSBAS_lib:': No such file or directory

**Comment by yumorishita** [comment]
`/home/sreetama/roy/LiCSBAS/LiCSBAS_lib` should exist. How did you get the LiCSBAS package?

**Comment by RoySreeta** [comment]
Hello Dr. Yumorishita,
I installed the versions of Python and Anaconda first. Then after creating this environment for the LiCSBAS,  I got the LiCSBAS package by cloning into your LiCSBAS github by executing this lien as mentioned in the wiki:
git clone https://github.com/yumorishita/LiCSBAS.git

But despite running these steps I do not know why it is displaying that there is no such file or directory.
What do you suggest I do now?

**Comment by yumorishita** [comment]
In which directory did you run `git clone`?
I recommend removing the LiCSBAS directory once and executing `git clone` and following commands again. Please show all the commands, logs (stdout), and working directory.

**Comment by RoySreeta** [comment]
Hello Dr. Yumorishita,
I removed the LiCSBAS directory and executed as you suggested. Please take a look:
sreetama@sreetama:~$ conda install gdal shapely
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

sreetama@sreetama:~$ git clone https://github.com/yumorishita/LiCSBAS.git
Cloning into 'LiCSBAS'...
remote: Enumerating objects: 1316, done.
remote: Counting objects: 100% (439/439), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 1316 (delta 407), reused 392 (delta 392), pack-reused 877
Receiving objects: 100% (1316/1316), 5.79 MiB | 29.49 MiB/s, done.
Resolving deltas: 100% (759/759), done.
sreetama@sreetama:~$ source ./LiCSBAS/bashrc_LiCSBAS.sh
sreetama@sreetama:~$ LiCSBAS_check_install.py

Python version: 3.11.5
  OK

Check required modues and versions
  astropy(5.1) OK
  bs4(4.12.2) OK
  h5py(3.9.0) OK
  matplotlib(3.7.2) OK
  numpy(1.25.2) OK
  psutil(5.9.0) OK
  requests(2.31.0) OK
  statsmodels(0.14.0) OK
  ERROR: No module named '_gdal'

Check LiCSBAS commands
  OK

Check LiCSBAS library
  ERROR: PYTHONPATH is not set to LiCSBAS library

ERROR: LiCSBAS install is NOT OK

sreetama@sreetama:~$ ls
anaconda3  Desktop  Documents  Downloads  LiCSBAS  Music  Pictures  Public  snap  Templates  Videos
sreetama@sreetama:~$ ls LiCSBAS/
bashrc_LiCSBAS.sh  batch_LiCSBAS.sh  bin  LICENSE  LiCSBAS_lib  LiCSBAS_requirements.txt  LiCSBAS.yml  README.md
sreetama@sreetama:~$

**Comment by yumorishita** [comment]
What is the return of `ls LiCSBAS/LiCSBAS_lib`?
I have no idea about the gdal error. I suggest trying downgrading Python from 3.11 to 3.8.

**Comment by LMurrayBergquist** [comment]
I had exactly the same problem, and same output as RoySreeta, I tried downgrading from python 3.11 to 3.8 and using gdal=2.4, but now the error is just slightly different, it can't find osgeo instead of "_gdal":

(base) [louisa@localhost ~]$ LiCSBAS_check_install.py 

Python version: 3.8.5
  OK

Check required modues and versions
  astropy(4.0.2) OK
  bs4(4.9.3) OK
  h5py(2.10.0) OK
  matplotlib(3.3.2) OK
  numpy(1.19.2) OK
  psutil(5.7.2) OK
  requests(2.24.0) OK
  statsmodels(0.12.0) OK
  ERROR: No module named 'osgeo'

Check LiCSBAS commands
  OK

Check LiCSBAS library
  ERROR: PYTHONPATH is not set to LiCSBAS library

ERROR: LiCSBAS install is NOT OK

(base) [louisa@localhost ~]$ echo $PYTHONPATH
/home/louisa/Software/LiCSBAS2/LiCSBAS_lib

**Comment by yumorishita** [comment]
I cannot reproduce the error... What OS do you use?

**Comment by LMurrayBergquist** [comment]
I am running it in a VirtualBox with Fedora 32, and I am using bash for the shell.

**Comment by yumorishita** [comment]
@LMurrayBergquist How did you get the LiCSBAS package? What is the return of `ls /home/louisa/Software/LiCSBAS2/LiCSBAS_lib` and `conda list`?

**Comment by RoySreeta** [comment]
Hello Dr. Yumorishita,
I downgraded to Python Version 3.8 and i ran the command as you asked. This is what it shows:
licsbas) sreetama@sreetama:~/LiCSBAS$ echo $PYTHONPATH
/home/sreetama/LiCSBAS/LiCSBAS_lib:
(licsbas) sreetama@sreetama:~/LiCSBAS$ cd LiCSBAS_lib/
(licsbas) sreetama@sreetama:~/LiCSBAS/LiCSBAS_lib$ ls
cmocean               GMT                  LiCSBAS_plot_lib.py
colorcet              LiCSBAS_inv_lib.py   LiCSBAS_tools_lib.py
extract_cmaps_GMT.sh  LiCSBAS_io_lib.py    SCM
extract_cmaps_SCM.sh  LiCSBAS_loop_lib.py
(licsbas) sreetama@sreetama:~/LiCSBAS/LiCSBAS_lib$

**Comment by LMurrayBergquist** [comment]
Hello, 
I got LiCSBAS from the Wiki instructions: https://github.com/yumorishita/LiCSBAS/wiki/1_Installation
But in step 1.2 I did: "git clone https://github.com/yumorishita/LiCSBAS2.git" instead of "/LiCSBAS.git"

This is the ls output: 
(licsbas) [louisa@localhost ~]$ ls Software/LiCSBAS2/LiCSBAS_lib/
cm_insar_qgis.xml  colorcet              extract_cmaps_SCM.sh  LiCSBAS_inv_lib.py  LiCSBAS_loop_lib.py  LiCSBAS_tools_lib.py  SCM
cmocean            extract_cmaps_GMT.sh  GMT                   LiCSBAS_io_lib.py   LiCSBAS_plot_lib.py  __pycache__

The "conda list" output is quite long, do you want to see all of it or just gdal?
(licsbas) [louisa@localhost ~]$ conda list | grep "gdal"
gdal                      3.4.1            py39h2c27f0e_0  
libgdal                   3.4.1                hdd9df00_0

**Comment by yumorishita** [comment]
@RoySreeta There should be no problem. Do you still get an error in `LiCSBAS_check_install.py`? What is your OS?

@LMurrayBergquist Everything looks fine. I have no idea about the error...

**Comment by RoySreeta** [comment]
Hello Dr. Yumorishita,
Yes, unfortunately despite everything being alright I'm still getting the same error. I'm using Linux.

**Comment by yumorishita** [comment]
Below is my example. Can you try the same commands and tell me the return?

```
$ echo $PYTHONPATH
/home/morishita/software/LiCSBAS2/LiCSBAS_lib:
$ ls ${PYTHONPATH%:}
GMT                  LiCSBAS_plot_lib.py   cm_insar_qgis.xml     extract_cmaps_SCM.sh
LiCSBAS_inv_lib.py   LiCSBAS_tools_lib.py  cmocean
LiCSBAS_io_lib.py    SCM                   colorcet
LiCSBAS_loop_lib.py  __pycache__           extract_cmaps_GMT.sh
$ python3
Python 3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import LiCSBAS_io_lib
>>> 
```

**Comment by LMurrayBergquist** [comment]
Hello, this is what mine returned: 

![grafik](https://github.com/yumorishita/LiCSBAS/assets/46690824/6d09ff52-1273-4ec3-bfb2-8645ee669712)

**Comment by yumorishita** [comment]
Please try:
https://stackoverflow.com/questions/71904252/gdalinfo-error-while-loading-shared-libraries-libtiledb-so-2-2-cannot-open-sh

**Comment by RoySreeta** [comment]
Hello Dr. Yumorishita,
 I installed the gdal poppler and my LiCSBAS installation is finally OK. Thanks for your help!
