### ISSUE TITLE
How to create a list of SAR time series and hours for acquisitions for GACOS Service for a specific frame of LICSAR?

### ISSUE THREAD

**Issue by mohseniaref** [yumorishita/LiCSBAS#3]
How can we create a list of SAR time series and hours for acquisitions for GACOS Service for a specific frame of LICSAR? Is there a parameter file in LicSBAS folder for this aim?

**Comment by yumorishita** [comment]
The list of acquisition dates can be derived from the dates of interferograms you use. Currently there is no information of the acquisition time in the metadata, but you can get to know it by searching the Sentinel-1 data on, e.g., ASF VERTEX (https://search.asf.alaska.edu/#/).

**Comment by yumorishita** [comment]
Now new metadata.txt is abailable for each frame (e.g., http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/46/046D_05292_131313/metadata/metadata.txt), which includes the time of acquisition. The list of the dates can be extracted from the 2nd column in a "baselines" file (http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/46/046D_05292_131313/metadata/baselines).
Thank you for your feedback.
