### ISSUE TITLE
Update with new interferograms

### ISSUE THREAD

**Issue by alejobeap** [yumorishita/LiCSBAS#30]
Dear

I have seen in the page of LICSAR portal that in my interest zone the last interferograms are not updated or there are cut interferograms and it does not cover the zone that I am interested in doing the temporal series. Is there any way to process the interferograms and copy them to the GEOC folders for processing?

Thank you very much.

Greetings

PE

**Comment by yumorishita** [comment]
You can request the processing of missing/additional interferograms by LiCSAR from the form on the LiCS portal web (https://comet.nerc.ac.uk/comet-lics-portal/, right column).
See also #6 and #9.
