### ISSUE TITLE
The download never completes with LiCSBAS01_get_geotiff.py.

### ISSUE THREAD

**Issue by Freed-thinks** [yumorishita/LiCSBAS#301]
Mr. Morishita,

I have encountered a recurring issue while downloading images with "LiCSBAS01_get_geotiff.py" where the download seems to be taking an exceptionally long time and doesn't appear to be progressing. For instance, it might be stuck at "Downloading 20201213_20201225 (300/1300)..." for about 8 hours. Do you have any suggestions for addressing this problem?

Thank you in advance.

**Comment by yumorishita** [comment]
Please try `p01_n_para="1"`.
https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/batch_LiCSBAS.sh#L73
