### ISSUE TITLE
ModuleNotFoundError: No module named 'LiCSBAS_tools_lib'

### ISSUE THREAD

**Issue by HugoLuVi** [yumorishita/LiCSBAS#302]
Dear Yu Morishita

I trust you are well. I am reaching out to request your guidance in resolving an issue I have encountered while trying to execute the ./batch_LiCSBAS.sh script within the LiCSBAS environment. Specifically, I am facing an error related to the 'LiCSBAS_tools_lib' module.

I am following the steps outlined in the Quick Start guide to process geospatial data using LiCSBAS. To provide context, here's an overview of the actions I've taken:

    Created a working directory named '124D_04854_171313' and navigated to it, as recommended in the Quick Start guide.

    Copied the batch script copy_batch_LiCSBAS.sh.

    Edited the copied batch_LiCSBAS.sh script to suit my specific area of interest. For example, I have modified the following parameters:
        do05op_clip="y" (set to 'y')
        p05_clip_range_geo="14.03/14.22/40.78/40.90" (geographic coordinates in degrees)
        p01_start_date="20160909" (start date)
        p01_end_date="20180508" (end date)

After making these necessary adjustments, I aim to run the ./batch_LiCSBAS.sh script to commence LiCSBAS processing. However, when I do so, I encounter the following error:

_Start step: 01
End step:   16
Log file:   log/202310251919batch_LiCSBAS_01_16.log

Traceback (most recent call last):
  File "/home/hugoluvi/Documentos/GitHub/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 79, in <module>
    import LiCSBAS_tools_lib as tools_lib
ModuleNotFoundError: No module named 'LiCSBAS_tools_lib'_

I have verified that the LiCSBAS_tools_lib module is present within the /home/hugoluvi/Documentos/GitHub/LiCSBAS/LiCSBAS_lib directory. Despite my attempts to run scripts from this directory or the /home/hugoluvi/Documentos/GitHub/LiCSBAS/bin directory, the "ModuleNotFoundError" issue remains.

I have even adjusted the paths in my ~/.bashrc file to ensure the necessary directories are included, which allows me to launch the LiCSBAS_plot_ts.py script from the /home/hugoluvi/Documentos/GitHub/LiCSBAS/bin directory. However, the issue persists when running the ./batch_LiCSBAS.sh script.

I would greatly appreciate your assistance in resolving this issue and ensuring a seamless execution of LiCSBAS for my geospatial data processing. If additional information or access to my system is required to diagnose the issue thoroughly, please do let me know.

Thank you for your prompt attention and valuable support.

Warm regards,
Hugo Luna

**Comment by yumorishita** [comment]
What is the return of `echo $PYTHONPATH` and `LiCSBAS_check_install.py`?

**Comment by yumorishita** [comment]
Did you run `source <your_LiCSBAS_path>/LiCSBAS/bashrc_LiCSBAS.sh`?
https://github.com/yumorishita/LiCSBAS/wiki/1_Installation#12-licsbas-module

**Comment by HugoLuVi** [comment]
Dear Yu Morishita,

I hope this message finds you well. My name is Hugo Luna, and I am writing to report some issues I encountered while trying to install LiCSBAS.

I followed the installation instructions carefully, but I ran into several problems that I would like to share with you. The main challenges I encountered are as follows:

1. Confusion Between `gdal` and `_gdal`:
   When attempting to install the `_gdal` package, I realized that it was not available in the Conda channels I was using. Instead, I had previously successfully installed the `gdal` package using `pip`. It seems that LiCSBAS may expect the `_gdal` package while I have `gdal` installed. This discrepancy led to issues with the GDAL functionality.

   Details: I installed `gdal` using `pip`, and the path to the `gdal` library is /home/hugoluvi/miniconda3/envs/licsbas/lib/python3.11/site-packages.

2. Errors Shown by LiCSBAS_check_install.py:
   I also experienced errors when running the `LiCSBAS_check_install.py` script. The tool detected a missing `_gdal` module and raised an error related to the `PYTHONPATH` not being set to the LiCSBAS library.

   Details: To address this issue, I made modifications to my `.bashrc` file, including adding the following lines:

   export LICSBAS_PATH="$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)"
   export PATH="$LICSBAS_PATH/bin:$PATH"
   export PYTHONPATH="$LICSBAS_PATH/LiCSBAS_lib:$PYTHONPATH"
   export PYTHONPATH="/home/hugoluvi/miniconda3/envs/licsbas/lib/python3.11/site-packages:$PYTHONPATH"

   These modifications were intended to ensure that LiCSBAS could access its library and dependencies.

Despite these changes, these issues persisted, and the LiCSBAS installation is not functioning as expected.

I am genuinely interested in using LiCSBAS for my work, and I believe that with your expertise, we can overcome these installation challenges. If you have any recommendations or insights, I would greatly appreciate your guidance.

I am willing to provide any further information, logs, or assistance that might help diagnose and resolve these issues. If you could please take a look and offer your expertise, it would be immensely helpful.

Thank you for your time and consideration. I look forward to your response and to potentially resolving these installation difficulties.

Best regards,
Hugo Luna
