### ISSUE TITLE
Connection Error and Connection Timeout on LiCSBAS Processing

### ISSUE THREAD

**Issue by AfifJanur** [yumorishita/LiCSBAS#304]
Hello Dr. Yumorishita,
I can't do processing on licsbas from October 28 2023 until now because of network errors and no network connection
I have also checked on the Licsar portal, it turns out that data cannot be downloaded, is there a problem with Licsar or is it undergoing maintenance?
Thank u.
![WhatsApp Image 2023-10-29 at 10 01 37 (1)](https://github.com/yumorishita/LiCSBAS/assets/75745598/533a267e-136d-49f6-b12e-3ef431e35178)
![eror](https://github.com/yumorishita/LiCSBAS/assets/75745598/dfa3a8c1-f7e6-4619-930a-fa54939ae167)

**Comment by yumorishita** [comment]
Please follow https://github.com/yumorishita/LiCSBAS/issues/303.
