### ISSUE TITLE
1_5 mask problem with n_loop_err

### ISSUE THREAD

**Issue by HN-Jiang** [yumorishita/LiCSBAS#305]
Hi, I want to ask about n_loop_err, I didn't understand what does this means, does it calculate the error in the individual interferogram that don't have loop? (Which means the folder "12no_loop_ifg_ras"?)

So please check my mask_ts.png, it looks like it have big error! I worry that these no loop ifgs may bring unwapping error to my results, Will it？

My solution is delate all  interferograms in 12no_loop_ifg_ras, but the result is still same, can you tell me what's the problem?

![图片](https://github.com/yumorishita/LiCSBAS/assets/53942586/41c7a11d-5ef2-41f5-a0c5-57b911c2a305)

**Comment by HN-Jiang** [comment]
By the way I'm using 2014-2023 datasets from LiCSAR.

**Comment by yumorishita** [comment]
The number of interferograms that have no loop is `n_ifg_noloop`, not `n_loop_err`. Please read [section 2.4.2](https://www.mdpi.com/2072-4292/12/3/424#sec2dot4dot2-remotesensing-12-00424) in my paper for the meaning of `n_loop_err`.

Your result includes many unwrapping errors. I would suggest checking `12loop/bad_loop_cand_png/*.png`, identifying interferograms that have unwrapping errors, and removing them.
