### ISSUE TITLE
Error when running the Campi Flegrei test code

### ISSUE THREAD

**Issue by RoySreeta** [yumorishita/LiCSBAS#306]
Hello Dr. YuMorishita,
I could successfully download and run the code now that the maintenance on LiCSBAS is over. So thank you so much for that. But I encountered an unusual error in the end at Step 11 and I'm copying it as follows:

Elapsed time: 00h 02m 13s

LiCSBAS02_ml_prep.py Successfully finished!!

Output directory: GEOCml1

LiCSBAS05op_clip_unw.py ver1.2.5 20210105 Y. Morishita
LiCSBAS05op_clip_unw.py -i GEOCml1 -o GEOCml1clip -g 14.03/14.22/40.78/40.90

Area to be clipped:
  0:3710/0:3236 -> 268:459/2311:2432
  13.7624448/17.4714419/39.9761686/43.2111661 ->
  14.0304446/14.2204444/40.7801680/40.9001679
  Width/Length: 3710/3236 -> 191/121

Clip E.geo
Clip N.geo
Clip U.geo
Copy baselines
Clip hgt
Recreate hgt.png
Clip slc.mli
Recreate slc.mli.png

Clip unw and cc
  12 parallel processing...
    0/211th unw...
  100/211th unw...
  200/211th unw...

Elapsed time: 00h 00m 20s

LiCSBAS05op_clip_unw.py Successfully finished!!

Output directory: GEOCml1clip

LiCSBAS11_check_unw.py ver1.3.3 20210402 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCml1clip

coh_thre     : 0.05
unw_cov_thre : 0.3

Size         : 191 x 121

Reading unw and cc data...
    0/211th unw to identify valid area...
  100/211th unw to identify valid area...
  200/211th unw to identify valid area...
    0/211th cc and unw...
  100/211th cc and unw...
  200/211th cc and unw...

0/211 ifgs are discarded from further processing.
ifg dates        unw_cov coh_av
Traceback (most recent call last):
  File "/home/sreetama/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
  File "/home/sreetama/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 331, in main
    plot_lib.plot_network(ifgdates, bperp, [], pngfile)
  File "/home/sreetama/LiCSBAS/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 285, in plot_network
    ax.grid(b=True, which='major')
  File "/home/sreetama/anaconda3/envs/licsbas/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 3194, in grid
    self.xaxis.grid(visible, which=which, **kwargs)
  File "/home/sreetama/anaconda3/envs/licsbas/lib/python3.8/site-packages/matplotlib/axis.py", line 1660, in grid
    self.set_tick_params(which='major', **gridkw)
  File "/home/sreetama/anaconda3/envs/licsbas/lib/python3.8/site-packages/matplotlib/axis.py", line 932, in set_tick_params
    kwtrans = self._translate_tick_params(kwargs)
  File "/home/sreetama/anaconda3/envs/licsbas/lib/python3.8/site-packages/matplotlib/axis.py", line 1076, in _translate_tick_params
    raise ValueError(
ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'zorder', 'gridOn', 'tick1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'labeltop', 'labelrotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_color', 'grid_dash_capstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'grid_in_layout', 'grid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_markerfacecoloralt', 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_params', 'grid_snap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'grid_aa', 'grid_c', 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']

Can you tell me what is causing thsi issue/error so that I can successfully proceed with my analysis?

**Comment by yumorishita** [comment]
Please see https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1498886957.

**Comment by RoySreeta** [comment]
Thank you. I downgraded to a version of matplotlib 3.4.2 and it works fine now.
