### ISSUE TITLE
Calculating displacement acceleration 

### ISSUE THREAD

**Issue by Sakina-A** [yumorishita/LiCSBAS#309]
Hello Morishita

I was wondering is there a way to calculate the acceleration from the displacement velocity values for the entire points/map? Also, could you please clarify what is the unit of t in the linear model equation (e.g. linear model: 0.329*t+0.050) written in the output txt file when using LiCSBAS_cum2tstxt.py.

Thanks in advance :)

**Comment by yumorishita** [comment]
LiCSBAS has no function to output acceleration for the entire point. You should implement it yourself and this code might be helpful:
https://github.com/yumorishita/LiCSBAS/blob/master/bin/LiCSBAS_plot_ts.py#L153

The unit of t is year.
