### ISSUE TITLE
increase quality

### ISSUE THREAD

**Issue by MarcoSal** [yumorishita/LiCSBAS#312]
Hi prof,
I processed a dataset.
these are the results.

Noise index    : Threshold  (rate to be masked)
- coh_avg      : 0.05       ( 0.0%)
- n_unw        :  241       ( 0.0%)
- vstd         :  100 mm/yr ( 0.0%)
- maxTlen      :  0.0 yr    ( 0.0%)
- n_gap        : 11.0       (35.0%)
- stc          :    5 mm    ( 0.0%)
- n_ifg_noloop :   50       (98.2%)
- n_loop_err   :    5       ( 0.6%)
- resid_rms    :    2 mm    ( 0.9%)

Masked pixels  : 3107/3110 (99.9%)
Kept pixels    : 3/3110 (0.1%)

I understood that, to have an adequate number of points, I have to increase n_gap and n_ifg_noloop.
is there a way to increase the quality of the solution without touching the 2 parameters?

thanks

**Comment by yumorishita** [comment]
The main problem is the interferogram network. Changing parameters in step04, 05, 11, and 12 might improve the network, but if the input data already have a network problem, LiCSBAS can do nothing. In that case, additional interferograms should be added before LiCSBAS processing.

**Comment by MarcoSal** [comment]
is there a document that describes the impact of the various parameters on the final result?

**Comment by yumorishita** [comment]
Please read my papers
- https://doi.org/10.3390/RS12030424
- https://doi.org/10.1186/s40645-020-00402-7

**Comment by MarcoSal** [comment]
Last question. The output has a planimetric resolution of 80m, is there the possibility of increasing it down to 5-10m?

**Comment by yumorishita** [comment]
5-10m is impossible for Sentinel-1 because its single-look azimuth pixel spacing is 14m.

**Comment by MarcoSal** [comment]
What is the maximum planimetric resolution achievable with LiCSBAS?
thanks

**Comment by yumorishita** [comment]
LiCSBAS cannot improve the resolution. If you use the LiCSAR product, the achievable resolution is the LiCSAR product's one (0.001deg). You can improve the resolution if you prepare the unwrapped data yourself.
