### ISSUE TITLE
Accuracy of my results and QGIS

### ISSUE THREAD

**Issue by oguzhannysr** [yumorishita/LiCSBAS#313]
Hi,

As a result of my experiment, I got the following outputs. What I want to ask is, is my accuracy reliable to the information here? Also, I want to open my displacement maps in QGIS, which file should I choose for this?

**Also, do the output results represent ew or vertical change?**

![1](https://github.com/yumorishita/LiCSBAS/assets/53774968/0851f547-2802-4df0-afa9-ef631c2e9f7e)
![2](https://github.com/yumorishita/LiCSBAS/assets/53774968/d51f14a3-aacf-456e-8938-825d91d8e948)
![3](https://github.com/yumorishita/LiCSBAS/assets/53774968/88d0fa6c-bf4a-4ac2-b316-46a95d532447)

**Comment by yumorishita** [comment]
The accuracy looks not bad. For more details of the each noise index, please read the paper: https://doi.org/10.3390/RS12030424
You can create a Geotiff file using LiCSBAS_flt2geotiff.py to display on QGIS.
The displacement is LOS, not ew or vertical.

**Comment by oguzhannysr** [comment]
Thank you Morishita, how would it be correct to also use masked pixels?

**Comment by yumorishita** [comment]
I don't recommend using the masked pixels in general because they include large noise but it depends on the situation.

**Comment by oguzhannysr** [comment]
LiCSBAS_flt2geotiff.py -i infile Should the infile here be my cum.h5 file?

**Comment by yumorishita** [comment]
No, it should be a float file as written in the [usage](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_flt2geotiffpy). A float file can be created by LiCSBAS_cum2flt.py or LiCSBAS_cum2vel.py from a h5 file.

**Comment by oguzhannysr** [comment]
thank you, I would have one more question, I want to produce ew and vertical maps from los maps, how can I do this. Should I produce both ascending and descending los displacement maps of the relevant region for this?

**Comment by yumorishita** [comment]
Yes, then you can use LiCSBAS_decomposeLOS.py.

**Comment by oguzhannysr** [comment]
I did the operations for ascending and descending products but when I compare the two result maps (los) I feel that the results are different. What is the reason for this? Below are the images. From step 1 to the end of step 16 I left the variables default, I only changed the following.

IDs I used:
Descending: 138D_04954_131111
Ascending: 058A_04914_121007

p05_clip_range_geo="29.969900343578978/30.09462591326207/40.82199952594731/40.892477514912436"
p01_start_date="20181009" # default: 20141001
p01_end_date="20231009" # default: today
**_Ascending_**
![Ascending](https://github.com/yumorishita/LiCSBAS/assets/53774968/393af1cc-d8c1-4c9e-b0af-3998e3936d83)
**_Descending_**
![Descending](https://github.com/yumorishita/LiCSBAS/assets/53774968/cdca5867-a302-4d75-afb5-0e1fb2d11d06)

**Comment by yumorishita** [comment]
Something must be wrong because the value is too large. How did you create the geotiff?

**Comment by oguzhannysr** [comment]
I made geotiffs using these codes respectively;

LiCSBAS_cum2flt.py -d 20231009[-i cum_filt.h5]

I'm going to use the result from here;

LiCSBAS_flt2geotiff.py -i 20181009_20231009.cum -p EQA.dem_par

That's how geotif came into being.

**Comment by oguzhannysr** [comment]
and these are the ew and ud maps.
![EW](https://github.com/yumorishita/LiCSBAS/assets/53774968/e8cd9710-9590-488a-9ee2-9d1f22400f04)
![UD](https://github.com/yumorishita/LiCSBAS/assets/53774968/15a7484e-cd47-41f6-bc85-dd7da653ede6)

**Comment by oguzhannysr** [comment]
and these are log files.

_**058A_04914_121007**_
[202311241052batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/13496560/202311241052batch_LiCSBAS_01_16.log)

**_138D_04954_131111_**
[202311271556batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/13496563/202311271556batch_LiCSBAS_01_16.log)

**Comment by oguzhannysr** [comment]
![vel filt mskd](https://github.com/yumorishita/LiCSBAS/assets/53774968/2dd7262f-8f1a-4e26-b1ec-4456c0d0a96c)
![vel filt mskd](https://github.com/yumorishita/LiCSBAS/assets/53774968/fe27b9b1-ff33-486c-b1d0-20a8738e5fc3)

**Comment by yumorishita** [comment]
Can you try LiCSBAS_cum2flt.py with --png option and show me the created png file?

**Comment by oguzhannysr** [comment]
![20181012_20231004 cum](https://github.com/yumorishita/LiCSBAS/assets/53774968/aad30184-0e71-44bb-8335-66da98532db3)
![20181012_20230928 cum](https://github.com/yumorishita/LiCSBAS/assets/53774968/48cc80f2-dec2-45f1-a9a4-4cc840a899d0)

**Comment by yumorishita** [comment]
Please try displaying the *cum.geo.tif by LiCSBAS_disp_img.py.

**Comment by oguzhannysr** [comment]
![1](https://github.com/yumorishita/LiCSBAS/assets/53774968/cfac9e37-91b1-4e36-a8ea-4b8eec2b0b33)
![2](https://github.com/yumorishita/LiCSBAS/assets/53774968/4c06ee9b-99bc-4aad-974d-eec7a6f10dec)

**Comment by oguzhannysr** [comment]
there is also something different I want to ask, I saw the output resolution in gmtsar as 30 metres, but I saw that it has a spatial resolution of 84 metres in licsbas. How can I improve this?

**Comment by yumorishita** [comment]
The geotiff files seem to be correct. Please recheck your QGIS setting.

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/312#issuecomment-1820894728

**Comment by oguzhannysr** [comment]
@
![q1](https://github.com/yumorishita/LiCSBAS/assets/53774968/dff5cf6c-d140-4863-9885-2080566f61ff)
@yumorishita Hello, how accurate are your results here? Also, how can I understand this? Are my ascending or descending results better quality?

**Comment by oguzhannysr** [comment]
So how can I understand this?

**Comment by oguzhannysr** [comment]
dear @yumorishita, Which one should I use better? I leave the logs below.
[202311291745batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/13561524/202311291745batch_LiCSBAS_01_16.log)
[202311291833batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/13561526/202311291833batch_LiCSBAS_01_16.log)

**Comment by oguzhannysr** [comment]
dear @yumorishita, According to your suggestion, I will use one of the two in my work. I would be happy if you help me.

**Comment by yumorishita** [comment]
167D_05077_131313 seems to be better because there is no gap in the refined network.

**Comment by oguzhannysr** [comment]
dear @yumorishita , 
I do not have the frame you mentioned, the names of the 2 frames I sent you are as follows;
036D_05175_131313
131A_05153_131313

**Comment by yumorishita** [comment]
Really? [202311291833batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/13561526/202311291833batch_LiCSBAS_01_16.log) contains the log of 167D_05077_131313.

**Comment by oguzhannysr** [comment]
hello dear @yumorishita , I have a question about decomposeLOS. After generating ascending and descending LOS results in the region I specified, I created EW and UD maps. But the result EW and UD pixel positions do not match the LOS as shown in the image. The LOS that does not match in the image is the displacement in the ascending direction. What am I doing wrong, or is everything normal? 
my frame numbers: 050D_05046_141313, 145A_05152_13131313

![image](https://github.com/yumorishita/LiCSBAS/assets/53774968/4ef80090-c6c3-4fe2-9504-467e40a8b3de)

**Comment by oguzhannysr** [comment]
Thank you very much sir @yumorishita

**Comment by oguzhannysr** [comment]
@yumorishita ,Hello, I don't understand the reason for this, the work stops on its own. 
![image](https://github.com/yumorishita/LiCSBAS/assets/53774968/d7dcfbae-5127-4b9e-b62f-a0a1387b7787)
[batch_LiCSBAS.txt](https://github.com/yumorishita/LiCSBAS/files/14061614/batch_LiCSBAS.txt)

**Comment by yumorishita** [comment]
I have no idea.
