### ISSUE TITLE
clip below equator error

### ISSUE THREAD

**Issue by maulanaheno** [yumorishita/LiCSBAS#315]
order_op03_05="03 04 05"	# can change order e.g., 05 03 04
do03op_GACOS="n"	# y/n
do04op_mask="n"	# y/n
do05op_clip="y"	# y/n
p04_mask_coh_thre=""	# e.g. 0.2
p04_mask_range=""	# e.g. 10:100/20:200 (ix start from 0)
p04_mask_range_file=""	# Name of file containing range list
p05_clip_range=""	# e.g. 10:100/20:200 (ix start from 0)
p05_clip_range_geo="110.32/110.44/-7.74/-7.84"	# e.g. 130.11/131.12/34.34/34.6 (in deg)

error:

LiCSBAS11_check_unw.py ver1.3.3 20210402 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCml1clip

coh_thre     : 0.05
unw_cov_thre : 0.3

Size         : 121 x -99
Traceback (most recent call last):
  File "/home/maulanaheno/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
  File "/home/maulanaheno/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 191, in main
    n_unw = np.zeros((length, width), dtype=np.float32)
ValueError: negative dimensions are not allowed

what is the clip range if it below equator?

**Comment by yumorishita** [comment]
Please try 110.32/110.44/-7.84/-7.74 because the third number is the southern side.

**Comment by maulanaheno** [comment]
> Please try 110.32/110.44/-7.84/-7.74 because the third number is the southern side.

thanks, it worked

**Comment by RaeGeoffrey** [comment]
i got same problem here the full log 
[202410051527batch_LiCSBAS_01_16.log](https://github.com/user-attachments/files/17265694/202410051527batch_LiCSBAS_01_16.log)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/315#issuecomment-1837136621
