### ISSUE TITLE
Error after download UNW and CC

### ISSUE THREAD

**Issue by dhiazalfaz** [yumorishita/LiCSBAS#316]
![error after download unw and cc](https://github.com/yumorishita/LiCSBAS/assets/152666223/faa216bf-3e62-4250-93fd-4501deaa2843)

excuse me sir, I wanna ask u about my problem, I've done with dowload unw and cc processing, then I got the problem like this picture that I send, how can I fix it and what should I do then? 
thanks in advance

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/158#issuecomment-1140718453
https://github.com/yumorishita/LiCSBAS/issues/280#issuecomment-1666485029

**Comment by NabilAttar** [comment]
![eror log](https://github.com/yumorishita/LiCSBAS/assets/155360570/c14761a9-2d59-4fc9-bc1e-41d23b3b40ac)
excuse me sir, i am student from Indonesian. i wanna ask you about my problem. i have done with download unw and cc, then i got the issue like this picture i send, how can i fix it? thank youu

[202401011605batch_LiCSBAS_01_16.txt](https://github.com/yumorishita/LiCSBAS/files/13804311/202401011605batch_LiCSBAS_01_16.txt)

**Comment by yumorishita** [comment]
The parameter `105.16/105.36/-5.53/-5.31` you specified is invalid. It must be within `13.7624448/17.4714419/39.9761686/43.2111661` according to the log.

**Comment by yumorishita** [comment]
No, the frame you are processing is not in the southern hemisphere but around 39-43N. You must select the correct frame ID.

**Comment by NabilAttar** [comment]
> No, the frame you are processing is not in the southern hemisphere but around 39-43N. You must select the correct frame ID.

which section settings do I need to change to be south, hemisphere? thank you

**Comment by yumorishita** [comment]
You must change the frame ID (directory name) from 124D_04854_171313.

**Comment by NabilAttar** [comment]
![image](https://github.com/yumorishita/LiCSBAS/assets/155360570/0fc5bbfa-4117-48a9-a672-d9bd069c2952)
ah yes i just realized, thank you very much, i will try tomorrow :)

**Comment by NabilAttar** [comment]
![image](https://github.com/yumorishita/LiCSBAS/assets/155360570/69549d1e-d8b4-47aa-9225-fdb8eeebf669)
excuse me sir, i have try to process again and get an issue in unw process. how can i fix it? thank youu
[202401020828batch_LiCSBAS_01_16.txt](https://github.com/yumorishita/LiCSBAS/files/13806604/202401020828batch_LiCSBAS_01_16.txt)

**Comment by Indianmedieval** [comment]
> ![error after download unw and cc](https://private-user-images.githubusercontent.com/152666223/287410899-faa216bf-3e62-4250-93fd-4501deaa2843.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMjU5NjYsIm5iZiI6MTcwNDIyNTY2NiwicGF0aCI6Ii8xNTI2NjYyMjMvMjg3NDEwODk5LWZhYTIxNmJmLTNlNjItNDI1MC05M2ZkLTQ1MDFkZWFhMjg0My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQyMDAxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDAwMDhkZmMzOTc4ZjRhMzU5MGVkMDEzNzdhMzExNjc4YzEyYWMzOGVmODVmMmI1MDY5ZWZmYzU5MzRiZGJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n-gXNuvgIcd_nnJHIVgysBDPE92RK5gM_PolmBESktM)
> 
> excuse me sir, I wanna ask u about my problem, I've done with dowload unw and cc processing, then I got the problem like this picture that I send, how can I fix it and what should I do then? thanks in advance

Dear Sir,

I am getting a similar error. Kindly please help me in solving this permission error.

thanks

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/158#issuecomment-1140718453
https://github.com/yumorishita/LiCSBAS/issues/280#issuecomment-1666485029
