### ISSUE TITLE
Plot SBAS Network Error

### ISSUE THREAD

**Issue by maulanaheno** [yumorishita/LiCSBAS#317]
(licsbas) maulanaheno@Henok:/mnt/d/licsbas/076D_09725_121107$ LiCSBAS_plot_network.py -i ifg_list -b bperp_list

Bad key text.latex.preview in file /home/maulanaheno/miniconda3/envs/licsbas/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key mathtext.fallback_to_cm in file /home/maulanaheno/miniconda3/envs/licsbas/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key savefig.jpeg_quality in file /home/maulanaheno/miniconda3/envs/licsbas/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key keymap.all_axes in file /home/maulanaheno/miniconda3/envs/licsbas/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key animation.avconv_path in file /home/maulanaheno/miniconda3/envs/licsbas/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key animation.avconv_args in file /home/maulanaheno/miniconda3/envs/licsbas/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

LiCSBAS_plot_network.py ver1.0 20200225 Y. Morishita
LiCSBAS_plot_network.py -i ifg_list -b bperp_list

ERROR:  No ifg_list exists!

For help, use -h or --help.

can you help me how to fix the error?

**Comment by yumorishita** [comment]
You must prepare ifg_list and bperp_list.

**Comment by maulanaheno** [comment]
how do i prepare it?

**Comment by yumorishita** [comment]
See the usage.

**Comment by maulanaheno** [comment]
didnt found it in the usage and if i export the velocity  to geotiff, is it the make only one time displacement or cumulative displacement form start to end time?

**Comment by yumorishita** [comment]
Usage:
```
 -i  Text file of ifg list (format: yyymmdd_yyyymmdd)
 -b  Text file of bperp list (format: yyyymmdd yyyymmdd bperp dt)
```

Velocity is velocity estimated from the entire period, not one time displacement nor cumulative displacement.

**Comment by maulanaheno** [comment]
and what the difference between velocity 1 and 2?

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/117#issuecomment-878956383
