### ISSUE TITLE
copy_batch_LiCSBAS.sh : command not found error

### ISSUE THREAD

**Issue by ceronimos** [yumorishita/LiCSBAS#318]
After mkdir frameID and cd FrameID, I got a command not found error when I issued copy_batch_LiCSBAS.sh. What should I do? 
![Ekran Görüntüsü   (1150)](https://github.com/yumorishita/LiCSBAS/assets/118771093/095ee8ff-011a-4d74-90e8-ab61ca119151) @yumorishita

**Comment by yogen1992** [comment]
Have you used this command?
source ../bashrc_LiCSBAS.sh
