### ISSUE TITLE
Displacement data resolution

### ISSUE THREAD

**Issue by oguzhannysr** [yumorishita/LiCSBAS#319]
Hello @yumorishita , is 50x50 spatial resolution possible for different frames? I saw this site as an example on the COMET page. I want to produce displacement maps with 50x50 spatial resolution with licsbas.

![image](https://github.com/yumorishita/LiCSBAS/assets/53774968/65d06ab2-cf7e-4c88-b901-85b0c7f9dba6)

**Comment by oguzhannysr** [comment]
As far as I understand, licsbas does not provide this.

**Comment by yumorishita** [comment]
You can use SNAP or ISCE2 to prepare the unwrapped data though I am not familiar with them.

**Comment by MIEMESSI** [comment]
Hello Professor, I would like to ask if there is any parameter here that is adjusted for resolution, because my research area is small, and the resolution is very low after amplification

**Comment by yumorishita** [comment]
LiCSBAS cannot derive the result with higher resolution than the input data.
