### ISSUE TITLE
 Gacos download and apply

### ISSUE THREAD

**Issue by alejobeap** [yumorishita/LiCSBAS#32]
Dear

I would like your help with downloading GACOS data for atmospheric correction, I have checked but the page does not work (http://ceg-research.ncl.ac.uk/v2/gacos/) and within the LICSAR folders there is no correction for the area I am processing.

Thank you for your help

Pedro

**Comment by yumorishita** [comment]
I have contacted Chen Yu (https://twitter.com/gacos_newcastle). We have to wait for the server restart.

**Comment by alejobeap** [comment]
Thanks for your help.

**Comment by yumorishita** [comment]
Chen showed me this article:
Newcastle University cyber attack 'to take weeks to fix' 
https://www.bbc.com/news/uk-england-tyne-54047179

**Comment by alejobeap** [comment]
Thanks for your help.

**Comment by yumorishita** [comment]
Finally GACOS website has come back with added new features. 
http://www.gacos.net/
https://twitter.com/GACOS_Newcastle/status/1328414495157477376?s=20
