### ISSUE TITLE
ValueError: keyword grid_b is not recognized

### ISSUE THREAD

**Issue by Indianmedieval** [yumorishita/LiCSBAS#320]
Dear Sir, 

after using the following code (LiCSBAS11_check_unw.py -d GEOCml1clip)

I am getting ValueError: keyword grid_b is not recognized

![WhatsApp Image 2024-01-06 at 18 37 33_ace35d54](https://github.com/yumorishita/LiCSBAS/assets/96385121/a75b26d1-aaca-423f-9c4d-da285467864c)

KINDLY PLEASE HELP me in this error.

Best Regards

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1498886957

**Comment by Indianmedieval** [comment]
Thank you so much Sir
