### ISSUE TITLE
Incomplete images

### ISSUE THREAD

**Issue by Alenhasha** [yumorishita/LiCSBAS#323]
![11](https://github.com/yumorishita/LiCSBAS/assets/117146434/bfbae67e-6cba-46f0-9a0e-c12f01f4cf68)
Hi
Why are some images, like the one below, incomplete?

**Comment by yumorishita** [comment]
It is not because of LiCSBAS but LiCSAR processing.

**Comment by Alenhasha** [comment]
In some frames, more than half of the interferograms have this issue. What do you suggest I should do?
 Thank you.

**Comment by yumorishita** [comment]
@espiritocz Any ideas?

**Comment by Alenhasha** [comment]
Thank you very much.

**Comment by espiritocz** [comment]
hi,

please send us an email, see 'Contact Us' at the bottom of
https://comet.nerc.ac.uk/COMET-LiCS-portal
please state the frame ID and try give details such as period of time of
the incomplete data (maybe this happens only after 12/2021?)
