### ISSUE TITLE
Connection error when running descending analysis

### ISSUE THREAD

**Issue by RoySreeta** [yumorishita/LiCSBAS#325]
Hello, Dr. Yumorishita,
I've tried to run a descending analysis on 2nd FEbruary and the internet connectivity on my device is perfect, but the analysis did not run. I have been trying since today morning as well. DEspite having the internet connectivity on my system, it is not running and shows connectivity error. Is there some issue with LiCSBAS (technical or maintenance related) that is causing this problem?

Warm regards
Sreetama

**Comment by yumorishita** [comment]
Probably the same issue as https://github.com/yumorishita/LiCSBAS/issues/324#issue-2116907205. Please try again.
