### ISSUE TITLE
blank plot without any legends

### ISSUE THREAD

**Issue by stallinbhandari** [yumorishita/LiCSBAS#326]
![image](https://github.com/yumorishita/LiCSBAS/assets/78250553/1b5096d8-b326-4627-94a7-652ab432e69a)
Hello sir!
I am not able to see any plots. Not even the legends or any axes. while running LiCSBAS_plot_ts.py -i TS_GEOCml1GACOSmask/cum_filt.h5 &
but when i save the plot i can see the velocity plot
![Cumulative_Displacement1](https://github.com/yumorishita/LiCSBAS/assets/78250553/76234b30-61b7-4a22-8186-ed04a43c5e8a)

**Comment by yumorishita** [comment]
I have no idea. It is probably because of your environmental setting.
