### ISSUE TITLE
All ifgs are regarded as bad!

### ISSUE THREAD

**Issue by MarcoSal** [yumorishita/LiCSBAS#329]
Greetings,
I have a problem in step11.
When I apply step 04 ("-i GEOCml1_corr_gacos -o GEOCml1_corr_mask_step04 -c 0.2 -r 0:0/0:0"), the next step11 fails reporting "All ifgs are regarded as bad!".
I have tried different parameters but it always rejects them. If I don't apply step04, it works fine.
Can you help me figure out what's wrong?
Thank you

**Comment by yumorishita** [comment]
Maybe all (or most of) the pixels have lower coherence than 0.2 and are masked in step04. Please check the output GEOCml1_corr_mask_step04.

**Comment by MarcoSal** [comment]
I tried raising the threshold from 0.2 to 0.8 but I didn't see any improvements. What parameters do you recommend using in steps 04 and 11? I mean, would it make sense to raise beyond 0.8?

**Comment by yumorishita** [comment]
You need to lower the threshold (e.g., 0.1) to increase the unmasked pixels. Also GEOCml1_corr_mask_step04 must be removed before rerunning because step04 does not overwrite the existing files.

**Comment by MarcoSal** [comment]
I also tried 0.05 but it discards them all anyway.

**Comment by yumorishita** [comment]
Please upload the full log file.

**Comment by MarcoSal** [comment]
the log referring to some particular step?
however, no errors are reported.
I add that, for other data strips, the problem does not exist.

**Comment by yumorishita** [comment]
I cannot investigate further without the full log. If you are not using batch_LiCSBAS.sh, I strongly recommend using it. It automatically generate the full log file.

**Comment by MarcoSal** [comment]
I carry out the processing step by step because I have made changes to the position of the workbooks.
I'll see if I can run the batch.
Thank you
