### ISSUE TITLE
step1-6:hope to add new function

### ISSUE THREAD

**Issue by EllenLee183** [yumorishita/LiCSBAS#33]
When we want to remove the trend term, we can select the far-field area where there is no deformation to fit the trend term, instead of fitting the trend term to the entire preliminary result, so that the deformation signal is lost. Hope you can consider this request.

**Comment by yumorishita** [comment]
Thank you for the feedback. It is a nice idea and could be easily implemented. I will update the script when I have time and let you know.

**Comment by EllenLee183** [comment]
Thanks for your help.

**Comment by yumorishita** [comment]
I have updated the scripts (batch_LiCSBAS.sh and LiCSBAS16_filt_ts.py). Please try using --range[_geo] or --ex_range[_geo] options. Feedback is very welcome.
