### ISSUE TITLE
ValueError: keyword grid_b is not recognized;

### ISSUE THREAD

**Issue by guoluo1999** [yumorishita/LiCSBAS#331]
Hi, everyone! After reading unw and cc data, the script raises value error like this. Could anyone tell me how to solve this problem?![licsbas error](https://github.com/yumorishita/LiCSBAS/assets/137704269/fc8a6425-0470-49ee-90ef-17292dad4aa4)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1498886957
