### ISSUE TITLE
Clarification on Reference Point Usage for Decomposing LOS Results in LiCSBAS

### ISSUE THREAD

**Issue by BahruzAhadov** [yumorishita/LiCSBAS#332]
Hello LiCSBAS Team,

I am currently utilizing the LiCSBAS software for an InSAR time series analysis project and have encountered a conceptual challenge that I hope you could help clarify.
How does LiCSBAS determine or utilize this reference point (or area) when decomposing LOS results into horizontal and vertical displacements? Is there a default setting, or does it require user input to specify this reference point? Where can see that used reference point during decomposition?

**Comment by as1234554321** [comment]
hi sir,
I have decomposed the 2017-2023 data. How do I get the decomposition value for each year?
Do I have to repeat running batch (01-16) every year?

**Comment by yumorishita** [comment]
You can output the velocity for each year by LiCSBAS_cum2vel.py.

**Comment by as1234554321** [comment]
Can the decomposed file be used on cum2vel? py to get points for each year (eg 2017-2020)?

**Comment by yumorishita** [comment]
No.

**Comment by yumorishita** [comment]
Yes.
