### ISSUE TITLE
Different result between ascending and descending

### ISSUE THREAD

**Issue by NabilAttar** [yumorishita/LiCSBAS#334]
Greeting Mr. Yumorishita

I have done to process frame 171A_09587_041313 and 120D_09443_131313 in 105.16/105.36/-5.53/-5.31 geo clip area, but it produces different velocity. In ascending we see that there is an area with up lift and subsidence. But in descending we see there're no area with subsidence, almost all areas experienced uplift. Is my processing wrong? Why does it happen?

Thank you.....

![Ascending](https://github.com/yumorishita/LiCSBAS/assets/155360570/79f32030-f2b3-48d3-ba03-cd2cf5da5d46)
![ascending2](https://github.com/yumorishita/LiCSBAS/assets/155360570/e9dfc73a-f202-4897-b002-f4e2c864face)
![descending](https://github.com/yumorishita/LiCSBAS/assets/155360570/46771a10-ca12-4456-91c8-8b4aa91eb8ad)

**Comment by yumorishita** [comment]
Maybe the time period is different?

**Comment by NabilAttar** [comment]
> Maybe the time period is different?

Yes sir, ascending in 2015 - 2023. Descending 2017 - 2023. does it have any effect?

**Comment by yumorishita** [comment]
I think so. Also, you should check the network and gaps.

**Comment by NabilAttar** [comment]
> I think so. Also, you should check the network and gaps.

in the normal case, should they both have the same velocity? Thank you

**Comment by yumorishita** [comment]
They are never same because the LOS geometry is different, but they should be similar if there is no horizontal component.

**Comment by NabilAttar** [comment]
greeting Mr. Yumorishita

this is network between ascending and descending. i think that descending is bad because infrenquently IFG, Do you have any suggestions regarding processing results that are not similar? thank you

![ascending network13_nobad](https://github.com/yumorishita/LiCSBAS/assets/155360570/1a4e6335-17c4-4273-b007-f7be7fa0bf8a)
![descending network13_nobad](https://github.com/yumorishita/LiCSBAS/assets/155360570/549d375c-901b-40bc-8506-4ac9e3ccc352)

**Comment by yumorishita** [comment]
I suggest using the common time period (Aug 2019 -  May 2022).

**Comment by NabilAttar** [comment]
I have tried time period (Aug 2019 - May 2022) in descending. However, there is still only uplift in the surrounding area. Maybe it's already from the IFG data

**Comment by NabilAttar** [comment]
excuse me sir, sorry for out of topic. I have done ascending and descending processing. but I think the results of descending are quite bad. i have use LiCSBAS_decompose but i think the result of UD is bad caused descending frame. Is it possible to get a UD velocity value just by using ascending? I only need UD and not EW. thank you sir

**Comment by ditafaith** [comment]
Hi @NabilAttar 
If you want to use only 1 orbit, and ensure that horizontal movement very small contribution, then you may extract time series at certain point and divided by cosinus incidence angle. If you want to get an image, may be you can operate [gdal_calc](https://gdal.org/programs/gdal_calc.html) for ascending.tiff file.

**Comment by NabilAttar** [comment]
> Hi @NabilAttar If you want to use only 1 orbit, and ensure that horizontal movement very small contribution, then you may extract time series at certain point and divided by cosinus incidence angle. If you want to get an image, may be you can operate [gdal_calc](https://gdal.org/programs/gdal_calc.html) for ascending.tiff file.

thank you sir, is gdal_calc same like raster calculator in QGIS? so, formula for get velocity upward/vertical direction tiff is only [velocity LOS.tiff / cos(incidence angle] ?? thank you

**Comment by NabilAttar** [comment]
> Hi @NabilAttar 
> If you want to use only 1 orbit, and ensure that horizontal movement very small contribution, then you may extract time series at certain point and divided by cosinus incidence angle. If you want to get an image, may be you can operate [gdal_calc](https://gdal.org/programs/gdal_calc.html) for ascending.tiff file.

excuse me sir, is my statement correct? Thank you

**Comment by yumorishita** [comment]
I think your statement is correct.

**Comment by NabilAttar** [comment]
Thank you sir

**Comment by NabilAttar** [comment]
> ![ascending network13_nobad](https://private-user-images.githubusercontent.com/155360570/309512781-1a4e6335-17c4-4273-b007-f7be7fa0bf8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDk2MTYsIm5iZiI6MTcxNDQ0OTMxNiwicGF0aCI6Ii8xNTUzNjA1NzAvMzA5NTEyNzgxLTFhNGU2MzM1LTE3YzQtNDI3My1iMDA3LWY3YmU3ZmEwYmY4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQwMzU1MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDE2MDQ2N2JkMzBhOGQyZDY2MGI5Zjg0Y2E5OGJjZDg4MjAxNGRlMTJhZDYxM2I5ZWIyYjM4N2I1NDEwYTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dfZfBALfvNhW8Hxgcog9twloicjEnNqCIhaMR8f6QeA) ![descending network13_nobad](https://private-user-images.githubusercontent.com/155360570/309512786-549d375c-901b-40bc-8506-4ac9e3ccc352.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDk2MTYsIm5iZiI6MTcxNDQ0OTMxNiwicGF0aCI6Ii8xNTUzNjA1NzAvMzA5NTEyNzg2LTU0OWQzNzVjLTkwMWItNDBiYy04NTA2LTRhYzllM2NjYzM1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQwMzU1MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGFhMDVmNzEzMjc1Nzc1NjA4ZDg1MGQ2OTQ3NGJlODA2NDc4ODQ5MTc4ZTY3ZGE0NDg4ZTliMjM5YmI0NTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TyMYKXhH8diBtJRMBWMqbvtZ084hY1_7wiwUtuIKT98)

greeting Mr. Yumorishita

I want to ask about ascending and descending baselines which I have uploaded. In ascending use dummy unit (look in left side picture), and descending use Bperp unit (baseline perpendicular). why the results are different? in your paper the network result in Bperp unit, what is dummy? thank you

**Comment by yumorishita** [comment]
If `baselines` file does not contain the values for all dates, the dummy baseline is used because the correct figure cannot be drawn from the incomplete data. Please check the log in step02 to find what date is lacking in `baselines`.

https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/LiCSBAS_lib/LiCSBAS_io_lib.py#L165
https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/bin/LiCSBAS02_ml_prep.py#L371

**Comment by NabilAttar** [comment]
![image](https://github.com/yumorishita/LiCSBAS/assets/155360570/6f96e63d-f96a-4541-90c0-a399145d7a3c)

excuse sir, here is "not baseline found" do you have any suggestions? is it a good idea if i delete 20170814 in GEOC and start batch licsbas from step 02? thank you

**Comment by NabilAttar** [comment]
![image](https://github.com/yumorishita/LiCSBAS/assets/155360570/9b305d41-0403-4ba1-ae71-4c07c012553a)
 in metadata network png on GEOC, baseline 20170814 is avaible

**Comment by yumorishita** [comment]
What is the frame ID?

> is it a good idea if i delete 20170814 in GEOC and start batch licsbas from step 02?

Yes, you will get the correct network figure with non-dummy y-axis.

**Comment by NabilAttar** [comment]
frame ID is 171A_09587_041313

![image](https://github.com/yumorishita/LiCSBAS/assets/155360570/556d682d-69f3-4b96-a81f-755bb605aa79)

i have tried by deleting 20170814 in GEOC and delete GEOCml1. but another IFG without baseline is found. do you have any suggestions? thank you

**Comment by yumorishita** [comment]
This is the baseline file used for the network figure:
https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/171/171A_09587_041313/metadata/baselines

I found some dates have no data in the 3rd column, e.g.,
```
20190512 20170802 -65.0 -648
20190512 20170814  -636
20190512 20170826 -52.0 -624
```
You can manually edit the file and fill the 3rd column, or ask COMET to fix this issue.

**Comment by NabilAttar** [comment]
how to determine the value of the 3rd column? are there any provisions for fill the 3rd column?

**Comment by ditafaith** [comment]
> how to determine the value of the 3rd column? are there any provisions for fill the 3rd column?

You might try to download the images and check it manually using SNAP software. Also, you can check it through Alaska Satellite Portal. It seems you are working on subsidence in Lampung.

**Comment by NabilAttar** [comment]
> > how to determine the value of the 3rd column? are there any provisions for fill the 3rd column?
> 
> You might try to download the images and check it manually using SNAP software. Also, you can check it through Alaska Satellite Portal. It seems you are working on subsidence in Lampung.

yes sir, i have research about this area. also i have visited alaska and check baseline manually. I equated it with baseline data from licsar, the perpendicular baseline difference from the missing third column is only about 3 meters. Thank you for the advice

**Comment by luvkesh5511** [comment]
Dear Prof.,
I had a doubt regarding how t o use a combination of ascending and descending pass interferograms to analyse ground deformation? Does the platform support combining two different passes (Asc and Desc) ? If so, how can we integrate them, should we add two frame ids in line 72: (p01_frame = "129A_xxxxx" "135D_xxxxx") ? Kindly guide.

Thank you

**Comment by yumorishita** [comment]
1. Run LiCSBAS step01-16 for the ascending frame (129A_xxxxx) using batch_LiCSBAS.sh
2. Run LiCSBAS step01-16 for the descending frame (135D_xxxxx) using batch_LiCSBAS.sh
3. Use LiCSBAS_decomposeLOS.py with the input from both ascending and descending
