### ISSUE TITLE
Data that does not appear when visualization of LiCSBAS results

### ISSUE THREAD

**Issue by esykusuma** [yumorishita/LiCSBAS#335]
Greetings Mr. Yumorisitha

I have carried out the LiCSBAS2 process, and was successful in downloading images and other processes, but when I plotted the visualization results from LiCSBAS InSAR, a lot of data spanning years did not appear, after I checked the IFG network the color was red, and I wanted to ask whether the network was unstable. Can it just be omitted and can data that doesn't appear be displayed? please answer sir.

Thank You

Here are the files I meant above, sir

[202403031820batch_LiCSBAS_01_16.zip](https://github.com/yumorishita/LiCSBAS/files/14475374/202403031820batch_LiCSBAS_01_16.zip)
![network13](https://github.com/yumorishita/LiCSBAS/assets/162069760/ccc14601-eefa-4570-b973-94dbd3c4b21b)
![network13_nobad](https://github.com/yumorishita/LiCSBAS/assets/162069760/ade46323-e186-4a30-84b9-5060b45919b1)
![network11_nobad](https://github.com/yumorishita/LiCSBAS/assets/162069760/4713c1f0-fe96-4e2b-ad04-9ccc2fe2c818)
![network12](https://github.com/yumorishita/LiCSBAS/assets/162069760/88200bb5-4c11-4c21-aaea-40141167a268)
![network12_all](https://github.com/yumorishita/LiCSBAS/assets/162069760/1fef310b-3b85-4b64-bf8b-fcb06d7f6a83)
![network12_nobad](https://github.com/yumorishita/LiCSBAS/assets/162069760/f22fe2f3-127c-4064-8420-12c39f3e612c)
![network11](https://github.com/yumorishita/LiCSBAS/assets/162069760/03ee05cd-12a0-468a-af87-739506ad3381)
![network11_all](https://github.com/yumorishita/LiCSBAS/assets/162069760/8e5133bb-daf5-4197-810d-a3c00dd7c45a)
![network13_all](https://github.com/yumorishita/LiCSBAS/assets/162069760/235d1042-b436-4156-a16a-b88a4ed316ca)

**Comment by yumorishita** [comment]
Too many ifgs are discarded in step11 and step12 because of severe decorrelation and unwrap errors. Try changing the parameters for step11 and/or step12.

**Comment by esykusuma** [comment]
Thank you sir for the answer, which parameters in steps 11 and 12 do I need to change? please explain sir

![WhatsApp Image 2024-03-05 at 08 35 09_f69f44a3](https://github.com/yumorishita/LiCSBAS/assets/162069760/ca4c04a9-42a3-4f80-b761-1f5463951a2c)

**Comment by esykusuma** [comment]
This is my problem sir, I set it from 2015 to 2023, but if I plot the results as below, the data for 2015, 2018, 2019, 2022 and 2023 is not there, so what is the solution to my problem below?

![WhatsApp Image 2024-03-05 at 08 43 26_53bbf8ff](https://github.com/yumorishita/LiCSBAS/assets/162069760/4e70fc76-aab7-418b-9a86-3a8f2f191279)

**Comment by yumorishita** [comment]
Discussion about the suitable parameters for a specific case is out of the scope of the issues in this repository. Please carefully read [the LiCSBAS paper](https://doi.org/10.3390/RS12030424), understand the logic, try changing the parameters, and check the result yourself.

**Comment by esykusuma** [comment]
Thank you sir for the explanation, I want to ask regarding the processing of one frame, there is a process that is not completed in step 14, do you have a solution to my problem, sir?

![WhatsApp Image 2024-03-13 at 13 34 44_afa59c64](https://github.com/yumorishita/LiCSBAS/assets/162069760/72ee3416-77b3-413b-a21d-48141d1cf643)

**Comment by yumorishita** [comment]
I have no idea. Maybe resource (memory or storage) limitation?

**Comment by sonyakkk** [comment]
I have finished the processing on frame 143A_08674_131308, the results I get have a complete time series of 2015-2024 but why do I get a small area? even though I clip on "98.32/99.01/2.99/3.97". do you have any suggestions sir?
![WhatsApp Image 2024-03-24 at 15 08 47_34c45584](https://github.com/yumorishita/LiCSBAS/assets/152505924/664a49f1-c81d-43ba-90d1-d8a54319d43b)

**Comment by sonyakkk** [comment]
this is sir
[Uploading 202403241041batch_LiCSBAS_01_16.log…]()

**Comment by yumorishita** [comment]
I cannot download it because the link is `https://github.com/yumorishita/LiCSBAS/issues/335`.

**Comment by yumorishita** [comment]
Also please see mask_ts.png

**Comment by sonyakkk** [comment]
Here's the mask_ts.png, sir
![WhatsApp Image 2024-03-27 at 19 27 13_d341b2e3](https://github.com/yumorishita/LiCSBAS/assets/152505924/67042d2f-f14f-480e-9a97-d0a159b835c2)

**Comment by yumorishita** [comment]
The data actually exists in the southern half and the problem is only in the visualization by LiCSBAS_plot_ts.py. I have no idea about the reason.

**Comment by yumorishita** [comment]
Ah, the cum_filt.h5 includes only the northern half because there is no unmasked pixel before step16 filter. You will find the southern pixels by plotting only cum.h5, i.e., `LiCSBAS_plot_ts.py -i cum.h5`.

**Comment by sonyakkk** [comment]
OK sir, I'll try later
Sorry sir, I want to ask again, I tried reprocessing, but why does it get stuck, even though I have a good signal. Do you have a solution sir?

This stuck has been happening for the past 2 days
![Screenshot 2024-03-27 201037](https://github.com/yumorishita/LiCSBAS/assets/152505924/4419c495-dcc2-4467-a3fc-be1b758763bc)

**Comment by yumorishita** [comment]
Maybe it is because of the COMET server issue. Please try again.
https://github.com/yumorishita/LiCSBAS/issues/303#issuecomment-2012470139

**Comment by esykusuma** [comment]
Excuse me sir, I want to ask why when we clip an area, after it is made into a tif the result when plotted is that the area is small and does not match the area that corresponds to the clip

**Comment by yumorishita** [comment]
Can you show a real example?

**Comment by esykusuma** [comment]
This is the AOI that I want to clip the image to with the coordinates that I adjusted
![After ](https://github.com/yumorishita/LiCSBAS/assets/162069760/22ba03aa-150f-4549-9be5-7c26fc254b07)

This is the result of the LiCSBAS process, which becomes small
![Before Procces](https://github.com/yumorishita/LiCSBAS/assets/162069760/c0d97e4b-a8cf-45b1-ad3d-66f83b4af5f5)

ini log dari hasil tersebut
[202403290025batch_LiCSBAS_02_16.txt](https://github.com/yumorishita/LiCSBAS/files/14809811/202403290025batch_LiCSBAS_02_16.txt)

**Comment by yumorishita** [comment]
It is because most of the pixels were masked in step15 and lost in step16. Similat to this: https://github.com/yumorishita/LiCSBAS/issues/335#issuecomment-2022670228

**Comment by esykusuma** [comment]
I want to ask, sir, how do I create 3D values in this LICSBAS process, such as separate EW and UD, is there a way to get 3D?

**Comment by yumorishita** [comment]
We cannot get 3D from 1 or 2 LOSs.

**Comment by esykusuma** [comment]
Excuse me sir, I want to ask 
how many steps I can set the parameters to filter COH values, I have tried several methods but have not succeeded can you help me sir

**Comment by yumorishita** [comment]
You can set the coherence threshold in step04, step11, and step15. However, coherence is generally not a critical parameter in LiCSBAS.
