### ISSUE TITLE
How do I process the whole 3 swaths in LiCSBAS?

### ISSUE THREAD

**Issue by shivamthescienceguy** [yumorishita/LiCSBAS#336]
Greetings,
If I want to process all the 3 swaths in the licsbas for velocity and time series. How do I change the batch file if I dont want to process a square shaped area but the whole swath?
p05_clip_range_geo= # e.g. 130.11/131.12/34.34/34.6 (in deg)
what should be written in this line to avoid a small region but the whole Sentinel scene.

**Comment by yumorishita** [comment]
By default (`do05op_clip="n"`), the step05 clip does not run and the whole area is processed.
https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/batch_LiCSBAS.sh#L35
