### ISSUE TITLE
AttributeError: module 'os' has no attribute 'sched_getaffinity'

### ISSUE THREAD

**Issue by bvicic** [yumorishita/LiCSBAS#34]
Hi!

I tried to make a quick test if the software works. After downloading the data (running ./batch_LiCSBAS.sh) I get this Error:

> Traceback (most recent call last):
>   File "/Users/bvicic/Documents/Seismology/Work/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 444, in <module>
>     sys.exit(main())
>   File "/Users/bvicic/Documents/Seismology/Work/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 119, in main
>     n_para = len(os.sched_getaffinity(0))
> AttributeError: module 'os' has no attribute 'sched_getaffinity'

From what I understand, this is a OS related issue (https://stackoverflow.com/questions/42538153/python-3-6-0-os-module-does-not-have-sched-getaffinity-method)

Is there a work around to run this on macOS/Windows?

Thanks!

**Comment by yumorishita** [comment]
What is your Python version?  The sched_getaffinity should be available in python>=3.3.

https://docs.python.org/3/library/os.html#os.sched_getaffinity

**Comment by bvicic** [comment]
> Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
> [Clang 10.0.0 ] :: Anaconda, Inc. on darwin

**Comment by yumorishita** [comment]
Are you working on Mac or Windows?

**Comment by bvicic** [comment]
Exactly, I am running maxOS, this is why I am asking if there is a workaround. Thanks

**Comment by yumorishita** [comment]
Can you try editing the line below in LiCSBAS02_ml_prep.py
https://github.com/yumorishita/LiCSBAS/blob/8c18dd54aa32eb6a8656a78896b27e3785bdee7d/bin/LiCSBAS02_ml_prep.py#L119
to `    n_para = multi.cpu_count()`, and re-run the batch_LiCSBAS.sh?

If it works, I will update the scripts (of other steps as well).

**Comment by bvicic** [comment]
This works yeah! thanks!
But now I hit this problem:

```
LiCSBAS02_ml_prep.py ver1.7 20201020 Y. Morishita
LiCSBAS02_ml_prep.py -i GEOC -n 1

Create E.geo
Traceback (most recent call last):
  File "/Users/bvicic/anaconda3/envs/licsbas/lib/python3.8/site-packages/osgeo/gdal_array.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_gdal_array', [dirname(__file__)])
  File "/Users/bvicic/anaconda3/envs/licsbas/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_gdal_array'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bvicic/Documents/Seismology/Work/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 444, in <module>
    sys.exit(main())
  File "/Users/bvicic/Documents/Seismology/Work/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 195, in main
    data = gdal.Open(enutif).ReadAsArray()
  File "/Users/bvicic/anaconda3/envs/licsbas/lib/python3.8/site-packages/osgeo/gdal.py", line 2084, in ReadAsArray
    from . import gdalnumeric
  File "/Users/bvicic/anaconda3/envs/licsbas/lib/python3.8/site-packages/osgeo/gdalnumeric.py", line 1, in <module>
    from osgeo.gdal_array import *
  File "/Users/bvicic/anaconda3/envs/licsbas/lib/python3.8/site-packages/osgeo/gdal_array.py", line 28, in <module>
    _gdal_array = swig_import_helper()
  File "/Users/bvicic/anaconda3/envs/licsbas/lib/python3.8/site-packages/osgeo/gdal_array.py", line 20, in swig_import_helper
    import _gdal_array
ModuleNotFoundError: No module named '_gdal_array'
```

I installed the LiCSBAS with:
conda env create -f LiCSBAS.yml

**Comment by yumorishita** [comment]
It is strange. Perhaps your python version might be too new for gdal. Can you try installing LiCSBAS in a slightly old python version (e.g. 3.7)?

**Comment by bvicic** [comment]
sure thing, will test this in next days!
cheers

**Comment by bvicic** [comment]
I retried the code using python 3.7. After changing n_para = multi.cpu_count() in all the scripts where this pops out, the code works without any problems!

Thanks!

**Comment by yumorishita** [comment]
I have updated the scripts to use "multi.cpu_count()". Thank you for the feedback.
