### ISSUE TITLE
error while running batch.sh script

### ISSUE THREAD

**Issue by shivamthescienceguy** [yumorishita/LiCSBAS#340]
While processing for 3 months of data for testing I got this error.
What could be the reason for this one?
![image](https://github.com/yumorishita/LiCSBAS/assets/88940973/b56cddce-c2f4-4d81-b730-5e4d8f70011c)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/307#issuecomment-1798388036
