### ISSUE TITLE
#11：LiCSBAS11_check_unw.py

### ISSUE THREAD

**Issue by keepfighting666** [yumorishita/LiCSBAS#341]
Dear Prof.Yumorishita,
When I run LiCSBAS11_check_unw.py, something goes wrong. I just skipped step04:mask unwrapped data and step05:clip unwrapped data. Here's the problem.
What can I do to fix it?
![2024-03-16_18-15](https://github.com/yumorishita/LiCSBAS/assets/86222061/fe945e6c-c87e-4688-8b04-a0b657f79072)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1498886957
