### ISSUE TITLE
Regarding the obvious seams in the result file

### ISSUE THREAD

**Issue by ghost** [yumorishita/LiCSBAS#343]
Dear Doctor yumorishita, Hello, when I was dealing with frame 099A _ 06214 _ 131313, there was an obvious seam problem in my result file. I have dealt with it twice, but there is still the same problem. What is the cause?

**Comment by hxwt1987** [comment]
![n_unw](https://github.com/yumorishita/LiCSBAS/assets/52560947/bbc9c702-f7b6-4abe-b46d-a3a63aae681f)
![vel](https://github.com/yumorishita/LiCSBAS/assets/52560947/3d4e00bd-5669-4b04-a1df-aaf2982e4783)

**Comment by yumorishita** [comment]
The LiCSAR products you used include some incomplete data. Please contact COMET.
