### ISSUE TITLE
Feature-related calculation concepts in LiCSBAS

### ISSUE THREAD

**Issue by NabilAttar** [yumorishita/LiCSBAS#344]
Greeting Mr. Yumorishita

I want to learn the concept of calculating several features in LICSBAS (for example LICSBAS_decompose). Maybe there is a journal or note that discusses processing and calculation concepts related to LiCSBAS_dekompose which converts velocity to 1D and 2.5D? thank you

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/bin/LiCSBAS_decomposeLOS.py#L8-L9

**Comment by NabilAttar** [comment]
thank youu sir

**Comment by NabilAttar** [comment]
excuse me sir, I'd like to ask. Is small baseline inversion in LiCSBAS is same like small baseline subset in several studies?

**Comment by yumorishita** [comment]
Not completely same. Please read the LiCSBAS paper: https://www.mdpi.com/2072-4292/12/3/424#sec2dot4dot3-remotesensing-12-00424
