### ISSUE TITLE
implementation of my own interfrograms insead of LiCSAR Comet interfrograms

### ISSUE THREAD

**Issue by soroushyasini** [yumorishita/LiCSBAS#345]
hi mr. morishita
as I am going to do a long-term time-series analysis (~2000-2023) i need to make interfrograms form various sensors ( e.g. Envisat Asar, sentinel-1 etc. ) . currently i am using GMTSAR to make interferograms and their Coherence file and as LiCSBAS has many useful tools to make results more accurate, i want to use it for the rest of the process.
the thing is, can i simply rename interferograms and coherence files and put the files into directories  just like LiCSBAS default file structure? and if the answer is yes, please provide me with additional information to do so if necessary.

**Comment by faraksoch1881** [comment]
> hi mr. morishita as I am going to do a long-term time-series analysis (~2000-2023) i need to make interfrograms form various sensors ( e.g. Envisat Asar, sentinel-1 etc. ) . currently i am using GMTSAR to make interferograms and their Coherence file and as LiCSBAS has many useful tools to make results more accurate, i want to use it for the rest of the process. the thing is, can i simply rename interferograms and coherence files and put the files into directories just like LiCSBAS default file structure? and if the answer is yes, please provide me with additional information to do so if necessary.

Hi @soroushyasini , I have assumed that you have successfully integrated your own interferograms to LiCSBAS. I am looking forward to do same. But I assume you will also need the following files along with coherence and unwrapped raster files. 
-filename.geo.E.tif
-filename.geo.N.tif
-filename.geo.U.tif
-filename.geo.hgt.tif and filename.geo.mli.tif

were you able to produce these files and can you guide me how to perform this to create this five files? @yumorishita
