### ISSUE TITLE
Overlapping Issue

### ISSUE THREAD

**Issue by sajid-zaman** [yumorishita/LiCSBAS#346]
I have an issue related to the overlapping between the frames; when I merge the frames, their values change. Is there any way in LICSBAS we can process different frames with each other along one track? or anyone has a solution, please, help me.
[ascending_LOS.docx](https://github.com/yumorishita/LiCSBAS/files/15007002/ascending_LOS.docx)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1937563971
