### ISSUE TITLE
coherence meaning

### ISSUE THREAD

**Issue by maulanaheno** [yumorishita/LiCSBAS#347]
what the difference between these three coherence??

p04_mask_coh_thre=""	# e.g. 0.2
p11_coh_thre=""	# default: 0.05
p15_coh_thre=""	# default: 0.05

**Comment by yumorishita** [comment]
- p04_mask_coh_thre="" # e.g. 0.2

Pixels whose average coherence among all IFGs is lower than that are masked in step04.

- p11_coh_thre="" # default: 0.05

IFGs whose average coherence among all pixels of the IFG is lower than that are dropped in step11.

- p15_coh_thre="" # default: 0.05

Pixels whose average coherence among all IFGs is lower than that are masked in step15 (similar to step04).
