### ISSUE TITLE
How to splice data after different Frames are processed in large areas, such as vel

### ISSUE THREAD

**Issue by wangtao11987** [yumorishita/LiCSBAS#349]
Hello, Dr. Yumorishita, I processed the data of a large watershed, which was designed to 7 Frames of data. Now I need to splice the result file, such as vel, and crop out the position I need. How can I splice perfectly and use the same color ribbon to represent the deformation of this position?
![Uploading 20240426224134.png…]()

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/24#issuecomment-652771363
