### ISSUE TITLE
LiCSBAS12_loop_closure.py Killed

### ISSUE THREAD

**Issue by PeymanPython** [yumorishita/LiCSBAS#350]
Dear Morishita,
I have 8000 ifgs (SR=30m) and when I run the step 1-2 (Loop Closure) running program is immediately killed, as you can see below;
<img width="192" alt="111" src="https://github.com/yumorishita/LiCSBAS/assets/55481769/863b05f6-1b9f-4a46-aa60-f16998e29d3b">

As far as I know, it's happened owing to the Memo-Size/RAM of the system, I'm wondering if there is a way to tackle that issue. Here is my system config:
- RAM 32
- Processor: 13th Gen Intel(R) Core(TM) i9-13900HX   2.20 GHz
- Memory: 2TB SSD

**Comment by yumorishita** [comment]
Step1-2 does not require such a large memory (at least at the killed timing). I have no idea.
You can try
- large nlook
- crop by step05
- decrease ifgs

or please upload the full log.

**Comment by PeymanPython** [comment]
Many Thanks for your prompt reply...

**Comment by PeymanPython** [comment]
Dear morishita,
I already have clipped based on my study area and is not too large area, and for step 0-2 I used nlook=1 because I need high precision results. Moreover, the number of my connections is differen e.g., from 15 connection to 53...
Do you have any idea about the nlook parameter? which nlook value does not degrade the resolusion and exactness? 
Does high connection number (long temporal baseline) heps us to get better results in urban and rock-outcrop area?

**Comment by yumorishita** [comment]
> Do you have any idea about the nlook parameter? which nlook value does not degrade the resolusion and exactness?

I just suggest trying a large nlook to confirm if it works or not. Not for the final result.

> Does high connection number (long temporal baseline) heps us to get better results in urban and rock-outcrop area?

I don't think so. You can reduce the number of connections if the AOI is urban or rock area.

If you show me the full log (using batch_LiCSBAS.sh), I might be able to find the root cause.
