### ISSUE TITLE
Starting from step 11

### ISSUE THREAD

**Issue by Bekir3343** [yumorishita/LiCSBAS#351]
Hello, I have been using your program with pleasure for a while. However, I am facing a problem: I am working with Batch Processing and the program may get stuck due to the 13th or 16th field width. When I restart, it starts again from step 11. Do I have an option to start directly from step 13 or 16? If so, how can I use it? I would appreciate it if you could help me.

**Comment by yumorishita** [comment]
You can set the start step here:
https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/batch_LiCSBAS.sh#L19

**Comment by Bekir3343** [comment]
Thank you very much for your quick response. I tried it and it worked.
