### ISSUE TITLE
OverflowError: cannot serialize a bytes object larger than 4 GiB

### ISSUE THREAD

**Issue by xbdqs** [yumorishita/LiCSBAS#352]
Dear Morishita,
When I run the 1-6 step, there ia a issue.

The detailed log file is attached.

[202405081300back-batch_LiCSBAS_16_16.log](https://github.com/yumorishita/LiCSBAS/files/15244352/202405081300back-batch_LiCSBAS_16_16.log)

**Comment by yumorishita** [comment]
I have never encounterd such a error, but please try setting 1 here
https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/batch_LiCSBAS.sh#L111

**Comment by xbdqs** [comment]
Hi, Morishita,
Thank you for your suggestion, bu it still report this error when I chang the parameter, p16_n_para to 1, 2. 
I will try to solve other possible error reasons.
Thnks a lot for your advice.

**Comment by yumorishita** [comment]
Can you show me the error log when you set `p16_n_para="1"`?
It should be different from the previous one because line 437 where the error occurred is not executed with `p16_n_para="1"`.
