### ISSUE TITLE
No clip

### ISSUE THREAD

**Issue by Bekir3343** [yumorishita/LiCSBAS#355]
Hello, I want to watch a large area without clipping. The process continues smoothly until step 16. However, at step 16, the process is suddenly interrupted.

[202405090742batch_LiCSBAS_1_16.log](https://github.com/yumorishita/LiCSBAS/files/15265135/202405090742batch_LiCSBAS_1_16.log)

The log file is as attached. Also, when I checked the files, I saw that files with filt extension were not produced in the results section. I'll be happy if you can help me

**Comment by Bekir3343** [comment]
Also, when I want to see the results, I get an error like this:
![1](https://github.com/yumorishita/LiCSBAS/assets/168960134/c7ca3d08-3455-4713-a668-4df9b3bda76f)

**Comment by yumorishita** [comment]
Maybe the file size is too large to process in your machine. You need to 
- clip the area
- increase nlook
- use more high-spec machine

**Comment by Bekir3343** [comment]
Thank you, I will try again by changing the nlook value.

**Comment by Bekir3343** [comment]
As you said, it worked when I increased the NLOOK value. I think at the last stage the RAM is not enough.
