### ISSUE TITLE
gnss

### ISSUE THREAD

**Issue by minaprgal** [yumorishita/LiCSBAS#356]
Hello, thank you for your good program
I wanted to ask, how did you visualize the gnss data in line with los?
My Insar displacement data is correct.
But when I visualize the gnss data, it is not the same as your gnss graphs.

**Comment by minaprgal** [comment]
I plotted the gnss displacement vector onto ENU obtained from LiCSBAS_flt2geotiff.py -i N.geo -p EQA.dem_par and then multiplied the insar displacement into ENU and compared.

**Comment by yumorishita** [comment]
https://groups.google.com/g/mintpy/c/etKnhodR4ZI
https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9622216
http://doris.tudelft.nl/Literature/catalao11.pdf
