### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by ajisugiantoro123** [yumorishita/LiCSBAS#357]
LiCSBAS01_get_geotiff.py ver1.6.4 20230215 Y. Morishita
LiCSBAS01_get_geotiff.py -f 142A_09168_080913 -s 20230223 -e 20240626 --get_gacos

Frame ID is 142A_09168_080913

Download 142A_09168_080913.geo.E.tif
    ConnectionError for 142A_09168_080913.geo.E.tif in 1th try
    ConnectionError for 142A_09168_080913.geo.E.tif in 2th try
    ConnectionError for 142A_09168_080913.geo.E.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/142/142A_09168_080913/metadata/142A_09168_080913.geo.E.tif
Download 142A_09168_080913.geo.N.tif
    ConnectionError for 142A_09168_080913.geo.N.tif in 1th try
    ConnectionError for 142A_09168_080913.geo.N.tif in 2th try
    ConnectionError for 142A_09168_080913.geo.N.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/142/142A_09168_080913/metadata/142A_09168_080913.geo.N.tif
Download 142A_09168_080913.geo.U.tif
    ConnectionError for 142A_09168_080913.geo.U.tif in 1th try
    ConnectionError for 142A_09168_080913.geo.U.tif in 2th try
    ConnectionError for 142A_09168_080913.geo.U.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/142/142A_09168_080913/metadata/142A_09168_080913.geo.U.tif
Download 142A_09168_080913.geo.hgt.tif
    ConnectionError for 142A_09168_080913.geo.hgt.tif in 1th try
    ConnectionError for 142A_09168_080913.geo.hgt.tif in 2th try
    ConnectionError for 142A_09168_080913.geo.hgt.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/142/142A_09168_080913/metadata/142A_09168_080913.geo.hgt.tif

Hello, Prof. I've tried several times and always encountered an error like this. Maybe something an error with the link download (website LiCSAR), Prof? Thank you

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS2/issues/50#issuecomment-2114657085
