### ISSUE TITLE
Missing cum_filt.h5  file and only cum.h5 exits. 

### ISSUE THREAD

**Issue by faraksoch1881** [yumorishita/LiCSBAS#359]
Hi Yu Morishita,

1) I used the batch processing script for processing. after it was finished I could only find cum.h5 file inside the folder. what process did i do wrong? 

2) when doing batch processing , does it take ascending or descending interferograms?

3) Also how to find the LOS and flight direction ?

4) How to conver the velocity to EW, NS and vertical displacement. Also i cannot move the black dot which is already in map.  whenever i click anywhere i cannot generate the time series on second image. Only when i draw a region, it gives me time series. what could be wrong?

![_Cumulative_Displacement](https://github.com/yumorishita/LiCSBAS/assets/26498290/378ef82d-491b-4885-ad4d-c56a7d583717)
![Time-series](https://github.com/yumorishita/LiCSBAS/assets/26498290/5063f326-6c5b-498b-9476-80fdfd0dbd91)

**Comment by yumorishita** [comment]
> I used the batch processing script for processing. after it was finished I could only find cum.h5 file inside the folder. what process did i do wrong?

Please show me the full log.

> when doing batch processing , does it take ascending or descending interferograms?

It depends on the frame you choose. Your result looks ascending.

> Also how to find the LOS and flight direction ?

GEOCml*/[ENU].geo contain LOS information as unit vectors.

> How to conver the velocity to EW, NS and vertical displacement. Also i cannot move the black dot which is already in map. whenever i click anywhere i cannot generate the time series on second image. Only when i draw a region, it gives me time series. what could be wrong?

We cannot convert a single LOS to 3D.
Please double-click to select a point as written in the left top of the window.

**Comment by faraksoch1881** [comment]
Thank you for your kind reply. I wanted to compare GNSS time series and InSAR time series. I obtained the GNSS time series from NGSS website with 'NS', 'EW' and 'UD' displacement and I found out that I need to convert the GNSS  displacement to LOS using

LOS = D(NS)sin(θ) cos(α) + D(EW)sin(θ) sin(α)  + D(UD)cos(θ)

where
D(NS) = displacement in NS of GNSS
D(EW) = displacement in EW of GNSS
D(UD) = displacement in UD of GNSS

and θ is the incidence angle and α is the azimuthal angle. where can i find α and θ ? My aim is to find the subsidence rate at my study area....what is best way to find subsidence rate from LOS velocity ?

**Comment by yumorishita** [comment]
GEOCml*/E.geo, N.geo, and U.geo are the unit vectors. You can compute LOS by D(NS)*N.geo+D(EW)*E.geo+D(UD)*U.geo.

**Comment by faraksoch1881** [comment]
It should be very basics and i might sound very stupid. But how can I read N.geo, E.geo and U.geo file? the GPS data file is in csv format with four column 'Date' , 'NS', 'EW' and 'UD'. I tried to open .geo format with QGIS both vector and raster but it is is not opening giving me error as not supported raster data source.

**Comment by yumorishita** [comment]
You need to convert the float file (*.geo) to GeoTIFF using LiCSBAS_flt2geotiff.py.

**Comment by blueyeti1994** [comment]
I am currently using sample to learn more about LiCSBAS before i actually do processing and the sample doesn't appear to contain N.geo, E.geo and U.geo file in it [ LiCSBAS_sample_CF.tar.gz ](https://raw.githubusercontent.com/wiki/yumorishita/LiCSBAS/sample/LiCSBAS_sample_CF.tar.gz), so it would be helpful if these could be provided with sample. 

and next is that i earlier i used batch script to process one of my study area and when i shared the output with others, i receive a comment that 'obital ramps' might not have been removed. Is it true ? isn't the batch script should remove it? if not how can i remove it? following is my output
![443717595_7385976258191953_4845803462716077608_n](https://github.com/yumorishita/LiCSBAS/assets/170682504/5075257e-072f-429d-afad-f7351d6237ee)

**Comment by yumorishita** [comment]
You can create the E/N/U.geo for the sample by following this instruction: https://github.com/yumorishita/LiCSBAS/wiki/2_0_workflow#2-running-licsbas--quick-start

By default, LiCSBAS does not apply deramping because the orbital and ionospheric ramp is generally very small in Sentinel-1. You can activate deramping here:
https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/batch_LiCSBAS.sh#L62

**Comment by blueyeti1994** [comment]
> You can create the E/N/U.geo for the sample by following this instruction: https://github.com/yumorishita/LiCSBAS/wiki/2_0_workflow#2-running-licsbas--quick-start
> 
> By default, LiCSBAS does not apply deramping because the orbital and ionospheric ramp is generally very small in Sentinel-1. You can activate deramping here:
> 
> https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/batch_LiCSBAS.sh#L62

It appears that to create E/N/U.geo file, instead of downloading the results provided into zip format , i will need to run the batchscript from and start from first step. It will take some time...I'll comment if i get any errors. Thank you for all your help.

**Comment by faraksoch1881** [comment]
> LiCSBAS_flt2geotiff.py.

Thank you for your comments Prof. Yu Morishita, I applied  LiCSBAS_flt2geotiff.py to convert N.geo file to raster file and used QGIS to open the file. If I have a GPS station in study area, do I have to use the pixel value of raster file using same coordinates of GNSS station and multiply that with  D(NS) in following formula?

 D(NS)*N.geo+D(EW)*E.geo+D(UD)*U.geo.

Here is illustration, Using LiCSBAS_flt2geotiff.py. to convert N.geo >N.geo.tif and importing it into QGIS

![one_](https://github.com/yumorishita/LiCSBAS/assets/26498290/690f625b-9dde-4597-b7c0-aaee4c17596c)

Then using pixel value of N.geo.tif to multiply with North displacement of GNSS station
![two_](https://github.com/yumorishita/LiCSBAS/assets/26498290/4a049993-6b32-45c3-aa70-676861a1e65c)

and repeat same with U.geo and E.geo and finally using summation get the LOS of 3D GNSS displacement. Am I in the right direction  Professor ?

**Comment by yumorishita** [comment]
Yes, I think you are right.

**Comment by MIEMESSI** [comment]
How to solve this problem
module 'numpy' has no attribute 'asscalar'
![image](https://github.com/user-attachments/assets/b11c2fb9-4eef-47ac-a130-435072cf5d7e)

**Comment by yumorishita** [comment]
https://github.com/astropy/astropy/issues/15075
