### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by sazzath** [yumorishita/LiCSBAS#36]
For display the derived time series and velocity: I applied this command 

LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &
![Screenshot from 2020-11-12 16-48-41](https://user-images.githubusercontent.com/72601348/99377740-dc531480-28c6-11eb-8fc7-eb41e09a6b8e.png)

Unfortunately I couldn't Found

No TS_GEOCml1clip/cum_filt.h5 found!

**Comment by yumorishita** [comment]
Can you upload the log file in the log directory?

**Comment by sazzath** [comment]
In your PDF its told that "all the steps will run, and GEOC, GEOCml1, GEOCml1clip, TS_GEOCml1clip and log directories (~16 GB in total) will be created" 
But after giving this command: chmod 764 batch_LiCSBAS_sample_CF.sh 
                                                 ./batch_LiCSBAS_sample_CF.sh

I found only GEOC and LOG Directory , but this 3 directory : GEOCml1, GEOCml1clip, TS_GEOCml1clip is not found. 
My team viewer ID is : 645 263 735 
pass: z4fd82
Whatsapp: +352661315657
please help me out !! 

![Screenshot from 2020-11-17 14-30-24](https://user-images.githubusercontent.com/72601348/99395989-7c1d9c00-28e1-11eb-81bb-cf8c4bf3916f.png)

**Comment by yumorishita** [comment]
I cannot help you from this very limited information. Can you show me all commands and logs you ran?

**Comment by sazzath** [comment]
My frame ID: 087A_04904_121313
I Edit batch_LiCSBAS.sh and put the frame ID inside the File.
Then I run it by this command: 
chmod 764 batch_LiCSBAS.sh 
./batch_LiCSBAS.sh 

Its download the log and GEOC
I attached the log File please find it in the attachment.

[202011171518batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/5554213/202011171518batch_LiCSBAS_01_16.log)

**Comment by sazzath** [comment]
I couldn't find this directory 

GEOCml1, GEOCml1clip, TS_GEOCml1clip 

I got only the directory GEOC and LOG

This is the problem ? 

even I run this with your file batch_LiCSBAS_sample_CF.sh

**Comment by yumorishita** [comment]
I realised that there is a bug in the codes. I will try to fix it and update. Just a moment please.

**Comment by yumorishita** [comment]
I have updated the codes. Please update your installed LiCSBAS module by git pull or downloading again, and try re-running. It should work.

**Comment by sazzath** [comment]
Yes i got this skipped directory now, But I couldn't show the display the derived time series and velocity.

Check the screenshot please !  
![image](https://user-images.githubusercontent.com/72601348/99520913-0292b600-2994-11eb-9549-7cebcd3b6e46.png)

**Comment by yumorishita** [comment]
Screenshots have too little information to identify the error source. Please upload the log file every time you report a issue.

**Comment by sazzath** [comment]
[202011181240batch_LiCSBAS_sample_CF_01_16.log](https://github.com/yumorishita/LiCSBAS/files/5560019/202011181240batch_LiCSBAS_sample_CF_01_16.log)

**Comment by yumorishita** [comment]
The processing seems to be successfully done. Please show me the output of `ls -l` and `ls -l TS_GEOCml1clip` commands.

**Comment by sazzath** [comment]
the output of ls -l and ls -l TS_GEOCml1clip commands.

![image](https://user-images.githubusercontent.com/72601348/99535248-eea57f00-29a8-11eb-934e-106d4df42c65.png)

**Comment by yumorishita** [comment]
Does a command `LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 -r 0:0/0:0 &` work?

**Comment by yumorishita** [comment]
In the two previous screen shot, you ran the command in `~/SAM/LiCSBAS`, while the previous one is in `~/SAM/LiCSBAS/124D_04854_171313`. The `LiCSBAS_plot_ts.py` should be run in `~/SAM/LiCSBAS/124D_04854_171313`.

**Comment by sazzath** [comment]
Yes Sir , Its Works.. Thanks a lot 

Another problem I got I select the other Frame ID : 087A_04904_121313
Problem is: For this frame ID , If I run the batch File I couldn't  get the TS_GEOCml1clip Directory 


[202011181442batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/5560595/202011181442batch_LiCSBAS_01_16.log)

![image](https://user-images.githubusercontent.com/72601348/99541972-c706e480-29b1-11eb-9cbd-54dcce8b2b7a.png)

**Comment by sazzath** [comment]
OMG 

[202011181633batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/5561061/202011181633batch_LiCSBAS_01_16.log)
![image](https://user-images.githubusercontent.com/72601348/99551324-fc183480-29bb-11eb-91b6-28765c835dd5.png)

**Comment by yumorishita** [comment]
First you must run `source <your path>/bashrc_LiCSBAS.sh`. I would recommend insert the line into `~/.bashrc`.

The error for 087A_04904_121313 in step0-5 is because the data area is 31.4113889/34.9463861/39.6532243/42.2822222 but you indicated 14.03/14.22/40.78/40.90 which is outside of the area. The longitude must be between 31.4113889/34.9463861.

**Comment by yumorishita** [comment]
It seems that the problem has been solved. I close this issue.
