### ISSUE TITLE
Few Basic Questions

### ISSUE THREAD

**Issue by blueyeti1994** [yumorishita/LiCSBAS#360]
Hi I am very beginner on **LICSBAS**. I downloaded the sample result of region 'Campi Flegrei from September 2016 to May 2018.' provided on the page to begin with. Here are few questions i have

**1. How to convert to kmz file ?**

_What I tried_
I ran 'LiCSBAS_plot_ts.py -i cum_filt.h5 &^C' and I tried to save both from displacement and time series plot in .tif format. as vel.tif and time.tif then i ran the code

'LiCSBAS_disp_img.py -i time.tif --kmz mykmz'

it gave me ERROR: ERROR: time.tif has multiple bands and cannot be displayed.

Also i ran ''LiCSBAS_disp_img.py -i vel.tif --kmz mykmz' and again i ran into problem

it gave me ERROR: ERROR: vel.tif has multiple bands and cannot be displayed.

so, which image i need to select as input parameter in **image_file** in following code

LiCSBAS_disp_img.py -i image_file -p par_file [-c cmap] [--cmin float]
  [--cmax float] [--auto_crange float] [--n_color int] [--cycle float]
  [--nodata float] [--bigendian] [--png pngname] [--kmz kmzname]

**2. If my study area contain the GNSS station, i can get the NS, EW and UD displacement from that station. Using the lat and long of that GNSS station, if i left click on the velocity plot from LICSBAS will that give me same UD displacement ? what is the best way to compare the velocity from time series and GNSS ? i want to compare UD from GNSS and time series from InSAR generated by LICSBAS.** 

_what i tried_

I noticed the area in example has GNSS station in 
Latitude: 40.834 degrees
Longitude: 14.099 degrees

and using UNAVCO website i was able to get the displacement map (which is in the left of figure). using the below code, i exported the LOS velocities in text file as disp.txt and using excel i plotted the time series (on the right) but the output i received it doesn't match with any of the displacement map in NW, EW or UD displacement (in the left)
![displacement](https://github.com/yumorishita/LiCSBAS/assets/170682504/33a25b9e-ff2c-4604-938a-014812b27bd9)

**3. In the output image, i didn't see the arrow pointing flight direction or LOS velocity direction. where can i find it in example '/LiCSBAS_sample_CF.tar.gz' file?**

and Thank you for your time and support.

**Comment by yumorishita** [comment]
1. You must create the data GeoTIFF by LiCSBAS_flt2geotiff.py, not image tiff by LiCSBAS_plot_ts.py, as the input for LiCSBAS_disp_img.py.
2. Generally we project GNSS 3D displacement into LOS and compare it with InSAR LOS displacement. You must set the same reference for both GNSS and InSAR because both are relative displacements.
3. What do you mean by "the output image"

**Comment by blueyeti1994** [comment]
Thank you for your kind reply. I will look and go through solutions you suggested. For 'GNSS 3D displacement' and 'set up reference for both GNSS and InSAR ' can you guide me through any resource online ? I am familiar with NS, UD and EW displacement so far from GNSS but 'GNSS 3D displacement ' is new term for me. 

For third question, 'the output image' reference is the displacement plot from LiCSBAS output below' (left) is original output and my expected output (right). The arrow of LOS and flight direction is assumed one. where can i find that information to draw the vectors?
![adf](https://github.com/yumorishita/LiCSBAS/assets/170682504/eeb3ac4e-0b0a-4c0a-874b-8d46d7ef680b)

and thank you so much for creating LiCSBAS.

**Comment by yumorishita** [comment]
GNSS 3D displacement means the NS, UD and EW displacement.
LiCSBAS has no function to plot such an arrow.

**Comment by blueyeti1994** [comment]
Thank you for your kind reply. For arrow, this is the assumed one, I wanted to know where can i find information on flight direction or LOS direction so that i could use this information to make such arrows over my images later ?

**Comment by yumorishita** [comment]
The flight direction can be found in the frame ID (4th character). For example, 124D_04854_171313 is descending.

You should set the common reference for both GNSS and LiCSBAS, e.g., by selecting a GNSS point existing in the LiCSBAS result area.

**Comment by blueyeti1994** [comment]
Thank you yumorishita for your reply. So what i understand is 

1. Find GPS station in LiCSBAS result area. 
2. Project GNSS 3D displacement into LOS
3. Using same lat and lon for GPS station, create a time series in LiCSBAS also
4. Find a offset between GPS and LiCSBAS in LOS displacement using same date and time. 
5. Adjust the entire LiCSBAS time serie from anyother coordinates using same offset. 

is this correct approach to have common reference frame for both and compare data?

**Comment by yumorishita** [comment]
You should convert the float file (*.geo) to GeoTIFF using LiCSBAS_flt2geotiff.py.
Your approach makes sense.

**Comment by blueyeti1994** [comment]
Looking at the documentation for Quick start, GACOS is optioal and turned off by default. So when i select any frame, i see there is percentage written next to GACOS..what does that percentage mean? 
<img width="254" alt="Screenshot 2024-05-27 155904" src="https://github.com/yumorishita/LiCSBAS/assets/170682504/3ec28fa7-df60-42d0-986c-a7996a762134">

**Comment by yumorishita** [comment]
I am not sure because it is out of LiCSBAS, but I guess it is [GACOS available dates]/[total dates].

**Comment by blueyeti1994** [comment]
> Thank you yumorishita for your reply.
> 
> how to read N.geo, E.geo or U.geo file ? is there command in LiCSBAS like **'LiCSBAS_cum2tstxt.py'?** I tried with notepad but it there are non readable characters in this file.
> 
> and lastly as per your suggestion, is following approach is right for having **same reference** for both GNSS and LiCSBAS ?
> 
> 1. Find GPS station in LiCSBAS result area.
> 2. Project GNSS 3D displacement into LOS
> 3. Using same lat and lon for GPS station, create a time series in LiCSBAS also
> 4. Find a offset between GPS and LiCSBAS in LOS displacement using same date and time.
> 5. Adjust the entire LiCSBAS time serie from anyother coordinates using same offset.

A very basic stupid question which is occupying my mind is. I processed the both ascending and descending orbit of same study area. Now when i run the command 

`LiCSBAS_decomposeLOS.py -f decompose.txt`

where decompose.txt contains
    asc_vel.geo.tif asc_E.geo.tif asc_N.geo.tif
    dsc_vel.geo.tif dsc_E.geo.tif dsc_N.geo.tif

As this will decompose  LOS displacement data to EW and UD components, If I have a GPS station nearby and if i set the reference of both GPS and LiCBAS as same area, should the UD compoent form decomposing LOS displacement and vertical displacement should be equal or nearly equal?

![qes](https://github.com/yumorishita/LiCSBAS/assets/170682504/a9b5b4ab-cb89-4ec1-ae57-5b1f0df1f73c)

If it is true and we can decompose LOS velocity to vertical velocity by using both ascending and descending path from satellite and compare it with nearby GPS staion, is it necessary then to decompose GPS 3D displacement to LOS and compare with LiCBAS becausei think the above method gives good results when compared but i am not sure.

**Comment by yumorishita** [comment]
> should the UD compoent form decomposing LOS displacement and vertical displacement should be equal or nearly equal?
> In this image is 'Up' component of GPS and du of LicBAS should yield almost same result if reference is same for both ?

Yes, I think so. You can compare in vertical rather than LOS. However, I usually compare in LOS because, when GNSS and LiCSBAS is not consistent in vertical, I can identify which is the cause of the inconsistency, ascending or descending.
