### ISSUE TITLE
Errors while running batch file

### ISSUE THREAD

**Issue by duyhoangatk** [yumorishita/LiCSBAS#362]
Hello prof Yumorishita,
I'm new to this LiCSBAS, and I'm currently following all steps from instructions to run the batch file of LiCSBAS, but I got error about the file baselines as following so the operation couldn't run until end
![スクリーンショット 2024-05-28 142539](https://github.com/yumorishita/LiCSBAS/assets/171003463/cee8067a-7366-44b2-8a54-f83f776060dd)

How can I fix this problem ? 
Please help. Thank you very much

**Comment by yumorishita** [comment]
I have no idea. You can try using a different disk.

**Comment by duyhoangatk** [comment]
Sorry but because my working laptop is not my private one, so I cannot do the disk partition to try your solution.
Is there any other solution ? Or how can I change the permission of batch file because I'm completely new, even to Ubuntu and WSL ?
Thank you very much.

**Comment by duyhoangatk** [comment]
Hi Prof Yumorishita,
About the Permission error, somehow I try again your example and it was running well until finished. But when I try to plot by using the code 'LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &' , it stops at this line as shown below ( I have waited for 1 hour)
![error when trying to plot](https://github.com/yumorishita/LiCSBAS/assets/171003463/83aeb2a9-65a5-4a58-992a-e2b50ccdfcf4)
Can you help me about this problem ? Sorry if I am asking too many questions 
Thank you very much.

**Comment by yumorishita** [comment]
It is warning and can be ignored.

**Comment by duyhoangatk** [comment]
Hi Prof Yumorishita,
Thank you for your reply. Which means the code is still running properly and I think the graph is being shown, but maybe the graph is shown only in Linux environment (using virtual envimonment like VMWare or VirtualBox).
Is there any other way to show the graph on Windows without using them ?
Waiting for your reply. Thank you very much.

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/85

**Comment by duyhoangatk** [comment]
Hi Prof Yumorishita,
Thank you for your reply. I will see and find the solution, so I will close the issue.
