### ISSUE TITLE
How to get hgt data?

### ISSUE THREAD

**Issue by NodyPeng** [yumorishita/LiCSBAS#365]
I'm Taiwanese. I want to use the frame 069A_06499_160709 data to perform SBAS. However, when I use batch_process to download the 069A_06499_160709.geo.hgt.tif data, it results in a NoData image.

To resolve this, I used our country's DEM data with a 20m resolution. I clipped and resampled it so that the columns, rows, and cell size matched the original NoData image. I then placed it in the GEOC folder and renamed it to 069A_06499_160709.geo.hgt.tif.

After that, I ran ./batch again, but the TIFF file was not recognized. The message displayed was:

069A_06499_160709.geo.E.tif already exists. Skip download.
069A_06499_160709.geo.N.tif already exists. Skip download.
069A_06499_160709.geo.U.tif already exists. Skip download.
Size of 069A_06499_160709.geo.hgt.tif is not identical.
Download 069A_06499_160709.geo.hgt.tif
          069A_06499_160709.geo.hgt.tif, 26.75MB, 6s, 4.46MB/s

**Comment by yumorishita** [comment]
As the message says, the size should be identical.
