### ISSUE TITLE
Error in LiCSBAS01_get_geotiff.py step

### ISSUE THREAD

**Issue by Hvmanshu** [yumorishita/LiCSBAS#367]
Hello Prof. Morishita, I am processing InSAR data for the frame 056A_06055_131313. However, I am getting error in downloading .mli file as shown in the figure. Kindly help in this issue.
![Screenshot from 2024-06-05 20-22-15](https://github.com/yumorishita/LiCSBAS/assets/74150900/4dc25dc7-f37a-4ee7-8e90-3c25b9889832)

**Comment by yumorishita** [comment]
The bug was fixed in LiCSBAS2 (https://github.com/yumorishita/LiCSBAS2/pull/55). Please use LiCSBAS2 or apply the fix in your local LiCSBAS script.

**Comment by Hvmanshu** [comment]
Yes, it is working now. Thanks Prof Morishita.
