### ISSUE TITLE
Import the value of veloicity from kmz file in QGIS

### ISSUE THREAD

**Issue by blueyeti1994** [yumorishita/LiCSBAS#369]
I exported the kmz file and used QGIS to open the file. My goals is to export the value of each pixels and filter out some unnecessary pixels. when i click any pixels on QGIS, i can't see the velocity value. isn't the velocity information is also exported when creating kmz files? On right side, i can only see value of Band 1...Band 4 and coordinates point. 

<img width="957" alt="kmz file" src="https://github.com/yumorishita/LiCSBAS/assets/170682504/dfd5465a-d490-4896-9e5e-888db2150feb">

This is from displacement map where v2 = -11.5 mm/yr. I was hoping to get similar value when i click any pixel in QGIS.
![14aa9020-bae8-4de0-b850-bfff07977c2c](https://github.com/yumorishita/LiCSBAS/assets/170682504/45428a5f-8743-482c-a2af-cedadcc9546a)

Also is the each single lat and lon is represented by each pixel or is it a combination of few lat and long to represent small area as pixel?

**Comment by yumorishita** [comment]
The kmz includes only a colorized image file. Please use LiCSBAS_flt2geotiff.py.

**Comment by blueyeti1994** [comment]
> The kmz includes only a colorized image file. Please use LiCSBAS_flt2geotiff.py.

Thank you for reply and constant support and one minor question,does each single lat and lon is represented by each pixel or is it a combination of few lat and long to represent small area as pixel?

**Comment by yumorishita** [comment]
What do you mean? It is the normal raster GeoTIFF file.

**Comment by yumorishita** [comment]
Let me close this ticket because there seem to be no more questions.
