### ISSUE TITLE
identifying the input file (float) for plotting profiles between two points of known geographical coordinates

### ISSUE THREAD

**Issue by RoySreeta** [yumorishita/LiCSBAS#371]
Dear Yumorishita San,
 i tried using one of the visualization tools listed on the LiCSAS wiki and I am facing a value error everytime for the following script:
LiCSBAS_profile.py -i infile -p dempar [-r x1,y1/x2,y2] [-g lon1,lat1/lon2,lat2] [-o outfile] [--bigendian] [--nodisplay]

Can you tell me which is going to be my input file after I have finished analyzing a reference frame? For e.g my reference frame is 064D_05884_131313 and after finishing the analysis and plotting the time series, I want to plot profiles along two points with geographical coordinates, but I keep getting the same value error.
So can tell me why the value error is happening and which one should be my input file in this case? How to find the input file here?

Best
Sreetama

**Comment by yumorishita** [comment]
infile can be any float file (e.g., vel.filt.mskd). Please show the full log for the value error.

**Comment by RoySreeta** [comment]
ext3/Zagros/064D_05884_131313$ LiCSBAS_profile.py -i TS_GEOCml1/cum_filt.h5 -p GEOCml1/EQA.dem_par -g 53.6,31.62/55.3,31.3

LiCSBAS_profile.py ver1.1 20200902 Y. Morishita
LiCSBAS_profile.py -i TS_GEOCml1/cum_filt.h5 -p GEOCml1/EQA.dem_par -g 53.6,31.62/55.3,31.3
Traceback (most recent call last):
  File "/home/sreetama/LiCSBAS2/bin/LiCSBAS_profile.py", line 239, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sreetama/LiCSBAS2/bin/LiCSBAS_profile.py", line 138, in main
    data = io_lib.read_img(infile, length, width, endian=endian)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sreetama/LiCSBAS2/LiCSBAS_lib/LiCSBAS_io_lib.py", line 199, in read_img
    data = np.fromfile(file, dtype=dtype).reshape((length, width))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 1066478373 into shape (2703,3126)
