### ISSUE TITLE
LiCSBAS13_sb_inv.py ValueError: cannot reshape array

### ISSUE THREAD

**Issue by crutland1** [yumorishita/LiCSBAS#373]
I am encountering an error in step 13 as follows:

> .....
> 
>   Elapsed time for 123th patch: 00h 00m 53s
> 
> Process 2852/2851th line (124/128th patch)...
>   Reading 1311 ifg's unw data...
> Traceback (most recent call last):
>   File "/local/xxxxx/Documents/github/LiCSBAS/bin/LiCSBAS13_sb_inv.py", line 1204, in <module>
>     sys.exit(main())
>   File "/local/xxxxx/Documents/github/LiCSBAS/bin/LiCSBAS13_sb_inv.py", line 663, in main
>     unw = np.fromfile(f, dtype=np.float32, count=countl).reshape((lengththis, width))*coef_r2m
> ValueError: cannot reshape array of size 82214 into shape (23,3737)

I saw some similar resolved issues but it appears the .unw files in my GEOCml2GACOSclip/ directory are all the same size (as are .cc, and .[ENU]) and as you can see it is getting most of the way through the inversion before it fails. Do you have any idea what this could be?

It is frame 056A_04947_282019.

Many thanks,
Conor

**Comment by yumorishita** [comment]
No idea. Please show the full log.

**Comment by crutland1** [comment]
[nohup_out.txt](https://github.com/user-attachments/files/15873208/nohup_out.txt)

Log attached

**Comment by yumorishita** [comment]
I cannot support because you are using the COMET version. Please contact COMET.
