### ISSUE TITLE
decompose coherence

### ISSUE THREAD

**Issue by maulanaheno** [yumorishita/LiCSBAS#374]
can i decompose 2 frame ascending and descending with different coherence parameter for each frame? and what is the requirement to do decompose? like is it must have same AOI for both frame?

**Comment by yumorishita** [comment]
> can i decompose 2 frame ascending and descending with different coherence parameter for each frame? 

Yes.

> and what is the requirement to do decompose? like is it must have same AOI for both frame

At least one ascending and one descending must have a common area.
