### ISSUE TITLE
Error in downloading Data

### ISSUE THREAD

**Issue by mdehgani** [yumorishita/LiCSBAS#376]
During the first step of LiCSBAS (LiCSBAS01_get_geotiff.py) I have the following error:

Download 130A_05989_131313.geo.E.tif
    TooManyRedirects for 130A_05989_131313.geo.E.tif in 1th try
    TooManyRedirects for 130A_05989_131313.geo.E.tif in 2th try
    TooManyRedirects for 130A_05989_131313.geo.E.tif in 3th try
    Error while downloading from http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/130/130A_05989_131313/metadata/130A_05989_131313.geo.E.tif
Download 130A_05989_131313.geo.N.tif
    TooManyRedirects for 130A_05989_131313.geo.N.tif in 1th try
    TooManyRedirects for 130A_05989_131313.geo.N.tif in 2th try
    TooManyRedirects for 130A_05989_131313.geo.N.tif in 3th try
    Error while downloading from http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/130/130A_05989_131313/metadata/130A_05989_131313.geo.N.tif
Download 130A_05989_131313.geo.U.tif
    TooManyRedirects for 130A_05989_131313.geo.U.tif in 1th try
    TooManyRedirects for 130A_05989_131313.geo.U.tif in 2th try
    TooManyRedirects for 130A_05989_131313.geo.U.tif in 3th try
    Error while downloading from http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/130/130A_05989_131313/metadata/130A_05989_131313.geo.U.tif
Download 130A_05989_131313.geo.hgt.tif
    TooManyRedirects for 130A_05989_131313.geo.hgt.tif in 1th try
    TooManyRedirects for 130A_05989_131313.geo.hgt.tif in 2th try
    TooManyRedirects for 130A_05989_131313.geo.hgt.tif in 3th try
    Error while downloading from http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/130/130A_05989_131313/metadata/130A_05989_131313.geo.hgt.tif
.....
How can I fix this problem?

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/370#issuecomment-2184930345
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2173156010

**Comment by shouyerenx** [comment]
hi,have you solvedq it? i have same problem

**Comment by mdehgani** [comment]
Hi, Yes. I used LiCSBAS2 instead of LiCSBAS and could download the data easily without problem.
