### ISSUE TITLE
ifg info meaning

### ISSUE THREAD

**Issue by maulanaheno** [yumorishita/LiCSBAS#377]
# ifg dates         bperp   dt unw_cov  coh_av
20180102_20180108   -75.6    6   0.993   0.258 
20180102_20180114   -46.0   12   0.975   0.223 

what is this bbrep, dt, unw_cov, coh_av mean?

**Comment by yumorishita** [comment]
Perpendicular baseline, time interval (day), percentage of unwrapped pixel coverage, average coherence.

**Comment by githubrahmatcoba** [comment]
![image](https://github.com/yumorishita/LiCSBAS/assets/147256980/deae0fa7-6359-4b2e-93b3-71b5d131d908)
![image](https://github.com/yumorishita/LiCSBAS/assets/147256980/c259609a-25a4-494b-aa70-5c1bf887a4f1)

i try to process a deformation and have the result like in the picture, its like raster of the result been sliced, and i look at the ifg info its because of it has low unw_coh. do you know whats make it have low unw_cov?

**Comment by yumorishita** [comment]
It is because of the LiCSAR system. Please contact COMET.

**Comment by maulanaheno** [comment]
> It is because of the LiCSAR system. Please contact COMET.

could you tell me the step of how to add our own pair of interferograms to be process using licsbas?

**Comment by yumorishita** [comment]
You should follow the file structure of GEOC (see [here](https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/bin/LiCSBAS01_get_geotiff.py#L13)) or GEOCml (see [here](https://github.com/yumorishita/LiCSBAS/wiki/file_structure#input-for-step-1-1-or-steps-0-3-to-0-5-output-of-step-0-2)).

**Comment by as1234554321** [comment]
Hi sir, sorry I asked basic questions again 
1. Why is the ref area point for each processing different even though the data and commands used are the same? Does this influence the determination of vertical deformation?
2. How to get a time series and land subsidence at several different location points?
3. If the processing is done with gacos and mask correction, does it have to be compared with GNSS data?

**Comment by yumorishita** [comment]
1. It should not happen if the data and commands are the same.
2. Do you mean exporting a text file? LiCSBAS_cum2tstxt.py can do it.
3. No.

**Comment by as1234554321** [comment]
thankyou sir, 
ascending and descending produce different reference points.
 - does it affect the results of vertical deformation?
 - should both orbits have the same reference point for decomposition processing?

**Comment by yumorishita** [comment]
Yes for both.

**Comment by as1234554321** [comment]
thank you sir
how to set the same reference point on each orbit?

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1964088205

**Comment by maulanaheno** [comment]
> Perpendicular baseline, time interval (day), percentage of unwrapped pixel coverage, average coherence.

what is the perpendicular baseline unit? and what the difference between negative and positive value?

**Comment by as1234554321** [comment]
> [#244 (comment)](https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1964088205)

hi sir
I have clipped the area in steps 0-5, if I do the decomposition process, do I have to align the reference points with LiCSBAS_cum2vel.py ?

**Comment by yumorishita** [comment]
You don't have to, but it would be better to do it.
