### ISSUE TITLE
No cum_filt.h5 exists

### ISSUE THREAD

**Issue by shubhayanroychowdhury** [yumorishita/LiCSBAS#378]
Hi @yumorishita ,
I was trying to run this command ** LiCSBAS_cum2tstxt.py -g 76.7708333319 30.7052083333 -i TS_GEOCclip/cum_filt.h5**, but i got this error..
![image](https://github.com/yumorishita/LiCSBAS/assets/129718401/13f6d8e6-8b3d-4c34-af5c-8af3e1aab6f1)

In TS_GEOCclip directory, cum_filt.h5 file exist. I do not know why i am getting this error.

![image](https://github.com/yumorishita/LiCSBAS/assets/129718401/5c1d96d1-e504-46f8-ae0e-824c4680820d)

Please look into it and thank you for your time and consideration.

**Comment by yumorishita** [comment]
` -g 76.7708333319 30.7052083333` must be ` -g 76.7708333319/30.7052083333`.
