### ISSUE TITLE
Not able to download data via ./batch_LiCSBAS.sh

### ISSUE THREAD

**Issue by abdullahkhanjaan** [yumorishita/LiCSBAS#379]
Respected,
I am trying to download the data files for my Frame ID 173A_05550_131313 but the following error occurs. the LICSAR_products website is also in maintenance, is this issue occuring due to maintenance? I also tried to access the website using one of the link given in your code but it also gives the error "Service Temporarily Unavailable.

https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/173/173A_05550_131313/epochs/20230527/20230527.geo.mli.tif
Resolving gws-access.jasmin.ac.uk (gws-access.jasmin.ac.uk)... 130.246.128.97
Connecting to gws-access.jasmin.ac.uk (gws-access.jasmin.ac.uk)|130.246.128.97|:443... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2024-07-14 01:27:29 ERROR 503: Service Temporarily Unavailable.

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2173156010
