### ISSUE TITLE
Dose LiCSBAS run on Windows ?

### ISSUE THREAD

**Issue by Pirog3266** [yumorishita/LiCSBAS#38]
Thanks to your advice, I could run LiCSBAS on Mac OS,
Now I'm trying to install LiCSBAS on windows10.
We can install Anaconda3 on windows10, and also can install Gdal by Anaconda prompt.
But after that it dose not go well. (Commands does not work well).
Do you have any report that LiCSBAS runs on windows ?

**Comment by yumorishita** [comment]
There seem to be some issues on Windows (see https://github.com/yumorishita/LiCSBAS/issues/10 and https://github.com/yumorishita/LiCSBAS/issues/27).

I recommend using VMware to install a Linux environment in Windows. You can find a detailed install manual in Japanese below:
https://raw.githubusercontent.com/wiki/yumorishita/LiCSBAS/documents/LiCSBAS_etc_install_J.pdf
(This file is currently hidden but I will make a manual page in Japanese soon.)

**Comment by Pirog3266** [comment]
Thanks your comments.
I tried to install on cygiwin environment, it did not go well.
For windows,  as you told, it seems to be better to install virtual environment.  
I'm looking forward to Japanese manual !
