### ISSUE TITLE
 Loop closure check issues

### ISSUE THREAD

**Issue by memorylorry** [yumorishita/LiCSBAS#380]
Hello Morishita
When I was executing ./batch_LiCSBAS.sh, I encountered some issues during the step12-loop process. I don't know how to solve them.
I really hope to get your response and help. Thank you very much.
![Screenshot from 2024-07-16 00-19-00](https://github.com/user-attachments/assets/b1eb93c5-f480-41d9-953a-0fd501ab236b)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2230694625
