### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by abdullahkhanjaan** [yumorishita/LiCSBAS#381]
what is the reason of getting these distorted results

![mask_ts](https://github.com/user-attachments/assets/6555f9ca-90df-445e-9756-805c48ffed21)

**Comment by yumorishita** [comment]
What part is distorted you mean?

**Comment by abdullahkhanjaan** [comment]
Like the results are not clearly visible. When I display the ts viewer, velocity range is from 0.0 to -0.5.  I will share the resultant ts window with you.

**Comment by yumorishita** [comment]
Let me close this ticket because there seem to be no more questions.
