### ISSUE TITLE
TooManyRedirects issues

### ISSUE THREAD

**Issue by abyan231102** [yumorishita/LiCSBAS#382]
hi Mr. Yumorishita, I have a problem which can be seen in the following image, can you tell me what is wrong with my processing?
![image](https://github.com/user-attachments/assets/f6aa3382-7a94-44a3-b9e3-d3cf9fad968d)

**Comment by mohammad-a-sh** [comment]
Hi
I think your problem is like issue#55 (https://github.com/yumorishita/LiCSBAS2/pull/55/files) and this problem was considered before. Because I had the same problem and I fixed it with this issue.

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2156004788
