### ISSUE TITLE
How to use GPU option

### ISSUE THREAD

**Issue by NabilAttar** [yumorishita/LiCSBAS#383]
greeting Mr. Yumorishita

I turned on the gpu option in the hope that the process would be faster. But it looks like an error because there is no module called cupy, is there a way to install cupy so it can use the gpu during the process?. The VGA that I have is NVIDIA GTX 1650 4GB. Below I attach the results of check_licsbas.py

thank you

![image](https://github.com/user-attachments/assets/195c2cc4-83ff-44c1-8af3-d3c1b595d5cd)

![image](https://github.com/user-attachments/assets/2c9de8ff-7c7e-4500-b398-a3ea4b95405d)

**Comment by yumorishita** [comment]
You can install by `conda install cupy` if you youse conda.

**Comment by NabilAttar** [comment]
excuse me sir, I have installed cupy, but an error occurs, do you have any suggestions? Thank You

![image](https://github.com/user-attachments/assets/fc67b1e6-a15d-4b2a-8b78-1d2a6fbd4b44)

**Comment by NabilAttar** [comment]
this is my version now

![image](https://github.com/user-attachments/assets/f66c14b8-5b13-4fd6-bbcb-249d3a71bcb1)

![image](https://github.com/user-attachments/assets/ee7ff9cc-3062-4bc3-91f1-6139ee9dbd5f)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1997318815

**Comment by NabilAttar** [comment]
the problem has solved, thank you sir
