### ISSUE TITLE
Use script

### ISSUE THREAD

**Issue by Alzaidy1** [yumorishita/LiCSBAS#385]
Hello professor 

How can I use this script to extract data without mask.

LiCSBAS_cum2flt.py -d 20171123 -i cum_filt.h5 -o TS-GEOCml -m 20141010 -r 740:760/2014:2021 --png

I don't Like this

![image](https://github.com/user-attachments/assets/47436b22-8ff8-44c7-9250-42f8c231f31e)

@yumorishita

**Comment by yumorishita** [comment]
If you use LiCSBAS2, add `--nomask` option. If you use LiCSBAS, it is already unmasked.

**Comment by yumorishita** [comment]
LiCSBAS has no function to do that, but the matplotlib interactive window should have a function to set the axis range.

**Comment by yumorishita** [comment]
![image](https://github.com/user-attachments/assets/805b6e52-1560-4f3f-a09c-e4f170f35a11)
![image](https://github.com/user-attachments/assets/8e363bcc-07fa-4c1e-9140-b3b5e988cc8b)
