### ISSUE TITLE
No browse image issues

### ISSUE THREAD

**Issue by abyan231102** [yumorishita/LiCSBAS#386]
![image](https://github.com/user-attachments/assets/46b83daa-5309-494a-8df7-a85e9485d03f)

**Comment by oguzhannysr** [comment]
@abyan231102, @yumorishita I had the same problem, can we find a solution?

**Comment by yumorishita** [comment]
I have no idea. Do you use WSL?

**Comment by oguzhannysr** [comment]
@yumorishita ,Yes, I have been using it, I have not received such an error until now for 1 year.

**Comment by oguzhannysr** [comment]
@yumorishita , 
![image](https://github.com/user-attachments/assets/32314c45-6e3b-4450-bba3-d89db768e72d)

**Comment by yumorishita** [comment]
Please try making a dummy file by touch, i.e., `touch /mnt/.../...11.unw.png`.
