### ISSUE TITLE
plot the time series of displacement using decompose result

### ISSUE THREAD

**Issue by maulanaheno** [yumorishita/LiCSBAS#387]
can i decompose LOS displacement result at once and plot the time series graph the result of decompose using LiCSBAS_plot_ts.py like using LOS discplacement cum result with h5 file format?

**Comment by yumorishita** [comment]
No.

**Comment by maulanaheno** [comment]
so i had to decompose a pair of los displacement one by one to make the time series of decompose result right?

**Comment by yumorishita** [comment]
It would be possible though I have never tried it. You may need to consider the time difference between ascending and descending epochs.
