### ISSUE TITLE
error in LiCSBAS11_check_unw.py step

### ISSUE THREAD

**Issue by Sharmila0809** [yumorishita/LiCSBAS#388]
Hello Sir, I got an error in step LiCSBAS11_check_unw.py -d GEOCml1clip, as shown in the attached image. Please resolve this issue. 
![Screenshot from 2024-08-06 14-18-34](https://github.com/user-attachments/assets/294978f5-4e56-41a0-a20e-661b0da439a7)
Thanks!

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2102667929
