### ISSUE TITLE
LiCSBAS decompose

### ISSUE THREAD

**Issue by NabilAttar** [yumorishita/LiCSBAS#389]
Greeting Mr. Yumorishita

I found some errors when using decompose, maybe there is any suggestion related to this, thank you

![image](https://github.com/user-attachments/assets/bba80dfd-7646-4702-ba9d-abab75f32d3d)

![image](https://github.com/user-attachments/assets/637e5876-91e2-4480-a51f-557d090d6272)

**Comment by yumorishita** [comment]
The files you wrote in files.txt must exist.

**Comment by NabilAttar** [comment]
Thank you sir, there was an error in naming the file so it caused an error, the problem has been fixed
