### ISSUE TITLE
LiCSBAS_decomposeLOS.py

### ISSUE THREAD

**Issue by Pirog3266** [yumorishita/LiCSBAS#39]
Hello again ! 
Would you tell me how to input LiCSBAS_decomposeLOS.py command line concretely?
(Would you show me  some example like Tutorial).
Are Efile1 and Nfile1 xxxx_xxxxx_xxxxxx.geo.E.tif  and xxxx_xxxxx_xxxxxx.geo.N.tif in CEOC folder 
or E.geo and N.geo in CEOCml1 folder ?
Is dispfile1 made from TS_GEOCml1clip/results/vel.mskd by LiCSBAS_flt2geotiff.py ?
Sorry for very basic question.

**Comment by yumorishita** [comment]
Sorry for unclear documentation. I should add some explanations into the usage.

As written in the usage, the input files must be in GeoTIFF format, which can be created by [LiCSBAS_flt2geotiff.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_flt2geotiffpy) from float files (e.g., GEOCml1/E.geo).

dispfile1 can be made from TS_GEOCml1clip/results/vel.mskd by LiCSBAS_flt2geotiff.py, or the vel file itself can be created by [LiCSBAS_cum2vel.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_cum2velpy) with a specified span and/or reference area.

**Comment by Pirog3266** [comment]
Sorry for late replying.
So, first, I need to make vel.maskd.geo.tiff, E.geo.tiff, N.geo.tiff form vel.maskd, E.geo, N.geo,
and then, if I move all files to same folder, should I type as below ?

LiCSBAS_decomposeLOS.py  -f  vel1.maskd.geo.tiff, E1.geo.tiff, N1.geo.tiff vel2.maskd.geo.tiff, E2.geo.tiff, N2.geo.tiff

**Comment by yumorishita** [comment]
The argument of -f is "Text file containing input GeoTIFF file paths." You must create a text file, e.g.,
```
cat << EOF > files.txt
vel1.maskd.geo.tiff E1.geo.tiff N1.geo.tiff
vel2.maskd.geo.tiff E2.geo.tiff N2.geo.tiff
EOF
```
and then run `LiCSBAS_decomposeLOS.py -f files.txt`.

You don't need to move the files because the text file can contain the path (though you can move the files of course).

**Comment by yumorishita** [comment]
Has the problem been solved?

**Comment by Pirog3266** [comment]
Sorry to late replying. 
I missed solving as I have been sick since last week.
(Problem with me (>_<))

**Comment by yumorishita** [comment]
Has the problem been solved?

**Comment by Pirog3266** [comment]
So Sorry. 
Not yet(><)

**Comment by khakim** [comment]
Dear Yuorishita,

I have two questions,
1. Which directory do we run LiCSBAS_decomposeLOS.py from? Is any directory okay?
2. How to create 3D deformation of each date (not velocity)?

**Comment by yumorishita** [comment]
1. Any directory is OK as long as you indicate the correct path to the input files for the -f option.
2. LiCSBAS_decomposeLOS.py decomposes into EW and UD, not 3D. The GeoTIFF file of the deformation for each date can be created by LiCSBAS_cum2flt.py and LiCSBAS_flt2geotiff.py. However, we should note that the ascending and descending data have different observation dates.

**Comment by khakim** [comment]
Thanks very much Yumorishita.  Do you have a python code for generate 3D deformation LiCSBAS?

**Comment by yumorishita** [comment]
I am developing it but currently have no plan to publish it.

**Comment by khakim** [comment]
Thanks for your information. I am looking forward to hearing your best codes for 3D deformation.

By the way, can we use unwrapped interferograms generate by using other software such as GMTSAR? If yes, how to prepare files for LICSBAS? As I know, LiCSAR doesn't cover all area and all time but only small percents of them.

**Comment by yumorishita** [comment]
Yes, please see the [file structure](https://github.com/yumorishita/LiCSBAS/wiki/file_structure#input-for-step-1-1-or-steps-0-3-to-0-5-output-of-step-0-2). The required files are cc, unw, EQA.dem_par and slc.mli.par only.

**Comment by khakim** [comment]
Are cc and unw in range-azimuth coordinates?

**Comment by yumorishita** [comment]
Either in range-azimuth or geographic coordinates can be processed, though some functions cannot be used in range-azimuth coordinates

**Comment by khakim** [comment]
Thank you very much.

**Comment by yumorishita** [comment]
I have slightly updated the usage of LiCSBAS_decomposeLOS.py. Let me close this issue because there seem to be no more questions. If someone has any questions, please reopen this.

**Comment by Pirog3266** [comment]
I'll try updated tone. Thanks.

**Comment by irmayolii** [comment]
Dear Prof. Yumorishita
After we get EN/UD.geotif from processing LiCSBAS_decomposeLOS.py, can I generate specified point  timeseries from EN/UD.geotif timeseries?

**Comment by nusretdemir** [comment]
Is there any script to create UD and EW time series data rather than geotiffs?

**Comment by yumorishita** [comment]
No.

**Comment by shubham-geolearner** [comment]
> Sorry for unclear documentation. I should add some explanations into the usage.
> 
> As written in the usage, the input files must be in GeoTIFF format, which can be created by [LiCSBAS_flt2geotiff.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_flt2geotiffpy) from float files (e.g., GEOCml1/E.geo).
> 
> dispfile1 can be made from TS_GEOCml1clip/results/vel.mskd by LiCSBAS_flt2geotiff.py, or the vel file itself can be created by [LiCSBAS_cum2vel.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_cum2velpy) with a specified span and/or reference area.

while converting N.geo, U.geo, E.geo to tiff format using LiCSBAS_flt2geotiff.py what file we should specify in -p attribute of LiCSBAS_flt2geotiff.py command?

LiCSBAS_flt2geotiff.py -i infile **-p dempar** [-o outfile] [--zero2nan] [--nan2zero] [--a_nodata num] [--bigendian]

are we suppose to keep TS_GEOCclip/info/EQA.dem_par ?

**Comment by yumorishita** [comment]
Yes.

**Comment by shubham-geolearner** [comment]
Thankyou!
