### ISSUE TITLE
LiCSBAS12_loop_closure.py -d GEOCml1clip

### ISSUE THREAD

**Issue by AshwaniAgnihotri** [yumorishita/LiCSBAS#390]
Hello Sir, I encountered an error in step 'LiCSBAS12_loop_closure.py -d GEOCml1clip', as shown in the attached image. Please resolve this issue. 

![Screenshot 2024-08-11 105355_error](https://github.com/user-attachments/assets/7b445d0e-e12d-4346-9eb4-e61ee4eaca59)

Thanks.

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2230694625

**Comment by oguzhannysr** [comment]
@yumorishita , It's been a long time and it's still going on. Is this normal? I make the entire frame, without clipping.

![image](https://github.com/user-attachments/assets/f1e0c9bc-5e8c-41ca-be40-f12346381fa7)
