### ISSUE TITLE
04 mask doesn't works

### ISSUE THREAD

**Issue by HN-Jiang** [yumorishita/LiCSBAS#391]
Dear yumorishita,
I have a problem with step 04. I try to mask before go futher. But I think it doesn't works. Even I try 0.9 as threshold, nothing has been masked. Can you please help me take a look?

By the way I'm using LiCSBAS2 now.,

[202408151546batch_LiCSBAS_04_05.log](https://github.com/user-attachments/files/16622977/202408151546batch_LiCSBAS_04_05.log)
![20141218_20150405 unw](https://github.com/user-attachments/assets/535ef84c-554b-4efd-bf0e-a8e5bfece5c5)

**Comment by yumorishita** [comment]
Check coh_avg.png. If you want to keep more pixels, you should decrease the threshold.

**Comment by HN-Jiang** [comment]
![coh_avg0 3](https://github.com/user-attachments/assets/235b8193-7c6d-40aa-8c65-8bebadc5cdc5)
HI，here is the coh_avg.png. I try 0.1 to 0.9 for mask, but seems nothing has been masked. Because mask.png shows nothing and also in each interferogram file, the file yyyymmdd_yyyymmdd.unw.png is also umpty.

![mask](https://github.com/user-attachments/assets/0c3aec3f-4588-4b2e-86e7-d180f4771e6d)

**Comment by yumorishita** [comment]
I found the cause. The option `-r 0:0/0:0` masks all pixels. Don't use it.

**Comment by HN-Jiang** [comment]
Thank you. But sorry, I don't understand this, because as I understand, we can mask the whole image for getting more good interferogram(loop) for step 12. That's why I use -r 0:0/0:0. And ideally it should remove all the pixel that under the threshold, and keep the pixel with good quality. But It looks like all the pixel has been masked(removed).

And I also try to specify an area(My research area), also give the threshold as 0.3. It looks like the given region has been fully masked.

![20170430_20170512 unw](https://github.com/user-attachments/assets/e07707bc-7559-4362-b2ea-dd6a78406f27)

**Comment by yumorishita** [comment]
If you mask the whole image, we lose all data and get no result. `-r` option remove all pixels in the specified area regardless of coherence. If you want to keep the pixels with good quality, you should only use `-c` option.
If you have a specific area of interest, I recommend first clipping the area by step05 and then applying step04 to the clipped data.

**Comment by RaeGeoffrey** [comment]
what is -c option and -r option, where i can find it ?

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/wiki/2_2_step01_5#step-0-4-mask-unw-optional
