### ISSUE TITLE
unw error

### ISSUE THREAD

**Issue by Osmanpour** [yumorishita/LiCSBAS#392]
Dear Morishita,
I faced this issues in my result and then i find that it's related raw ifg.
how can i solve this?
![Screenshot from 2024-08-19 21-30-50](https://github.com/user-attachments/assets/091198a4-ccd9-4586-b563-f171b948833a)
 
![Uploading vel.png…]()

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1914532449
