### ISSUE TITLE
clip specifying ranges

### ISSUE THREAD

**Issue by Osmanpour** [yumorishita/LiCSBAS#393]
Dear Morishita, 
Is that any way to clip clip specifying multiple ranges in LiCSBAS ?
I need to remove the area of subsidence to show other deformation around faults?

**Comment by yumorishita** [comment]
You can mask (exclude) multiple areas with -f option in step04 or p04_mask_range_file in batch_LiCSBAS.sh.

https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/batch_LiCSBAS.sh#L38

**Comment by Osmanpour** [comment]
with -f just i could mask rectangle shape, isn't it?
what can I do for other polygons? 
format in the script is x1:x2/y1:y2 , what about format in polygon (x1/y1) can be true? if it possible?

**Comment by Osmanpour** [comment]
[TEH-SUB.txt](https://github.com/user-attachments/files/16739291/TEH-SUB.txt)

**Comment by yumorishita** [comment]
Currently LiCSBAS does not support the polygon.
