### ISSUE TITLE
Color bar

### ISSUE THREAD

**Issue by abdullahkhanjaan** [yumorishita/LiCSBAS#394]
How can I generate result images, such as good and bad interferograms or filtered deramped PNGs, with a color map? For instance, in the current example, there is no color bar included.
![image](https://github.com/user-attachments/assets/ced54c10-e83b-48a3-a20d-a22ab44c8f97)

**Comment by yumorishita** [comment]
I think the color bar can be included by using LiCSBAS_disp_img.py, i.e., 
`LiCSBAS_disp_img.py -i <image_file> -p <par_file> -c cm_insar --png <pngname>`

**Comment by abdullahkhanjaan** [comment]
Could you please provide an example of a use case, explaining which parameters correspond to which files?

**Comment by yumorishita** [comment]
`LiCSBAS_disp_img.py -i 20180525_20180712/20180525_20180712.unw -p EQA.dem_par -c cm_insar --png 20180525_20180712.unw.png`
See the usage.
