### ISSUE TITLE
LiCSBAS_decomposeLOS.py

### ISSUE THREAD

**Issue by as1234554321** [yumorishita/LiCSBAS#395]
basic questions
 decomposition must use 2 orbits or can  only be descending/ascending?

**Comment by yumorishita** [comment]
Must use 2 orbits.

**Comment by as1234554321** [comment]
How do you calculate the rate of subsidence/vertical rate in one of the orbits? 
is it possible without decomposition?

**Comment by as1234554321** [comment]
halo sir, sorry I ask you different theme in this issue
why matplot command is like this?
![WhatsApp Image 2024-09-03 at 10 42 28](https://github.com/user-attachments/assets/970942e4-6018-4110-ae0d-b03b5d687405)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2230694625

**Comment by as1234554321** [comment]
> [#244 (comment)](https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2230694625)
sorry sir, This answer is to answer which question? 
should I uninstall comet licsbas and replace it with licsbas2?

**Comment by yumorishita** [comment]
If you want to ask me, yes.

**Comment by as1234554321** [comment]
> If you want to ask me, yes.

1.What are the significant differences between comet and licsbas2?
2.Can I still use data id frame from 2022-now if I use licsbas?
3. prefer install licsbas or licsbas2?

**Comment by yumorishita** [comment]
> 1.What are the significant differences between comet and licsbas2?

Please see the PRs for [LiCSBAS2](https://github.com/yumorishita/LiCSBAS2/pulls?q=is%3Apr+is%3Aclosed) and [COMET version](https://github.com/comet-licsar/LiCSBAS/pulls?q=is%3Apr+is%3Aclosed), but I don't know much about the COMET version.

> 2.Can I still use data id frame from 2022-now if I use licsbas?

Sorry, I cannot understand your question.

> 3. prefer install licsbas or licsbas2?

I recommend LiCSBAS2.

**Comment by as1234554321** [comment]
> Please see the PRs for [LiCSBAS2](https://github.com/yumorishita/LiCSBAS2/pulls?q=is%3Apr+is%3Aclosed) and [COMET version](https://github.com/comet-licsar/LiCSBAS/pulls?q=is%3Apr+is%3Aclosed), but I don't know much about the COMET version.
>>The batch used is similar, so I process the data like the steps in your wiki even though the licsbas version is different. is that a big mistake?

>I recommend LiCSBAS2
>>if I use licsbas2, can I still use start dates from 2022-2024?
 in your licsbas general information repository cannot be updated from 2022

Sorry if I ask basic questions, because I am a beginner learning remote sensing in combination with Python, Thankyou sir

**Comment by yumorishita** [comment]
1. You can use the batch in the same way.
2. You can process any dates using any version of LiCSBAS if you have the input data.
