### ISSUE TITLE
Error in generating kmz file

### ISSUE THREAD

**Issue by faraksoch1881** [yumorishita/LiCSBAS#396]
Hi Dr. Morishita,

I ran the following command to generate kmz files,

`LiCSBAS_disp_img.py -i TS_GEOCml1clip/results/vel.mskd -p TS_GEOCml1clip/info/EQA.dem_par --kmz sagarasc`

but it displays following errors. 

`LiCSBAS_disp_img.py ver1.11.0 20210205 Y. Morishita
LiCSBAS_disp_img.py -i TS_GEOCml1clip/results/vel.mskd -p TS_GEOCml1clip/info/EQA.dem_par --kmz sagarasc
/home/sagar/anaconda3/lib/python3.11/zipfile.py:1550: UserWarning: Duplicate name: 'sagarasc'
  return self._open_to_write(zinfo, force_zip64=force_zip64)
Traceback (most recent call last):
  File "/home/sagar/Downloads/LiCSBAS2-master/bin/LiCSBAS_disp_img.py", line 317, in <module>
    os.remove(pngnametmp)
FileNotFoundError: [Errno 2] No such file or directory: 'sagarasc'`

How to solve this? I tried to save the png file with --png pngname and  there is no issue but in generating the kmz i'm getting erros. Also instead of vel.mskd , I also used the GeoTif File generated using LiCSBAS_flt2geotiff.py but error is same. Thank you !!

![error_kmz](https://github.com/user-attachments/assets/63252c69-dc32-4414-94a5-87395e78f29f)

**Comment by yumorishita** [comment]
Please try `sagarasc.kmz`, not `sagarasc`.

**Comment by faraksoch1881** [comment]
> Please try `sagarasc.kmz`, not `sagarasc`.

Thank you it worked. The one small issue is i can click anywhere in the generated map which produces time series with LOS velocity displayed on top. Is there a way to find the maximum LOS velocity rate ? As now I click randomly by guessing it might be area with max LoS velocity looking at color which might not be true. It would be possible if I could export all LoS values with lat and lon also to excel file and i could easily use filter to find maximum and minimum value. is it can be done? How to find the maximum LoS velocity  ?

**Comment by yumorishita** [comment]
You can export the GeoTIFF values to the text file by [gdal2xyz](https://gdal.org/en/latest/programs/gdal2xyz.html).

**Comment by faraksoch1881** [comment]
Thank you !!
