### ISSUE TITLE
velocity map sliced in half

### ISSUE THREAD

**Issue by faraksoch1881** [yumorishita/LiCSBAS#397]
The area i'm interested is lies in two frames 121D_06267_131313 and 019D_06217_131313 but 121D_06267_131313  contains considerable amount of area i'm interested in. Hence i processed 121D_06267_131313  frame, but the output results are clipped in east-west direction in vel.mskd while vel contains whole image. What could be the source of error and how to resolved it ?
![456421983_1766818537184864_6397117318222094522_n](https://github.com/user-attachments/assets/59785974-eba1-4ad7-a5b0-617704ff3b3c)

**Comment by as1234554321** [comment]
sorry oot @faraksoch1881 
1. how do you display this image on the computer?, on mine there is only 1 image of 1 part, not combined as above 
2. What version of licsbas are you using comet licsbas/licsbas/licsbas2?

thankyou

**Comment by faraksoch1881** [comment]
> sorry oot @faraksoch1881
> 
> 1. how do you display this image on the computer?, on mine there is only 1 image of 1 part, not combined as above
> 2. What version of licsbas are you using comet licsbas/licsbas/licsbas2?
> 
> thankyou

The time series can be produced by using LiCSBAS_plot_ts.py command which displayed half of image. but when i check inside the folder TS_GMC1 folder there is two png images and when i viewed one image, i could see that all images were cut into half except vel. So that means my frame has whole image but somehow using mask or any other issue is cutting it into half which i have no idea how to solve so i posted that png image here

I'm using LiCsbas2 version.

**Comment by yumorishita** [comment]
Please upload the full log.

**Comment by as1234554321** [comment]
hi sir, can i ask something about the result (png) in AOI.
I have processed using batch
first try, just changed do05op clip to y, everything else was default. png results below:
![mask_ts_masked](https://github.com/user-attachments/assets/7068120f-c430-40aa-84c9-5c59f3ea0c2d)


second try, change part 03-05 "y" ,  get gacos "y", others default  
do03op_GACOS="y" # y/n
do04op_mask="y" # y/n
do05op_clip="y" #y/n
### Frequently used options. If blank, use default. ###
p01_start_date="20190105" #default: 20141001
p01_end_date="20230309" # default: today
p01_get_gacos="y" # y/n 

The result is like the following PNG image:
![mask_ts_masked](https://github.com/user-attachments/assets/72d72ab8-b372-4da4-ae11-613877c203cc)

In your opinion, which one is better, or do you have other suggestions for changing parameter values?
thank you for your help sir.

**Comment by as1234554321** [comment]
> The coverage looks better in the upper one. There seems to be no other significant difference.

thankyou sir, 
true, no other significant difference because I processed it with parameter values default. 
The difference lies in the gacos and masking process. in tutorial (he masking and masking optional) This step is optional and highly recommended to do it but the result is a lot of white areas. Are there any suggestions for reducing the white/blank area?

thankyou sir

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2009502904

**Comment by as1234554321** [comment]
1. in LiCSBAS15_mask_ts.py is it better to  high percentage of kept pixels or masked pixels?
2. Is there a minimum standard percentage value that is good for masked pixels or kept pixels?
sorry for basic questions
thankyou

**Comment by faraksoch1881** [comment]
> Please upload the full log.

[202409021636batch_LiCSBAS_01_16.log](https://github.com/user-attachments/files/16879223/202409021636batch_LiCSBAS_01_16.log)
Here is the full log where my map is cut into half in horizontal direction.

**Comment by faraksoch1881** [comment]
> hi sir, can i ask something about the result (png) in AOI. I have processed using batch first try, just changed do05op clip to y, everything else was default. png results below: ![mask_ts_masked](https://private-user-images.githubusercontent.com/178903767/364394676-7eeb0de4-a7b5-4c5e-ae95-47228ff685f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0Nzk1MzcsIm5iZiI6MTcyNTQ3OTIzNywicGF0aCI6Ii8xNzg5MDM3NjcvMzY0Mzk0Njc2LTdlZWIwZGU0LWE3YjUtNGM1ZS1hZTk1LTQ3MjI4ZmY2ODVmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxOTQ3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjE3MmMxNGU0NmNjMzRjMDMyNWVkNDU5ODI3YWJjNGRiNTdjY2ZjMWRlOGU1ZTZmMzM2MjE2NmI5ZWUzMGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VI3MvwqhXT3XSc0hta5GLa9FTWRhpFdt-4hrYEGqfpk)
> 
> second try, change part 03-05 "y" , get gacos "y", others default do03op_GACOS="y" # y/n do04op_mask="y" # y/n do05op_clip="y" #y/n
> 
> p01_start_date="20190105" #default: 20141001 p01_end_date="20230309" # default: today p01_get_gacos="y" # y/n
> 
> The result is like the following PNG image: ![mask_ts_masked](https://private-user-images.githubusercontent.com/178903767/364390911-72d72ab8-b372-4da4-ae11-613877c203cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0Nzk1MzcsIm5iZiI6MTcyNTQ3OTIzNywicGF0aCI6Ii8xNzg5MDM3NjcvMzY0MzkwOTExLTcyZDcyYWI4LWIzNzItNGRhNC1hZTExLTYxMzg3N2MyMDNjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxOTQ3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWM4MWI0OWVmNzRlOWZkNTVlMzc2ZjRlYzc1MDUxYjdkMDJjZWEzZDE5ZDRjOWJhNGQ4YTk0YmQwMzgyY2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2VHEvB0WvvBEznE-rX0LZ6_4-qicdngOT2sHDChCg80)
> 
> In your opinion, which one is better, or do you have other suggestions for changing parameter values? thank you for your help sir.

I also tried to use GACOS data by using batch processing but it failed saying "No Gacos folder". So did you first download the GACOS data inside GACOS folder and then ran the batch processing or else?

**Comment by as1234554321** [comment]
> I also tried to use GACOS data by using batch processing but it failed saying "No Gacos folder". So did you first download the GACOS data inside GACOS folder and then ran the batch processing or else?

I run the batch then automatically download the gacos data

**Comment by faraksoch1881** [comment]
> > I also tried to use GACOS data by using batch processing but it failed saying "No Gacos folder". So did you first download the GACOS data inside GACOS folder and then ran the batch processing or else?
> 
> I run the batch then automatically download the gacos data

could you please share me your batch file here !!

**Comment by faraksoch1881** [comment]
Hi Dr.yumorishita

Here is the full log 
[202409021636batch_LiCSBAS_01_16.log](https://github.com/user-attachments/files/16884152/202409021636batch_LiCSBAS_01_16.log)

**Comment by yumorishita** [comment]
Was the image you showed at the top mask_ts_masked.png? If so, please show mask_ts.png.

**Comment by faraksoch1881** [comment]
> Was the image you showed at the top mask_ts_masked.png? If so, please show mask_ts.png.

I'm off my computer right now. but masked png look like the image from first row second column. Like this
<img width="173" alt="Screenshot 2024-09-05 070655" src="https://github.com/user-attachments/assets/a363a988-b6ca-4d2e-8b54-2e8165472165">

**Comment by yumorishita** [comment]
No, mask_ts.png.

**Comment by faraksoch1881** [comment]
> No, mask_ts.png.

I will upload mask_ts.png few hours later as away from my computer now.

**Comment by faraksoch1881** [comment]
![mask_ts](https://github.com/user-attachments/assets/1b6fd8be-968e-40f0-bf68-2b419e6730f4)
Hi prof. I have attached here mask_ts.png

**Comment by yumorishita** [comment]
Try increasing p15_n_loop_err_thre.
https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/batch_LiCSBAS.sh#L58

**Comment by faraksoch1881** [comment]
> Try increasing p15_n_loop_err_thre.
> 
> https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/batch_LiCSBAS.sh#L58

Thank you Dr. yumorishita. I changed it to 8, 12 and pixel seems to appear and when i finally change it to 20. I could see the full map. would you please kindly tell me what was wrong and how increasing '20' solved the problem...and since putting 20 seems to solve the problem  so if i keep increasing the results will improve or how much i can increase this value ? Is there upper limit?
![mask_ts](https://github.com/user-attachments/assets/fce9b7ef-0d39-4a46-9d02-31dcc97fedec)

**Comment by yumorishita** [comment]
Please read the [LiCSBAS paper](https://www.mdpi.com/2072-4292/12/3/424), especially sections 2.4.2 and 2.4.5.

**Comment by faraksoch1881** [comment]
Thank you Dr. Yumorishita for all your help and guidance.

**Comment by faraksoch1881** [comment]
> Please read the [LiCSBAS paper](https://www.mdpi.com/2072-4292/12/3/424), especially sections 2.4.2 and 2.4.5.

Though i markdown as closed, a final doubt i have is I look at the png files inside folder GEOCml1clip and found two interferograms divided as center by a line. is that a source of this problem? will removing them and running processing can solve it and give better results ? Below are the two interferograms which i suspect be the culprit.

![20171003_20171015 unw](https://github.com/user-attachments/assets/7944825f-688d-4984-ad8f-049186e1bfd4)
![20171027_20171202 unw](https://github.com/user-attachments/assets/28cb3e1e-54c5-4583-9265-6d7357cf3c99)

**Comment by faraksoch1881** [comment]
Thank you. Finally solved the problem !
