### ISSUE TITLE
cum2tstxt use cum.h5 only

### ISSUE THREAD

**Issue by NabilAttar** [yumorishita/LiCSBAS#398]
greeting Mr. Yumorishita

i want to extract time series use cum.h5 only because cum_filt.h5 is corrupt (i have process with the large area). how to extract cum.h5 correctly?

![image](https://github.com/user-attachments/assets/8bd97902-f099-47db-a51e-9b48aa4b6332)

**Comment by yumorishita** [comment]
Please try adding `--nomask` option.

**Comment by NabilAttar** [comment]
> Please try adding `--nomask` option.

Excuse me sir, how can i add --nomask option? Thank you

**Comment by yumorishita** [comment]
`LiCSBAS_cum2tstxt.py -g 97.26157/5.02922 -i cum.h5 --nomask`

**Comment by NabilAttar** [comment]
its work sir, thank you very much
