### ISSUE TITLE
Question about 

### ISSUE THREAD

**Issue by mohseniaref** [yumorishita/LiCSBAS#4]
Hi ,

I have seen in the paper that you produced annual amplitude and phase for InSAR displacement. I was wondering if you consider harmonic parameter in SBAS inversion? I wanted to reproduce it but I couldn't find these parameter in LiCSBAS13_sb_inv.py . Would you please inform me if there is possibility to reproduce similar result using LiCSBAS?

Regarding atmospheric correction,Do you have plan to use another product like ERA5 instead of GACOS? It take very long time to request and download GACOS product.What's the main advantage of GACOS in comparison of other atmospheric model?

Best,
M

**Comment by yumorishita** [comment]
The annual parameters are calculated at the post-processing stage by a command LiCSBAS_cum2vel.py with --sin option using cumulative displacement data (cum_filt.h5) after all steps are done. No temporal function or only linear function is used if there is no gap or there is a gap, respectively, during the SB inversion.

I have currently no plan to integrate other atmospheric products. GACOS service is in the COMET group and closely collaborates with LiCS. 
The corresponding GACOS data to each epoch/interferogram will become available soon along with the LiCSAR products, which means you will no longer need to request the GACOS product yourself.
