### ISSUE TITLE
LiCSBAS_cum2vel.py error

### ISSUE THREAD

**Issue by sizzer13-13** [yumorishita/LiCSBAS#40]
I met a problem when run LiCSBAS_cum2vel.py. Could you help me with that?

LiCSBAS_cum2vel.py ver1.3 20200703 Y. Morishita
LiCSBAS_cum2vel.py 
Traceback (most recent call last):
  File "/Users/local/Program/LiCSBAS/bin/LiCSBAS_cum2vel.py", line 285, in <module>
    sys.exit(main())
  File "/Users/local/Program/LiCSBAS/bin/LiCSBAS_cum2vel.py", line 154, in main
    refx1, refx2, refy1, refy2 = [int(s) for s in re.split('[:/]', refarea)]
  File "/Users/local/licsbas/lib/python3.7/re.py", line 213, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object

Thank you for consideration.

**Comment by yumorishita** [comment]
Can you type following commands and show me the output?

```
python3
>>> import h5py
>>> print(h5py.File('cum_filt.h5','r')['refarea'][()])
```

**Comment by sizzer13-13** [comment]
It occurs:

b'62:63/111:112'

**Comment by yumorishita** [comment]
I cannot reproduce the situation in my environment. Could you tell me about your environment (e.g., OS, $LANG)? Also how about the output of the following commands?

```
python3
>>> import h5py
>>> print(h5py.File('cum.h5','r')['refarea'][()])
```

As a temporary solution, I think the error can be avoided by editing the code:
`refarea = cumh5['refarea'][()].decode('utf-8')`
https://github.com/yumorishita/LiCSBAS/blob/ee9a54c3e344ab6147e71f1692ef45022548eff4/bin/LiCSBAS_cum2vel.py#L153

**Comment by sizzer13-13** [comment]
Sorry.
Mine is OS system.
It seems the problem has been solved by your replacement in the code.

Thank you again.

**Comment by yumorishita** [comment]
Although I cannot reproduce this error in my environment, I have modified the codes to avoid it because the error reports have been increasing.
https://github.com/yumorishita/LiCSBAS/commit/7637465c7b8687ea2910954246452d9cf946c96a

Please update the LiCSBAS module and try again.
