### ISSUE TITLE
Axis limits cannot be NaN or InF when using Gacos correction

### ISSUE THREAD

**Issue by faraksoch1881** [yumorishita/LiCSBAS#401]
Hello Dr. Yumorishita
I changed the "do03op_GACOS="y"" in batch script file and used the command 'LiCSBAS01_get_geotiff.py --get_gacos" to download the Gacos data set in the default folder. I downloaded the missing files manually and placed them inside same folder. I manually downloaded files by using input of lon1\lon2\lat1\lat2 more then frame size to make sure that it covers entire area ( as i read form comments that there will be errors if Gacos data don't contain study area" though my study is very small which i used clip property to crop image form whole frame. Just for information the file i downloaded from Gacos website is named as ztd..tif and files automatically downloaded has a name sltd.geo.tif, if it is something needs to be taken notice. 
Also the file size the LiCSBAS downloaded is around 13 MB but file i downloaded manually from Gacos webiste is not more then 500 KB. 

then i ran the batchscript and now and it is giving me an error of

`
  File "/home/sagar/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 3585, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf

`

Here is my logfile
[202409061743batch_LiCSBAS_01_16.log](https://github.com/user-attachments/files/16913620/202409061743batch_LiCSBAS_01_16.log)

 and my file directory image
![file_directory](https://github.com/user-attachments/assets/026936a6-e111-41ef-874f-d20c5518bbc7)

How to solve this issue ?

**Comment by yumorishita** [comment]
I guess the manually downloaded files have something wrong. Please check if all the files cover the AOI.

**Comment by faraksoch1881** [comment]
It should be pretty basic question but is there any text file where i can get list of files name whose gacos data is not availaible after running step 01. The new folder is created with name GACOS and i want to download the missing files manually from GACOS website to apply atmospheric correction.

**Comment by yumorishita** [comment]
Just `ls` and compare the list.

**Comment by as1234554321** [comment]
Hi sir, 
I have succeeded in processing the data to the ts plot, but when I look at the log it says something like this, what does that mean, does it affect the results?
1) "GACOS data for the following dates are missing". Do I have to download it manually?
![image](https://github.com/user-attachments/assets/a3d2ac4d-9e0b-42af-8a9f-da6cd23f0eb0)
2)the percentage of masked files is higher than kept, is it better to mask/kept with a high percentage? how to increase the percentage?
![image](https://github.com/user-attachments/assets/d1ae4ebf-c5be-493a-8a4e-217982930295)
3)how to get ztd?
![image](https://github.com/user-attachments/assets/b2c07a47-6958-4edd-bb74-7ea1c63af2c7)
thankyou

**Comment by yumorishita** [comment]
1. You don't have to, but you can do it.
2) It seems to be not bad.
3) http://www.gacos.net/
2. Generally I recommend a masked one,

**Comment by as1234554321** [comment]
Thankyou sir
> 1. You don't have to, but you can do it.
I wrote the end date "20240715" but the GACOS data (get gacos option 0-3) is only up to 20240219. UNW and CC data is up to 20240715. Is there a big influence on the LOS results? 
> 2. It seems to be not bad
Does the percentage of the size of the mask and kept pixels have no effect?
better higher mask pixels or kept pixels?
> 3. http://www.gacos.net/
> 4. Generally I recommend a masked one,
which file is better to use for decomposition vel.mskd or vel.filter.mskd?

**Comment by yumorishita** [comment]
1. I don't know.
2. The better the more the kept pixels, but the masked result seems to be acceptable because the deformation is captured.
3. 
4. vel.filt.mskd

**Comment by faraksoch1881** [comment]
Thank you !!

**Comment by as1234554321** [comment]
thankyou sir, 
Hi sir,  I want ask again
the results of licsbas processing in the area I studied showed a velocity value (+) while gmtsar processing (-) and supported by paper in the area also velocity (-). Both processing (licsbas and gmtsar) use the same time period
1) what causes the anomaly in the processing results in licsbas processing? 
2) what affects these results?

**Comment by as1234554321** [comment]
4. vel.filt.mskd
why you recommended this file for decomposed? 
in the png file the vel data. mskd and vel.filt mskd look the same, why do you suggest vel.filt.mskd? in the decompose formula in files.txt it says vel. MSKD. Sorry, I'm confused
