### ISSUE TITLE
identifying and Removing bad interferograms

### ISSUE THREAD

**Issue by faraksoch1881** [yumorishita/LiCSBAS#403]
Hi Dr. Yumorishita,
I was going through several past issues and found that apart from looking at last column of bad_ifg.txt file which has *nan values for bad interferograms, we also need to look at each interferogram inside folder "GEOCml1" which might also contain bad interferograms. I identified 3 such interferograms from  frame "085A_06253_131313 ". I added interferogram (1), for reference which i think is good interferogram. 

Interferogram (2) contains colored speckles scattered, should i remove it? is that a bad interferogram? 

Interferogram (3), is there was error during deburst ? Is that also a bad interferogram and should i remove such interferogram?

Finally interferogram(4) is cut into half and only top part is visible, there are few of them should i remove them? will keeping them is good idea or they will contribute to bad results?
![sag](https://github.com/user-attachments/assets/e3285009-1958-4e3a-9986-8fcecd5abd9f)

The value of four interferogram from ifg_stats.txt is
```plaintext
# ifg dates         bperp   dt unw_cov  coh_av
20230801_20230825  -168.0   24   0.857   0.216
20230825_20231012   337.2   48   0.786   0.147 
20231129_20231223    17.9   24   0.995   0.389 
20240409_20240527   -11.1   48   0.611   0.082
```

#Also looking at the whole ifg_stats.txt , it appears that average coherence 
<img width="144" alt="fre" src="https://github.com/user-attachments/assets/9131857a-e38f-4a76-87c6-c52b40ee45a5">

(0.5 - 0.4): 45 interferogram
(0.3 to 0.4): 131 interferogram
(0.2 to 0.3): 419 interferogram
(0.1 to 0.2): 379 interferogram
Less than )0.1: 25) interferogram

As most interferogram has average coherence between 0.2 - 0.3, will you suggest 0.2 as good thershold average coherence ?

**Comment by yumorishita** [comment]
These issues are caused by the LiCSAR system, not LiCSBAS. I would suggest you contact COMET. LiCSBAS cannot solve such an issue.

**Comment by faraksoch1881** [comment]
> These issues are caused by the LiCSAR system, not LiCSBAS. I would suggest you contact COMET. LiCSBAS cannot solve such an issue.

Thank you reply Dr. Yumorishita. Sorry for misunderstanding..i wanted to know how to identify bad interferograms visually. Here the first is good interferogram but i'm not sure about rest three. Second appears to contains many colored speckles scattered which appears to be bad interferogram and third one seems to have deburst problem and fourth is sliced in half which i assume if i don't remove might cause problem in licsbash. I wanted your opinion if my assumption are good or am i make any mistake here.

**Comment by yumorishita** [comment]
Yes, all three interferograms have problems and should be removed.

**Comment by faraksoch1881** [comment]
> Yes, all three interferograms have problems and should be removed.

Thank you Dr. Yumorishita for informaiton. I was wondering is there anyway to convert the coordinates of reference point from  x/y to geographical coordinat in time series plot. how to interpret the coordinates in x/y displayed in time series displacement to geographical coordinates so it would be easier to see in google map where is the reference area exactly .

**Comment by yumorishita** [comment]
Lat/lon at the selected points are displayed at the right top of the the time series graph window.
https://raw.githubusercontent.com/wiki/yumorishita/LiCSBAS/images/sample_ts.png

**Comment by faraksoch1881** [comment]
Thnak you yumorishita...your comments has been a very informative and helpful in solving many issues. I have final questions..is there way to plot such plots in LiCSABAS. Which files contain coherence results so that i can plot and interpret the quality of coherence. these are examples from Mintpy. 

![image (3)](https://github.com/user-attachments/assets/ff5073e6-148c-46e1-b758-4c03ad9158af)
![image (2)](https://github.com/user-attachments/assets/a19edb7c-5c62-42c5-8f66-aefbd13ed3e5)
![image (1)](https://github.com/user-attachments/assets/14ebb6ea-693a-4311-8a0f-ea3399b200f9)

**Comment by yumorishita** [comment]
There is no function to plot such images, but the coherence information is saved in TS_GEOCml*/info/11ifg_stats.txt. You can read the file to plot the images.
