### ISSUE TITLE
gacos correction error

### ISSUE THREAD

**Issue by maulanaheno** [yumorishita/LiCSBAS#408]
LiCSBAS03op_GACOS.py ver1.5.5 20201119 Y. Morishita
LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOCml1GACOS

Convert ztd/sltd.geo.tif files to sltd.geo files...
   20/ 20 sltd already exist. Skip

Correct unw data...
   76/ 76 corrected unw already exist. Skip

Traceback (most recent call last):
  File "/home/maulanaheno/LiCSBAS2/bin/LiCSBAS03op_GACOS.py", line 549, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/maulanaheno/LiCSBAS2/bin/LiCSBAS03op_GACOS.py", line 368, in main
    plot_lib.plot_gacos_info(gacinfofile, pngfile)
  File "/home/maulanaheno/LiCSBAS2/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 152, in plot_gacos_info
    xylim1 = np.max(np.concatenate((std_bf, std_af)))+1
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/numpy/core/fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation maximum which has no identity

can you help me to fix this issue??

**Comment by maulanaheno** [comment]
> LiCSBAS03op_GACOS.py ver1.5.5 20201119 Y. Morishita LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOCml1GACOS
> 
> Convert ztd/sltd.geo.tif files to sltd.geo files... 20/ 20 sltd already exist. Skip
> 
> Correct unw data... 76/ 76 corrected unw already exist. Skip
> 
> Traceback (most recent call last): File "/home/maulanaheno/LiCSBAS2/bin/LiCSBAS03op_GACOS.py", line 549, in sys.exit(main()) ^^^^^^ File "/home/maulanaheno/LiCSBAS2/bin/LiCSBAS03op_GACOS.py", line 368, in main plot_lib.plot_gacos_info(gacinfofile, pngfile) File "/home/maulanaheno/LiCSBAS2/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 152, in plot_gacos_info xylim1 = np.max(np.concatenate((std_bf, std_af)))+1 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/numpy/core/fromnumeric.py", line 2810, in max return _wrapreduction(a, np.maximum, 'max', axis, None, out, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction return ufunc.reduce(obj, axis, dtype, out, **passkwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: zero-size array to reduction operation maximum which has no identity
> 
> can you help me to fix this issue??

I already found the problem, its because the reduction rate after gacos correction of all ifg are negative. But what negative reduction rate means? could you explain it?

**Comment by yumorishita** [comment]
Please read the paper: https://www.mdpi.com/2072-4292/12/3/424#sec2dot3dot3-remotesensing-12-00424
