### ISSUE TITLE
generate interferograms

### ISSUE THREAD

**Issue by Alenhasha** [yumorishita/LiCSBAS#410]
Hi,

I hope you’re doing well. I’m currently working on a project and I need to generate interferograms using specific Sentinel-1 image pairs that I’ve manually selected. Could you guide me on how to create interferograms based on custom image pairs?

Thank you in advance!

**Comment by Alenhasha** [comment]
Thank you for your prompt response. I understand that generating interferograms using custom image pairs may be outside the scope of LiCSBAS. However, if you have any guidance or resources that could help me with this task, I would greatly appreciate it.

**Comment by yumorishita** [comment]
https://github.com/isce-framework/isce2
https://github.com/gmtsar/gmtsar
https://step.esa.int/main/download/snap-download/
