### ISSUE TITLE
Formula used for LOS decomposition 

### ISSUE THREAD

**Issue by faraksoch1881** [yumorishita/LiCSBAS#411]
Hi Dr, Yumorishita

i read your paper but couldn’t find what formula was used to get UD and EW component using asc and dsc displacement. Can i get link to source of forumla used ?

and here is website i created using your LiCSBAS. Hope you like it
[LiCSBAS Implementation ](https://ktmsub.alwaysdata.net/)

User can view, download timeseries or comment in each points in website

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/344

**Comment by faraksoch1881** [comment]
> #344

Thank you !!
