### ISSUE TITLE
Step16 error about ArrayMemoryError

### ISSUE THREAD

**Issue by shubham-rajewar** [yumorishita/LiCSBAS#414]
Hello Sir,
Sorry to bother you again. During processing I'm facing problem at step 16. Please suggest cause of this error.

LiCSBAS16_filt_ts.py -t TS_GEOCml1GACOSmask

Size of image (w,l)      : 3338, 2685
Number of images         : 109
Width of filter in space : 2 km (22.5x18.0 pixel)
Width of filter in time  : 0.129 yr (46 days)
Deramp flag              : []
hgt-linear flag          : False
Traceback (most recent call last):
  File "/home/gps7/LiCSBAS2/bin/LiCSBAS16_filt_ts.py", line 853, in <module>
    sys.exit(main())
  File "/home/gps7/LiCSBAS2/bin/LiCSBAS16_filt_ts.py", line 430, in main
    cum = np.zeros((cum_org.shape), dtype=np.float32)*np.nan
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.64 GiB for an array with shape (109, 2685, 3338) and data type float32

**Comment by yumorishita** [comment]
I have never seen such an error, but it probably means the memory in your machine is not enough.
See https://github.com/yumorishita/LiCSBAS2/issues/82#issuecomment-2431782611

**Comment by shubham-rajewar** [comment]
Ok, 
Right maybe the problem with my system. I'll check.
Thank you

**Comment by shubham-rajewar** [comment]
I have one query about master and slave images.
How do I get information about that? How does LiCSBAS select master and slave for processing, and is it possible to manually select our choice of master and slave image during processing?
Please suggest any solution regarding this.
Thank you!
