### ISSUE TITLE
"All pixels are masked" error

### ISSUE THREAD

**Issue by geomaticss** [yumorishita/LiCSBAS#415]
first of all hello there. i was going to get my geoclip file as a result of a very long time process but i realized that all pixels were masked. you can see the relevant part of the code below. what could be the reason? how can i fix it? also do i need to redo the whole process? it really took a lot of time...

"....
  Elapsed time for 1th patch: 106 sec

Output png images...

Elapsed time: 00h 01m 46s

LiCSBAS14_vel_std.py Successfully finished!!

Output directory: TS_GEOCml1clip

LiCSBAS15_mask_ts.py ver1.8.1 20200911 Y. Morishita
LiCSBAS15_mask_ts.py -t TS_GEOCml1clip

All pixels would be masked with n_ifg_noloop thre of 50
Automatically change the thre to 52.0 (ceil of min value)

Noise index    : Threshold  (rate to be masked)
- coh_avg      : 0.05       ( 0.0%)
- n_unw        :  624       ( 0.0%)
- vstd         :  100 mm/yr ( 0.0%)
- maxTlen      :    1 yr    ( 0.0%)
- n_gap        :   10       ( 0.0%)
- stc          :    5 mm    ( 0.0%)
- n_ifg_noloop : 52.0       (100.0%)
- n_loop_err   :    5       (52.7%)
- resid_rms    :    2 mm    ( 6.9%)

Masked pixels  : 63509/63510 (100.0%)
Kept pixels    : 1/63510 (0.0%)

All pixels are masked!!
Try again with different threshold."

I worked with a dataset that is almost 10 years old so there are a lot of image pairs etc. I had previously experimented with 6-7 year old datasets in different regions and did not encounter such a problem. thank you in advance for your reply.

**Comment by yumorishita** [comment]
Try increasing p15_n_ifg_noloop_thre to >52 and rerun from step15.
https://github.com/yumorishita/LiCSBAS/blob/master/batch_LiCSBAS.sh#L57

**Comment by geomaticss** [comment]
![image](https://github.com/user-attachments/assets/7827ae65-ef73-43c9-ae47-9827750cb5bd)

sir thank you for your quick reply. i updated “n_ifg_noloop” for a higher value as you said and ran the command related to the updated code. but it continues to see the default value of 50 again, what could be the reason?  you can see the problem in the attachment
