### ISSUE TITLE
About pixel size

### ISSUE THREAD

**Issue by faraksoch1881** [yumorishita/LiCSBAS#417]
Hi Dr. Yumorishita,
In your paper, it is mentioned that "**Wrapped and unwrapped interferograms and coherence images are geocoded with a pixel spacing of 0.001 degree (~100 m) and converted to the GeoTIFF format"**, does that mean if i plot time series from cum_filt.h5, or produce text file using LiCSBAS_cum2tstxt.py and any lat/lon, it is average value within 10000 sq meter area ? if pixel size is 100m , i assume total area would be the size of pixel 100m×100m.

**Comment by yumorishita** [comment]
Yes, it is not a simple average but similar to it.

**Comment by faraksoch1881** [comment]
Thank you !!
