### ISSUE TITLE
Error in step 1

### ISSUE THREAD

**Issue by Bekir3343** [yumorishita/LiCSBAS#421]
Hi, I am getting this error when I start the process.

/home/bekir/LiCSBAS2/LiCSBAS_lib/LiCSBAS_tools_lib.py:607: SyntaxWarning: invalid escape sequence '\d'
  if re.match('[+-]?\d+(?:\.\d+)?/[+-]?\d+(?:\.\d+)?/[+-]?\d+(?:\.\d+)?/[+-]?\d+(?:\.\d+)?', range_str):
/home/bekir/LiCSBAS2/LiCSBAS_lib/LiCSBAS_tools_lib.py:628: SyntaxWarning: invalid escape sequence '\d'
  if re.match('[+-]?\d+(?:\.\d+)?,[+-]?\d+(?:\.\d+)?/[+-]?\d+(?:\.\d+)?,[+-]?\d+(?:\.\d+)?', range_str):

LiCSBAS01_get_geotiff.py ver1.6.5 20240607 Y. Morishita
LiCSBAS01_get_geotiff.py -s 20140101 -e 20231023 --get_gacos

Frame ID is 077D_05487_141313

Download 077D_05487_141313.geo.E.tif
    HTTPError for 077D_05487_141313.geo.E.tif in 1th try
    HTTPError for 077D_05487_141313.geo.E.tif in 2th try
    HTTPError for 077D_05487_141313.geo.E.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/77/077D_05487_141313/metadata/077D_05487_141313.geo.E.tif
Download 077D_05487_141313.geo.N.tif
    HTTPError for 077D_05487_141313.geo.N.tif in 1th try
    HTTPError for 077D_05487_141313.geo.N.tif in 2th try
    HTTPError for 077D_05487_141313.geo.N.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/77/077D_05487_141313/metadata/077D_05487_141313.geo.N.tif
Download 077D_05487_141313.geo.U.tif
    HTTPError for 077D_05487_141313.geo.U.tif in 1th try
    HTTPError for 077D_05487_141313.geo.U.tif in 2th try
    HTTPError for 077D_05487_141313.geo.U.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/77/077D_05487_141313/metadata/077D_05487_141313.geo.U.tif
Download 077D_05487_141313.geo.hgt.tif
    HTTPError for 077D_05487_141313.geo.hgt.tif in 1th try
    HTTPError for 077D_05487_141313.geo.hgt.tif in 2th try
    HTTPError for 077D_05487_141313.geo.hgt.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/77/077D_05487_141313/metadata/077D_05487_141313.geo.hgt.tif

Download baselines
    HTTPError for baselines in 1th try
    HTTPError for baselines in 2th try
    HTTPError for baselines in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/77/077D_05487_141313/metadata/baselines
Download network.png
    HTTPError for network.png in 1th try
    HTTPError for network.png in 2th try
    HTTPError for network.png in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/77/077D_05487_141313/metadata/network.png
Download metadata.txt
    HTTPError for metadata.txt in 1th try
    HTTPError for metadata.txt in 2th try
    HTTPError for metadata.txt in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/77/077D_05487_141313/metadata/metadata.txt

Searching latest epoch for mli...

No mli available on https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/77/077D_05487_141313/epochs/

Download GACOS data
  There are 0 epochs from 20140101 to 20231023
  Searching available epochs (4 parallel)...
No GACOS data available from 20140101 to 20231023

Download geotiff of unw and cc
Traceback (most recent call last):
  File "/home/bekir/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 502, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bekir/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 342, in main
    print('{} IFGs available from {} to {}'.format(n_ifg, imdates[0], imdates[-1]), flush=True)
                                                          ~~~~~~~^^^
IndexError: list index out of range

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2173156010

**Comment by Bekir3343** [comment]
Thank you for your reply.
