### ISSUE TITLE
n_loop_err

### ISSUE THREAD

**Issue by Bekir3343** [yumorishita/LiCSBAS#425]
Hi, in step 12, while creating the n_loop_err file, the 12bad_ifg.txt file is removed. However, I do not use the bad_ifg_cand ifgs in step 13. For this reason, in the masking process of step 15, the n_loop_err file is also used with the files containing the bad_ifg_cand ifgs. What can I do to not use them when creating the n_loop_err file?

**Comment by yumorishita** [comment]
bad_ifg_cand is just candidates of bad ifgs and therefore is not removed from the following steps. If you want to remove more ifgs as bad ones, decrease `p12_loop_thre` or use `p12_rm_ifg_list`.

**Comment by Bekir3343** [comment]
After doing step 12 I need to add the bad_ifg_cand list to p12_rm_ifg_list and run step 12 again, thanks.
