### ISSUE TITLE
Reference point

### ISSUE THREAD

**Issue by Bekir3343** [yumorishita/LiCSBAS#426]
Hi, , I get this error when I determine the reference point myself. I tried different regions with both pixel and geographic references. The result was always the same, the work area turns into a mixture of red and blue at different dates.

![Ekran görüntüsü 2024-12-05 181711](https://github.com/user-attachments/assets/ffb854f5-995f-4b9f-891b-93cf397fa9a4)

**Comment by yumorishita** [comment]
`93.67/93.67/35.30/35.30` means no area. You must give different lat/lon values to specify the reference area, e.g., `93.66/93.68/35.29/35.31`.

**Comment by Bekir3343** [comment]
I think I'm getting an error about there being no data there after masking. Can you help me out with this mask? Is it the mask applied in step 15 or is it another mask created for filtering in step 16?

**Comment by yumorishita** [comment]
The mask is created only in step15.

**Comment by Bekir3343** [comment]
Thanks, I'll try changing the mask parameters.
