### ISSUE TITLE
Automatically search for the Frame ID corresponding to the specified longitude and latitude

### ISSUE THREAD

**Issue by LiuXu4512** [yumorishita/LiCSBAS#429]
Hello, how can I use COMET-LiCS Sentinel-1 InSAR portal to search for the Frame ID of the LiCSAR data covering the location based on the longitude and latitude? I see that the Frame ID can only be entered manually in the LiCSABS software package, but I want to write a program to download multiple files at once, so I have to automatically search for the Frame ID by longitude and latitude. How can I do this?

**Comment by yumorishita** [comment]
I have no good idea. Please ask COMET.

**Comment by LiuXu4512** [comment]
OK，thank you very much
