### ISSUE TITLE
calculation crashed？

### ISSUE THREAD

**Issue by CalvinDrStar** [yumorishita/LiCSBAS#43]
Dear Prof. Morishita,

I ran the tutorial case study successfully. Then I just applied your program to the area which I am interested in. Then, it seems that Steps1(get_geotiff.py)～15(mask_ts.ps) were all successfully finished, however, when it comes to "LiCSBAS16_filt_ts.py -t TS_GEOCmllclip", 
"
HP filter in time, LP filter in space
with 8 parallel processing....
    0/23th image....
    10/23th image....
    20/23th image.... 
"
The program stayed in this state for 10 hours and still didn't make progress. I re-ran the program again, however, the program was still stocked in this part.
I don't know if it's because my laptop's performance is poor or because the selected area is too large.

Thanks for your assistance in the issue.
Respectfully submitted.

**Comment by yumorishita** [comment]
Can you try with n_para="1"?
https://github.com/yumorishita/LiCSBAS/blob/ee9a54c3e344ab6147e71f1692ef45022548eff4/batch_LiCSBAS.sh#L24

**Comment by CalvinDrStar** [comment]
Roger that, I will try it now. Thanks a lot.

**Comment by CalvinDrStar** [comment]
It works, thank you so much Prof.
