### ISSUE TITLE
About the output units of LiCSBAS

### ISSUE THREAD

**Issue by sakuya-izayoi-0518** [yumorishita/LiCSBAS#433]
Mr.Morishita 

I have a question.
I believe that the displacement velocity and displacement amount calculated by LiCSBAS are in the LOS direction (with positive values indicating movement toward the satellite's line of sight). 
In this case, are the units 「mm/year」 and 「mm」 correct?

Thank you.

**Comment by yumorishita** [comment]
Yes, the units are mm/yr and mm.

**Comment by sakuya-izayoi-0518** [comment]
Mr.Morishita

Thank you for answer.

I’d like to confirm something. 
In LiCSBAS, is it correct to interpret that for displacement and displacement velocity, a positive value indicates movement towards the satellite's line-of-sight?
`https://github.com/yumorishita/LiCSBAS/issues/294`

On the other hand, the Geospatial Information Authority of Japan (GSI)'s SBAS results state that positive values for displacement velocity indicate movement away from the satellite. Could this be due to differences in software?
`https://www.gsi.go.jp/uchusokuchi/sar_tsa.html`

**Comment by yumorishita** [comment]
Yes.

**Comment by sakuya-izayoi-0518** [comment]
Mr.Morishita

Thank you！！
