### ISSUE TITLE
Error when plotting Networks

### ISSUE THREAD

**Issue by faraksoch1881** [yumorishita/LiCSBAS#435]
Hi Dr. Yumorishita,

I'm trying to plot the generate spatial and temporal baseline plots using LiCSBAS_plot_network.py. 

The command i gave is
LiCSBAS_plot_network.py -i my_ifg.txt -b my_bprep.txt

and it throws error
`
LiCSBAS_plot_network.py ver1.0 20200225 Y. Morishita
LiCSBAS_plot_network.py -i net_b.txt -b net_a.txt
ERROR: bperp for 20230505 not found!
Traceback (most recent call last):
  File "/home/sagar/Downloads/LiCSBAS2-master/bin/LiCSBAS_plot_network.py", line 131, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sagar/Downloads/LiCSBAS2-master/bin/LiCSBAS_plot_network.py", line 115, in main
    plot_lib.plot_network(ifgdates, bperp, bad_ifgdates, pngfile, plot_bad_flag)
  File "/home/sagar/Downloads/LiCSBAS2-master/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 256, in plot_network
    plt.plot([imdates_dt_all[ix_m], imdates_dt_all[ix_s]], [bperp[ix_m],
                                                            ~~~~~^^^^^^
`

Here this line 'ERROR: bperp for 20230505 not found!' was saying bperp is not found, but when i check my_ifg.txt and my_bpre.txt, it does exist. But still i remove any line with 20230505 , and it created the plot. So i was wondering what could be issue here. 

[Small this i noticed is that the my_ifg.txt should have format (format: yyyymmdd yyyymmdd bperp dt)

and the date should appear in both first and second column. 20230505 was only on first column but not in second column but any other date i picked was in both column. The date highlighted in yellow color cannot be found on second column but any other date highlighted by red box can be found in both column. May be it can be reason for the error and if it is then why it is causing the problem. i have uploaded both my_ifg.txt and my_brep.txt file as well. [
[my_bprep.txt](https://github.com/user-attachments/files/18264034/my_bprep.txt)
[my_ifg.txt](https://github.com/user-attachments/files/18264035/my_ifg.txt)
](url)
![error_](https://github.com/user-attachments/assets/6f96675b-6b30-496a-af6b-7e469af0aa7d)

**Comment by yumorishita** [comment]
20230505 exist only in the first column of my_bprep.txt. Please add a ifg pair with the secondary image of 20230505.

**Comment by yumorishita** [comment]
Also the format of my_bprep.txt is wrong. If it has 4 columns, the 1st column is the date of the single primary and therefore constant value.

https://github.com/yumorishita/LiCSBAS/blob/5ca6550c8adbcb90e47aefc338d36ef33e122f03/LiCSBAS_lib/LiCSBAS_io_lib.py#L127

**Comment by faraksoch1881** [comment]
Thank you Dr. Yumorishita for reply,  I used the 11ifg_stats.txt to get those information. I then splitted the text for example '20170112_20170118' before underscore to separate into two column 
20170112 20170118

and rest two column i used from same .txt file 11ifg_stats. I have a huge dataset of more then 1K such pairs. where can i find info for ifg pair other then 11ifg_stats.txt to use it for plotting network

Also you suggested 1st column needs to be constant but 11ifg_stats.txt has different dates joined by _ sign. Hence I different date appeared in my_bprep.txt file where i just splitted two dates in excel using formula. So the first column should be the first date throughout the entire column ? and what should i used in second column, where i can find the dates to use in second column? please find my ifg_stats.txt file

[11ifg_stats.txt](https://github.com/user-attachments/files/18268466/11ifg_stats.txt)

**Comment by faraksoch1881** [comment]
finally i find the solution, the info of bprep is in baseline in folder GEOcml* which is formed before TS. Thank you Dr. for guidance.

**Comment by as1234554321** [comment]
Hi sir, I want to ask something
 1) how to find out master data, total interferogram, temporal baseline, perpendicular baseline?
 2) What is the determination of a master at LICSBAS based on?

**Comment by yumorishita** [comment]
There is no particular single prime data in LiCSBAS. Please see GEOC*/baselines for the baseline information.
