### ISSUE TITLE
LiCSBAS03op_GACOS.py : Is there a small problem with atmospheric difference

### ISSUE THREAD

**Issue by EllenLee183** [yumorishita/LiCSBAS#44]
When using GACOS atmospheric products to perform unwrapping phase correction, the atmospheric phase difference in your script is to subtract the atmospheric phase of the master image from the atmospheric phase of the slave image. Is this the opposite of the interference phase of the GAMMA software?

**Comment by yumorishita** [comment]
I am not sure about the GAMMA's definition. Since the LiCSAR interferograms (date1_date2) have phase difference of date2 with reference to date1, the atm phase to be subtracted from ifgs should also be date2-date1.

**Comment by EllenLee183** [comment]
Thank you for your answer. In GAMMA, it is true that the phase of the Master image is subtracted from the phase of the slave image. When the unwrapping result of gamma is used, then the sign needs to be modified during atmospheric correction.
