### ISSUE TITLE
Question about the filtered result

### ISSUE THREAD

**Issue by SiyuanZhao1** [yumorishita/LiCSBAS#46]
Dear Morishita

Thanks for sharing LiCSBAS, I think it is remarkable. I met two issues when I use it, hope can get some help.

The first question is about the filtered result. I can find an obvious gap between the filtered velocity result and unfiltered velocity result, and comparing the cumulative displacements at each acquisition epoch in filter and no filter situation respectively, the difference is quite large. But in the example showed in your paper (Morishita et al., 2020), the difference is not that big. Do you have any clue about why this happened?

The second question is about the velocity map I got. Theoretically, most of the deformation should concentrate at the upper part of the map I showed, but the velocity result shows the deformation also occured at the lower part of the map. Is it because that there is not stable reference area on the unwrapped images? Is there any way we can do to force the far field deformation to zero? 

Thanks very much!

<img width="889" alt="Filtered_velocity" src="https://user-images.githubusercontent.com/51397425/100612580-55db1000-3367-11eb-9395-1f27a1e9fffa.png">

<img width="868" alt="Velocity_map" src="https://user-images.githubusercontent.com/51397425/100617041-08ae6c80-336e-11eb-9161-bcbddc44afa4.png">

[202011302322batch_LiCSBAS_02_16.log](https://github.com/yumorishita/LiCSBAS/files/5615990/202011302322batch_LiCSBAS_02_16.log)

**Comment by yumorishita** [comment]
Thank you for using LiCSBAS. The big difference between the filtered and unfiltered time series is generally caused by the atmospheric noise, which is large at far place from the reference. If you select a reference point (by right drag) near the point at which the time series is shown, you will see small difference because the effect of the atmospheric noise is small.

Though I don't know why theoretically most of the deformation should concentrate at the upper part, the deformation in the lower part might be caused by atmospheric noises or orbital errors. It might be worth trying the GACOS correction in step1-3 (unless you have used it), or using an deramping option in step1-6.
https://github.com/yumorishita/LiCSBAS/blob/4cab0af0f59107a0f119174a735e27aa04626737/batch_LiCSBAS.sh#L55

**Comment by SiyuanZhao1** [comment]
> Thank you for using LiCSBAS. The big difference between the filtered and unfiltered time series is generally caused by the atmospheric noise, which is large at far place from the reference. If you select a reference point (by right drag) near the point at which the time series is shown, you will see small difference because the effect of the atmospheric noise is small.
> 
> Though I don't know why theoretically most of the deformation should concentrate at the upper part, the deformation in the lower part might be caused by atmospheric noises or orbital errors. It might be worth trying the GACOS correction in step1-3 (unless you have used it), or using an deramping option in step1-6.
> https://github.com/yumorishita/LiCSBAS/blob/4cab0af0f59107a0f119174a735e27aa04626737/batch_LiCSBAS.sh#L55

**Comment by SiyuanZhao1** [comment]
> Thank you for using LiCSBAS. The big difference between the filtered and unfiltered time series is generally caused by the atmospheric noise, which is large at far place from the reference. If you select a reference point (by right drag) near the point at which the time series is shown, you will see small difference because the effect of the atmospheric noise is small.
> 
> Though I don't know why theoretically most of the deformation should concentrate at the upper part, the deformation in the lower part might be caused by atmospheric noises or orbital errors. It might be worth trying the GACOS correction in step1-3 (unless you have used it), or using an deramping option in step1-6.
> https://github.com/yumorishita/LiCSBAS/blob/4cab0af0f59107a0f119174a735e27aa04626737/batch_LiCSBAS.sh#L55

Thanks for the reply, I followed the suggestion about changing the reference point, and it works well, thanks.

About the second question, the reason I think the most of the deformation should concentrate at the upper part is because that the earthquake occured at the top of map, and all the time-series epoches I used here are two years data after the mainshock. So it is mainly shows the postseismic activity. I will try the deramp. I used GACOS correction, but for some images, it said like that " ztd file not available for 20190219_20190225", and in the following process, those no corrected images will be removed. But when I used the GACOS website to manually check the tropospheric delay data, they actually exist, do you have any idea why some data are not available when download them automatically? and can we use the data download from the GACOS.net manually do the correction ?  Thanks very much.

<img width="550" alt="Screen Shot 2020-12-01 at 2 00 09 am" src="https://user-images.githubusercontent.com/51397425/100626095-79a75180-3379-11eb-872a-4a80b24cf2cc.png">

**Comment by SiyuanZhao1** [comment]
I just notice that I accidently closed the issue,  sorry for that, and I reopened it. Thanks.

**Comment by yumorishita** [comment]
> But when I used the GACOS website to manually check the tropospheric delay data, they actually exist

What website did you see?

> do you have any idea why some data are not available when download them automatically?

Most of the frames do not have full GACOS data in the LiCSAR portal and therefore auto-downloading does not work. What frame are you processing? 

> can we use the data download from the GACOS.net manually do the correction (from the website I cannot find the sltd format file)? 

Sure. The ztd files can be used and are converted to sltd during the LiCSBAS processing.

**Comment by SiyuanZhao1** [comment]
> > But when I used the GACOS website to manually check the tropospheric delay data, they actually exist
> 
> What website did you see?
> 
> > do you have any idea why some data are not available when download them automatically?
> 
> Most of the frames do not have full GACOS data in the LiCSAR portal and therefore auto-downloading does not work. What frame are you processing?
> 
> > can we use the data download from the GACOS.net manually do the correction (from the website I cannot find the sltd format file)?
> 
> Sure. The ztd files can be used and are converted to sltd during the LiCSBAS processing.

The website I saw is "http://www.gacos.net/ ", I just input the date that the log said GACOS data is not available, and it turns out I can find the them. I used two frame, "032D_09854_070505" and "156A_09814_081406_2019" . Could you tell me how to add the manually downloaded ztd file into the LiCSBAS processing, I didn't find related step in batch_config file, do I need extra step for this? Thanks very much.

**Comment by yumorishita** [comment]
Just add the ztd and rsc files into the GACOS directory in your processing frame directory which have other sltd files (more specifically, into the directory specified by p03_gacosdir parameter, see below) and rerun step0-3.
https://github.com/yumorishita/LiCSBAS/blob/4cab0af0f59107a0f119174a735e27aa04626737/batch_LiCSBAS.sh#L76

**Comment by SiyuanZhao1** [comment]
> Thank you for using LiCSBAS. The big difference between the filtered and unfiltered time series is generally caused by the atmospheric noise, which is large at far place from the reference. If you select a reference point (by right drag) near the point at which the time series is shown, you will see small difference because the effect of the atmospheric noise is small.
> 
> Though I don't know why theoretically most of the deformation should concentrate at the upper part, the deformation in the lower part might be caused by atmospheric noises or orbital errors. It might be worth trying the GACOS correction in step1-3 (unless you have used it), or using an deramping option in step1-6.
> https://github.com/yumorishita/LiCSBAS/blob/4cab0af0f59107a0f119174a735e27aa04626737/batch_LiCSBAS.sh#L55

Thanks for the reply, but I just find a new issue on the filter results. You suggested to change the reference point, and it works when I plot the descending time-series. But when I start doing the ascending time-series, the filtered and unfiltered data show highly different trend in some area, and  for some area, the velocity directions are even different, even though I make the reference area and detected area quite close. I attached the time-series plot and corresponding reference area. Do you think it is normal, and would you mind to provide some suggestion about how to fix it ?  thanks very much.

<img width="700" alt="Screen Shot 2020-12-05 at 11 48 38 pm" src="https://user-images.githubusercontent.com/51397425/101243477-bf3a9480-3754-11eb-80da-89db49a91a63.png">

<img width="860" alt="Screen Shot 2020-12-05 at 11 49 04 pm" src="https://user-images.githubusercontent.com/51397425/101243482-c366b200-3754-11eb-9ead-4b73a10029e4.png">

<img width="691" alt="Screen Shot 2020-12-05 at 11 50 03 pm" src="https://user-images.githubusercontent.com/51397425/101243483-c497df00-3754-11eb-9fbc-b4de6664779d.png">

<img width="852" alt="Screen Shot 2020-12-05 at 11 50 38 pm" src="https://user-images.githubusercontent.com/51397425/101243485-c5307580-3754-11eb-82f4-8b4473acba60.png">

**Comment by yumorishita** [comment]
I think it is quite normal because the absolute value of the velocity is very small (a few mm/yr) and the length of the connected network is short (<1yr) which means the uncertainty of the velocity is large. The difference seems to be within the error range. You would need to use more data to obtain a better result.
Please read my paper:
https://www.mdpi.com/2072-4292/12/3/424/htm#sec3dot5-remotesensing-12-00424

**Comment by SiyuanZhao1** [comment]
> I think it is quite normal because the absolute value of the velocity is very small (a few mm/yr) and the length of the connected network is short (<1yr) which means the uncertainty of the velocity is large. The difference seems to be within the error range. You would need to use more data to obtain a better result.
> Please read my paper:
> https://www.mdpi.com/2072-4292/12/3/424/htm#sec3dot5-remotesensing-12-00424

Thanks for the reply and suggestions. They are helpful.
