### ISSUE TITLE
LONG DATA PROCESS

### ISSUE THREAD

**Issue by sazzath** [yumorishita/LiCSBAS#47]
[202012011419batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/5622968/202012011419batch_LiCSBAS_01_16.log)

WHY IT TAKES TOO LONG TIME ? BEFORE ITS DIDN'T !!!!!

![image](https://user-images.githubusercontent.com/72601348/100749020-62517e00-33e4-11eb-9072-b8d7df769980.png)

**Comment by yumorishita** [comment]
Please upload the log which shows short time processing as well.

**Comment by sazzath** [comment]
I already upload the log 
[202012011419batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/5623111/202012011419batch_LiCSBAS_01_16.log)

**Comment by sazzath** [comment]
![image](https://user-images.githubusercontent.com/72601348/100753663-641e4000-33ea-11eb-99d5-3cde1d3ae2b4.png)

same issue ? How long it takes ? 
[202012011419batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/5623199/202012011419batch_LiCSBAS_01_16.log)

**Comment by yumorishita** [comment]
No, I mean the previous log with SHORT TIME processing. You said "BEFORE ITS DIDN'T !!!!!". I cannot compare the previous and current processing.

**Comment by sazzath** [comment]
Yesterday I leave my computer like this still its processing like this 
![image](https://user-images.githubusercontent.com/72601348/100869940-17943c80-349e-11eb-871f-ab1cb8781ff1.png)

Log file included sir 
[202012011419batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/5629083/202012011419batch_LiCSBAS_01_16.log)

**Comment by yumorishita** [comment]
It seems to be no problem because the process is ongoing. It is natural to take long time because you are processing the entire data with nlook=1. In a case of my paper, it takes ~5 hours (https://www.mdpi.com/2072-4292/12/3/424/htm#remotesensing-12-00424-t002).

If the processing is stacked, I suggest just killing and rerunning the process. I am not sure but it might be because of your environment.

**Comment by yumorishita** [comment]
I suggest changing the parameter to nlook="10" to get the result quickly.

https://github.com/yumorishita/LiCSBAS/blob/4cab0af0f59107a0f119174a735e27aa04626737/batch_LiCSBAS.sh#L22

**Comment by yumorishita** [comment]
It seems that the problem has been solved. I close this issue.
