### ISSUE TITLE
LiCSBAS14_vel_std.py error

### ISSUE THREAD

**Issue by kedaxu1** [yumorishita/LiCSBAS#48]
When I run the step of LiCSABS14 have the problem "Running  63/100th bootstrap...Killed"

**Comment by yumorishita** [comment]
Please upload the log file. Have you tried some times?

**Comment by kedaxu1** [comment]
[LiCSBAS14_vel_std.py.log](https://github.com/yumorishita/LiCSBAS/files/5634595/LiCSBAS14_vel_std.py.log)
Sir,this is my log file,and I have tried many times,but always have the problem "Running 63/100th bootstrap...Killed"

**Comment by yumorishita** [comment]
What is the memory size of your machine? Also please upload the log file for the earlier steps (01-13). If you used batch_LiCSBAS.sh, the log file was automatically created in a log directory. I recommend using the batch_LiCSBAS.sh.

**Comment by kedaxu1** [comment]
Thanks for your answer.The memoty of my machine is 4G,and I not have the log file.I will use the batch_LiCSBAS.sh next time.

**Comment by yumorishita** [comment]
Perhaps setting p14_mem_size="2000" in batch_LiCSBAS.sh could solve the problem.
https://github.com/yumorishita/LiCSBAS/blob/master/batch_LiCSBAS.sh#L99
