### ISSUE TITLE
Copy baselines file

### ISSUE THREAD

**Issue by alejobeap** [yumorishita/LiCSBAS#49]
Dear
I'll trying to run in descending track but I had the error:

Copy baselines file
  File "/home/LICSBAS/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 453, in <module>
    sys.exit(main())
  File "/home/LICSBAS/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 370, in main
    if not io_lib.read_bperp_file(bperp_file_in, imdates):
  File "/home/LICSBAS/LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 124, in read_bperp_file
    bperp_dict[l.split()[1]] = l.split()[2]
IndexError: list index out of range

I've run the ascending track in the same area and it's working correctly.

Thanks

Alejandro

**Comment by yumorishita** [comment]
What is the frame ID? Can you upload the baselines file?

**Comment by alejobeap** [comment]
The frame id is 142D_09147_131313
in the LICSAR web page the baseline file is incomplete, maybe it is the cause that I have the error in my run ??

Thanks

**Comment by yumorishita** [comment]
It seems to be because there is a blank line at the bottom of the baselines file. I updated the LiCSBAS module to ignore the blank line. Please update LiCSBAS and try again. I hope the error will not occur.

**Comment by yumorishita** [comment]
It seems that the problem has been solved. I close this issue.
