### ISSUE TITLE
Keep getting [Errno 2] No such file or directory while running batch script

### ISSUE THREAD

**Issue by lamebird** [yumorishita/LiCSBAS#5]
Hi

I keep getting error while working with batch script. The error is happening while recreating slc.mli.png on  LiCSBAS05op_clip_unw.py.
Full error message is : 

Recreate slc.mli.png
Traceback (most recent call last):
  File "/home/farhanmakarim/LiCSBAS/bin/LiCSBAS05op_clip_unw.py", line 286, in <module>
    sys.exit(main())
  File "/home/farhanmakarim/LiCSBAS/bin/LiCSBAS05op_clip_unw.py", line 222, in main
    mli = io_lib.read_img(os.path.join(out_dir, 'slc.mli'), length_c, width_c)
  File "/home/farhanmakarim/LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 134, in read_img
    data = np.fromfile(file, dtype=dtype).reshape((length, width))
FileNotFoundError: [Errno 2] No such file or directory: '/home/farhanmakarim/127A_09749_121312/GEOCml1clip/slc.mli'

I'm currently using Fedora 31, and i dont have such problem in Ubuntu 19.10. Is it probably the cause?
I've attached full log below
Thanks! Love your works!

[202002280238batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/4265233/202002280238batch_LiCSBAS_01_16.log)

**Comment by yumorishita** [comment]
Can you show me the file list in GEOCml1 (i.e., ls -l GEOCml1 | grep -v 20)?

**Comment by lamebird** [comment]
Hi, here's the result: 
(base) [farhanmakarim@gamla-stan 127A_09749_121312]$ ls -l GEOCml1 | grep -v 20
total 160944
-rw-rw-r--. 1 farhanmakarim farhanmakarim     3598 Feb 28 14:35 baselines
-rw-rw-r--. 1 farhanmakarim farhanmakarim 32534256 Feb 28 14:25 E.geo
-rw-rw-r--. 1 farhanmakarim farhanmakarim      812 Feb 28 14:35 EQA.dem_par
-rw-rw-r--. 1 farhanmakarim farhanmakarim 32534256 Feb 28 14:25 hgt
-rw-rw-r--. 1 farhanmakarim farhanmakarim 32534256 Feb 28 14:25 N.geo
-rw-rw-r--. 1 farhanmakarim farhanmakarim 32534256 Feb 28 14:25 slc.mli
-rw-rw-r--. 1 farhanmakarim farhanmakarim       77 Feb 28 14:35 slc.mli.par
-rw-rw-r--. 1 farhanmakarim farhanmakarim   446483 Feb 28 14:25 slc.mli.png
-rw-rw-r--. 1 farhanmakarim farhanmakarim 32534256 Feb 28 14:25 U.geo
 
I've reinstalled anaconda environment several times and still get same results

**Comment by lamebird** [comment]
It works! Thank you!

**Comment by yumorishita** [comment]
Thank you for your bug report. I will update the master code later.
