### ISSUE TITLE
A question about Loop Closure

### ISSUE THREAD

**Issue by Fanchengyan** [yumorishita/LiCSBAS#50]
in the paper "LiCSBAS: An Open-Source InSAR Time Series Analysis Package Integrated with the LiCSAR Automated Sentinel-1 InSAR Processor" ,  it is said loop phase Φ123 should be close to zero  if unwrapping is  correct , and will usually be close to an integer multiple of 2π  if one (or more) of the interferograms contains unwrapping errors.

Φ123 = φ12 + φ23 − φ13.

but in the `LiCSBAS12_loop_closure.py`，the cloop phase minus the  n bias (2pi*n) as the final cloop phas

```python
loop_ph = unw12+unw23-unw13
loop_2pin = int(np.round(np.nanmedian(loop_ph)/(2*np.pi)))*2*np.pi
loop_ph = loop_ph-loop_2pin #unbias 2pi x n
```
I can't understand why added this step, Is there any relevant paper for reference?

**Comment by yumorishita** [comment]
The subtraction of the 2pi*n bias is to unbias the loop phase, as mentioned in the comment of the code.

Suppose that we have three complete 0 phases (phi1=phi2=phi3=0) and differential phases (phi12=phi23=phi13=0). The 2pi*n biases in each interferogram is completely unknown without the reference in the 1st and 2nd loop closure check (e.g., phi12 could be 2*pi*5). To get the reasonable loop phases taking into account the unknown biases, the 2pi*n bias estimated from the median must be subtracted.

You would understand why this unbias is necessary if you removed the lines for the unbias in the code.

**Comment by Fanchengyan** [comment]
Hi, yumorishita. Thanks for your reply. But I'm still confused about this unbias operation. 

As you said，suppose that we have three complete 0 phases SAR image (φ1=φ2=φ3=0), and it's differential phases should be (φ12=φ23=φ13=0), but why φ12 could be 5×2π without the reference. Do you mean it is still wrap phase? But we are dealing with unwrapping phase in loop close operation.

I still chouldn't understand **where this bias comes from**. Is it because my wrong understanding of interference and unwrap operation? I put my understanding of those operation below, please see which step is problematic.

Suppose we have three SAR image 1, 2, 3, the phases are  φ1, φ2, φ3 separately. If the phase unwrapping operation is correct, Interferogram φ12，φ23，φ13 should be:
```
                φ12=φ1-φ2
                φ23=φ2-φ3
                φ13=φ1-φ3
```
Then:
```
               φ12 + φ23 = φ1-φ2 + φ2-φ3 =  φ13
```
Or:
```
               φ12 + φ23 - φ13 = 0
```

Example:
------------------------------------------------------------------------------------------------
Suppose the phases of a pixel with same location for SAR image 1, 2, 3 are:
```
                 φ1 = n×2π + 0.3π
                 φ2 = (n+1)×2π - 0.3π
                 φ3 = (n+1)×2π + 0.3π
```
If the phase unwrapping operation is correct, Then:
```
                φ12 = φ1 - φ2  = -2π + 0.6π
                φ23 = φ2 - φ3  =  -0.6π
                φ13 = φ1 - φ3  = -2π
```
Then:
```
               φ12 + φ23 - φ13 = -2π + 0.6π + (-0.6π) - (-2π) = 0
```
According to my train of thought，I chouldn't understand **where this bias comes from** .

**Comment by yumorishita** [comment]
I mean the phase is unwrapped. The each unwrapped phase has each unknown 2πn. The unwrapped phases for each interferogram are
```
φ12=φ1-φ2+2π*l
φ23=φ2-φ3+2π*m
φ13=φ1-φ3+2π*n
```
then,
`φ12 + φ23 - φ13 = 2π(l+m-n)`

**Comment by Fanchengyan** [comment]
I think I understand where the  bias comes from：
The unwrapping operation cann't generate a absolutely right unwrapped phase for every pixel, but with a same 2π*n bias for one interferogram. Is that right?

**Comment by yumorishita** [comment]
Yes, you are right.

**Comment by Fanchengyan** [comment]
OK，thanks for your reply. I will close this issue
