### ISSUE TITLE
Question about the Sentinel-1 InSAR Data coverage

### ISSUE THREAD

**Issue by CalvinDrStar** [yumorishita/LiCSBAS#51]
Dear Prof. Morishita,

I am trying to use LiCSBAS to study **the subsidence in central and eastern China. However, the corresponding LiCSAR products are not available** on the COMET-LiCS web portal (https://comet.nerc.ac.uk/COMET-LiCS-portal/), also as you mentioned in your paper (_Remote Sens. 2020, 12, 424_) "up-to-date LiCSAR products are available primarily over the Alpine Himalayan Belt, Japan, the East African Rift".

So I would like to ask if there are any other unwrapped interferograms and coherence products like LiCSBAS that we, who are not from remote sensing field, can use directly? if possible, even the products derived based on Sentinal-2 and Sentinal-3?

Thanks for your assistance in the issue.
Respectfully submitted.

**Comment by yumorishita** [comment]
I recommend requesting the LiCSAR processing in your frame of interest from the form on the LiCS portal web (https://comet.nerc.ac.uk/comet-lics-portal/, right column). See also #6, #9, #30.

**Comment by CalvinDrStar** [comment]
Sorry Prof. Morishita, I have checked the LiCS portal web again and also  #6, #9, #30.，but still donot really get it. I mean the data in the area circled by the red dotted line in the figure below. 
![image](https://user-images.githubusercontent.com/57609119/102966059-12b92a80-452a-11eb-821a-b5776961537b.png)

Thanks again for your help in this issue.

**Comment by yumorishita** [comment]
The request form is in the right bottom. If you would like to request the frames that have not been initiated and the frame ID is unknown, just send an email to comet@leeds.ac.uk with the image above attached.
![クリップボード03](https://user-images.githubusercontent.com/37470321/102995326-271a1900-4564-11eb-81a2-668aa88f7bb7.jpg)

**Comment by CalvinDrStar** [comment]
![image](https://user-images.githubusercontent.com/57609119/103001472-0a7fe000-4568-11eb-89d7-90ab0ff7d5ef.png)

Now I finally understand why I cannot find the "right column"，since without using VPN, for the users in china, the Twitter part and the "right column" part cannot be displayed successfully as shown above. 

Sorry for the inconvenience and thank you so much for your help this issue.

**Comment by ShadiAbdelhadi** [comment]
Professor Morishita;
I have already sent an email to comet@leeds.ac.uk  with an attached image the illustrates my study area location which does not have a defined Frame ID. Since there's no data available for LiCSBAS the request is not guaranteed to be processed because my study area is far away from the Alpine-Himalayan tectonic bell, what other options may I consider in the mean time so that my project continues?

**Comment by irmayolii** [comment]
Dear Prof. Morishita. 
How to get standard deviation (STD) displacement in each epoch?. Because in the result of LiCSBAS processing I just found  STD of velocity  not displacement.
