### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by CalvinDrStar** [yumorishita/LiCSBAS#52]
Dear Prof. Morishita,

I just attempted to analyze a new Frame, however met the typeerror warming as mentioned in another issue created yesterday, even though that issue cannot be found now.  
Attached please find the log. 

Thanks for your assistance in the issue.
Respectfully submitted.
[202012251100good_luck_01_16.log](https://github.com/yumorishita/LiCSBAS/files/5740997/202012251100good_luck_01_16.log)

**Comment by yumorishita** [comment]
I cannot reproduce the error in my environment. Are you working on Mac?

Can you try:
`p01_n_para="1"	# default: 4`
https://github.com/yumorishita/LiCSBAS/blob/e40922432ffde6e678956f1ef85f40248b3dc890/batch_LiCSBAS.sh#L67

**Comment by CalvinDrStar** [comment]
Thanks for your answer.

No, Prof., i am working on linux/Ubuntu. I tried your suggestion, but still doesnot work.
Back to my previous Frame again, it ran sucessfully again.
I really don't know what leads to this Typeerror. It may be caused by specific frame data?

**Comment by CalvinDrStar** [comment]
For the tutorial case, the codes also work, i just tested it again.
But doesnot work for Frame ID: 164D_06070_131313.

**Comment by yumorishita** [comment]
The same command worked in my environment. Please try removing GEOC directory and running again.

[202012251636batch_LiCSBAS_01_01.log](https://github.com/yumorishita/LiCSBAS/files/5741424/202012251636batch_LiCSBAS_01_01.log)

**Comment by yumorishita** [comment]
I have reproduced the error. Removing GEOC directory would solve the problem. I need to fix the bug, but will do it next year.

**Comment by CalvinDrStar** [comment]
Okay, thanks alot. 
In order to avoid the same problem next time, could you tell me what causes this situation, or what we need to pay attention to during operation, so as to avoid this situation happening again.

**Comment by CalvinDrStar** [comment]
Since re-create GEOC directory (download thoese data again) will cost a lot time, I would like to ask if it is feasible to delete only some files in GEOC directory that cause this problem? 

Thank you so much.

**Comment by yumorishita** [comment]
It was not difficult to identify the cause, so I have updated the code to avoid the error. Please update your installed LiCSBAS module and run again. You don't need to delete the GEOC directory.

The cause of this error is that 20160923_20170226.geo.unw.tif is empty on the LiCSAR server. This is not a problem in LiCSBAS but LiCSAR products.
http://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/164/164D_06070_131313/interferograms/20160923_20170226/

**Comment by CalvinDrStar** [comment]
Okay. Thanks for your inspring work and continuously patient help.

**Merry Christmas, Prof.**
