### ISSUE TITLE
Running LiCSBAS & Quick Start

### ISSUE THREAD

**Issue by sarelfonlus** [yumorishita/LiCSBAS#53]
Hello and thanks for your kind availability. I have a problem when I do quick start ... I create directory and copy the batch script to the root folder. When I go to run. / ..... it gives me an error Permission denied. Thanks for your attention. Michele

**Comment by yumorishita** [comment]
Please show me the screenshot.

**Comment by sarelfonlus** [comment]
- [ ] 
![deskprob](https://user-images.githubusercontent.com/54473389/103460184-90441e00-4d14-11eb-9588-989ff84de724.PNG)

**Comment by yumorishita** [comment]
Please try:
`chmod 755 batch_LiCSBAS_sample_CF.sh`

**Comment by sarelfonlus** [comment]
![Prova 1](https://user-images.githubusercontent.com/54473389/103474984-71dc3200-4da9-11eb-80ba-23ce90c9e3ad.PNG)

**Comment by sarelfonlus** [comment]
Hello, thank you for your kind availability, I entered your string as you can see from the photo, but it didn't give me any more login error, but it doesn't start processing. Thanks for your commitment ...

**Comment by yumorishita** [comment]
It is normal. Then please run:
`./batch_LiCSBAS_sample_CF.sh`

**Comment by sarelfonlus** [comment]
![p2](https://user-images.githubusercontent.com/54473389/103475894-891f1d80-4db1-11eb-9ed8-bb5edeb70b69.PNG)

**Comment by yumorishita** [comment]
You must "source" bashrc_LiCSBAS.sh as is written in [wiki](https://github.com/yumorishita/LiCSBAS/wiki/1_Installation#12-licsbas-module). Please carefully read the wiki page.
