### ISSUE TITLE
How to get "OOOP_AAAAA_BBBBBB.geo.{E,N,U}.tif"?

### ISSUE THREAD

**Issue by wwbian116** [yumorishita/LiCSBAS#55]
I would like to ask you what processing steps should I take to get this file(OOOP_AAAAA_BBBBBB.geo.{E,N,U}.tif). I'm sorry this is a very basic question.

**Comment by yumorishita** [comment]
Step 0-1 download the geotiff files. You can also directly download them from the [LiCSAR  product page](http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/) for each frame.

**Comment by wwbian116** [comment]
I now use GAMMA software to process the ScanSAR data of ALOS-2, and then use LICSABS to get the time series, so I need to process the data to get NEU.tif. Unfortunately, I cannot use the generated product.

**Comment by yumorishita** [comment]
Sorry but I don't know how to create NEU.geo.tif using GAMMA. This question is not about LiCSBAS, but LiCSAR products. Probably the LiCSAR team member can answer the question because the LiCSAR system is based on GAMMA. Please contact [Dr. Milan Lazecky](https://twitter.com/MLazecky) or comet@leeds.ac.uk.

**Comment by wwbian116** [comment]
Thank you very much for your answer. I will consult Dr. Milan Lazecky later.

**Comment by songzwgithub** [comment]
Hello, I now use GAMMA software to process the data too. I would like to ask if you have solved this problem on how to create NEU.geo.tif using GAMMA or other software by yourself. Looking forward to your reply.

**Comment by yumorishita** [comment]
`lk_vec_lt` can output the unit look vector.

**Comment by songzwgithub** [comment]
Thanks for your answer! I have obtained the NEU.geo.tif through this script. But I have other questions for GACOS correction. The value of U.geo.tif obtained through GAMMA software is negative， is it right？
![U geo tif_from GAMMA](https://user-images.githubusercontent.com/75102164/191251618-69da69be-de7e-4f61-9526-9c77ccd1ab03.png)
I use the products downloaded from the GACOS website to correct the unw data generated by GAMMA software, but the results look bad. Is this the right process? Or do you have any good suggestions? I'm sorry for so many basic questions. 
![GACOS_info](https://user-images.githubusercontent.com/75102164/191254901-c15a9897-941b-4441-b6ec-575eb9e19135.png)
[GACOS_info.txt](https://github.com/yumorishita/LiCSBAS/files/9607470/GACOS_info.txt)
![20171008_20171020 gacos](https://user-images.githubusercontent.com/75102164/191254988-ea45d913-f49f-47e5-9658-44ada820d0fe.png)
![20171008_20171020 unw](https://user-images.githubusercontent.com/75102164/191254998-455694b9-a815-4fae-a31b-876db7b7bb24.png)
[202209200250batch_LiCSBAS_sample_CF_03_03.log](https://github.com/yumorishita/LiCSBAS/files/9607475/202209200250batch_LiCSBAS_sample_CF_03_03.log)

> `lk_vec_lt` can output the unit look vector.

**Comment by yumorishita** [comment]
Yes, I think the sign of the ENU GAMMA output should be inverted.
I am not sure but the GACOS result does not seem so bad. GACOS does not always reduce the noise but sometimes adds artificial noise.

**Comment by songzwgithub** [comment]
Thank you very much for your answer. I learned a lot!
