### ISSUE TITLE
LiCSBAS12_loop_closure.py  error

### ISSUE THREAD

**Issue by alejobeap** [yumorishita/LiCSBAS#56]
Dear 
I'm trying to procces the frame 018A_09021_121620 but I had the problem (bellow).

LiCSBAS12_loop_closure.py ver1.5.3 20201118 Y. Morishita
LiCSBAS12_loop_closure.py -d GEOCml1clip -l 0.5

/home/LICSBAS/LiCSBAS/bin/LiCSBAS12_loop_closure.py:355: RuntimeWarning: All-NaN slice encountered
  refyx = np.where(loop_ph_rms_points_masked==np.nanmin(loop_ph_rms_points_masked))
Traceback (most recent call last):
  File "/home/LICSBAS/LiCSBAS/bin/LiCSBAS12_loop_closure.py", line 831, in <module>
    sys.exit(main())
  File "/home/LICSBAS/LiCSBAS/bin/LiCSBAS12_loop_closure.py", line 356, in main
    refy1 = refyx[0][0] # start from 0, not 1
IndexError: index 0 is out of bounds for axis 0 with size 0

Thanks for your help.

P.

**Comment by yumorishita** [comment]
I guess the number of ifgs and/or the loop_thre are too small. Try increasing them.

**Comment by alejobeap** [comment]
Thanks.
