### ISSUE TITLE
Unwrapping error

### ISSUE THREAD

**Issue by yagmurn** [yumorishita/LiCSBAS#57]
Dear yumorishita,
I took an error given below;
LiCSBAS13_sb_inv.py ver1.4.6 20201119 Y. Morishita
LiCSBAS13_sb_inv.py -d GEOCml1clip
In geographical coordinates

Size of image (w,l)    : 2001, 781
of all images        : 238
of images to be used : 235
of all ifgs          : 764
of ifgs to be used   : 697
of removed ifgs      : 67
Threshold of used unw  : 235

Reference area (X/Y)   : 127:128/240:241
Allowed memory size    : 4000 MB
Number of patches      : 3
Inversion algorism     : LS
Gamma value            : 0.0001

Process 261/781th line (1/3th patch)...
  Reading 697 ifg's unw data...
Killed
What can be the problem and how can I solve that?

**Comment by yumorishita** [comment]
I have no idea. Please upload the full log file and batch_LiCSBAS.sh.

**Comment by yagmurn** [comment]
[202012101224batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/5834784/202012101224batch_LiCSBAS_01_16.log)

[batch_LiCSBAS.zip](https://github.com/yumorishita/LiCSBAS/files/5834788/batch_LiCSBAS.zip)

**Comment by yumorishita** [comment]
I could not reproduce the error. It might be because of the memory shortage. What is the memory size of your computer? Please run `free -b`.

**Comment by yagmurn** [comment]
I applied free -b command. Here is the result:
              total        used        free      shared  buff/cache   available
Mem:     3062702080  1275338752   810287104   250593280   977076224  1366241280
Swap:    1469710336  1428668416    41041920

But I got same error again.
I applied before many times, there wasn't any error. I didn't understand why.

**Comment by yumorishita** [comment]
Please try changing p13_mem_size to e.g. 1500.
https://github.com/yumorishita/LiCSBAS/blob/1770ec603d8333ff8790d35cb3bf428b30fd14fe/batch_LiCSBAS.sh#L93

If it works, I will update the code to automatically change the parameter depending on the computer memory.

**Comment by yagmurn** [comment]
It worked but it is still in the same process for hours as below:

LiCSBAS13_sb_inv.py ver1.4.6 20201119 Y. Morishita
LiCSBAS13_sb_inv.py -d GEOCml1clip --mem_size 1500
In geographical coordinates

Size of image (w,l)    : 2001, 781
 of all images        : 114
 of images to be used : 112
 of all ifgs          : 346
 of ifgs to be used   : 316
 of removed ifgs      : 30
Threshold of used unw  : 112

Reference area (X/Y)   : 1836:1837/440:441
Allowed memory size    : 1500.0 MB
Number of patches      : 4
Inversion algorism     : LS
Gamma value            : 0.0001

Process 196/781th line (1/4th patch)...
  Reading 316 ifg's unw data...
  239328/392196 points removed due to not enough ifg data...

  Identifing gaps, and counting n_gap and n_ifg_noloop,
  with 1 parallel processing...
    Running  1/ 1th patch...

  Small Baseline inversion by LS...

  Solving  35517/152868th points with full unw at a time...
  Next, solve 117351 points including nan point-by-point...
  Running 117000/117351th point...
  Elapsed time for 1th patch: 00h 09m 00s

Process 392/781th line (2/4th patch)...
  Reading 316 ifg's unw data...
  74146/392196 points removed due to not enough ifg data...

  Identifing gaps, and counting n_gap and n_ifg_noloop,
  with 1 parallel processing...
    Running  1/ 1th patch...

Is it due to the size of the study area?

**Comment by yumorishita** [comment]
Yes, I recommend larger nlook for quick testing
https://github.com/yumorishita/LiCSBAS/blob/1770ec603d8333ff8790d35cb3bf428b30fd14fe/batch_LiCSBAS.sh#L22

**Comment by yagmurn** [comment]
It worked by increasing nlook parameter.  Thank you for your interest.
