### ISSUE TITLE
LiCSBAS_disp_img.py cmap

### ISSUE THREAD

**Issue by fangjinSGG** [yumorishita/LiCSBAS#58]
Dear Yumorishita

I'd like to use LiCSBAS_disp_img.py to generate kmz files. The cmap option is set to be 'bwr'. I suppose this is a supported value, but I got an error as follows:

TypeError: 'cmap' must be an instance of matplotlib.colors.Colormap or None, not a str

Thanks

Jin

**Comment by yumorishita** [comment]
Thank you for reporting the issue. It is indeed a bug. I have fixed the problem and updated the module. Please update your installed LiCSBAS and try again.

**Comment by Zuzchan** [comment]
was the issue solved?
can you please inform me how to use LiCSBAS_disp_img.py to generate kmz files.
Is there a code that I need to use?

**Comment by yumorishita** [comment]
Use `--kmz kmzname` option.
https://github.com/yumorishita/LiCSBAS/wiki/3_visualization#licsbas_disp_imgpy
