### ISSUE TITLE
Common reference point at step1-6

### ISSUE THREAD

**Issue by fangjinSGG** [yumorishita/LiCSBAS#60]
I have several frames to process. I wonder how to select a common reference point for each frame. It seems that the current LiCSBAS version can't do that.

**Comment by yumorishita** [comment]
The reference point has no effect in Step 1-6 (i.e., you would get the same result of Step 1-6 with any reference point). You can manually set the common reference area for multiple frames in the post-processing (e.g., LiCSBAS_cum2vel.py or LiCSBAS_plot_ts.py) using the --ref_geo option.

**Comment by fangjinSGG** [comment]
The common reference area should be located within the overlapping area of multiple frames, is that right? If I set the reference area outside the frames, I got an error:

ERROR: Ref area has only NaN value!

So I can't set a common reference area for all frames? (I'm currently processing 6 frames.)

**Comment by yumorishita** [comment]
Yes, the reference area must be inside of each frame. It is not possible to set the common reference area for multiple frames with no overlapping area. I suggest tying to external deformation data (e.g. GNSS; see https://doi.org/10.1029/2020GL087376, chapter 3).
