### ISSUE TITLE
computing is stuck over 'HP filter in time, LP filter in space processing' with LiCSBAS16_filt_ts.py

### ISSUE THREAD

**Issue by wzmucas** [yumorishita/LiCSBAS#62]
Dear Dr. Morishita,

Each step before LiCSBAS16 running smooth, but it is stuck when applying LiCSBAS16_filt_ts.py.

1. system: HPC Linux
2. CPU 32 and 32G memory 
3. **command**  `LiCSBAS16_filt_ts.py -t TS_GEOCml -r bl   --n_para 32`
4. **102** images and **369** interferograms without clip
5. issue: the computing process stucks as below log shown with no ending for nearly 12 hours, which is not reasonable based on the time you listed on **Table 2. Processing time and disk usage of LiCSBAS in the case studies**. in you paper.  
6. Result: After 12 hours running, **102** _deramp.png and **14** _filt.png can be viewed under **16filt_cum**, and **101** _deramp.png can be seen under **16filt_increment**; the file of **cum_filt.h5** is almost empty . There's also no error during the processing. BTW, **cum.h5** (1.2G) is normal and can be ploted by LiCSBAS command.

Do you have any idea about this or could you give me some clues to address this issue? Many thanks for your time!

**computing log:**
> 
LiCSBAS16_filt_ts.py ver1.4.5 20201124 Y. Morishita
LiCSBAS16_filt_ts.py -t TS_GEOCml -r bl --n_para 32

Size of image (w,l)      : 2986, 2712
Number of images         : 102
Width of filter in space : 2 km (20.4x18.0 pixel)
Width of filter in time  : 0.119 yr (43 days)
Deramp flag              : bl
hgt-linear flag          : False

Deramp ifgs with the degree of bl,
with 32 parallel processing...
    0/102th image...
   10/102th image...
   20/102th image...
   30/102th image...
   40/102th image...
   50/102th image...
   60/102th image...
   70/102th image...
   80/102th image...
   90/102th image...
  100/102th image...

Create png for increment with 32 parallel processing...

HP filter in time, LP filter in space, **_[get stuck here forever]_**
with 32 parallel processing...
    0/102th image...
   10/102th image...
   20/102th image...
   30/102th image...
   40/102th image...
   50/102th image...
   60/102th image...
   70/102th image...
   80/102th image...
   90/102th image...
  100/102th image...

**Comment by yumorishita** [comment]
I don't know why but the multiprocessing sometimes stacks in some environments. Reducing n_para (e.g., to 1) might solve this problem. Please try.

**Comment by wzmucas** [comment]
> I don't know why but the multiprocessing sometimes stacks in some environments. Reducing n_para (e.g., to 1) might solve this problem. Please try.

Wow, your suggestion perfectly solved my problem. Thanks to the LiCSBAS you have developed, I can implement SBAS method over a quite big area with LicSAR data. In order to process dozens of frames, have you tried to run LiCSBAS over GPU attempting to short the processing time (especially in the step of LiCSBAS13_sb_inv.py )?

**Comment by yumorishita** [comment]
Not yet, but the GPU option should be one of my future tasks. I am not sure when I can implement it.

**Comment by wzmucas** [comment]
> Not yet, but the GPU option should be one of my future tasks. I am not sure when I can implement it.

Thanks, looking forward to seeing it.

**Comment by yumorishita** [comment]
I have updated the LiCSBAS module to add the GPU option in step13. Great speed-up has been achieved. Please try if you are interested.

The GPU option can also be technically added in steps14 and 16. It is future task.
