### ISSUE TITLE
2nd Loop closure check without bad ifgs to define ref area...

### ISSUE THREAD

**Issue by 20152023** [yumorishita/LiCSBAS#63]
help please, i encounter this problem:
LiCSBAS12_loop_closure.py:350: RuntimeWarning: **All-NaN slice encountered**
  **refyx = np.where(loop_ph_rms_points_masked==np.nanmin(loop_ph_rms_points_masked))**
Traceback (most recent call last):
  File "/home/LiCSBAS/bin/LiCSBAS12_loop_closure.py", line 827, in <module>
    sys.exit(main())
  File "/home/LiCSBAS/bin/LiCSBAS12_loop_closure.py", line 352, in main
    refy1 = refyx[0][0] # start from 0, not 1
IndexError: index 0 is out of bounds for axis 0 with size 0

i try to solve it using zero replace nan, but it did not work

**Comment by yumorishita** [comment]
Can you upload the full log file including step 11?

**Comment by 20152023** [comment]
thank you,
**start from 02nd step to 16th step: the log as following**

LiCSBAS02_ml_prep.py ver1.7.1 20201028 Y. Morishita
LiCSBAS02_ml_prep.py -i GEOC -n 1

Create E.geo
  No *.geo.E.tif found in GEOC

Create N.geo
  No *.geo.N.tif found in GEOC

Create U.geo
  No *.geo.U.tif found in GEOC

Create slc.mli
  No *.geo.mli.tif found in GEOC

Create hgt
  No *.geo.hgt.tif found in GEOC

Create unw and cc
   62/ 62 unw and cc already exist. Skip

Copy baselines file
  No valid baselines file exists. Make dummy.

Elapsed time: 00h 00m 00s

LiCSBAS02_ml_prep.py Successfully finished!!

Output directory: GEOCml1


LiCSBAS11_check_unw.py ver1.3.1 20200911 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCml1

coh_thre     : 0.05
unw_cov_thre : 0.3

Size         : 1463 x 650

Reading unw and cc data...
    0/ 62th unw to identify valid area...
    0/ 62th cc and unw...

0/62 ifgs are discarded from further processing.
ifg dates        unw_cov coh_av

Check network/*, 11bad_ifg_ras/* and 11ifg_ras/* in TS dir.
If you want to change the bad ifgs to be discarded, re-run with different thresholds or edit bad_ifg11.txt before next step.

Elapsed time: 00h 00m 01s

LiCSBAS11_check_unw.py Successfully finished!!

Output directory: TS_GEOCml1


LiCSBAS12_loop_closure.py ver1.5.1 20201028 Y. Morishita
LiCSBAS12_loop_closure.py -d GEOCml1

loop_thre : 1.5 rad

1st Loop closure check and make png for all possible 43 loops,
with 2 parallel processing...
    0/ 43th loop...

2nd Loop closure check without bad ifgs to define ref area...
with 2 parallel processing...
    0/ 43th loop...
/home/wangt/下载/LiCSBAS/bin/LiCSBAS12_loop_closure.py:350: RuntimeWarning: **All-NaN slice encountered
  refyx = np.where(loop_ph_rms_points_masked==np.nanmin(loop_ph_rms_points_masked))**
Traceback (most recent call last):
  File "/home/wangt/下载/LiCSBAS/bin/LiCSBAS12_loop_closure.py", line 827, in <module>
    sys.exit(main())
  File "/home/wangt/下载/LiCSBAS/bin/LiCSBAS12_loop_closure.py", line 352, in main
    **refy1 = refyx[0][0] # start from 0, not 1
IndexError: index 0 is out of bounds for axis 0 with size 0**
 **it should be the unwrap errors  bring the problem, i suppose. i will try it by changing the unwrap method, hope it works. of course, if you have any suggestion, please let me know. thank you**

**Comment by yumorishita** [comment]
Yes, I guess there are so many unwrapping errors that no interferograms remain after 1st loop closure check. Please try to use the improved unwrapped data if possible.

**Comment by yumorishita** [comment]
Let me close this issue. If you have any more questions, please reopen this.

**Comment by MIEMESSI** [comment]
Dear Professor, I have been stuck here for a long time, is there any way to solve it
![image](https://github.com/yumorishita/LiCSBAS/assets/161692921/349e8502-4772-4e45-a6c9-540d68628a26)

**Comment by yumorishita** [comment]
It is the COMET version and I cannot support it.
