### ISSUE TITLE
Some problems with step 0-2 and 1-6 

### ISSUE THREAD

**Issue by CanZhang-zc** [yumorishita/LiCSBAS#64]
Help please, I encounter some problems:
When run the batch script, there are some problems with step 0-2 (some errors) and step 1-6 (unable to finish). I tried to redownload the data and run the batch script repeatedly, but it still had the same problems.
Sorry for any inconvenience caused, your assistance will be highly appreciated. 

**Here is the log file (step 0-2):**
LiCSBAS02_ml_prep.py ver1.7.4 20201119 Y. Morishita
LiCSBAS02_ml_prep.py -i GEOC -n 1

Create E.geo
  E.geo created

Create N.geo
  N.geo created

Create U.geo
  U.geo created

Create slc.mli
  slc.mli[.png] created

Create hgt
  hgt[.png] created

Create unw and cc
  12 parallel processing...
/home/zhangcan/anaconda3/envs/licsbas/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py:11: MatplotlibDeprecationWarning: 
The support for Qt4  was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  from matplotlib.backends.qt_compat import QtGui
    0/362th IFG...
   40/362th IFG...
   80/362th IFG...
   50/362th IFG...
   90/362th IFG...
   10/362th IFG...
   20/362th IFG...
   60/362th IFG...
   70/362th IFG...
   30/362th IFG...
  120/362th IFG...
  160/362th IFG...
  130/362th IFG...
  170/362th IFG...
  100/362th IFG...
ERROR 1: LZWDecode:Wrong length of decoded string: data probably corrupted at scanline 2048
ERROR 1: TIFFReadEncodedStrip() failed.
ERROR 1: /home/zhangcan/128A_05969_131313/GEOC/20180830_20181005/20180830_20181005.geo.cc.tif, band 1: IReadBlock failed at X offset 0, Y offset 1024: TIFFReadEncodedStrip() failed.
  20180830_20181005.geo.cc.tif cannot open. Skip
  140/362th IFG...
  180/362th IFG...
  110/362th IFG...
  190/362th IFG...
  150/362th IFG...
  200/362th IFG...
  240/362th IFG...
  280/362th IFG...
ERROR 1: LZWDecode:Wrong length of decoded string: data probably corrupted at scanline 2238
ERROR 1: TIFFReadEncodedStrip() failed.
ERROR 1: /home/zhangcan/128A_05969_131313/GEOC/20190403_20190415/20190403_20190415.geo.cc.tif, band 1: IReadBlock failed at X offset 0, Y offset 1119: TIFFReadEncodedStrip() failed.
  20190403_20190415.geo.cc.tif cannot open. Skip
ERROR 1: LZWDecode:Wrong length of decoded string: data probably corrupted at scanline 2270
ERROR 1: TIFFReadEncodedStrip() failed.
ERROR 1: /home/zhangcan/128A_05969_131313/GEOC/20190521_20190602/20190521_20190602.geo.cc.tif, band 1: IReadBlock failed at X offset 0, Y offset 1135: TIFFReadEncodedStrip() failed.
  20190521_20190602.geo.cc.tif cannot open. Skip
  210/362th IFG...
  250/362th IFG...
  220/362th IFG...
  260/362th IFG...
  230/362th IFG...
  270/362th IFG...
ERROR 1: LZWDecode:Wrong length of decoded string: data probably corrupted at scanline 2152
ERROR 1: TIFFReadEncodedStrip() failed.
ERROR 1: /home/zhangcan/128A_05969_131313/GEOC/20190930_20191024/20190930_20191024.geo.cc.tif, band 1: IReadBlock failed at X offset 0, Y offset 1076: TIFFReadEncodedStrip() failed.
  20190930_20191024.geo.cc.tif cannot open. Skip
ERROR 1: LZWDecode:Wrong length of decoded string: data probably corrupted at scanline 2532
ERROR 1: TIFFReadEncodedStrip() failed.
ERROR 1: /home/zhangcan/128A_05969_131313/GEOC/20190202_20190310/20190202_20190310.geo.cc.tif, band 1: IReadBlock failed at X offset 0, Y offset 1266: TIFFReadEncodedStrip() failed.
  20190202_20190310.geo.cc.tif cannot open. Skip
  320/362th IFG...
  360/362th IFG...
  290/362th IFG...
  330/362th IFG...
ERROR 1: ZIPDecode:Decoding error at scanline 2166, incorrect header check
ERROR 1: TIFFReadEncodedStrip() failed.
ERROR 1: /home/zhangcan/128A_05969_131313/GEOC/20200304_20200328/20200304_20200328.geo.cc.tif, band 1: IReadBlock failed at X offset 0, Y offset 1083: TIFFReadEncodedStrip() failed.
  20200304_20200328.geo.cc.tif cannot open. Skip
  300/362th IFG...
  340/362th IFG...
ERROR 1: ZIPDecode:Decoding error at scanline 2595, invalid distance too far back
ERROR 1: TIFFReadEncodedStrip() failed.
ERROR 1: /home/zhangcan/128A_05969_131313/GEOC/20200128_20200209/20200128_20200209.geo.unw.tif, band 1: IReadBlock failed at X offset 0, Y offset 2595: TIFFReadEncodedStrip() failed.
  20200128_20200209.geo.unw.tif cannot open. Skip
  310/362th IFG...
ERROR 1: ZIPDecode:Decoding error at scanline 2383, incorrect data check
ERROR 1: TIFFReadEncodedStrip() failed.
ERROR 1: /home/zhangcan/128A_05969_131313/GEOC/20200409_20200421/20200409_20200421.geo.unw.tif, band 1: IReadBlock failed at X offset 0, Y offset 2383: TIFFReadEncodedStrip() failed.
  20200409_20200421.geo.unw.tif cannot open. Skip
  350/362th IFG...

Create slc.mli.par

Create EQA.dem_par

Copy baselines file

Elapsed time: 00h 00m 46s

LiCSBAS02_ml_prep.py Successfully finished!!

**Here is the log file (step 1-6):**
LiCSBAS16_filt_ts.py ver1.4.5 20201124 Y. Morishita
LiCSBAS16_filt_ts.py -t TS_GEOCml1clip --ex_range_geo 102.9/104.88/30.08/31.43

Size of image (w,l)      : 1981, 1351
Number of images         : 92
Width of filter in space : 2 km (20.9x18.0 pixel)
Width of filter in time  : 0.148 yr (54 days)
Deramp flag              : []
hgt-linear flag          : False
Excluded range           : 0:1981/0:1351

HP filter in time, LP filter in space,
with 12 parallel processing...
/home/zhangcan/anaconda3/envs/licsbas/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py:11: MatplotlibDeprecationWarning: 
The support for Qt4  was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  from matplotlib.backends.qt_compat import QtGui
    0/ 92th image...
   10/ 92th image...
   20/ 92th image...
   30/ 92th image...
   40/ 92th image...
   50/ 92th image...
   60/ 92th image...
   70/ 92th image...
   80/ 92th image...
   90/ 92th image...

**Comment by yumorishita** [comment]
The errors in step02 probably stem from a recent system trouble in the LiCSAR server. The person in charge is now trying to solve it, but what we can do is only waiting. Other messages of MatplotlibDeprecationWarning are just warning and therefore does not matter. I am not sure why the step16 does not finish, but suggest trying with n_para=1
https://github.com/yumorishita/LiCSBAS/blob/d87bd3e20ccebfa4260bb00941a58ed1f3fd5856/batch_LiCSBAS.sh#L109

**Comment by CanZhang-zc** [comment]
Thanks a lot for your response. 
I will try with n_para=1 and redo the step 1-6.

**Comment by yumorishita** [comment]
It seems that the problem has been solved. Let me close this issue.
