### ISSUE TITLE
Multi Prime mode at step 1-2

### ISSUE THREAD

**Issue by fangjinSGG** [yumorishita/LiCSBAS#66]
There is an option '--multi_prime' for checking loop closure at step 1-2. I was wondering in which case I should take into account bias in loop. Thanks for your help.

**Comment by yumorishita** [comment]
If ifgs were created from a stack of SLCs coregistered to a single prime (i.e., in case of LiCSAR products), the --multi_prime is not necessary.

**Comment by fangjinSGG** [comment]
Thanks. I'm now using LiCSAR products. It seems that the --multi_prime can retain some more ifgs.

**Comment by yumorishita** [comment]
Yes, some LiCSAR products unintentionally have inconsistent biases. In that case you may use the --multi_prime option.

**Comment by fangjinSGG** [comment]
Could I find out in which case LiCSAR products might have biases?

**Comment by yumorishita** [comment]
Please check the loop phase images in *loop_*_png/*png. If the majority of the right bottom image (loop phase) has non zero value, one (or more) of the three ifgs has a bias.

**Comment by fangjinSGG** [comment]
In some cases, I need to set a large threshold (3.0 rad or more) at step 1-2, so that the networks are well connected (i.e. there are no gaps in the networks). But the consequences are that a large number of pixels will be masked, with large loop errors and/or large RMS of residuals. I would be very grateful for any suggestions you could give me.

**Comment by yumorishita** [comment]
If the pixels of interest have low coherence (e.g., forest), it is not possible to obtain a reliable time series using Sentinel-1 whatever methods are used. L-band data (currently only ALOS-2) would be the only solution for those areas.

If the pixels of interest are not low coherence but most areas in the frame are decorrelated or have unwrapping errors, I would recommend masking (step04) and/or clipping (step05).

**Comment by fangjinSGG** [comment]
Thanks. I've tried masking some areas. But I still need to specify a large threshold (>3 rad) at step12 to make sure gaps do not exist in the networks.

By the way, I can only specify a rectangular area instead of a polygon.

**Comment by yumorishita** [comment]
Sorry but masking by a polygon is not supported. I recommend using coherence based masking with the rectangular option.

**Comment by fangjinSGG** [comment]
I got a bad network after checking loop closure (with a threshold of 1.5 rad), although there were no interferograms discarded at step11. Pixels with low coherences (<=0.1) were masked. I really appreciate your suggestions.

![image](https://user-images.githubusercontent.com/40376779/108563238-0d454a00-72f9-11eb-8d6e-de0ee1d4b6c9.png)
![image](https://user-images.githubusercontent.com/40376779/108563409-51384f00-72f9-11eb-8cdb-efbd5f0c884d.png)
![image](https://user-images.githubusercontent.com/40376779/108563467-6614e280-72f9-11eb-8a91-9cb4fbf35785.png)

**Comment by yumorishita** [comment]
What is your area and deformation of interest? Large-scale tectonic deformation across the scene, or subsidence in a scene? Have your tried step05?

**Comment by fangjinSGG** [comment]
Thanks. I did think about trying clipping, but I aim to measure the large-scale deformation.

**Comment by yumorishita** [comment]
What is the frame ID?

**Comment by fangjinSGG** [comment]
026A_06124_131313

**Comment by yumorishita** [comment]
I have processed the frame and realised that too many unwrapping errors are included in most of the data over the entire frame. Please see 12loop/bad_loop_png/*.png. It seems to be not possible to obtain a significant result from this data set using LiCSBAS.
