### ISSUE TITLE
Using External interferograms with LiCSBAS

### ISSUE THREAD

**Issue by stallinbhandari** [yumorishita/LiCSBAS#67]
I have a stack of 12 interferograms generated using SNAP with complex values, Intensity,phase coherence, elevation, orthorectified latitude and longitude. how can i use it on LiCSBAS?

**Comment by yumorishita** [comment]
Please see the [file structure](https://github.com/yumorishita/LiCSBAS/wiki/file_structure#input-for-step-1-1-or-steps-0-3-to-0-5-output-of-step-0-2).

See also https://github.com/yumorishita/LiCSBAS/issues/39#issuecomment-758361987

**Comment by yumorishita** [comment]
It seems that you have successfully used your data in LiCSBAS. Let me close this issue.
