### ISSUE TITLE
GACOS correction

### ISSUE THREAD

**Issue by stallinbhandari** [yumorishita/LiCSBAS#68]
Is the GACOS correction data available through COMET web portal also? 
If not, are there any scripts of API for downloading the files from GACOS website automatically?
Do I have to download the GACOS data from gacos website for each epoch individually with several requests?

**Comment by yumorishita** [comment]
The GACOS data are available in some frames, but not in others. I have no API. Generally, we have to request the GACOS data from the website (max 20 epochs/request). Perhaps Chen Yu (https://twitter.com/GACOS_Newcastle) gives you a better way (e.g., API) for a bulk request. Please contact him.
