### ISSUE TITLE
LiCSBAS error

### ISSUE THREAD

**Issue by sarelfonlus** [yumorishita/LiCSBAS#7]
Hi Dr. Dear Prof Yu, I kindly have a problem that arose:
(base) iMac-di-Sarelf: 124D_04854_171313 sarelf $ ./batch_LiCSBAS.sh

Start step: 01
End step: 16
Log file: log / 202005011608batch_LiCSBAS_01_16.log

./batch_LiCSBAS.sh: line 120: LiCSBAS01_get_geotiff.py: command not found
(base) iMac-di-Sarelf: 124D_04854_171313 sarelf $

I kindly ask you for your help. Thank you for your time and kindness. '

**Comment by yumorishita** [comment]
Please confirm that you have run:
`source <your_LiCSBAS_path>/LiCSBAS/bashrc_LiCSBAS.sh`
and <your_LiCSBAS_path>/LiCSBAS/bin has been correctly set in $PATH by
`echo $PATH`

**Comment by sarelfonlus** [comment]
Thank you for your availability and kindness: Elapsed time: 00h 10m 00s

LiCSBAS01_get_geotiff.py Successfully finished!!

Output directory: /Users/sarelf/LiCSBAS/124D_04854_171313/GEOC

Traceback (most recent call last):
  File "/Users/sarelf/LiCSBAS/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 71, in <module>
    import gdal
ModuleNotFoundError: No module named 'gdal'
(base) iMac-di-Sarelf:124D_04854_171313 sarelf$ import gdal
-bash: import: command not found

**Comment by sarelfonlus** [comment]
(base) iMac-di-Sarelf:124D_04854_171313 sarelf$ LiCSBAS_plot_ts.py -i TS_GEOCml1clip / cum_filt.h5 &
[1] 66581
(base) iMac-di-Sarelf:124D_04854_171313 sarelf$ 
LiCSBAS_plot_ts.py ver1.8 20200408 Y. Morishita
LiCSBAS_plot_ts.py -i TS_GEOCml1clip / cum_filt.h5

No TS_GEOCml1clip found!

**Comment by yumorishita** [comment]
You need to install gdal module in your python environment, as is written in:
https://github.com/yumorishita/LiCSBAS/wiki/1_Installation#11-python3-and-required-modules

**Comment by sarelfonlus** [comment]
Yumorishita......
Unfortunately I really have problems solving, probably something wrong. If you can help me .... thank you. I am attaching a screenshot
<img width="2048" alt="Schermata 2020-05-03 alle 16 55 21" src="https://user-images.githubusercontent.com/54473389/80917473-5f63b180-8d5f-11ea-8d8e-b171f0eb28e8.png">

**Comment by sarelfonlus** [comment]
I get lost in this passage maybe I don't do something important ... (source <your_LiCSBAS_path>/LiCSBAS/bashrc_LiCSBAS.sh)must this file (bashrc_LiCSBAS.sh) only be present and copied or should some script be executed?

**Comment by yumorishita** [comment]
You should write `source <your_LiCSBAS_path>/LiCSBAS/bashrc_LiCSBAS.sh` in your ~/.bashrc, or you must run this every time you launch the terminal.
