### ISSUE TITLE
error in masking

### ISSUE THREAD

**Issue by stallinbhandari** [yumorishita/LiCSBAS#70]
While running mask script as
LiCSBAS04op_mask_unw.py -i GEOCml1_GACOS -o GEOCml1_GACOS_masked -c 0.2
I get this error->

LiCSBAS04op_mask_unw.py ver1.3.5 20210105 Y. Morishita
LiCSBAS04op_mask_unw.py -i GEOCml1_GACOS -o GEOCml1_GACOS_masked -c 0.2 -r 0

Calculate coh_avg and define mask (<=0.2)
Traceback (most recent call last):
  File "/home/stu/LiCSBAS/bin/LiCSBAS04op_mask_unw.py", line 326, in <module>
    sys.exit(main())
  File "/home/stu/LiCSBAS/bin/LiCSBAS04op_mask_unw.py", line 191, in main
    coh = io_lib.read_img(ccfile, length, width)
  File "/home/stu/LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 153, in read_img
    data = np.fromfile(file, dtype=dtype).reshape((length, width))
ValueError: cannot reshape array of size 0 into shape (2721,2974)

**Comment by yumorishita** [comment]
It seems that a coherence file is empty. Please check the size of GEOCml1_GACOS/*/*.cc files.

If you are not using batch_LiCSBAS.sh, I recommend using it.

**Comment by stallinbhandari** [comment]
Thank you, the problem was solve. The process was not running on the original coherence file. I removed the GEOCml1 folder and re did the conversion and applied the correction and masked it successfully.
