### ISSUE TITLE
WARNING in GACOS correction step

### ISSUE THREAD

**Issue by stallinbhandari** [yumorishita/LiCSBAS#71]
I get this type of warning while running the GACOS correction step. Nevertheless, the process finishes successfully. Will there be any problem?
warning seems like folows
/home/stu/miniconda3/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
  Finished   70/ 206th unw...
  Finished  110/ 206th unw...
  Finished   90/ 206th unw...

**Comment by yumorishita** [comment]
I guess some of the unwrapped data have completely no data. It is just a warning and not be a significant problem.
