### ISSUE TITLE
licsbas decompose:cumulative displacements from ascending and descending orbits

### ISSUE THREAD

**Issue by stallinbhandari** [yumorishita/LiCSBAS#72]
hi yumorishita,
I got the cumulative displacements from both ascending and descending orbits. but the values have high discrepancy (Asc.-> -404 to 64 and Dsc.->-237 to 74)mm for Kathmandu, Nepal. Is it rational or not? do they differ to that extent?
The final decomposed values for components EW =-17 to 109 and UD =-400 to 82.
What shall I do for the NS component?

**Comment by yumorishita** [comment]
The difference between asc and des could be rational because they contain different deformation components (opposite contribution from horizontal deformation).
The NS component cannot be obtained only from right looking because of insensitivity to the NS deformation.

**Comment by stallinbhandari** [comment]
And, how can we validate the results? 
can we convert the GNSS data onto the LOS vector? how?

**Comment by yumorishita** [comment]
You can project GNSS 3D (EW, NS, UD) deformation data to a LOS direction by multiplying LOS unit vector components (E.geo, N.geo, U.geo) and summing them.

**Comment by stallinbhandari** [comment]
can i do it this way?
first converting the U.geo file to tiff
then multiplying the U.geo.tiff with the UD component of GNSS in a GIS software?

**Comment by stallinbhandari** [comment]
both the asc. and dsc. frames have U.geo file. Which one should I use?

**Comment by yumorishita** [comment]
Asc and des have different LOS. You should convert GNSS 3D deformation to asc and des LOS respectively. You need E/N/U.geo in both orbits. I suggest reading the E/N/U value at the location of GNSS points from E/N/U.geo using GIS software. Then multiplying and summing them (i.e., calculate the inner product of the GNSS 3D deformation vector and the LOS unit vector).

**Comment by stallinbhandari** [comment]
Can we compare the EW and UD components from LiCSBAS_decompose output with the vertical component of GNSS measurement?

**Comment by stallinbhandari** [comment]
> Asc and des have different LOS. You should convert GNSS 3D deformation to asc and des LOS respectively. You need E/N/U.geo in both orbits. I suggest reading the E/N/U value at the location of GNSS points from E/N/U.geo using GIS software. Then multiplying and summing them (i.e., calculate the inner product of the GNSS 3D deformatio

**Comment by yumorishita** [comment]
Yes, UD from LiCSBAS and vertical GNSS are comparable. We should note the reference point.

**Comment by stallinbhandari** [comment]
are the E,N,U unit vectors same for a particular frame even if the master image is changed?

**Comment by stallinbhandari** [comment]
the cumulative displacements for ascending and descending data are for two different time periods. The deformation of which time period is given by the LiCSBAS_decompose output?

**Comment by yumorishita** [comment]
It depends on the input LOS deformation files you used.

**Comment by yumorishita** [comment]
If you used different time periods for asc and des, the decomposed deformation has no particular time period. You must assume something (e.g., no deformation between... or constant velocity)

**Comment by stallinbhandari** [comment]
in my case, the study area has a tectonic movement of 4cm/yr in NE direction, does this influence my results?

**Comment by yumorishita** [comment]
It depends.

**Comment by yumorishita** [comment]
This question is not about LiCSBAS software, but general InSAR knowledge. Let me close this issue.

**Comment by shubham-geolearner** [comment]
how to get cummulative displacement geotiff file?
