### ISSUE TITLE
how to show the map automatically in the figure?

### ISSUE THREAD

**Issue by 20152023** [yumorishita/LiCSBAS#74]
thank you for your previous reply, and i had figured out the problems that i had met
but now, i have a burst image from sentinel-1 shown in the figure 
![QQ图片20210218112543](https://user-images.githubusercontent.com/32829802/108301981-083fa800-71de-11eb-93bd-3dd5cecb7f47.png)
, it do not filled all canvas and still remains lots of blank, its width larger than height, how can i spread it all over the canvas?

**Comment by yumorishita** [comment]
Not sure but aspect ratio might be wrongly set. Please try replacing the following line with aspect = 1.

https://github.com/yumorishita/LiCSBAS/blob/5ddc43b98f3f26dc229f72ae95bcc18d8472847f/bin/LiCSBAS_plot_ts.py#L340

**Comment by 20152023** [comment]
> Not sure but aspect ratio might be wrongly set. Please try replacing the following line with aspect = 1.
> 
> https://github.com/yumorishita/LiCSBAS/blob/5ddc43b98f3f26dc229f72ae95bcc18d8472847f/bin/LiCSBAS_plot_ts.py#L340

yes, it works, thanks
