### ISSUE TITLE
Licsbas plotting parmeters

### ISSUE THREAD

**Issue by stallinbhandari** [yumorishita/LiCSBAS#75]
hi yumorishita
i want to know what the parameters in licsbasplot infer to . like: vel1, vel2 in velocity/cumulative displacement  plot and the time-series plot... are there any documentations that i can refer to to know the details of the plot?

**Comment by yumorishita** [comment]
vel1 and vel2 correspond to files indicated by -i (default: filtered cum_filt.h5) and --i2 (default: unfiltered cum.h5) options, also shown as 1 (blue) and 2 (red) in the time series window.
