### ISSUE TITLE
ModuleNotFoundError: No module named 'psutil'

### ISSUE THREAD

**Issue by sazzath** [yumorishita/LiCSBAS#76]
[202102191419batch_LiCSBAS_sample_CF_01_16.log](https://github.com/yumorishita/LiCSBAS/files/6010385/202102191419batch_LiCSBAS_sample_CF_01_16.log)

**Comment by yumorishita** [comment]
Please install psutil in your python environment.

**Comment by sazzath** [comment]
LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &   

This command is not working , Its shows No TS_GEOCml1clip/cum_filt.h5 found!

**Comment by yumorishita** [comment]
Sure, because the cum_filt.h5 was not created due to the error in step13. See the log. Install psutil and restart from step13.

**Comment by sazzath** [comment]
![image](https://user-images.githubusercontent.com/72601348/108696167-7b5c5d80-7501-11eb-9ead-7363067558af.png)

Why its takes too long time Like 2 days r
[202102210449batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/6021303/202102210449batch_LiCSBAS_01_16.log)
unning

**Comment by yumorishita** [comment]
Because you are processing very large data set. It is quite natural.
