### ISSUE TITLE
LOS decompose and reference area

### ISSUE THREAD

**Issue by stallinbhandari** [yumorishita/LiCSBAS#77]
the stable reference points/area for ascending and descending orbits from SB Inversion are different. Does it matter while using the corresponding cumulative displacements in the decomposition?

**Comment by yumorishita** [comment]
It depends, but the common reference is better.

**Comment by stallinbhandari** [comment]
Dear yumorishita,
-what  are the factors that may influence the use?

**Comment by stallinbhandari** [comment]
I used same ref area for both orbits and got no difference in cumulative displacements. Is there any thing wrong ?

**Comment by yumorishita** [comment]
It is difficult to describe the factors... In your case, the original different references seem to be OK. Choosing a different point but having the same deformation would make the same result.

**Comment by stallinbhandari** [comment]
my ascending data ranges from 2016/01/10 to 2020/06/29 and descending data ranges from 2016/02/11 to 2020/07/07. then what will be the time period of the UD components from LiCSBAS_decompose?

**Comment by yumorishita** [comment]
Not possible to define the exact time period of the UD components.

**Comment by yumorishita** [comment]
This question is not about LiCSBAS software, but general InSAR knowledge. Let me close this issue.
