### ISSUE TITLE
About LiCSAR products

### ISSUE THREAD

**Issue by stallinbhandari** [yumorishita/LiCSBAS#78]
is it that the master image is the one provided in the metadata.txt file?
i see interferograms with different pairs of dates what do they mean? 
in format: date1_date2
                date1_date3
                date1_date4
                date2_date3............. and so on 
aren't the interferogram meant to be in M_s1,M_s2,Ms_3.... format where M is master image and s1,s2,s3 are slave images ?

**Comment by yumorishita** [comment]
The image written in the metadata.txt is the single primary image. date1 and date2 mean primary and secondary in date1_date2, respectively.

By the way, we no longer use master and slave. See https://comet.nerc.ac.uk/about-comet/insar-terminology/
