### ISSUE TITLE
step01_get_geotiff doesn't skip download when file exist

### ISSUE THREAD

**Issue by sahitono** [yumorishita/LiCSBAS#8]
I've been wondering why it is slow when skip download in step01. And then, i realize that it's not skipping download for geo.mli.tiff, geo.unw.tiff and geo.cc.tiff . I changed some code and found out that download_data in elif statement is the source of problem. So i changed download_data from tool_lib to be this.
``` python
def download_data(url, file):
    try:
        with requests.get(url) as res:
            res.raise_for_status()
            with open(file, "wb") as output:
                output.write(res.content)
        return True
    except requests.exceptions.RequestException as error:
        print(
            "    Error while downloading from {}".format(url),
            file=sys.stderr,
            flush=True,
        )
        raise SystemExit(error)
```

and i changed the elif statement to be this
```python
        if os.path.exists(path_unw):
            print("    {}.geo.unw.tif already exist. Skip".format(ifgd), flush=True)
        else:
            tools_lib.download_data(url_unw, path_unw)
```

And it works as expected.

**Comment by yumorishita** [comment]
Thank you very much for reporting the issue and suggesting the modification. I will update the code.

Regarding the elif statement, I think I should update all 
` [el]if not tools_lib.download_data(*, *):
    print...`
lines to
` else:
      tools_lib.download_data(*, *)`
as you suggested.
Do you think is that right?

**Comment by sahitono** [comment]
You're welcome. Yes, that is right. I also think it's better not to return any value in download_data because the error already caught and the data is saved not returned. 

I found out that it's better to send HEAD than GET when checking mli.tif to find the earliest date in which mli is available. So, it won't download the entire file but only check if link exist.

**Comment by yumorishita** [comment]
Thanks! I see your points. I will update the codes soon.

**Comment by sahitono** [comment]
You are welcome, glad to hear that ^^

**Comment by yumorishita** [comment]
I will update the codes almost as you suggested, but I will not include "raise SystemExit(error)" in download_data because the not-downloaded data are not necessary for later steps (i.e., can be skipped) and the step01 processing should not be stopped.

Please let me know if you have any thoughts about this.

**Comment by sahitono** [comment]
Oohh,  so that's okay to ignore not-downloaded data ? Then it is not necessary to raise any exception and systemexit.

**Comment by yumorishita** [comment]
Yes, sometimes missing data exist in LiCSAR products but later steps in LiCSBAS can run without them.

I have updated the codes. Thank you for your suggestion.
