### ISSUE TITLE
module 'roma' is not a valid value for name

### ISSUE THREAD

**Issue by Leaqiliang** [yumorishita/LiCSBAS#80]
[202102212018bash_01_16.log](https://github.com/yumorishita/LiCSBAS/files/6019097/202102212018bash_01_16.log)

Hello, when I run batch_LiCSBAS.sh, it report an error that 'module SCM not find.So I copied roma0.py to work dir and modified LiCSBAS02_ml_prep.py that 'import roma0'.And then, it report this error.

how can I fix it? or how can I import SCM correctly?

Thank you .

**Comment by yumorishita** [comment]
SCM is included in the LiCSBAS package. If LiCSBAS was correctly installed, such errors would not occur. Have you checked the installation by LiCSBAS_check_install.py?
https://github.com/yumorishita/LiCSBAS/wiki/1_Installation#13-check-install

**Comment by Leaqiliang** [comment]
Thank you! I checked and it works.

But it report a warning when it running Licsbas13_sb_inv.py that 'Not enough memory available compared mem_size(4000mb)'.And then it reducemem_size and keep running.I want to know if it use swap, because my pc have 4g memory and 16g swap.

**Comment by yumorishita** [comment]
LiCSBAS does not use swap. The automatic reduction of the mem_size is normal behaviour and should be no problem.

**Comment by Leaqiliang** [comment]
OK, Thank you!
