### ISSUE TITLE
KMZ

### ISSUE THREAD

**Issue by fk364202818** [yumorishita/LiCSBAS#81]
Hallo!

Can cum_filt.h5  be converted to KMZ?

Best regards
Kun

**Comment by yumorishita** [comment]
Yes. First, create a float file using [LiCSBAS_cum2flt.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_cum2fltpy) or [LiCSBAS_cum2vel.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_cum2velpy), then output a kmz by [LiCSBAS_disp_img.py](https://github.com/yumorishita/LiCSBAS/wiki/3_visualization#licsbas_disp_imgpy) with --kmz option.

**Comment by fk364202818** [comment]
Thank you very much!

**Comment by AlirezaS89** [comment]
Hi,
I create a float file using LiCSBAS_cum2vel.py. When using LiCSBAS_disp_img.py, which .par file should I use?

**Comment by yumorishita** [comment]
EQA.dem_par
