### ISSUE TITLE
Step LICSBAS03op_Gacos.py

### ISSUE THREAD

**Issue by alejobeap** [yumorishita/LiCSBAS#83]
Dear
I'm processing with GACOS correction but LICSBAS is already 12 hours into this step. What can I do to avoid this?

LiCSBAS03op_GACOS.py ver1.5.5 20201119 Y. Morishita
LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOCml1GACOS --fillhole

Convert ztd/sltd.geo.tif files to sltd.geo files...
  8 parallel processing...
  Finished    0/ 195th sltd...
    Use 20141006.ztd[.rsc]
    Use 20160504.ztd[.rsc]
    Use 20170423.ztd[.rsc]
    Use 20151130.ztd[.rsc]
    Use 20160913.ztd[.rsc]
    Use 20161212.ztd[.rsc]
    Use 20170123.ztd[.rsc]
    Use 20170622.ztd[.rsc]
    Use 20160516.ztd[.rsc]
    Use 20170429.ztd[.rsc]
    Use 20170129.ztd[.rsc]
    Use 20151224.ztd[.rsc]
  Finished   50/ 195th sltd...
    Use 20170704.ztd[.rsc]
    Use 20161001.ztd[.rsc]
    Use 20141217.ztd[.rsc]
    Use 20161218.ztd[.rsc]
    Use 20170505.ztd[.rsc]
    Use 20160528.ztd[.rsc]
    Use 20160117.ztd[.rsc]
    Use 20161025.ztd[.rsc]
  Finished   30/ 195th sltd...
    Use 20161224.ztd[.rsc]
    Use 20170710.ztd[.rsc]
    Use 20150110.ztd[.rsc]
    Use 20170210.ztd[.rsc]
    Use 20170511.ztd[.rsc]
    Use 20160609.ztd[.rsc]
  Finished   10/ 195th sltd...
    Use 20160210.ztd[.rsc]
    Use 20161230.ztd[.rsc]
    Use 20170222.ztd[.rsc]
    Use 20161112.ztd[.rsc]
    Use 20150203.ztd[.rsc]
    Use 20170716.ztd[.rsc]
    Use 20170517.ztd[.rsc]
    Use 20160703.ztd[.rsc]
    Use 20160305.ztd[.rsc]
    Use 20170105.ztd[.rsc]
    Use 20170405.ztd[.rsc]
    Use 20170728.ztd[.rsc]
    No 20150311.ztd|ztd.tif|sltd.geo.tif! Skip.
    No 20150428.ztd|ztd.tif|sltd.geo.tif! Skip.
    Use 20161118.ztd[.rsc]
    Use 20151106.ztd[.rsc]
    Use 20170604.ztd[.rsc]
    Use 20160329.ztd[.rsc]
    Use 20160727.ztd[.rsc]
  Finished   40/ 195th sltd...
    Use 20170411.ztd[.rsc]
    Use 20170111.ztd[.rsc]
    Use 20170815.ztd[.rsc]
    Use 20161130.ztd[.rsc]
    Use 20170803.ztd[.rsc]
  Finished   20/ 195th sltd...
    Use 20160820.ztd[.rsc]
    Use 20170616.ztd[.rsc]
    Use 20160422.ztd[.rsc]
    Use 20170117.ztd[.rsc]
    Use 20170417.ztd[.rsc]
    Use 20170821.ztd[.rsc]
    Use 20161206.ztd[.rsc]
    Use 20170809.ztd[.rsc]
    Use 20171008.ztd[.rsc]
  Finished   70/ 195th sltd...
    Use 20171207.ztd[.rsc]
    Use 20180217.ztd[.rsc]
    Use 20180412.ztd[.rsc]
    Use 20180530.ztd[.rsc]
    Use 20170827.ztd[.rsc]
    Use 20180717.ztd[.rsc]
    Use 20180223.ztd[.rsc]
    Use 20171213.ztd[.rsc]
    Use 20171014.ztd[.rsc]
    Use 20180828.ztd[.rsc]
    Use 20180605.ztd[.rsc]
    Use 20180418.ztd[.rsc]
    Use 20170908.ztd[.rsc]
    Use 20180723.ztd[.rsc]
    Use 20180903.ztd[.rsc]
    Use 20171026.ztd[.rsc]
    Use 20171225.ztd[.rsc]
    Use 20180301.ztd[.rsc]
    Use 20180424.ztd[.rsc]
    Use 20180611.ztd[.rsc]
  Finished   60/ 195th sltd...
    Use 20170914.ztd[.rsc]
  Finished  100/ 195th sltd...
    Use 20180729.ztd[.rsc]
    Use 20180909.ztd[.rsc]
    Use 20171101.ztd[.rsc]
    Use 20180112.ztd[.rsc]
  Finished   80/ 195th sltd...
    Use 20180313.ztd[.rsc]
    Use 20180430.ztd[.rsc]
    Use 20180617.ztd[.rsc]
    Use 20170920.ztd[.rsc]
    Use 20180319.ztd[.rsc]
    Use 20171119.ztd[.rsc]
    Use 20180804.ztd[.rsc]
    Use 20180124.ztd[.rsc]
    Use 20180506.ztd[.rsc]
    Use 20180915.ztd[.rsc]
    Use 20170926.ztd[.rsc]
    Use 20180623.ztd[.rsc]
    Use 20180325.ztd[.rsc]
    Use 20171125.ztd[.rsc]
    Use 20180810.ztd[.rsc]
    Use 20180921.ztd[.rsc]
    Use 20180205.ztd[.rsc]
    Use 20180705.ztd[.rsc]
    Use 20180512.ztd[.rsc]
    Use 20181009.ztd[.rsc]
    Use 20180406.ztd[.rsc]
    Use 20171201.ztd[.rsc]
    Use 20180816.ztd[.rsc]
  Finished  110/ 195th sltd...
    Use 20180927.ztd[.rsc]
    Use 20181015.ztd[.rsc]
    Use 20180211.ztd[.rsc]
    Use 20180711.ztd[.rsc]
    Use 20181120.ztd[.rsc]
  Finished   90/ 195th sltd...
    Use 20180518.ztd[.rsc]
    Use 20190107.ztd[.rsc]
    Use 20180822.ztd[.rsc]
    Use 20181003.ztd[.rsc]
    Use 20181021.ztd[.rsc]
    Use 20190302.ztd[.rsc]
  Finished  140/ 195th sltd...
    Use 20190419.ztd[.rsc]
  Finished  120/ 195th sltd...
    Use 20181202.ztd[.rsc]
    Use 20190823.ztd[.rsc]
    Use 20190113.ztd[.rsc]
    Use 20191103.ztd[.rsc]
    Use 20200126.ztd[.rsc]
    Use 20181027.ztd[.rsc]
    Use 20190314.ztd[.rsc]
    Use 20190425.ztd[.rsc]
    Use 20181208.ztd[.rsc]
    Use 20190904.ztd[.rsc]
    Use 20190119.ztd[.rsc]
    Use 20191115.ztd[.rsc]
    Use 20181102.ztd[.rsc]
    Use 20200207.ztd[.rsc]
    Use 20190320.ztd[.rsc]
    Use 20190501.ztd[.rsc]
    Use 20181214.ztd[.rsc]
    Use 20190916.ztd[.rsc]
    Use 20190125.ztd[.rsc]
    Use 20191127.ztd[.rsc]
    Use 20181108.ztd[.rsc]
    Use 20190326.ztd[.rsc]
    Use 20200219.ztd[.rsc]
    Use 20190507.ztd[.rsc]
  Finished  150/ 195th sltd...
    Use 20190928.ztd[.rsc]
  Finished  130/ 195th sltd...
    Use 20190206.ztd[.rsc]
    Use 20181220.ztd[.rsc]
    Use 20191209.ztd[.rsc]
    Use 20181114.ztd[.rsc]
    Use 20190401.ztd[.rsc]
    Use 20200302.ztd[.rsc]
    Use 20190519.ztd[.rsc]
    Use 20191221.ztd[.rsc]
    Use 20190218.ztd[.rsc]
    Use 20191004.ztd[.rsc]
    Use 20181226.ztd[.rsc]
    Use 20200419.ztd[.rsc]
    Use 20190407.ztd[.rsc]
    Use 20200314.ztd[.rsc]
    Use 20190612.ztd[.rsc]
    Use 20200102.ztd[.rsc]
    Use 20190224.ztd[.rsc]
    Use 20191010.ztd[.rsc]
    Use 20190101.ztd[.rsc]
    Use 20190413.ztd[.rsc]
    Use 20200326.ztd[.rsc]
    Use 20190706.ztd[.rsc]
    Use 20200501.ztd[.rsc]
  Finished  160/ 195th sltd...
    Use 20200114.ztd[.rsc]
    Use 20200712.ztd[.rsc]
    Use 20191022.ztd[.rsc]
    Use 20200904.ztd[.rsc]
    Use 20200407.ztd[.rsc]
    Use 20201022.ztd[.rsc]
  Finished  170/ 195th sltd...
    Use 20200513.ztd[.rsc]
    Use 20200724.ztd[.rsc]
    Use 20200910.ztd[.rsc]
    Use 20200525.ztd[.rsc]
    Use 20200805.ztd[.rsc]
    Use 20200922.ztd[.rsc]
  Finished  190/ 195th sltd...
    Use 20201028.ztd[.rsc]
    Use 20200606.ztd[.rsc]
    Use 20200811.ztd[.rsc]
    Use 20201109.ztd[.rsc]
    Use 20200928.ztd[.rsc]
    Use 20200618.ztd[.rsc]
    Use 20200817.ztd[.rsc]
    Use 20201203.ztd[.rsc]
    Use 20201004.ztd[.rsc]
    Use 20200630.ztd[.rsc]
  Finished  180/ 195th sltd...
    Use 20200823.ztd[.rsc]
    No 20201215.ztd|ztd.tif|sltd.geo.tif! Skip.
    No 20201227.ztd|ztd.tif|sltd.geo.tif! Skip.
    Use 20201010.ztd[.rsc]
    Use 20200829.ztd[.rsc]
    Use 20201016.ztd[.rsc]

Correct unw data...
  8 parallel processing...
  Finished    0/ 416th unw...
  Finished   40/ 416th unw...
  Finished   80/ 416th unw...
  ztd file not available for 20141217_20150311
  Finished   30/ 416th unw...
  ztd file not available for 20150110_20150428
  ztd file not available for 20150203_20150428
  Finished   70/ 416th unw...
  Finished   10/ 416th unw...
  Finished   20/ 416th unw...
  Finished   60/ 416th unw...
  Finished  100/ 416th unw...
  Finished   50/ 416th unw...
  Finished   90/ 416th unw...
  Finished  130/ 416th unw...
  Finished  120/ 416th unw...
  Finished  170/ 416th unw...
  Finished  110/ 416th unw...
  Finished  160/ 416th unw...
  Finished  200/ 416th unw...
  Finished  150/ 416th unw...
  Finished  190/ 416th unw...
  Finished  210/ 416th unw...
  Finished  140/ 416th unw...
  Finished  180/ 416th unw...
  Finished  260/ 416th unw...
  Finished  300/ 416th unw...
  Finished  250/ 416th unw...
  Finished  230/ 416th unw...
  Finished  240/ 416th unw...
  Finished  290/ 416th unw...
  Finished  220/ 416th unw...
  Finished  280/ 416th unw...
  Finished  270/ 416th unw...
  Finished  310/ 416th unw...
  Finished  340/ 416th unw...
  Finished  330/ 416th unw...
  Finished  390/ 416th unw...
  Finished  320/ 416th unw...
  Finished  380/ 416th unw...
  Finished  370/ 416th unw...
  ztd file not available for 20201022_20201215
  Finished  410/ 416th unw...
  ztd file not available for 20201028_20201215
  ztd file not available for 20201109_20201215
  ztd file not available for 20201203_20201215
  ztd file not available for 20201203_20201227
  Finished  360/ 416th unw...
  Finished  350/ 416th unw...
  Finished  400/ 416th unw...

Thanks for your help

Alejandro

**Comment by yumorishita** [comment]
You can make it faster with larger nlook at the cost of resolution. You must start from step02 again if you change the nlook.

https://github.com/yumorishita/LiCSBAS/blob/db454df4220a3dbc30ca092102fa3151dff560b9/batch_LiCSBAS.sh#L22

Or clipping the area in step05 can also make it faster, which can be done before step03 by setting the order of the optional steps like "05 03 04"

https://github.com/yumorishita/LiCSBAS/blob/db454df4220a3dbc30ca092102fa3151dff560b9/batch_LiCSBAS.sh#L72

**Comment by NabilAttar** [comment]
> You can make it faster with larger nlook at the cost of resolution. You must start from step02 again if you change the nlook.
> 
> https://github.com/yumorishita/LiCSBAS/blob/db454df4220a3dbc30ca092102fa3151dff560b9/batch_LiCSBAS.sh#L22
> 
> Or clipping the area in step05 can also make it faster, which can be done before step03 by setting the order of the optional steps like "05 03 04"
> 
> https://github.com/yumorishita/LiCSBAS/blob/db454df4220a3dbc30ca092102fa3151dff560b9/batch_LiCSBAS.sh#L72

excuse me sir Yumorishita, i have a same problem. In the nlook parameter, 
change it to what number for faster processing GACOS? thank you
