### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by tanmeimei** [yumorishita/LiCSBAS#84]
Hi,

If there would be any possible choice to store data in time series. I have tried LiCSBAS_cum2tstxt.py but it could only store in point. If there would be any tool to store it in line or area?

Best regards

**Comment by yumorishita** [comment]
There is no direct tool to store the time series in a line or area. I suggest an easy solution:
1. Create a list of lat/lon or x/y for the line or area of interested
2. Iterate LiCSBAS_cum2tstxt.py for each point

Or, you can directory manipulate the cum*.h5 using h5py module in python.

**Comment by tanmeimei** [comment]
Thanks.

**Comment by tanmeimei** [comment]
Thanks, now it works.
