### ISSUE TITLE
LiCSBAS16_filt_ts.py

### ISSUE THREAD

**Issue by Gautam5673** [yumorishita/LiCSBAS#86]
Hi Sir 
I'm facing the problem in 16th step. I have run the batch script 3 times but got struck in the last step.It seems that Steps1(get_geotiff.py)～15(mask_ts.ps) were all successfully finished, however, when it comes to "LiCSBAS16_filt_ts.py -t TS_GEOCml1",

"
LiCSBAS16_filt_ts.py ver1.4.5 20201124 Y. Morishita
LiCSBAS16_filt_ts.py -t TS_GEOCml1 --n_para 1

Size of image (w,l)      : 2986, 2712
Number of images         : 125
Width of filter in space : 2 km (20.4x18.0 pixel)
Width of filter in time  : 0.138 yr (50 days)
Deramp flag              : []
hgt-linear flag          : False

HP filter in time, LP filter in space,
with 1 parallel processing...
    0/125th image...
   10/125th image...
   20/125th image...
   30/125th image...
   40/125th image...
   50/125th image...
   60/125th image...
  100/125th image...

"
The program stayed in this state for 16 hours and still didn't make progress. I re-ran the program again, however, the program was still stocked in this part.
I have also tried your previous suggestion in  #45--    try with n_para="1"
Pleas help me out !

Here is the screenshot of terminal along with system monitor.
![Screenshot from 2021-03-07 10-18-41](https://user-images.githubusercontent.com/66096290/110229632-ee69c900-7f30-11eb-974a-63491098de30.png)

I'm also attaching the log files-
[202103060131batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/6096578/202103060131batch_LiCSBAS_01_16.log)
[202103070138batch_LiCSBAS_15_16.log](https://github.com/yumorishita/LiCSBAS/files/6096579/202103070138batch_LiCSBAS_15_16.log)

**Comment by Gautam5673** [comment]
It seems  n_para="1"  is not working here.

**Comment by yumorishita** [comment]
I have slightly updated the code of step16. Please update your installed module and try again with n_para=1.

**Comment by Gautam5673** [comment]
Sir
Thank you so much. It worked well.
But taking time larger time with single processing Core.

**Comment by yumorishita** [comment]
Of course the single processing takes longer time, but there is no other choice without multi processing in your environment. I usually use downsample (step02) and/or clip (step05) to save processing time.

**Comment by Gautam5673** [comment]
Ok
Thank you Sir !

**Comment by smailt** [comment]
Hi,
I re- download the LiCSBAS as you said.
and changed the file LiCSBAS01_get_geotiff.py (n_para = 1) but the same problem!.

and for the clip (step05) to save processing time it seems don't working ?  
`do05op_clip="Y"	# y/n
p04_mask_coh_thre=""	# e.g. 0.2
p04_mask_range=""	# e.g. 10:100/20:200 (ix start from 0)
p04_mask_range_file=""	# Name of file containing range list
p05_clip_range=""	# e.g. 10:100/20:200 (ix start from 0)
p05_clip_range_geo="6.1/6.43/36.38/36.58"	# e.g. 130.11/131.12/34.34/34.6 (in deg)
`

**Comment by yumorishita** [comment]
Please upload the log file. I wonder if the Y should be y.
