### ISSUE TITLE
PermissionError with step 1-1

### ISSUE THREAD

**Issue by CanZhang-zc** [yumorishita/LiCSBAS#89]
Help please, I encounter some problems:
When run the batch script, there is an PermissionError with step 1-1. And when running the batch script this time, I use a mobile hard disk drive. I do not know if this is related to the error.
Sorry for any inconvenience caused, your assistance will be highly appreciated. 

**Here is the log file (step 1-1):**
LiCSBAS11_check_unw.py ver1.3.2 20201116 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCml1clip

coh_thre     : 0.05
unw_cov_thre : 0.3

Size         : 3036 x 2699

Reading unw and cc data...
    0/534th unw to identify valid area...
  100/534th unw to identify valid area...
  200/534th unw to identify valid area...
  300/534th unw to identify valid area...
  400/534th unw to identify valid area...
  500/534th unw to identify valid area...
    0/534th cc and unw...
  100/534th cc and unw...
  200/534th cc and unw...
  300/534th cc and unw...
  400/534th cc and unw...
  500/534th cc and unw...
Traceback (most recent call last):
  File "/home/zhangcan/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 348, in <module>
    sys.exit(main())
  File "/home/zhangcan/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 281, in main
    os.symlink(os.path.relpath(rasorg, ifg_rasdir), os.path.join(ifg_rasdir, rasname))
PermissionError: [Errno 1] Operation not permitted: '../../GEOCml1clip/20160113_20160206/20160113_20160206.unw.png' -> '/media/zhangcan/Backup Plus/128A_05969_131313/TS_GEOCml1clip/11ifg_ras/20160113_20160206.unw.png'

**Comment by yumorishita** [comment]
I think the error is caused by the mobile device. Changing permission (i.e. `chmod -R 777 128A_05969_131313`) might solve the problem. If it does not work, I just suggest not using the mobile device.

**Comment by CanZhang-zc** [comment]
Thanks a lot for your response.
May I ask how to change permission? What are the specific steps?

**Comment by CanZhang-zc** [comment]
Type the command (i.e. chmod -R 777 128A_05969_131313) directly at the terminal?

**Comment by yumorishita** [comment]
Yes.

```bash
cd /media/zhangcan/Backup Plus
chmod -R 777 128A_05969_131313
```

**Comment by CanZhang-zc** [comment]
Thanks a lot for your response again.
I will try it later and wait for the result of processing.

**Comment by yumorishita** [comment]
Yes, you should sudo is you can.

**Comment by CanZhang-zc** [comment]
Thanks a lot.
I will try to do it this way like this:
**cd /media/zhangcan/Backup Plus
sudo chmod -R 777 128A_05969_131313**

**Comment by CanZhang-zc** [comment]
Dear Yu,
Yesterday I used the above command to change the permission, but after this command, I got stuck at the beginning, even did not get to the PermissionError steps. What's the reason of it?
Thanks a lot.

**Here is the log file:**
LiCSBAS01_get_geotiff.py ver1.6.3 20201207 Y. Morishita
LiCSBAS01_get_geotiff.py -f 128A_05969_131313 -s 20160113 -e 20200714

Frame ID is 128A_05969_131313

128A_05969_131313.geo.E.tif already exist. Skip download.
128A_05969_131313.geo.N.tif already exist. Skip download.
128A_05969_131313.geo.U.tif already exist. Skip download.
128A_05969_131313.geo.hgt.tif already exist. Skip download.

Download baselines
    baselines, 4.28KB, 1s, 4.28KB/s
Download network.png
    network.png, 514.08KB, 77s, 6.68KB/s
Download metadata.txt
    metadata.txt, 44.0B, 1s, 44.0B/s

128A_05969_131313.geo.mli.tif already exist. Skip.



Download geotiff of unw and cc
528 IFGs available from 20160113 to 20200714
Checking existing unw and cc (4 parallel, may take time)...

**Comment by yumorishita** [comment]
How long have you waited? The step01 may take long time as mentioned the log file.

Also why did you start from step01? Your first issue was in step11.

**Comment by CanZhang-zc** [comment]
Thanks a lot for your response again.
I just want to rerun the batch script to see if changing the permission would solve the problem, but I just continued to get the PermissionError.
At the same time, I would like to ask you if there is any way to avoid this error with mobile devices when LiCSBAS is executed by laptop in the case of insufficient space.

**Comment by CanZhang-zc** [comment]
Thanks a lot for your response again.
I just want to rerun the batch script to see if changing the permission would solve the problem, but I just continued to get the PermissionError.
Thank you very much for your help these days. I will try to solve the problems on the device. Thank you again!

**Comment by CanZhang-zc** [comment]
Dear Yu,
The step 1-3 have stopped here for a long time, What's the reason of it?

**Here is the log file:**
Find stable reference point...
Selected ref: 2237:2238/1110:1111

Output increment png images with 12 parallel processing...

**Comment by yumorishita** [comment]
The parallel processing sometimes stops, but I don't know why. Please try again with n_para=1.

Have you solved the permission error?

**Comment by CanZhang-zc** [comment]
Thanks a lot for your response.
The PermissionError have solved, this error is due to the file format of the hard disk.
In addition, **n_para=1** is **p13_n_para=""	# default: # of usable CPU**?

**Comment by yumorishita** [comment]
Yes.

**Comment by CanZhang-zc** [comment]
Thanks a lot, Yu.
I will do it then. 
Now I close the issue (because the PermissionError has solved). If there are any other problems, I'll ask you with other new issue.
Thank you very much for your response and help. I wish you all the best!
