### ISSUE TITLE
Error occurs when apply --gpu for LiCSBAS13_sb_inv.py 

### ISSUE THREAD

**Issue by wzmucas** [yumorishita/LiCSBAS#90]
Dear Yu,

I got a problem running LiCSBAS13_sb_inv.py with GPU function, any idea about it? Thanks a lot for your time.

BTW, when I remove the GPU flag for pure CPU computation, for the below case, it will stop in the second-last patch (i.e, `(5/6th patch)...`) though the new version of 1.5.1 does have faster performance than the previous version. Even I decreased the CPUs from 32 to 4 in case the stop is caused by multiprocessing error in Python, but it will stop anyway. Maybe this is due to my working system, but the previous version running is ok except for the slow speed.

System: Linux 64 HPC, allocated 32G memory and 32 GPUs, as well as an NVIDIA Tesla V100GPU [T4 GPU got the same error]
Licsbas version:1.5.1
cupy version: 6.0.0

**This is the running log:**

LiCSBAS13_sb_inv.py ver1.5.1 20210309 Y. Morishita
`LiCSBAS13_sb_inv.py -d GEOCml_mask -t TS_GEOCml --inv_alg LS --mem_size 8000 --n_para 32 --keep_incfile --gpu`

GPU option is activated. Need cupy module.

In geographical coordinates
Read cum data on memory (fast but need memory).

```
#Size of image (w,l)    : 3114, 2690
#of all images        : 34
#of images to be used : 34
#of all ifgs          : 126
#of ifgs to be used   : 125
#of removed ifgs      : 1
#Threshold of used unw  : 34
```

Reference area (X/Y)   : 2292:2293/1478:1479
Allowed memory size    : 8000.0 MB
Number of patches      : 2
Inversion algorism     : LS
Gamma value            : 0.0001

Process 1345/2690th line (1/2th patch)...
  Reading 125 ifg's unw data...
  1440550/4188330 points removed due to not enough ifg data...

  Identifing gaps, and counting n_gap and n_ifg_noloop,
  using GPU...
**Traceback (most recent call last):
  File "/home/users/uw806028/soft_install/licsar/LiCSBAS/bin/LiCSBAS13_sb_inv.py", line 966, in <module>
    sys.exit(main())
  File "/home/users/uw806028/soft_install/licsar/LiCSBAS/bin/LiCSBAS13_sb_inv.py", line 588, in main
    axis=1, dtype=cp.int16) for i in range(n_im-1)])
  File "/home/users/uw806028/anaconda3/env/licsar/lib/python3.7/site-packages/cupy/creation/from_data.py", line 41, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/core/core.pyx", line 1692, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1726, in cupy.core.core.array
ValueError: object __array__ method not producing an array**

**Comment by yumorishita** [comment]
I am not sure, but could you try replacing cp.array with cp.asarray? 
https://github.com/yumorishita/LiCSBAS/blob/16ec612d8f876c6f5c2b35364f84cc9fa850b445/bin/LiCSBAS13_sb_inv.py#L586

Have you tried n_para=1? Still the error occurs?

**Comment by wzmucas** [comment]
> I am not sure, but could you try replacing cp.array with cp.asarray?
> https://github.com/yumorishita/LiCSBAS/blob/16ec612d8f876c6f5c2b35364f84cc9fa850b445/bin/LiCSBAS13_sb_inv.py#L586
> 
> Have you tried n_para=1? Still the error occurs?

Thanks for your quick reply. I have tested --gpu again with corrected code, still doesn't work and finally I got exactly the same error as above.

Regarding CPU computing, I have tested it by running it in different frames, it will freeze at the second-last patch or at reference point selection part, the last part of the output log is listed below. I also managed to run it with ` n_para=1`, it already took 1 hour for the first 3 patches calculation.  
```
Process 2235/2681th line (5/6th patch)...
  Reading 310 ifg's unw data...
  316655/1458114 points removed due to not enough ifg data...

  Identifing gaps, and counting n_gap and n_ifg_noloop,
  with 8 parallel processing...
    Running  1/ 8th patch...
    Running  2/ 8th patch...
    Running  3/ 8th patch...
    Running  4/ 8th patch...
    Running  5/ 8th patch...
    Running  6/ 8th patch...
    Running  7/ 8th patch...
    Running  8/ 8th patch...
```
**or**
```
Elapsed time for 7th patch: 00h 01m 58s

Find stable reference point...
Selected ref: 1587:1588/848:849
```

**Comment by yumorishita** [comment]
You mean the processing successfully finished with n_para=1 in >2hr?

I got some similar reports working on HPC. The multiprocessing module sometimes seems to stack on HPC. I have no other idea than n_para=1 in that case.

**Comment by wzmucas** [comment]
> You mean the processing successfully finished with n_para=1 in >2hr?
> 
> I got some similar reports working on HPC. The multiprocessing module sometimes seems to stack on HPC. I have no other idea than n_para=1 in that case.

Yes, n_para=1 in >2hr with the newest version works, but n_para > 1 it will freeze at some point on HPC. Sometimes it works, for example, ver1.4.5 works well with n_para=32. The only way to avoid the n_para > 1 frozen on HPC is to set n_para=1 or n_para=2 (if it works)

**Comment by yumorishita** [comment]
What is the version of CUDA? Can you update the cupy? My environment is cupy ver8.3 and CUDA ver11.0.

**Comment by yumorishita** [comment]
Have you solved this issue? I close this issue now but if you have more comments, please reopen this.
