### ISSUE TITLE
Plot Results

### ISSUE THREAD

**Issue by ederliga07** [yumorishita/LiCSBAS#93]
HI I have a problem with licsbas at this time:
LiCSBAS_plot_ts.py -i TS_GEOCml1clipGACOS/cum_filt.h5 &
![Captura de pantalla de 2021-03-16 20-52-27](https://user-images.githubusercontent.com/60079150/111403342-c994f480-869a-11eb-9018-de3d6145772f.png)
(base) eder@ederHP:/mnt/A83800E53800B3FA/LICSBAS/Desc_P1$ 
LiCSBAS_plot_ts.py ver1.13.3 20210205 Y. Morishita
LiCSBAS_plot_ts.py -i TS_GEOCml1GACOSclip/cum_filt.h5

Reading TS_GEOCml1GACOSclip/cum_filt.h5
Traceback (most recent call last):
  File "/home/eder/LiCSBAS/LiCSBAS/bin/LiCSBAS_plot_ts.py", line 361, in <module>
    refx1, refx2, refy1, refy2 = [int(s) for s in re.split('[:/]', refarea)]
  File "/home/eder/anaconda3/lib/python3.8/re.py", line 231, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object
(base) eder@ederHP:/mnt/A83800E53800B3FA/LICSBAS/Desc_P1$

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/65
https://github.com/yumorishita/LiCSBAS/issues/40
