### ISSUE TITLE
LiCSBAS Installation

### ISSUE THREAD

**Issue by ederliga07** [yumorishita/LiCSBAS#94]
Hey I need some help pls
At the time I already did the steps of installation with Anaconda Anaconda3-2020.11-Linux-x86_64.sh and validate the installation present some issue 
![Captura de pantalla de 2021-03-16 21-05-26](https://user-images.githubusercontent.com/60079150/111403868-c51d0b80-869b-11eb-80b6-f3761f410afe.png)
It suppose that gdal its installed on his last version

**Comment by yumorishita** [comment]
You need to install the gdal in anaconda using conda, not in the system.
https://github.com/yumorishita/LiCSBAS/wiki/1_Installation#example-1-using-anaconda

**Comment by ederliga07** [comment]
It's installed in anaconda but it don't recognized and give me this error at the time of plotting results
![Captura de pantalla de 2021-03-16 20-52-27](https://user-images.githubusercontent.com/60079150/111493480-963e7e00-870b-11eb-86cd-0155a7e24f53.png)

**Comment by yumorishita** [comment]
This is the temporary solution:
#65
#40

It is quite strange. Could you tell me the return of the following commands?

`conda list | grep gdal`

```
python
>>> import osgeo.gdal
```

**Comment by najibkakar** [comment]
Hello Yumorishita, I have the same problem. I have already checked and the gdal is install and working as followings:[
![LICSBAS](https://user-images.githubusercontent.com/81171809/112003337-1bb59a00-8b21-11eb-9d4b-c9539440c88b.png)
](url)

**Comment by yumorishita** [comment]
I think it is not a critical problem and you would be able to run LiCSBAS. The LiCSBAS_check_install.py may have a bug, I will investigate later. For the error in LiCSBAS_plot_ts.py, please try the solution in #65 and #40.

**Comment by yumorishita** [comment]
I have slightly updated the LiCSBAS_check_install.py. Could you please update your installed module, try again and tell me the result?

**Comment by najibkakar** [comment]
I have installed everything over and it is working now with the updated installed module. Thank you very much!
