### ISSUE TITLE
How to determine which frame IDs are included in a large area

### ISSUE THREAD

**Issue by CanZhang-zc** [yumorishita/LiCSBAS#95]
Dear Yu,
Please, if I want to perform LiCSBAS on a large area (such as Sichuan Province, China), after I search on the COMET official website, how should I accurately determine the frame IDs included in the experiment range? 
Sorry for any inconvenience caused, your assistance will be highly appreciated.
![微信截图_20210317185842](https://user-images.githubusercontent.com/78521332/111457419-20f69b80-8753-11eb-8fe0-82108b8403b6.png)

**Comment by CanZhang-zc** [comment]
When I zoom in and out of the range, I feel it’s not easy to accurately determine the frame IDs.

**Comment by yumorishita** [comment]
You can download the coherence kmz files which can be displayed on Google Earth. I hope these can help.
http://gws-access.jasmin.ac.uk/public/nceo_geohazards/shared/A_ml10_merged.coh_avg.kmz
http://gws-access.jasmin.ac.uk/public/nceo_geohazards/shared/D_ml10_merged.coh_avg.kmz

**Comment by CanZhang-zc** [comment]
Thanks a lot.
I will try it later.
