### ISSUE TITLE
Plotting Issue

### ISSUE THREAD

**Issue by smailt** [yumorishita/LiCSBAS#96]
Hello, All

how do I solve this problem when plotting TS?
LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &

I get this message?
![newissue](https://user-images.githubusercontent.com/15068367/111550417-55cc1800-877e-11eb-9c49-2a1d8fa3662c.jpg)

All my best :)

**Comment by yumorishita** [comment]
#65
#40

I cannot reproduce the error in my environment, but I will try to fix it because some users have reported the same issue.

**Comment by smailt** [comment]
Hello Many thanks
I solved the issue by
Go to LiCSBAS\bin and open LiCSBAS_plot_ts.py by any text editor then
add this to your code in  line 360    (.decode('utf-8'))
`refarea = cumh5['refarea'][()].decode('utf-8')`

![slv](https://user-images.githubusercontent.com/15068367/111614078-7c6e6b00-87df-11eb-94d8-71f9f9e45c6d.jpg)
