### ISSUE TITLE
Clip problem

### ISSUE THREAD

**Issue by tanmeimei** [yumorishita/LiCSBAS#97]
Hi,
I meet a clip problem.[](url)
![1](https://user-images.githubusercontent.com/23070338/111875959-aae57500-899c-11eb-9047-4f27fee81706.png)
Do you know how to do with it?

Kind regards

**Comment by tanmeimei** [comment]
And it happens the same when I use range_geo. The Id is 065D_05087_131313.
![2](https://user-images.githubusercontent.com/23070338/111875990-e41de500-899c-11eb-8b15-2636ff786067.png)

**Comment by yumorishita** [comment]
Please try again from step03 after removing the GEOCml1clip.
Unless it works, please upload the full log from step03.

**Comment by tanmeimei** [comment]
Thanks, now it works

**Comment by MIEMESSI** [comment]
Dear Professor, I have the following problem


LiCSBAS01_get_geotiff.py ver1.6.3 20201207 Y. Morishita
LiCSBAS01_get_geotiff.py -s 20230101 -e 20240101

Frame ID is 143A_05651_131313

143A_05651_131313.geo.E.tif already exist. Skip download.
143A_05651_131313.geo.N.tif already exist. Skip download.
143A_05651_131313.geo.U.tif already exist. Skip download.
143A_05651_131313.geo.hgt.tif already exist. Skip download.

Download baselines
    baselines, 6.55KB, 7s, 957.0B/s
Download network.png
    network.png, 602.47KB, 8s, 75.31KB/s
Download metadata.txt
    metadata.txt, 219.0B, 6s, 36.0B/s

143A_05651_131313.geo.mli.tif already exist. Skip.



Download geotiff of unw and cc
83 IFGs available from 20230101 to 20231227
Checking existing unw and cc (4 parallel, may take time)...
83 unw already downloaded
0 unw will be downloaded
83 cc already downloaded
0 cc will be downloaded

Elapsed time: 00h 04m 05s

LiCSBAS01_get_geotiff.py Successfully finished!!

Output directory: /home/pl/wx/LiCSBAS/bin/143A_05651_131313/GEOC


LiCSBAS02_ml_prep.py ver1.7.4 20201119 Y. Morishita
LiCSBAS02_ml_prep.py -i GEOC -n 1

Create E.geo
  E.geo created

Create N.geo
  N.geo created

Create U.geo
  U.geo created

Create slc.mli
  slc.mli[.png] created

Create hgt
  hgt[.png] created

Create unw and cc
   83/ 83 unw and cc already exist. Skip

Copy baselines file

Elapsed time: 00h 00m 02s

LiCSBAS02_ml_prep.py Successfully finished!!

Output directory: GEOCml1


LiCSBAS05op_clip_unw.py ver1.2.5 20210105 Y. Morishita
LiCSBAS05op_clip_unw.py -i GEOCml1 -o GEOCml1clip -g 92.54/92.57/34.48/34.52
Traceback (most recent call last):
  File "/home/pl/wx/LiCSBAS/bin/LiCSBAS05op_clip_unw.py", line 345, in <module>
    sys.exit(main())
  File "/home/pl/wx/LiCSBAS/bin/LiCSBAS05op_clip_unw.py", line 161, in main
    width = int(io_lib.get_param_par(mlipar, 'range_samples'))
  File "/home/pl/wx/LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 236, in get_param_par
    value = subp.check_output(['grep', field,mlipar]).decode().split()[1].strip()
  File "/home/pl/anaconda3/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/pl/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['grep', 'range_samples', '/home/pl/wx/LiCSBAS/bin/143A_05651_131313/GEOCml1/slc.mli.par']' returned non-zero exit status 1.

**Comment by yumorishita** [comment]
I am not sure but some files may be corrupted. Please remove all files and retry from start again.

**Comment by yumorishita** [comment]
Can you upload the full log?
