### ISSUE TITLE
LiCSBAS Freeze 

### ISSUE THREAD

**Issue by smailt** [yumorishita/LiCSBAS#98]
Hello ,
The application freeze at this step, I recalculate twice and the same step took a lot time.

![Screenshot from 2021-03-25 16-01-46](https://user-images.githubusercontent.com/15068367/112522153-925ecb80-8d9d-11eb-830d-cdbc614b6940.png)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/86
