### ISSUE TITLE
Cum2txt

### ISSUE THREAD

**Issue by tanmeimei** [yumorishita/LiCSBAS#99]
Hi,
I am using one of the file LiCSBAS_cum2tstxt.py but I don't understand what i get from its output. Dose it give a file about the deformation of a point? Then what's the direction of this deformation? Dose it mean the vertical direction? and also what's the unit of this variable. I also find it have variable of "ts" and "ts_ref" inside. Do they represent the height of the point?

Best regards

**Comment by yumorishita** [comment]
Yes, the output text file contains the cumulative deformation time series at the indicated point. The direction is LOS and the positive value is toward the satellite (i.e., upward). The unit is mm. "ts" and "ts_ref" are the time series at a point and reference, respectively, not the height.

**Comment by tanmeimei** [comment]
So, the deformation is respect to the first epoch? or the previous epoch? And if there is any visualization tool to have a topography output? 
Thanks.

**Comment by yumorishita** [comment]
Yes, the deformation time series is cumulative, not increment, and the reference epoch is the first one. You would see 0 deformation at the first epoch.

The height can be displayed by LiCSBAS_plot_ts.py (select hgt) or LiCSBAS_disp_img.py reading the results/hgt file.

**Comment by tanmeimei** [comment]
Thanks, and I see a small "+" in the figure, what dose this imply?
![6](https://user-images.githubusercontent.com/23070338/113072940-7063af80-91c8-11eb-9e39-cf50f1b3e7fb.png)

**Comment by yumorishita** [comment]
The + means a selected point at which the time series is plotted in the other window. You can select the point by double click.

**Comment by yumorishita** [comment]
It seems that there is no more question. Let me close this issue.
